### ISSUE TITLE
sts.getSessionToken() call returns "Cannot read property 'DurationSeconds' of undefined" TypeError

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1038]
**Describe the bug**
sts.getSessionToken() call returns "Cannot read property 'DurationSeconds' of undefined" TypeError

**SDK version number**
```console
$ npm list aws-sdk
└── aws-sdk@2.612.0
$ npm list @aws-sdk/client-sts
└── @aws-sdk/client-sts@1.0.0-alpha.18
```

**Is the issue in the browser/Node.js?**
Both

**Details of the browser/Node.js version**
```console
$ node -v
v12.16.0
```

**To Reproduce (observed behavior)**

<details>
<summary>Code</summary>

```javascript
const AWS = require("aws-sdk");
const { STS } = require("@aws-sdk/client-sts");

(async () => {
  let response;

  const region = "us-west-2";
  const v2Client = new AWS.STS({ region });
  const v3Client = new STS({ region });

  response = await v2Client.getSessionToken().promise();
  console.log("Data returned by v2:");
  console.log(JSON.stringify(response, null, 2));

  response = await v3Client.getSessionToken();
  console.log("\nData returned by v3:");
  console.log(JSON.stringify(response, null, 2));
})();
```

</details>

<details>
<summary>Output</summary>

```console
Data returned by v2:
{
  "ResponseMetadata": {
    "RequestId": "b8a65264-c75c-4cc1-9c25-887d6131e82b"
  },
  "Credentials": {
    "AccessKeyId": "<REDACTED>",
    "SecretAccessKey": "<REDACTED>",
    "SessionToken": "<REDACTED>",
    "Expiration": "<REDACTED>"
  }
}
(node:31862) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'DurationSeconds' of undefined
    at serializeAws_queryGetSessionTokenRequest (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-sts/dist/cjs/protocols/Aws_query.js:574:15)
    at Object.serializeAws_queryGetSessionTokenCommand (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-sts/dist/cjs/protocols/Aws_query.js:73:21)
    at serialize (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-sts/dist/cjs/commands/GetSessionTokenCommand.js:25:28)
    at Object.<anonymous> (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-serde/build/serializerMiddleware.js:7:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:31862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:31862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Expected behavior**
`await v3Client.getSessionToken()` returns a set of temporary credentials

**Comment by trivikr** [comment]
JS SDK v3 doesn't accept empty params, the code works fine when an empty object is passed to it:
```diff
   console.log("Data returned by v2:");
   console.log(JSON.stringify(response, null, 2));
 
-  response = await v3Client.getSessionToken();
+  response = await v3Client.getSessionToken({});
   console.log("\nData returned by v3:");
   console.log(JSON.stringify(response, null, 2));
 })();
```

Refs: https://github.com/aws/aws-sdk-js-v3/issues/424
