### ISSUE TITLE
[Beta] Kinesis is not working with new clients.

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#1053]
**Describe the bug**
Kinesis.PutRecords and Firehose.PutRecordsBatch has stopped working after upgrading to beta clients with the following service level error (400 HTTP request)
`{"__type":"SerializationException"}`

and below error in console
```
[DEBUG] 48:05.697 AWSKinesisProvider - Failed to upload records to Kinesis SerializationException: "SerializationException"
    deserializeAws_json1_1PutRecordsCommandError Aws_json1_1.js:4226
```

**SDK version number**
Beta clients

**Is the issue in the browser/Node.js?**
Browser

**To Reproduce (observed behavior)**
Make a call to Kinesis.PutRecords and Firehose.PutRecordsBatch

**Comment by trivikr** [comment]
Verified that putRecords works in Node.js, checking in browser.

```console
$ npm list @aws-sdk/client-kinesis
└── @aws-sdk/client-kinesis@1.0.0-beta.1
```

<details>
<summary>Code</summary>

```javascript
const AWS = require("aws-sdk");
const { Kinesis } = require("@aws-sdk/client-kinesis");

(async () => {
  let response;
  const region = "us-west-2";

  const v2Client = new AWS.Kinesis({ region });
  const v3Client = new Kinesis({ region });

  const ShardCount = 1;
  const StreamName = `test-stream-${Math.floor(Math.random() * 10 ** 10)}`;
  await v2Client.createStream({ StreamName, ShardCount }).promise();
  await v2Client.waitFor("streamExists", { StreamName }).promise();

  response = await v2Client.listShards({ StreamName }).promise();
  const { ShardId } = response.Shards[0];
  const ShardIteratorType = "LATEST";
  const { ShardIterator } = await v2Client
    .getShardIterator({ ShardId, StreamName, ShardIteratorType })
    .promise();

  const params = {
    Records: [
      {
        Data: "Data",
        PartitionKey: "PartitionKey"
      }
    ],
    StreamName
  };
  await v2Client.putRecords(params).promise();

  response = await v2Client.getRecords({ ShardIterator }).promise();
  console.log("Data returned by v2:");
  console.log(response);

  await v3Client.putRecords(params);
  response = await v3Client.getRecords({ ShardIterator });
  console.log("Data returned by v3:");
  console.log(response);

  await v2Client.deleteStream({ StreamName }).promise();
})();

```

</details>

<details>
<summary>Output</summary>

```console
Data returned by v2:
{
  Records: [
    {
      SequenceNumber: '49605521209211344642692070135288644122484063658672390146',
      ApproximateArrivalTimestamp: 2020-03-27T16:52:07.410Z,
      Data: <Buffer 44 61 74 61>,
      PartitionKey: 'PartitionKey'
    }
  ],
  NextShardIterator: 'AAAAAAAAAAH7c7iw1onu8j7TXl8o6591GYSEgXsxgYuzzfsEFB3DxrcGfpsd9qcQyl2EMBpoWhHOvNThSdkA+QFT3Ju2das1xG37RcN4PhEwdQWd1vbdzH3Y3SdUaK/mFjCBATsrBcnnx00faYE+6yZ5J8116Mp4pNYQ7SebzojDzg2UavU1gGbAEQusH1LJTKkk4s3EcXgmIuuvEMMI3CH1TuMyKT/jKBlA38reHPesooTCABV9dw==',
  MillisBehindLatest: 0
}
Data returned by v3:
{
  '$metadata': {
    httpStatusCode: 200,
    httpHeaders: {
      'x-amzn-requestid': 'd1b09dd4-630c-3b6f-8748-aca3148ac050',
      'x-amz-id-2': 'YYbmFye7MvbOGQx2+eq5mU7Aq0niPahibOTs3IfZOlBBdIBSNtRkUwz2ecHlS39XPv1nWlAG/OZgEgXhqfnO/M4G5RAzB9Vk',
      date: 'Fri, 27 Mar 2020 16:52:07 GMT',
      'content-type': 'application/x-amz-json-1.1',
      'content-length': '648'
    },
    requestId: 'd1b09dd4-630c-3b6f-8748-aca3148ac050',
    retries: 0,
    totalRetryDelay: 0
  },
  __type: 'GetRecordsOutput',
  MillisBehindLatest: 0,
  NextShardIterator: 'AAAAAAAAAAFLUt0i+4jci6jjQTr++xEJBbmxadRogooOQ7Kz/257DchLVNpZugXcgYnJQFbLGzQQAHzhbWFWpuMCqoNjcnJvK88nbrTuHO8QFg+ojACtTJvcbJWVd0eNclR/7BMvbycuXlKy+trUVqIQXREodyNRQuSGIniK4XyhB6b/u/K/z8suXplTpDLmpk2uQTeqUEyuETK+gGGdWGFE1haQbpdQ0hrbPGsBHwUIqLjVB/HyFw==',
  Records: [
    {
      __type: 'Record',
      ApproximateArrivalTimestamp: 2020-03-27T16:52:07.410Z,
      Data: [Uint8Array],
      EncryptionType: undefined,
      PartitionKey: 'PartitionKey',
      SequenceNumber: '49605521209211344642692070135288644122484063658672390146'
    },
    {
      __type: 'Record',
      ApproximateArrivalTimestamp: 2020-03-27T16:52:07.849Z,
      Data: [Uint8Array],
      EncryptionType: undefined,
      PartitionKey: 'PartitionKey',
      SequenceNumber: '49605521209211344642692070136970259937568012909408157698'
    }
  ]
}
```

</details>

**Comment by trivikr** [comment]
Not able to repro the issue in browser

Code: https://github.com/trivikr/aws-sdk-js-tests/tree/repro-1053

ToDo while testing:
* update REGION in config.js
* update IDENTITY_POOL_ID in config.js
* update StreamName in utils.js
* update ShardIterator in utils.js

Output:

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-03-27 at 11 11 09 AM](https://user-images.githubusercontent.com/16024985/77786816-bc12d480-701b-11ea-9dff-9131ae06b800.png)

</details>

Observations:
* Record ending with SequenceNumber 1042 was added using v2
* Record ending with SequenceNumber 7218 was added using v3

**Comment by trivikr** [comment]
Verified that `SerializationException` is reproducible, if stringified JSON is passed in Record.Data in putRecords API call

Using Node.js v12.16.1 for ease of repro

<details>
<summary>Code</summary>

```javascript
const AWS = require("aws-sdk");
const { Kinesis } = require("@aws-sdk/client-kinesis");

(async () => {
  let response;
  const region = "us-west-2";

  const v2Client = new AWS.Kinesis({ region });
  const v3Client = new Kinesis({ region });

  const ShardCount = 1;
  const StreamName = `test-stream-${Math.floor(Math.random() * 10 ** 10)}`;
  await v2Client.createStream({ StreamName, ShardCount }).promise();
  await v2Client.waitFor("streamExists", { StreamName }).promise();

  response = await v2Client.listShards({ StreamName }).promise();
  const { ShardId } = response.Shards[0];
  const ShardIteratorType = "LATEST";
  const { ShardIterator } = await v2Client
    .getShardIterator({ ShardId, StreamName, ShardIteratorType })
    .promise();

  const params = {
    Records: [
      {
        Data: JSON.stringify({ name: "albumVisit" }),
        PartitionKey: "PartitionKey"
      }
    ],
    StreamName
  };
  await v2Client.putRecords(params).promise();

  response = await v2Client.getRecords({ ShardIterator }).promise();
  console.log("Data returned by v2:");
  console.log(response);

  await v3Client.putRecords(params);
  response = await v3Client.getRecords({ ShardIterator });
  console.log("Data returned by v3:");
  console.log(response);

  await v2Client.deleteStream({ StreamName }).promise();
})();
```

</details>

<details>
<summary>Output</summary>

```console
Data returned by v2:
{
  Records: [
    {
      SequenceNumber: '49605523885300768466366847035555701302890846759493304322',
      ApproximateArrivalTimestamp: 2020-03-27T18:57:07.371Z,
      Data: <Buffer 7b 22 6e 61 6d 65 22 3a 22 61 6c 62 75 6d 56 69 73 69 74 22 7d>,
      PartitionKey: 'PartitionKey'
    }
  ],
  NextShardIterator: 'AAAAAAAAAAF3914tuDBelxgoClQ3Z0BTJcbLabCy3/QkJ3ZgNPK2+X3ZenK5esFpxLswrCFBQi9ztQhFThrsij+3giRbYoNHLe23C7khf8RPWpxv56YnzhbhTKO3lxBZmTuwpjYY6Ufb8zNGKCHfKnZzMbNM23eZ44V177+6uCEQBhTmcnUHbnzqRnmATGoS8jgkjzbPEMH5JPzqbMpurA2GQ7P1a/67Ce1U0Vee8EJomAiBVbh1Nw==',
  MillisBehindLatest: 0
}
(node:39618) UnhandledPromiseRejectionWarning: SerializationException: SerializationException
    at deserializeAws_json1_1PutRecordsCommandError (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-kinesis/dist/cjs/protocols/Aws_json1_1.js:1207:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:39618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:39618) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Comment by trivikr** [comment]
Verified that issue is caused because of the same reason as described in https://github.com/aws/aws-sdk-js-v3/issues/1054#issuecomment-605205869
