### ISSUE TITLE
DescribeTableCommand accepts undefined for required input TableName

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1124]
**Describe the bug**
DescribeTableCommand accepts undefined for required input TableName

**SDK version number**
`@aws-sdk/client-dynamodb@1.0.0-beta.5`

**Is the issue in the browser/Node.js?**
Both

**Details of the browser/Node.js version**
Doesn't matter

**To Reproduce (observed behavior)**
Verified by running the following code:

<details>
<summary>Code</summary>

```typescript
import { DynamoDBClient, DescribeTableCommand } from "@aws-sdk/client-dynamodb";

(async () => {
  const region = "us-west-2";
  const client = new DynamoDBClient({ region });

  try {
    const command = new DescribeTableCommand({ TableName: undefined });
    console.log(await client.send(command));
  } catch (e) {
    console.log(e);
  }
})();
```

</details>

<details>
<summary>Output</summary>

```console
$ ts-node index.ts
ValidationException: The parameter 'TableName' is required but was not present in the request
    at deserializeAws_json1_0DescribeTableCommandError (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-dynamodb/protocols/Aws_json1_0.ts:2417:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  __type: 'com.amazon.coral.validate#ValidationException',
  name: 'ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      server: 'Server',
      date: 'Wed, 29 Apr 2020 17:38:52 GMT',
      'content-type': 'application/x-amz-json-1.0',
      'content-length': '143',
      connection: 'keep-alive',
      'x-amzn-requestid': 'JIOSGM4O97VTBI3VTVQ0PQK7OVVV4KQNSO5AEMVJF66Q9ASUAAJG',
      'x-amz-crc32': '3733221906'
    },
    requestId: 'JIOSGM4O97VTBI3VTVQ0PQK7OVVV4KQNSO5AEMVJF66Q9ASUAAJG',
    retries: 0,
    totalRetryDelay: 0
  }
}
```

</details>

**Expected behavior**
* DescribeTableCommand should not accept undefined as a TableName
* This can be done by removing `| undefined` in `DescribeTableInput` interface
https://github.com/aws/aws-sdk-js-v3/blob/65a36581db0279a6044fd815201f91bcab4dcf90/clients/client-dynamodb/models/index.ts#L2675-L2681

**Comment by trivikr** [comment]
Example of how TypeScript will catch this error while editing code if `| undefined` check is removed:
* [TypeScript playground](https://www.typescriptlang.org/play/?ssl=13&ssc=25&pln=13&pc=35#code/JYOwLgpgTgZghgYwgAmAVRAEwjUFPIDeAUMsgNYQCeAXMgM5hSgDmyAPsgK5Y56YBuYgF9ixUJFiIUwAHIB7MBmy4Q+IqQrU6jZiBZDRxBPJCNUyvmswB5AEYArOul6r1AXg1lKtbq-4iYiZmYKgKSv7W9k5hipZuBJ4k3tp+KgHCQA)
* <details>
  <summary>Code</summary>

  ```typescript
  interface iUndefined {
    key: string | undefined;
  }

  interface iNotUndefined {
    key: string;
  }

  const iUndefinedObj: iUndefined = {
    key: undefined
  }

  const iNotUndefinedObj: iNotUndefined = {
    key: undefined
  }
  ```

  </details>
* <details>
  <summary>Screenshot</summary>

  <img width="572" alt="Screen Shot 2020-04-29 at 10 46 52 AM" src="https://user-images.githubusercontent.com/16024985/80629199-5a250080-8a07-11ea-9f1a-a8a80db92f29.png">

  </details>

**Comment by trivikr** [comment]
Findings:
* The CodeGen code which adds `| undefined` check
  * Code https://github.com/awslabs/smithy-typescript/blob/499bb5860e51d00c7babf5783bfa259cf715f3ad/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java#L58
* This check if added if member is required, and has idempotencyToken trait ([spec](https://awslabs.github.io/smithy/spec/core.html#idempotencytoken-trait))

**Comment by trivikr** [comment]
We decided to stick with using `| undefined` because of the following reasons:
* If we ship the SDK with output member documented as required explicitly, for sure users will consume it without validation. This may break them in future, if service decides to make the member optional and returns undefined.
* This change will require making objects upstream of deserialize() method to `any`, which removes type safety for deserialize section of internal code. There is a solution to have type safety without increasing bundle size, but it'll add lot of additional internal code.
