### ISSUE TITLE
BadRequestException in appmesh.createVirtualNode call

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1209]
**Describe the bug**
appmesh.createVirtualNode returns BadRequestException for the same parameters which succeed in v3

**SDK version number**
```console
$ npm list @aws-sdk/client-app-mesh
└── @aws-sdk/client-app-mesh@1.0.0-gamma.2 
```

**Is the issue in the browser/Node.js?**
Both

**Details of the browser/Node.js version**
All

**To Reproduce (observed behavior)**

<details>
<summary>Code</summary>

```javascript
const AWS = require("aws-sdk");
const { AppMesh } = require("@aws-sdk/client-app-mesh");

(async () => {
  const region = "us-west-2";
  const meshName = "meshName";
  const hostname = "localhost";
  const virtualNodeName = "virtualNodeName";

  const v2Client = new AWS.AppMesh({ region });
  const v3Client = new AppMesh({ region });

  await v2Client.createMesh({ meshName }).promise();
  console.log(`\nCreated mesh "${meshName}"`);
  console.log(await v2Client.describeMesh({ meshName }).promise());

  const params = {
    meshName,
    spec: {
      serviceDiscovery: {
        dns: {
          hostname,
        },
      },
      listeners: [
        {
          portMapping: {
            port: 80,
            protocol: "http",
          },
        },
      ],
    },
    virtualNodeName,
  };

  try {
    await v2Client.createVirtualNode(params).promise();
    console.log(`\nCreated virtualNode "${virtualNodeName}" using v2`);
    console.log(
      await v2Client
        .describeVirtualNode({ meshName, virtualNodeName })
        .promise()
    );
    await v2Client.deleteVirtualNode({ meshName, virtualNodeName }).promise();
    console.log(`Deleted virtualNode "${virtualNodeName}" using v2\n`);
  } catch (error) {
    console.log(error);
  }

  try {
    await v3Client.createVirtualNode(params);
    console.log(`\nCreated virtualNode "${virtualNodeName}" using v3`);
    console.log(
      await v3Client.describeVirtualNode({ meshName, virtualNodeName })
    );
    await v3Client.deleteVirtualNode({ meshName, virtualNodeName });
    console.log(`Deleted virtualNode "${virtualNodeName}" using v3\n`);
  } catch (error) {
    console.log(error);
  }

  await v2Client.deleteMesh({ meshName }).promise();
  console.log(`\nDeleted mesh "${meshName}"`);
})();

```

</details>

<details>
<summary>Output</summary>

```console
Created mesh "meshName"
{
  mesh: {
    meshName: 'meshName',
    metadata: {
      arn: 'arn:aws:appmesh:us-west-2:930809265900:mesh/meshName',
      createdAt: 2020-05-27T19:48:57.965Z,
      lastUpdatedAt: 2020-05-27T19:48:57.965Z,
      uid: '6d6fbb79-042d-4ff3-ae71-a37b22947cff',
      version: 1
    },
    spec: {},
    status: { status: 'ACTIVE' }
  }
}

Created virtualNode "virtualNodeName" using v2
{
  virtualNode: {
    meshName: 'meshName',
    metadata: {
      arn: 'arn:aws:appmesh:us-west-2:930809265900:mesh/meshName/virtualNode/virtualNodeName',
      createdAt: 2020-05-27T19:48:58.120Z,
      lastUpdatedAt: 2020-05-27T19:48:58.120Z,
      uid: '58ea500c-2148-490a-bed5-6834ee4c5f23',
      version: 1
    },
    spec: { backends: [], listeners: [Array], serviceDiscovery: [Object] },
    status: { status: 'ACTIVE' },
    virtualNodeName: 'virtualNodeName'
  }
}
Deleted virtualNode "virtualNodeName" using v2

BadRequestException: One type of Service Discovery Configuration must be set.
    at deserializeAws_restJson1_1CreateVirtualNodeCommandError (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-app-mesh/dist/cjs/protocols/Aws_restJson1_1.js:1142:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'BadRequestException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      'x-amzn-requestid': '94836e09-b8d1-4558-85aa-4e46afdc4d6a',
      'x-amzn-errortype': 'BadRequestException:http://internal.amazon.com/coral/com.amazonaws.lattice.v20190125/',
      'content-type': 'application/json',
      'content-length': '70',
      date: 'Wed, 27 May 2020 19:48:58 GMT',
      'x-envoy-upstream-service-time': '8',
      server: 'envoy'
    },
    requestId: '94836e09-b8d1-4558-85aa-4e46afdc4d6a',
    retries: 0,
    totalRetryDelay: 0
  }
}

Deleted mesh "meshName"
```

</details>

**Expected behavior**
The call to create virtualNode should be successful in v3, with the same parameters passed in v2.

**Comment by trivikr** [comment]
This bug appears to be with naming of variables in UnionShape generator (`ServiceDiscovery` in the case shared above)

Error:
```console
BadRequestException: One type of Service Discovery Configuration must be set.
    at deserializeAws_restJson1_1CreateVirtualNodeCommandError (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/@aws-sdk/client-app-mesh/dist/cjs/protocols/Aws_restJson1_1.js:1142:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'BadRequestException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      'x-amzn-requestid': '94836e09-b8d1-4558-85aa-4e46afdc4d6a',
      'x-amzn-errortype': 'BadRequestException:http://internal.amazon.com/coral/com.amazonaws.lattice.v20190125/',
      'content-type': 'application/json',
      'content-length': '70',
      date: 'Wed, 27 May 2020 19:48:58 GMT',
      'x-envoy-upstream-service-time': '8',
      server: 'envoy'
    },
    requestId: '94836e09-b8d1-4558-85aa-4e46afdc4d6a',
    retries: 0,
    totalRetryDelay: 0
  }
}
```

Code: https://github.com/aws/aws-sdk-js-v3/blob/4895ac7070cf6d845846e0c3b40aa4ee6ad94f82/clients/client-app-mesh/models/index.ts#L2251-L2292

**Comment by kstich** [comment]
This is a `Union`-specific serialization issue where the name of the Union member isn't being added to the resulting document. Request body segment for relevant part here:

```
"spec":{"listeners":[{"portMapping":{"port":80,"protocol":"http"}}],"serviceDiscovery":{"hostname":"localhost"}}
```
