### ISSUE TITLE
client-secrets-manager unable to retrieve secrets

### ISSUE THREAD

**Issue by Harvester0fSorrow** [aws/aws-sdk-js-v3#1215]
**Describe the bug**
I tried using the client-secrets-manager but i always get below error
```
Error: com.amazon.AWSMimirService#ValidationException
    at deserializeAws_json1_1GetSecretValueCommandError (/var/task/app.js:1118:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  __type: 'com.amazon.AWSMimirService#ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      date: 'Wed, 27 May 2020 16:26:11 GMT',
      'content-type': 'application/x-amz-json-1.1',
      'content-length': '152',
      connection: 'keep-alive',
      'x-amzn-requestid': '4af526d6-33fd-4f86-a368-a46631968f09'
    },
    requestId: '4af526d6-33fd-4f86-a368-a46631968f09',
    retries: 0,
    totalRetryDelay: 0
  }
}
```
It is possible that i am doing something daft so please do tell

**SDK version number**
"@aws-sdk/client-secrets-manager": "^1.0.0-alpha.1"

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.13.1

**To Reproduce (observed behavior)**
```
const getSecrets = async (secretsManagerClient) => {
  const params = {
    SecretId: "secret",
  }
  let data
  try {
    data = await secretsManagerClient.send(new GetSecretValueCommand(params))
  } catch (err) {
    console.log("err", err)
  }
  let secret
  if ("SecretString" in data) {
    secret = data.SecretString
  } else {
    console.log("else:", data)

    const buff = new Buffer(data.SecretBinary, "base64")
    secret = buff.toString("ascii")
  }
  return secret
}
```

**Expected behavior**
a json of secret values returned

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Hi @Harvester0fSorrow 

Can you try [our gamma clients](https://github.com/aws/aws-sdk-js-v3/issues/944) to see if the issue persists?
