### ISSUE TITLE
s3.putObject to a different region fails silently

### ISSUE THREAD

**Issue by monken** [aws/aws-sdk-js-v3#1385]
**Describe the bug**
When calling s3.putObject on a bucket in a different region the call will succeed but the file is not actually uploaded. The response from S3 is a 301 redirect and the SDK accepts that as a valid response.

**SDK version number**
1.0.0-gamma.4

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Expected behavior**
Throw an exception or follow the redirect and upload to the correct region. I'd prefer the exception because it involves less magic.

**Comment by AllanFly120** [comment]
Hi @monken 
Like I mentioned in https://github.com/aws/aws-sdk-js-v3/issues/1446#issuecomment-705849410, we fix this by throwing redirection response instead of swallow them.

**Comment by trivikr** [comment]
Verified that putObject fails with 301 in `@aws-sdk/client-s3@1.0.0-rc.2` if called on different region

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");
const { S3 } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-east-1";
  const Bucket = `test-bucket-${Math.ceil(Math.random() * 10 ** 10)}`;
  const Key = `Key`;
  const Body = `Body`;

  const v2Client = new AWS.S3({ region });
  const v3Client = new S3({ region });

  await v3Client.createBucket({ Bucket });
  // Waiters missing in v3.
  await v2Client.waitFor("bucketExists", { Bucket }).promise();

  try {
    const client = new S3({ region: "us-west-2" });
    console.log(await client.putObject({ Bucket, Key, Body }));
    await v3Client.deleteObject({ Bucket, Key });
  } catch (e) {
    console.log(e);
  }

  await v3Client.deleteBucket({ Bucket });
})();

```

</details>

<details>
<summary>Output</summary>

```
PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at deserializeAws_restXmlPutObjectCommandError (/Users/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:7583:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:12:20
    at async /Users/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)
    at async /Users/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async /Users/trivikr/workspace/temp/testBucket.js:19:17 {
  Code: 'PermanentRedirect',
  Endpoint: 's3.amazonaws.com',
  Bucket: 'test-bucket-9250623973',
  RequestId: 'EB2260124CD3B45E',
  HostId: 'P5+KgO7yuxIhf9LxwqBWwqU050/P1662KPMqJonXhLrya4P09vqAXSEERQ2VgceAtY42IwlmM9M=',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 301,
    httpHeaders: {
      'x-amz-bucket-region': 'us-east-1',
      'x-amz-request-id': 'EB2260124CD3B45E',
      'x-amz-id-2': 'P5+KgO7yuxIhf9LxwqBWwqU050/P1662KPMqJonXhLrya4P09vqAXSEERQ2VgceAtY42IwlmM9M=',
      'content-type': 'application/xml',
      'transfer-encoding': 'chunked',
      date: 'Fri, 23 Oct 2020 02:33:14 GMT',
      connection: 'close',
      server: 'AmazonS3'
    },
    requestId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

</details>
