### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Region is missing

### ISSUE THREAD

**Issue by KaranGauswami** [aws/aws-sdk-js-v3#1474]
**Describe the bug**
For creating simple DynamoDb client its throwing region missing error even when region is provided in code.
Here is my code .
```ts
import dotenv from 'dotenv'
dotenv.config()
import { DynamoDB } from '@aws-sdk/client-dynamodb';

async function main() {
  try {
   const client =  new DynamoDB({
      region: 'ap-south-1',
      credentials: {
        accessKeyId: process.env.ACCESS_KEY,
        secretAccessKey: process.env.SECRET_KEY
      }
    });
    console.log("client init");
  } catch (e) {
    console.log(e);
  }
}
main();
```

This is the output
```
(node:9304) UnhandledPromiseRejectionWarning: Error: Region is missing
    at default (D:\node-projects\aws-exp\node_modules\@aws-sdk\config-resolver\dist\cjs\RegionConfig.js:11:15)
    at D:\node-projects\aws-exp\node_modules\@aws-sdk\node-config-provider\dist\cjs\fromStatic.js:9:31
    at step (D:\node-projects\aws-exp\node_modules\tslib\tslib.js:141:27)
    at Object.next (D:\node-projects\aws-exp\node_modules\tslib\tslib.js:122:57)
    at D:\node-projects\aws-exp\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\node-projects\aws-exp\node_modules\tslib\tslib.js:111:16)
    at D:\node-projects\aws-exp\node_modules\@aws-sdk\node-config-provider\dist\cjs\fromStatic.js:8:68
    at D:\node-projects\aws-exp\node_modules\@aws-sdk\property-provider\dist\cjs\chain.js:26:28
(node:9304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:9304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

**SDK version number**
"@aws-sdk/client-dynamodb": "^1.0.0-gamma.7"

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v12.16.1`

**To Reproduce (observed behavior)**
[link](https://github.com/KaranGauswami/aws-exp/tree/main) to repo

**Expected behavior**
It should not throw exception

**Screenshots**
[https://github.com/KaranGauswami/aws-exp/blob/main/error.png](https://github.com/KaranGauswami/aws-exp/blob/main/error.png)

**Comment by AllanFly120** [comment]
Hi @KaranGauswami 

This issue is duplicated with #1466 . I will close this one for now, can you post your comments there? So that we can better track it. 

This issue has been fix in the master branch
