### ISSUE TITLE
v3 doesn't throw UnexpectedParameter error on unexpected keys

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1606]
**Describe the bug**
v3 doesn't throw UnexpectedParameter error on unexpected keys

**SDK version number**
`@aws-sdk/client-s3@1.0.0-rc.2`

**Is the issue in the browser/Node.js/ReactNative?**
N/A

**Details of the browser/Node.js/ReactNative version**
N/A

**To Reproduce (observed behavior)**
Code which passes unexpected `Key` in headBucket operation doesn't throw error in v3:

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");
const { S3 } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-west-2";

  const v2Client = new AWS.S3({ region });
  const v3Client = new S3({ region });

  const Bucket = `test-bucket-${Math.ceil(Math.random() * 10 ** 10)}`;
  const Key = `non-existent-key`;
  await v3Client.createBucket({ Bucket });

  // Waiters are not available in v3.
  await v2Client.waitFor("bucketExists", { Bucket }).promise();

  try {
    await v3Client.headBucket({ Bucket, Key });
  } catch (e) {
    console.log(e);
  }

  await v3Client.deleteBucket({ Bucket });
})();
```

</details>

However, if the following code change is made:
```diff
-    await v3Client.headBucket({ Bucket, Key });
+    await v2Client.headBucket({ Bucket, Key }).promise();
```

The error thrown is:
```
UnexpectedParameter: Unexpected key 'Key' found in params
    at ParamValidator.fail (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/config.js:386:7)
    at /Users/trivikr/workspace/temp/node_modules/aws-sdk/lib/config.js:404:9 {
  code: 'UnexpectedParameter',
  time: 2020-10-23T00:04:40.674Z
}
```

**Expected behavior**
v3 should throw error if Unexpected keys are passed inside params.

**Comment by trivikr** [comment]
This happens as the v3 doesn't have client side validation.
