### ISSUE TITLE
TypeError in JsonBuilder using DynamoDB map

### ISSUE THREAD

**Issue by Manc** [aws/aws-sdk-js-v3#162]
Hi, I already had success DynamoDB function `putItem`, but when I want my Item to contain a map (`M`), I get an error: `TypeError: Cannot read property 'type' of undefined`

Code example:

	const args: PutItemInput = {
		TableName: 'myTableName',
		Item: {
			email: { S: 'xxx@xxx' },
			example: {
				M: {
					email: { S: 'hello' },
				}
			},
		},
		ConditionExpression: 'attribute_not_exists(email)',
	};
	return client.putItem(args);

I also tried representing the map as an array:

	const args: PutItemInput = {
		TableName: 'myTableName',
		Item: {
			email: { S: 'xxx@xxx' },
			example: {
				M: [ 'email', { S: 'hello' } ],
			},
		},
		ConditionExpression: 'attribute_not_exists(email)',
	};

Full error:
```
    TypeError: Cannot read property 'type' of undefined

      at JsonBuilder.Object.<anonymous>.JsonBuilder.format (node_modules/@aws-sdk/json-builder/src/index.ts:41:19)
      at JsonBuilder.Object.<anonymous>.JsonBuilder.format (node_modules/@aws-sdk/json-builder/src/index.ts:103:34)
      at JsonBuilder.Object.<anonymous>.JsonBuilder.format (node_modules/@aws-sdk/json-builder/src/index.ts:65:47)
      at JsonBuilder.Object.<anonymous>.JsonBuilder.format (node_modules/@aws-sdk/json-builder/src/index.ts:103:34)
      at JsonBuilder.Object.<anonymous>.JsonBuilder.format (node_modules/@aws-sdk/json-builder/src/index.ts:65:47)
      at JsonBuilder.Object.<anonymous>.JsonBuilder.build (node_modules/@aws-sdk/json-builder/src/index.ts:36:36)
      at JsonRpcSerializer.Object.<anonymous>.JsonRpcSerializer.serialize (node_modules/@aws-sdk/protocol-json-rpc/src/JsonRpcSerializer.ts:33:39)
      at Object.<anonymous> (node_modules/@aws-sdk/middleware-serializer/src/index.ts:24:43)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at fulfilled (node_modules/tslib/tslib.js:104:62)
```

Used SDK version: 0.1.0-preview.1

**Comment by AllanFly120** [comment]
Hey @Manc 

Sorry for the late response. Looks like the API model for the map shape is broken somewhere. I'm working on to fix it.
