### ISSUE TITLE
listObjectsV2Paginate produces `The continuation token provided is incorrect`

### ISSUE THREAD

**Issue by vivmaha** [aws/aws-sdk-js-v3#1636]
**Describe the bug**
I'm using listObjectsV2Paginate, and seeing the following error:
````
    "errorType": "InvalidArgument",
    "errorMessage": "The continuation token provided is incorrect",
    "Code": "InvalidArgument",
    "ArgumentName": "continuation-token"
````

**SDK version number**
1.0.0-rc.1

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
12

**To Reproduce (observed behavior)**
````
      const paginator = listObjectsV2Paginate(
        {
          client: createS3Client(),
        },
        {
          Bucket: bucketName,
          Delimiter: "/",
          Prefix: prefix,
        }
      );
      const prefixes: string[] = [];
      for await (const foo of paginator) {
      }
````

**Expected behavior**
I'll get back pages of results. The listObjectsV2Paginate will handle the pagination for me. 

**Screenshots**
````
{
    "errorType": "InvalidArgument",
    "errorMessage": "The continuation token provided is incorrect",
    "Code": "InvalidArgument",
    "ArgumentName": "continuation-token",
    "RequestId": "EE65005C2498FA64",
    "HostId": "FDtm1+2/63Ppj52VWaMj1eXFW+ykgAtTjbpJ1qxlLzQ6EaSvtKSkjxq0clCN4oNaEkBL/L4o+xg=",
    "name": "InvalidArgument",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "httpHeaders": {
            "x-amz-bucket-region": "us-west-2",
            "x-amz-request-id": "EE65005C2498FA64",
            "x-amz-id-2": "FDtm1+2/63Ppj52VWaMj1eXFW+ykgAtTjbpJ1qxlLzQ6EaSvtKSkjxq0clCN4oNaEkBL/L4o+xg=",
            "content-type": "application/xml",
            "transfer-encoding": "chunked",
            "date": "Wed, 28 Oct 2020 19:12:35 GMT",
            "server": "AmazonS3",
            "connection": "close"
        },
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "InvalidArgument: The continuation token provided is incorrect",
        "    at deserializeAws_restXmlListObjectsV2CommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6293:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:12:20",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24",
        "    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22",
        "    at async makePagedClientRequest (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/pagination/ListObjectsV2Paginator.js:9:12)",
        "    at async Object.listObjectsV2Paginate (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/pagination/ListObjectsV2Paginator.js:26:20)",
        "    at async Object.getSets (/var/task/src/lib/cloud-set.js:81:30)",
        "    at async Runtime.exports.stitchParsedBlocks [as handler] (/var/task/src/handlers/parser/stitch-parsed-blocks-lambda-aws.js:9:19)"
    ]
}
````

**Additional context**
I can always fallback to manual pagination, but it feels like this would lead to simpler application level code, so it'd be nice if it worked.

The following code, which does the pagination manually, works:

````
      let continuationToken: string | undefined;
      const setPrefixes: string[] = [];
      do {
        const list = await createS3Client().send(
          new ListObjectsV2Command({
            Bucket: bucketName,
            Delimiter: "/",
            Prefix: prefix,
            ContinuationToken: continuationToken,
          })
        );
        continuationToken = list.NextContinuationToken;
      } while (continuationToken !== undefined);
````

**Comment by alexforsyth** [comment]
Just tested this on my machine. It should be working as intended. Please make sure you're using rc.3

```
// using rc.3
import { S3Client, listObjectsV2Paginate } from "@aws-sdk/client-s3";

// Using paginator with s3Client:
(async () => {
    // ======================================
    const paginatorConfiguration = {
        client: new S3Client({}),
        pageSize: 1000
    };
    const paginator = listObjectsV2Paginate(paginatorConfiguration, {
        Bucket: 'aws-js-sdk-browser-builder-staging',
    });

    for await (const bucketPage of paginator) {
        console.log(bucketPage.Contents && bucketPage.Contents.length);
    }
    // ======================================
})();
```

**Comment by vivmaha** [comment]
@alexforsyth confirmed that it works on `1.0.0-rc.4` (I was on `1.0.0-rc.1`). Thanks.
