### ISSUE TITLE
Cannot specify `Not` operator in cost explorer filter

### ISSUE THREAD

**Issue by yaron-idan** [aws/aws-sdk-js-v3#1652]
**Describe the bug**
Cannot specify `Not` operator in cost explorer filter, when I try to I get this error - 
```
TypeError: Cannot redefine property: Not
    at Function.defineProperty (<anonymous>)
    at Object.get Not [as Not] (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/client-cost-explorer-node/model/shapes/_Expression.ts:18:14)
    at JsonBuilder.format (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/json-builder/src/index.ts:62:57)
    at JsonBuilder.format (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/json-builder/src/index.ts:62:37)
    at JsonBuilder.build (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/json-builder/src/index.ts:36:32)
    at JsonRpcSerializer.serialize (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/protocol-json-rpc/src/JsonRpcSerializer.ts:29:33)
    at Object.<anonymous> (/Users/yaron/code/cloud-cost-fetcher/node_modules/@aws-sdk/middleware-serializer/src/index.ts:24:39)
    at step (/Users/yaron/code/cloud-cost-fetcher/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/yaron/code/cloud-cost-fetcher/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/yaron/code/cloud-cost-fetcher/node_modules/tslib/tslib.js:112:62)
```

**SDK version number**
"@aws-sdk/client-cost-explorer-node": "^0.1.0-preview.2",
"aws-sdk": "^2.747.0",    

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v15.0.1

**To Reproduce (observed behavior)**
```
import { GetCostAndUsageCommand } from '@aws-sdk/client-cost-explorer-node/commands/GetCostAndUsageCommand'
import { CostExplorerClient } from '@aws-sdk/client-cost-explorer-node/CostExplorerClient'
import AWS from 'aws-sdk'

  const costExplorer = new CostExplorerClient({
    region: 'us-east-1',
    credentials: new AWS.SharedIniFileCredentials({ profile: billingProfile }),
  })
  const getCostAndUsageCommand = new GetCostAndUsageCommand({
    TimePeriod,
    Granularity: 'MONTHLY',
    GroupBy: [
      {
        Type: 'TAG',
        Key: '<TAG_NAME>',
      },
    ],
    Filter: {
      Not: {
        Dimensions: {
          Key: 'LINKED_ACCOUNT',
          Values: ['<ACCOUNT_NUMBER'],
        },
      },
    },
    Metrics: [metricsType],
  })

```

**Expected behavior**
Query should return it's results (the same exact parameters work with the AWS CLI)

**Comment by AllanFly120** [comment]
Hi @yaron-idan, 

The package you are using `@aws-sdk/client-cost-explorer-node` is being deprecated. You need to use `@aws-sdk/client-cost-explorer` instead. You can follow the steps in [README](https://github.com/aws/aws-sdk-js-v3#getting-started) to install the packages. 

We will deprecate the old preview packages soon: https://github.com/aws/aws-sdk-js-v3/issues/1397

**Comment by yaron-idan** [comment]
Thanks @AllanFly120! I ended up removing the client altogether as it was not mandatory for the small piece of code we are currently using. However, your advice will come in handy if we amp up our usage of the cost explorer client.

**Comment by alexforsyth** [comment]
Sounds like this is resolved!
