### ISSUE TITLE
Paginate operations don't accept undefined for input

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1664]
**Is your feature request related to a problem? Please describe.**
Paginate operations don't accept undefined for input. The callee needs to pass an empty object.

```
"@aws-sdk/client-dynamodb": "1.0.0-rc.4",
```

<details>
<summary>Code</summary>

```js
const {
  DynamoDBClient,
  listTablesPaginate,
} = require("@aws-sdk/client-dynamodb");

(async () => {
  const region = "us-west-2";
  const client = new DynamoDBClient({ region });
  for await (const response of listTablesPaginate({ client })) {
    console.log(response.TableNames);
  }
})();

```

</details>

<details>
<summary>Output</summary>

```console
(node:91956) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'ExclusiveStartTableName' of undefined
    at listTablesPaginate (/Users/trivikr/workspace/paginate/node_modules/@aws-sdk/client-dynamodb/dist/cjs/pagination/ListTablesPaginator.js:20:39)
    at listTablesPaginate.next (<anonymous>)
    at /Users/trivikr/workspace/paginate/v3.js:9:20
    at Object.<anonymous> (/Users/trivikr/workspace/paginate/v3.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:91956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

This issue can be fixed from customer side by passing an empty object in input.

```diff
 (async () => {
   const region = "us-west-2";
   const client = new DynamoDBClient({ region });
-  for await (const response of listTablesPaginate({ client })) {
+  for await (const response of listTablesPaginate({ client }, {})) {
     console.log(response.TableNames);
   }
 })();
```

**Describe the solution you'd like**
Accept undefined for input in pagination operations.

**Describe alternatives you've considered**
Explicitly passing empty object for input.

**Comment by RanVaknin** [comment]
Closing as a duplicate 
https://github.com/aws/aws-sdk-js-v3/issues/424
