### ISSUE TITLE
Support multiple clients in different regions

### ISSUE THREAD

**Issue by codypenta** [aws/aws-sdk-js-v3#1718]
**Is your feature request related to a problem? Please describe.**

Provide the ability to provision multiple clients with different regions

**Describe the solution you'd like**

```typescript
    const ec2ClientNV = new ec2.EC2Client({ region: 'us-east-1'})
    const ec2ClientOH = new ec2.EC2Client({ region: 'us-east-2' })
```

But the error given when tried is:

```bash
Error: Duplicate middleware name 'deserializerMiddleware'
    at Object.add (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/node_modules/@aws-sdk/middleware-stack/src/MiddlewareStack.ts:165:17)
    at Object.applyToStack (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/node_modules/@aws-sdk/middleware-serde/src/serdePlugin.ts:38:20)
    at Object.use (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/node_modules/@aws-sdk/middleware-stack/src/MiddlewareStack.ts:190:14)
    at DescribeTransitGatewaysCommand.resolveMiddleware (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/node_modules/@aws-sdk/client-ec2/commands/DescribeTransitGatewaysCommand.ts:42:26)
    at EC2Client.send (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/node_modules/@aws-sdk/smithy-client/src/client.ts:42:29)
    at checkExistingPeeringConnection (/Users/cpenta/Documents/Repos/tavern/network/tavern-network-infrastructure/src/scripts/glue-network.ts:27:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
✨  Done in 4.83s.
```

**Alternatives**

Alternative would be an easy way to swap in and out regions

```typescript
client.config.region = 'us-east-2'
client.send(command) // with context of us-east-2
client.config.region = 'us-east-1' 
```

**Comment by codypenta** [comment]
This turned out to be a PEBKAC issue for the curious. I was re-using a command `(let command = new ec2.DescribeTransitGatewaysCommand({TransitGatewayIds: tgwIds}))` for both clients. Each client needed it's own initiation of the command

```typescript
        let command = new ec2.DescribeTransitGatewaysCommand({TransitGatewayIds: [tgwIds[0]]})
        const resultsNV = await clientNV.send(command)
        command = new ec2.DescribeTransitGatewaysCommand({TransitGatewayIds: [tgwIds[1]]})
        const resultsOH = await clientOH.send(command)
```
