### ISSUE TITLE
DynamoDB: Putting item that contains multi-byte characters causes error

### ISSUE THREAD

**Issue by cockscomb** [aws/aws-sdk-js-v3#177]
I tried to put an item that contains multi-byte characters and it produces an error.

Could you please help me?

https://github.com/cockscomb/aws-sdk-js-v3-test/blob/51d3a2416e2ed4859574457e080dd15a682929ae/src/dynamodb-multibyte.test.ts#L51-L71

```
    InternalFailure: The request processing has failed because of an unknown error, exception or failure.

      at JsonRpcParser.Object.<anonymous>.exports.jsonErrorUnmarshaller [as parseServiceException] (node_modules/@aws-sdk/json-error-unmarshaller/src/index.ts:65:33)
      at JsonRpcParser.<anonymous> (node_modules/@aws-sdk/protocol-json-rpc/src/JsonRpcParser.ts:33:24)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at fulfilled (node_modules/tslib/tslib.js:104:62)
```

<details>
<summary>Test result</summary>
```
$ docker-compose run --rm node npm test
Creating network "aws-sdk-js-v3-test_default" with the default driver
Creating aws-sdk-js-v3-test_dynamodb_1 ... done

> aws-sdk-js-v3-test@1.0.0 test /app
> jest

 FAIL  src/dynamodb-multibyte.test.ts (9.712s)
  DynamoDBClient
    ✓ create table (603ms)
    ✓ put item (76ms)
    ✓ get item (39ms)
    ✕ put item contains multi-byte characters (599ms)
    ✕ get item contains multi-byte characters (51ms)

  ● DynamoDBClient › put item contains multi-byte characters

    InternalFailure: The request processing has failed because of an unknown error, exception or failure.

      at JsonRpcParser.Object.<anonymous>.exports.jsonErrorUnmarshaller [as parseServiceException] (node_modules/@aws-sdk/json-error-unmarshaller/src/index.ts:65:33)
      at JsonRpcParser.<anonymous> (node_modules/@aws-sdk/protocol-json-rpc/src/JsonRpcParser.ts:33:24)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at fulfilled (node_modules/tslib/tslib.js:104:62)

  ● DynamoDBClient › get item contains multi-byte characters

    TypeError: Cannot read property 'Title' of undefined

      68 |         });
      69 |         const result = await dynamoDB.send(getItem);
    > 70 |         expect(result.Item!.Title.S).toEqual('これはitem2。')
         |                             ^
      71 |     });
      72 | });
      73 |

      at Object.it (src/dynamodb-multibyte.test.ts:70:29)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        13.131s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
</details>

**Comment by srchase** [comment]
@cockscomb 

Thanks for opening this issue!  I get the same behavior.  We'll look at getting this resolved.

**Comment by srchase** [comment]
@cockscomb 

Fixed in #183.  You can build from source now, or else it'll go out with the next release.

**Comment by cockscomb** [comment]
Thank you so much! I’m looking forward to the next release!

**Comment by AllanFly120** [comment]
Hey @cockscomb, the fix has been released! Tryout and see if the issue still there!

**Comment by cockscomb** [comment]
Hi @AllanFly120. I've updated the SDK to the latest release. And now the test worked well. Thank you!

```
 PASS  src/dynamodb-multibyte.test.ts (10.086s)
  DynamoDBClient
    ✓ create table (403ms)
    ✓ put item (50ms)
    ✓ get item (39ms)
    ✓ put item contains multi-byte characters (25ms)
    ✓ get item contains multi-byte characters (26ms)

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        13.013s
Ran all test suites.
```
