### ISSUE TITLE
MediaStoreData client PutObject return InvalidSignatureException

### ISSUE THREAD

**Issue by jncheung** [aws/aws-sdk-js-v3#1825]
**Describe the bug**
Was successfully list items in the container but fail to put objects to container

**SDK version number**
3.0.0

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
node -v
v12.19.0
```

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```js
const msd = new MediaStoreData({
  region: "<media-store-region>",
  credentials: creds,
  endpoint:
    "https://<media-store-id>.data.mediastore.<media-store-region>.amazonaws.com",
});

// ... in async function
let params = {
  Body: chunk /* required */,
  Path: `test2/${path}` /* required */,
  CacheControl: "no-cache",
  ContentType: "audio/wav",
  StorageClass: "TEMPORAL",
  UploadAvailability: "STREAMING",
};

msd.middlewareStack.add(
  (next, ctx) => (args) => {
    args.request.headers["Transfer-Encoding"] = "chunked";
    return next(args);
  },
  {
    step: "build",
  }
);
try {
  let req = await msd.putObject(params);
  console.log(req);
} catch (err) {
  console.log(err);
}
```
**Expected behavior**

Put Objects to Containers

**Screenshots**

```console
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at deserializeAws_restJson1PutObjectCommandError (/Users/jason.cheung/workspace/media_store/node/node_modules/@aws-sdk/client-mediastore-data/dist/cjs/protocols/Aws_restJson1.js:512:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/jason.cheung/workspace/media_store/node/node_modules/@aws-sdk/client-mediastore-data/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:7:20
    at async /Users/jason.cheung/workspace/media_store/node/node_modules/@aws-sdk/client-mediastore-data/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/jason.cheung/workspace/media_store/node/node_modules/@aws-sdk/client-mediastore-data/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:55:46)
    at async /Users/jason.cheung/workspace/media_store/node/node_modules/@aws-sdk/client-mediastore-data/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:7:22
    at async putchunkObject (/Users/jason.cheung/workspace/media_store/node/main.js:49:19)
    at async mediaService (/Users/jason.cheung/workspace/media_store/node/main.js:20:9)
    at async Socket.<anonymous> (/Users/jason.cheung/workspace/media_store/node/main.js:114:13) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    httpHeaders: {
      'x-amzn-requestid': 'SBEWSRBWXQAYNACVTWEG6YLHA5SL7FBYEJPH6YISBAXX2JOWWZN53BQRUZGFE6WPYBZ2QDNKN4QXNWMMPXQBIBQ',
      'x-amzn-errortype': 'InvalidSignatureException',
      'content-type': 'application/x-amz-json-1.1',
      'content-length': '192',
      date: 'Tue, 22 Dec 2020 02:44:56 GMT',
      connection: 'close'
    },
    requestId: 'SBEWSRBWXQAYNACVTWEG6YLHA5SL7FBYEJPH6YISBAXX2JOWWZN53BQRUZGFE6WPYBZ2QDNKN4QXNWMMPXQBIBQ',
    attempts: 3,
    totalRetryDelay: 365
  }
}

```
**Additional context**

I am using credential from cognito identity provider, I have already configured the correct policy for authRole and I can get the result from `listItems()`

**Comment by AllanZhengYP** [comment]
Hi @jncheung 

Thank you for reporting this. I will investigate this more. I think it may have something to do with https://github.com/aws/aws-sdk-js-v3/issues/1800#issuecomment-747378768. Can you try workaround it with https://github.com/aws/aws-sdk-js-v3/issues/1800#issuecomment-749459712? We will provide a bug fix soon.

**Comment by jncheung** [comment]
I tried the workaround and dig keep into the S3 document and found out that we also need to delete few more things to make it run. (But srsly why S3??? We are using MediaStore !!!)


```

        msd.middlewareStack.add((next, ctx)=> (args)=> {
            args.request.headers['Transfer-Encoding'] = 'chunked'
            delete args.request.headers['content-type']
            delete args.request.headers['Content-Length']
            delete args.request.headers['content-length']

            return next(args);
        },
        {
          step: "build",
        })

```

Since we are using the `streaming` feature, it is very similar to S3 multipart upload. 
if you are using `standard`, then keep the `content-length` header.

Here is the link to the document for other people to reference: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by ajredniwja** [comment]
Hey @jncheung this issue should have been fixed now, can you please confirm?

**Comment by jncheung** [comment]
I will try this in later time and closing this issue as well. 
let u guys know if there is any issues. 

thanks a lot.
