### ISSUE TITLE
util-dynamodb convertToAddr function does not identify objects with null prototype

### ISSUE THREAD

**Issue by EricCrosson** [aws/aws-sdk-js-v3#1861]
**Describe the bug**

[This line](https://github.com/aws/aws-sdk-js-v3/blob/314d3b37ac9d0d500e5762705be6188d9bd69625/packages/util-dynamodb/src/convertToAttr.ts#L17) does not identify objects created with a null prototype (i.e. `Object.create(null)`) and thus tries to decode a null-prototype object as a scalar value, eventually throwing the following error:
```
{ 
  type: 'aws',
  err: TypeError: Cannot convert object to primitive value
      at convertToScalarAttr (/home/eric/workspace/stratos/node_modules/@aws-sdk/util-dynamodb/src/convertToAttr.ts:122:47)
      at Object.convertToAttr (/home/eric/workspace/stratos/node_modules/@aws-sdk/util-dynamodb/src/convertToAttr.ts:20:12)
      at Object.marshall (/home/eric/workspace/stratos/node_modules/@aws-sdk/util-dynamodb/src/marshall.ts:29:41)
      at /home/eric/workspace/stratos/aws/lib/src/dynamo.ts:241:30
      at MapSink.event (/home/eric/workspace/stratos/node_modules/most/lib/fusion/Map.js:71:22)
      at TapSink.event (/home/eric/workspace/stratos/node_modules/most/lib/combinator/transform.js:81:13)
      at MapSink.event (/home/eric/workspace/stratos/node_modules/most/lib/fusion/Map.js:71:13)
      at PropagateTask.runJust [as _run] (/home/eric/workspace/stratos/node_modules/most/lib/source/core.js:46:8)
      at PropagateTask.run (/home/eric/workspace/stratos/node_modules/most/lib/scheduler/PropagateTask.js:43:8)
      at ScheduledTask.run (/home/eric/workspace/stratos/node_modules/most/lib/scheduler/ScheduledTask.js:20:20)
}
```

**SDK version number**

Installed from source today, so > 3.1.0 (currently unpublished)

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
v14.15.3

**To Reproduce (observed behavior)**
Try to marshall an object created with `Object.create(null)`

**Expected behavior**
`marshall` should marshall null-prototype objects in exactly the same was as it marshalls objects created with `{}`.

**Comment by trivikr** [comment]
Reopening this issue as it needs to be fixed in absence of configuration `convertClassInstanceToMap` added in https://github.com/aws/aws-sdk-js-v3/pull/1969

**Comment by trivikr** [comment]
Using `Object.entries()` on an object created via `Object.create()` results in an empty array being returned. The code to convert object needs to be modified.

https://github.com/aws/aws-sdk-js-v3/blob/10ab6a1d32807c55382b6e8877724d5120db31e6/packages/util-dynamodb/src/convertToAttr.ts#L108
