### ISSUE TITLE
Logger should log error in case of failure

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1912]
**Is your feature request related to a problem? Please describe.**
Logger does not log in case of failure.

<details>
<summary>Code</summary>

```js
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");
const logger = require("pino")({ prettyPrint: true });

(async () => {
  const region = "us-west-2";
  const Bucket = "test-logging-success-failure";
  const client = new S3({ region, logger });

  await client.createBucket({ Bucket });
  await waitForBucketExists({ client }, { Bucket });
  await client.deleteBucket({ Bucket });

  try {
    // HeadBucket for bucket which doesn't exist.
    // Logger will not log this error.
    await client.headBucket({
      Bucket: `test-bucket-${Math.ceil(Math.random() * 10 ** 10)}`,
    });
  } catch (error) {
    console.log(error);
  }
})();

```

</details>

<details>
<summary>Output</summary>

```console
{"level":30,"time":1610584981950,"pid":18837,"hostname":"147dda5df021.ant.amazon.com","clientName":"S3Client","commandName":"CreateBucketCommand","input":{"Bucket":"test-logging-success-failure"},"output":{"Location":"http://test-logging-success-failure.s3.amazonaws.com/"},"metadata":{"httpStatusCode":200,"extendedRequestId":"x/hM/ebHwtjfkYp5ELp/sURRzdtHzlQWBbaoSDlm6snAQ5CI4LoN4bEgbVQVwHWBzuOoEdol/40=","attempts":1,"totalRetryDelay":0}}

{"level":30,"time":1610584987051,"pid":18837,"hostname":"147dda5df021.ant.amazon.com","clientName":"S3Client","commandName":"HeadBucketCommand","input":{"Bucket":"test-logging-success-failure"},"output":{},"metadata":{"httpStatusCode":200,"extendedRequestId":"OWXHh0aeIU4GLebA/71y+D9btca8vR5FT+lFzm4YuV6dasr5emqCW23k1z6sKt5L7DKeAqMh9vE=","attempts":1,"totalRetryDelay":0}}

{"level":30,"time":1610584987273,"pid":18837,"hostname":"147dda5df021.ant.amazon.com","clientName":"S3Client","commandName":"DeleteBucketCommand","input":{"Bucket":"test-logging-success-failure"},"output":{},"metadata":{"httpStatusCode":204,"extendedRequestId":"ATVNP5CwyX/HZmtsL7cQeHMMfUftVgaL6pCSDZPnznE4gL6woa6Zg0Uj9Jz4LGLizEgnYNbQMCU=","attempts":1,"totalRetryDelay":0}}

NotFound: NotFound
    at deserializeAws_restXmlHeadBucketCommandError (/Users/trivikr/workspace/v2-vs-v3/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6405:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/v2-vs-v3/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/trivikr/workspace/v2-vs-v3/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/trivikr/workspace/v2-vs-v3/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /Users/trivikr/workspace/v2-vs-v3/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async /Users/trivikr/workspace/v2-vs-v3/logger.js:15:5 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: undefined,
    extendedRequestId: 'jxoDlsfBpnsKcR9W7OoJ0qtOmc5A5XmD+Cb3a1GVwaXEnCzhzpSv1lnw88e/MxhWYlkbGKdW+m0=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

</details>

**Describe the solution you'd like**
Logger should also log the errors.

**Describe alternatives you've considered**
Logging the errors myself in the client application code.

**Comment by trivikr** [comment]
This error is thrown in deserializer, and can be logged in a try-catch at https://github.com/aws/aws-sdk-js-v3/blob/130872194bc94590f599051ee067d862210252f8/packages/middleware-serde/src/deserializerMiddleware.ts#L20
