### ISSUE TITLE
S3 PutObject gives a PermanentRedirect error (301) on Vercel, in a Next.js application.

### ISSUE THREAD

**Issue by dyarleniber** [aws/aws-sdk-js-v3#1924]
**Describe the bug**
When I try to upload an image to S3 using the SDK in a Vercel environment I get an 301 error ("PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."). The exact same code with the same credentials works perfectly in a local environment.

**SDK version number**
```
"@aws-sdk/client-s3": "^3.2.0",
```

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
It runs in a Node.js Serverless Functions on Vercel
```
v14.15.4
```

**To Reproduce (observed behavior)**
Given a simple function like the following, with valid values for credentials, unique name as key, image file as body and an image mimetype as contentType. Running in a Node.js Serverless Functions on Vercel:
> The name of the env variables are `AWS_DEFAULT_ACCESS_KEY_ID` and `AWS_DEFAULT_SECRET_ACCESS_KEY`, since Vercel has some reserved variables.
```javascript
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

export const putObject = async (key, body, contentType) => {
  const s3 = new S3Client({
    region: "us-east-2",
    credentials: {
      accessKeyId: process.env.AWS_DEFAULT_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_DEFAULT_SECRET_ACCESS_KEY,
    },
  });

  // workaround for the issue: https://github.com/aws/aws-sdk-js-v3/issues/1800
  s3.middlewareStack.add(
    (next, context) => (args) => {
      delete args.request.headers["content-type"];
      return next(args);
    },
    {
      step: "build",
    }
  );

  const objectParams = {
    ACL: "public-read",
    Bucket: "folhetosonline",
    Key: key,
    Body: body,
    ContentType: contentType,
  };

  const results = await s3.send(new PutObjectCommand(objectParams));
  return results;
};
```

The response is:
```
[POST] /api/categories
17:02:14:80
ask_queues.js:97:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async putObject (/var/task/.next/serverless/pages/api/categories.js:1283:19)
    at async storeFile (/var/task/.next/serverless/pages/api/categories.js:1352:3)
    at async storeSEOImage (/var/task/.next/serverless/pages/api/categories.js:994:18)
    at async handleSEOImages (/var/task/.next/serverless/pages/api/categories.js:1016:11) {
  Code: 'PermanentRedirect',
  Endpoint: 'folhetosonline.s3.us-east-2.amazonaws.com',
  Bucket: 'folhetosonline',
  RequestId: '5BF03201AC030AC0',
  HostId: 'k7neCOYZ/vW58UbSFI6SbmkoxF4WvfwX7xwJUdJQrfW1NIam4VqxhjGbzwswW09QPC6XJ0PYvRU=',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 301,
    requestId: undefined,
    extendedRequestId: 'k7neCOYZ/vW58UbSFI6SbmkoxF4WvfwX7xwJUdJQrfW1NIam4VqxhjGbzwswW09QPC6XJ0PYvRU=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
2021-01-16T17:02:15.941Z  845db71e-7947-48de-92a4-f1a651f50d89  ERROR Unhandled Promise Rejection   {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.","reason":{"errorType":"PermanentRedirect","errorMessage":"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.","Code":"PermanentRedirect","Endpoint":"folhetosonline.s3.us-east-2.amazonaws.com","Bucket":"folhetosonline","RequestId":"5BF03201AC030AC0","HostId":"k7neCOYZ/vW58UbSFI6SbmkoxF4WvfwX7xwJUdJQrfW1NIam4VqxhjGbzwswW09QPC6XJ0PYvRU=","name":"PermanentRedirect","$fault":"client","$metadata":{"httpStatusCode":301,"extendedRequestId":"k7neCOYZ/vW58UbSFI6SbmkoxF4WvfwX7xwJUdJQrfW1NIam4VqxhjGbzwswW09QPC6XJ0PYvRU=","attempts":1,"totalRetryDelay":0},"stack":["PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.","    at deserializeAws_restXmlPutObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:8035:41)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20","    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24","    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)","    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22","    at async putObject (/var/task/.next/serverless/pages/api/categories.js:1283:19)","    at async storeFile (/var/task/.next/serverless/pages/api/categories.js:1352:3)","    at async storeSEOImage (/var/task/.next/serverless/pages/api/categories.js:994:18)","    at async handleSEOImages (/var/task/.next/serverless/pages/api/categories.js:1016:11)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

**Expected behavior**
I would expect upload my image on S3.

**Additional context**
As mentioned before, Vercel has some reserved variables related to AWS (https://vercel.com/docs/platform/limits#reserved-variables). Maybe this has some influence on this error.

**Comment by ajredniwja** [comment]
Hey @dyarleniber, thanks for opening this issue, was not able to reproduce this issue locally, as you mentioned as well this might be related to Vercel and not the SDK.  Can you set up a repo which gives out the same error?

**Comment by dyarleniber** [comment]
Hi, I renamed the environment variables by placing a suffix `_MYAPP` in each one, as follows:
```
AWS_ACCESS_KEY_ID_MYAPP=
AWS_SECRET_ACCESS_KEY_MYAPP=
AWS_REGION_MYAPP=
AWS_BUCKET_MYAPP=
```
And it's working now.

This is a repository with a example: https://github.com/dyarleniber/aws-sdk-js-v3-s3-vercel-example.

This issue can be closed.
