### ISSUE TITLE
Unable to upload file to S3 from ReadableStream due to "ENOENT: no such file or directory, lstat"

### ISSUE THREAD

**Issue by mmykhaylov** [aws/aws-sdk-js-v3#2059]
## Describe the bug
I am unable to upload a file to my S3 bucket if I pass a ReadableStream to Body of PutObjectCommand

## Your environment
AWS Lambda Node.js 12.x Environment

#### SDK version number
@aws-sdk/client-s3@3.6.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
—

## Steps to reproduce
Error happens inside a resolver of Apollo Server, set up as a Lamda function:
```js
// awsSetup.js
import { S3Client } from '@aws-sdk/client-s3';

const AWS_REGION = 'REGION';

export const bucketName = 'BUCKET_NAME';

export const s3Client = new S3Client({
  region: AWS_REGION,
});

// index.js
const resolvers = {
  uploadFile: async (_, args) => {
    const { createReadStream, filename, mimetype, encoding } = await args.file;
    const uploadParams = {
      Bucket: bucketName,
      Key: `${uuidv4()}${extname(filename)}`,
      ContentType: mimetype,
      Body: createReadStream(),
    };
    const result = await s3Client.send(new PutObjectCommand(uploadParams));
    return {
      filename,
      mimetype,
      encoding,
      uri: JSON.stringify(result),
    };
  },
};

const typeDefs = gql`
  type File {
    uri: String!
    filename: String!
    mimetype: String!
    encoding: String!
  }
  type Mutation {
    uploadFile(file: Upload!): File
  }
`;

const server = new ApolloServer({
  uploads: {
    maxFileSize: 5000000,
  },
  typeDefs,
  resolvers,
});

const graphql = server.createHandler({
  cors: {
    origin: true,
    credentials: true,
  },
});

export { graphql };
```

I created a query.sh file with this content
```shell
curl $1 \
  -F operations='{ "query": "mutation ($file: Upload!) { uploadFile(file: $file) { uri filename mimetype encoding } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@$2
```

To make a query I run:
```shell
./query.sh ENDPOINT_URL FILE_PATH
```

#### Observed behavior
Error isn't showing up on the CloudWatch logs, however the request returns an error
```json
{
  "errors": [
    {
      "message": "ENOENT: no such file or directory, lstat",
      "locations": [{ "line": 1, "column": 29 }],
      "path": ["uploadFile"],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errno": -2,
          "syscall": "lstat",
          "code": "ENOENT",
          "stacktrace": [
            "Error: ENOENT: no such file or directory, lstat",
            "    at Object.lstatSync (fs.js:1007:3)",
            "    at calculateBodyLength (/var/task/node_modules/@aws-sdk/util-body-length-node/dist/cjs/index.js:21:21)",
            "    at /var/task/node_modules/@aws-sdk/middleware-content-length/dist/cjs/index.js:15:32",
            "    at /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/serializerMiddleware.js:6:12",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22",
            "    at async uploadFile (/var/task/src/handlers.js:2:3746)"
          ]
        }
      }
    }
  ],
  "data": { "uploadFile": null }
}
```

#### Expected behavior
File successfully uploads with no errors

#### Screenshots
—

## Additional context
If I replace uploadParams with this, the upload goes fine, implying that the problem is with the ReadableStream
```js
const uploadParams = {
        Bucket: bucketName,
        Key: 'test.txt',
        ContentType: 'text/plain',
        Body: 'test',
      };
```

**Comment by alexforsyth** [comment]
This is probably coming from fs. lstat is used to figure out file stats. It's saying it cannot actually find your file 'uploadFile'.

Or.. even easier ... you should be able to do use Upload to get around this:

```
import { S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";

const client = new S3Client({
    region,
    credentials: fromCognitoIdentityPool({
      client: new CognitoIdentityClient({ region }),
      identityPoolId: idPool,
    }),
  });

  const Key = configuration.Key;

  let upload = new Upload({
    client,
    params: {
      Key,
      Bucket,
      Body: fakeStreamOfUnknownlength,
    },
  });

  upload.on("httpUploadProgress", (progress: ProgressEvent) => {
    console.log(progress);
  });

  const uploadResult = await upload.done();
  console.log("done uploading", uploadResult);
  ```
