### ISSUE TITLE
Cannot filter by "Charge Type" on "GetCostAndUsageCommand"

### ISSUE THREAD

**Issue by matiasdecarli** [aws/aws-sdk-js-v3#2115]
## Describe the bug
I'm trying to filter by `Charge Type` on to my `GetCostAndUsageCommand` from the SDK, so far with no luck

```
const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {      
      Dimensions: {
        Key: "CHARGE_TYPE",
        Values: [ "USAGE"]
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }]    
  }
```

#### SDK version number
`@aws-sdk/client-cost-explorer": "3.5.0`

#### Is the issue in the browser/Node.js/ReactNative?
node.js

#### Details of the browser/Node.js/ReactNative version
```
node --version
v14.15.1
```

## Steps to reproduce
```
async function getCostReportForTheDay (startDate, endDate) {
  const client = new CostExplorerClient({})

  const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {      
      Dimensions: {
        Key: "CHARGE_TYPE",
        Values: [ "USAGE"]
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }]    
  }

  const command = new GetCostAndUsageCommand(params)

  try {
    const data = await client.send(command)

    return data
  } catch (error) {
    throw new Error(error)
  }
}
```

#### Observed behavior
```
{
    "errorMessage": "ValidationException: Dimension CHARGE_TYPE is not allowed. Allowed dimension(s): SAVINGS_PLAN_ARN, RESERVATION_ID, AZ, CACHE_ENGINE, INSTANCE_TYPE_FAMILY, INSTANCE_TYPE, SAVINGS_PLANS_TYPE, PURCHASE_TYPE, LINKED_ACCOUNT, REGION, SERVICE, LEGAL_ENTITY_NAME, USAGE_TYPE, PLATFORM, USAGE_TYPE_GROUP, OPERATION, OPERATING_SYSTEM, DATABASE_ENGINE, TENANCY, BILLING_ENTITY, RECORD_TYPE, DEPLOYMENT_OPTION",
    "errorType": "Error",
    "stackTrace": [
        "Error: ValidationException: Dimension CHARGE_TYPE is not allowed. Allowed dimension(s): SAVINGS_PLAN_ARN, RESERVATION_ID, AZ, CACHE_ENGINE, INSTANCE_TYPE_FAMILY, INSTANCE_TYPE, SAVINGS_PLANS_TYPE, PURCHASE_TYPE, LINKED_ACCOUNT, REGION, SERVICE, LEGAL_ENTITY_NAME, USAGE_TYPE, PLATFORM, USAGE_TYPE_GROUP, OPERATION, OPERATING_SYSTEM, DATABASE_ENGINE, TENANCY, BILLING_ENTITY, RECORD_TYPE, DEPLOYMENT_OPTION",
        "    at getCostReportForTheDay (/Users/matias/Workspace/justos/Aws-Slack-CostReport/report.js:95:11)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at daily (/Users/matias/Workspace/justos/Aws-Slack-CostReport/report.js:20:16)"
    ]
}
```

#### Expected behavior
I would expect this call to returns the same thing that i'm seeing on the billing dashboard, being able to filter by usage and remove the credits that i have in my account

#### Screenshots
<img width="255" alt="Screen Shot 2021-03-08 at 19 33 07" src="https://user-images.githubusercontent.com/2442390/110390732-30842f00-8045-11eb-928d-fd55185ea31d.png">

**Comment by ajredniwja** [comment]
Hi @matiasdecarli, thanks for opening this issue, looking at the [API Reference](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_DimensionValues.html), unfortunately it looks like it has not been implemented in the SDKs. 

I will mark it as a feature request for the `costExplorer` team.

**Comment by ajredniwja** [comment]
Will transfer this to a unified repo for all the SDKs as this will effect other SDKs as well.
