### ISSUE TITLE
Misleading and inconsistent error when credentials are unset

### ISSUE THREAD

**Issue by spencerwilson** [aws/aws-sdk-js-v3#2137]
## Describe the bug
When making an API request without any [credentials set](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html), the SDK throws/rejects with a misleading and inconsistent error.

#### SDK version number
`@aws-sdk/client-sts@3.8.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the Node.js version
v15.6.0

## Steps to reproduce

1. Attempt to send a command like `GetCallerIdentityCommand`, with the env var `AWS_REGION` set to something valid (e.g., `us-west-2`) but no credentials in any of the supported locations.

#### Observed behavior
When the error is `console.log`'d, either
```
Error: TimeoutError
    at ClientRequest.<anonymous> (/Users/ssw/code/api/node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/httpRequest.js:17:20)
    at ClientRequest.emit (node:events:379:20)
    at Socket.emitRequestTimeout (node:_http_client:812:9)
    at Object.onceWrapper (node:events:485:28)
    at Socket.emit (node:events:391:22)
    at Socket._onTimeout (node:net:482:8)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```
or
```
ProviderError: Unable to connect to instance metadata service
    at ClientRequest.<anonymous> (/Users/ssw/code/api/node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/httpRequest.js:14:34)
    at ClientRequest.emit (node:events:379:20)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:379:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  tryNextLink: true,
  errno: -64,
  code: 'EHOSTDOWN',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```
_Which_ exception is thrown is nondeterministic, in my experience.

#### Expected behavior
The error should be deterministic, and have a `message` or some other property that explicitly indicates that the credential resolution process found no credentials. Then perhaps within that somehow, nest the timeout/instance metadata service error (since the user might actually be intending to leverage getting credentials via that service).

## Additional context
I think this issue might be the v3 version of https://github.com/aws/aws-sdk-js/issues/849. In the [explanation](https://github.com/aws/aws-sdk-js/issues/849#issuecomment-247725567) there, they referenced
> We do then overwrite the error code to be CredentialsError, as you can see in the code property of the error you logged, but the error name did not get changed, and it shows up as [TimeoutError: ...]. I will mark this as a bug, since the error name is intended to change to CredentialsError.

That sounds good. Does v3 have something similar, or could it?

**Comment by clindsey** [comment]
i ran into this issue also, the error message was no help and it also turned out to be a credentials issue.  In my case it was because i was wiping out the environment variables my app received (webpack defineplugin) and the error messages didn't mention anything about credentials/auth

**Comment by ajredniwja** [comment]
Hi @clindsey @spencerwilson you are right and the explanation in the comment holds true for this case as well. There is an open PR for this which should solve the issue. https://github.com/aws/aws-sdk-js-v3/pull/2408
