### ISSUE TITLE
V3 SDK s3 managed uploader fails with older api version - V2 is fine

### ISSUE THREAD

**Issue by marcolarosa** [aws/aws-sdk-js-v3#2144]
## Describe the bug
Using `Upload` from `@aws-sdk/lib-storage` against a fake S3 endpoint (RadosGW running Ceph Nautilus.) fails. The V2 equivalent works fine with the same endpoint.

## Your environment

RadosGW running Ceph Nautilus. API Version: '2006-03-01'.

#### SDK version number
```
"@aws-sdk/client-s3": "^3.8.1"
"@aws-sdk/lib-storage": "^3.8.1"
"aws-sdk": "^2.865.0"
```

#### Is the issue in the browser/Node.js/ReactNative?
Node

#### Details of the browser/Node.js/ReactNative version
v14.16.0

## Steps to reproduce
I've created a test with the v2 and v3 codes. https://github.com/marcolarosa/test-s3-multipart-upload.

#### Observed behavior
The V3 uploader fails with:
```
*** MalformedXML: MalformedXML
    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4170:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Upload.__doMultipartUpload (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/lib-storage/dist/cjs/Upload.js:104:41)
    at async Upload.done (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/lib-storage/dist/cjs/Upload.js:45:16)
    at async v3MultipartUpload (/home/debian/src/test-s3-multipart-upload/test-s3-multipart-upload.js:103:17)
    at async /home/debian/src/test-s3-multipart-upload/test-s3-multipart-upload.js:30:2 {
  Code: 'MalformedXML',
  BucketName: '1190_pdsc_2020',
  RequestId: 'tx000000000000000021d31-006051895d-91267cb-unimelb-qh2',
  HostId: '91267cb-unimelb-qh2-unimelb',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
Either it should be backwards compatible with responses from older API versions or fail early stating
that the API version is not compatible.

## Additional context
From the operators of the fake S3 service:

> I can verify that v3 upload class errored out. I've tested the upload on a 
> 100GB file with 1910 parts and it looks like the uploader works fine until the end, 
> where it probably aggregates the parts metadata and raises a MalformedXML.

**Comment by alexforsyth** [comment]
I have a feeling this is may be an issue with the custom S3 service implementation, but its curious that v2 works and v3 doesn't. Looks like [the current version](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html) of s3 is `2006-03-01`.

 In v3 we use service generated models to code generate the s3 client and upload wraps multipart upload from that generated s3 client. This is because the raw multipart upload is a pain to use. I've tested this with an extremely large file and it seems to work just fine for me against amazon's s3. Unfortunately, I'm having trouble reproducing the error against your custom endpoint. Can you let me know what the error looks like if we run an old school multipart upload?
 
 something like:
 ```
import {
    CompleteMultipartUploadCommand,
    CreateMultipartUploadCommand,
    S3Client,
    UploadPartCommand,
  } from "@aws-sdk/client-s3";


(async () => {
    const client = new S3Client({
        ...
    });

    const createMultipartUploadResult = await client.send(new CreateMultipartUploadCommand({
        ...
    }));

    const PartNumber = 1;
    const partResult = await client.send(
        new UploadPartCommand({
            UploadId: createMultipartUploadResult.UploadId,
            Body: "this is the first and only part",
            PartNumber,
        })
    );

    const uploadedParts = [];
    uploadedParts.push({
        PartNumber,
        ETag: partResult.ETag,
    });

    const completeMultipartUpload = await client.send(
        new CompleteMultipartUploadCommand({
            UploadId: createMultipartUploadResult.UploadId,
            MultipartUpload: {
            Parts: uploadedParts,
            },
        })
    );
})();
```

This code may need minor tinkering.

**Comment by marcolarosa** [comment]
hi @alexforsyth 

I've updated the repo with another method containing this code. It fails at the complete step. Here's the output from that stage:

```
{
  apiVersion: '2006-03-01',
  disableHostPrefix: false,
  logger: {},
  regionInfoProvider: [Function: defaultRegionInfoProvider],
  serviceId: 'S3',
  signingEscapePath: false,
  urlParser: [Function: parseUrl],
  useArnRegion: [Function (anonymous)],
  runtime: 'node',
  base64Decoder: [Function: fromBase64],
  base64Encoder: [Function: toBase64],
  bodyLengthChecker: [Function: calculateBodyLength],
  credentialDefaultProvider: [Function: defaultProvider],
  defaultUserAgentProvider: [AsyncFunction (anonymous)],
  eventStreamSerdeProvider: [Function: eventStreamSerdeProvider],
  maxAttempts: [Function (anonymous)],
  md5: [Function: bound Hash],
  region: [Function (anonymous)],
  requestHandler: NodeHttpHandler {
    metadata: { handlerProtocol: 'http/1.1' },
    connectionTimeout: undefined,
    socketTimeout: undefined,
    httpAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      [Symbol(kCapture)]: false
    },
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: [Object],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: 50,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    }
  },
  sha256: [Function: bound Hash],
  streamCollector: [Function: streamCollector],
  streamHasher: [Function: fileStreamHasher],
  utf8Decoder: [Function: fromUtf8],
  utf8Encoder: [Function: toUtf8],
  endpoint: [Function (anonymous)],
  credentials: [Function (anonymous)],
  tls: true,
  isCustomEndpoint: true,
  retryStrategy: StandardRetryStrategy {
    maxAttemptsProvider: [Function (anonymous)],
    mode: 'standard',
    retryDecider: [Function: defaultRetryDecider],
    delayDecider: [Function: defaultDelayDecider],
    retryQuota: {
      hasRetryTokens: [Function: hasRetryTokens],
      retrieveRetryTokens: [Function: retrieveRetryTokens],
      releaseRetryTokens: [Function: releaseRetryTokens]
    }
  },
  systemClockOffset: 0,
  signer: [Function: signer],
  bucketEndpoint: false,
  forcePathStyle: false,
  useAccelerateEndpoint: false,
  useDualstackEndpoint: false,
  customUserAgent: undefined,
  eventStreamMarshaller: EventStreamMarshaller {
    eventMarshaller: EventStreamMarshaller { headerMarshaller: [HeaderMarshaller] },
    universalMarshaller: EventStreamMarshaller {
      eventMarshaller: [EventStreamMarshaller],
      utfEncoder: [Function: toUtf8]
    }
  }
}
(node:8866) UnhandledPromiseRejectionWarning: MalformedXML: MalformedXML
    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4171:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /home/debian/src/test-s3-multipart-upload/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async v3MultipartManualUpload (/home/debian/src/test-s3-multipart-upload/test-s3-multipart-upload.js:70:37)
    at async /home/debian/src/test-s3-multipart-upload/test-s3-multipart-upload.js:34:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:8866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marcolarosa** [comment]
hi devs! any word on this ?

**Comment by rlueder** [comment]
This is related to https://github.com/aws/aws-sdk-js-v3/issues/1814 there's a PR open with a fix at https://github.com/aws/aws-sdk-js-v3/pull/2434
