### ISSUE TITLE
EventBridge PutTargets validation error

### ISSUE THREAD

**Issue by nazarvovk** [aws/aws-sdk-js-v3#2240]
## Describe the bug
Regex validation fails on ARN

#### SDK version number
`@aws-sdk/client-eventbridge@3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
AWS_Lambda_nodejs14.x

## Steps to reproduce
```ts
const rule = await this.eventBridge.putRule({
  Name: 'Test',
  ScheduleExpression: scheduleExpression,
})

await this.eventBridge.putTargets({
  Rule: ensure(rule.RuleArn),
  Targets: [
    {
      Id: 'TestID',
      Arn: targetArn,
      Input: JSON.stringify(event),
    },
  ],
})
```

#### Observed behavior
```json
"error": {
    "type": "Error",
    "message": "1 validation error detected: Value 'arn:aws:events:eu-west-1:<omitted>:rule/Test' at 'rule' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\.\\-_A-Za-z0-9]+",
    "stack": "ValidationException: 1 validation error detected: Value 'arn:aws:events:eu-west-1:<omitted>:rule/Test' at 'rule' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\.\\-_A-Za-z0-9]+\n    at deserializeAws_json1_1PutTargetsCommandError (/var/task/index.js:78054:41)\n        -> /node_modules/@aws-sdk/client-eventbridge/protocols/Aws_json1_1.ts:3048:39\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /var/task/index.js:63826:20\n        -> /node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18\n    at async /var/task/index.js:66232:22\n        -> /node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22\n    at async StandardRetryStrategy.retry (/var/task/index.js:69106:38)\n        -> /node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38\n    at async /var/task/index.js:71290:22\n        -> /node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20\n    at async EventBusTransportEventBridge.schedule (/var/task/index.js:139472:5)\n        -> /src/shared/services/event-bus/event-bus-transport-event-bridge.ts:55:5\n    at async CreateReportSchedulesUseCase.execute (/var/task/index.js:140648:5)\n        -> /src/modules/selling-partner/use-cases/create-report-schedules/create-report-schedules.ts:49:5\n    at async Object.<anonymous> (/var/task/index.js:140671:3)\n        -> /src/modules/selling-partner/infra/report-collection-scheduler/report-collection-scheduler.ts:45:5",
    "__type": "ValidationException",
    "name": "ValidationException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "24d73532-2fa6-4860-bc61-a948b0e2e72f",
        "attempts": 1,
        "totalRetryDelay": 0
    }
},
```

#### Expected behavior
Should work. Seems like it validates the string of `ARN+provided_id`, and because ARN has colons, validation fails

**Comment by ajredniwja** [comment]
Hi @nazarvovk thanks for opening this issue, can you change the `Rule` to name of the rule, looking [here](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html#API_PutTargets_RequestSyntax) the rule needs to be the name of the rule and not an `ARN`, changing that to the name makes the code work. 

Closing this issue now, please reach out if that doesnt solve the problem.
