### ISSUE TITLE
When an error occurs the original stack is not preserved and you do not know the call location

### ISSUE THREAD

**Issue by w-turner-getbamboo-io** [aws/aws-sdk-js-v3#2261]
## Describe the bug

When an error occurs the original stack is not preserved and you do not know the call location

e.g.

```
"AccessDeniedException: User:  is not authorized to perform: secretsmanager:GetSecretValue on resource: ZZZZ",
        "    at call (/var/task/webpack:/node_modules/@aws-sdk/client-secrets-manager/dist/es/protocols/Aws_json1_1.js:857:68)",
        "    at step (/var/task/webpack:/node_modules/@aws-sdk/client-secrets-manager/node_modules/tslib/tslib.es6.js:102:23)",
        "    at Object.next (/var/task/webpack:/node_modules/@aws-sdk/client-secrets-manager/node_modules/tslib/tslib.es6.js:83:53)",
        "    at i (/var/task/webpack:/node_modules/@aws-sdk/client-secrets-manager/node_modules/tslib/tslib.es6.js:73:58)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

This is similar to[ this issue](https://github.com/aws/aws-sdk-js-v3/issues/1287)

#### SDK version number
`@aws-sdk/client-secrets-manager@3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
(the version that runs on aws lambda, 12.x)

## Steps to reproduce

1) request a Secret that does not exist
```
const client = new SecretsManagerClient({ region: expectedEnv.AWS_REGION });
var command = new GetSecretValueCommand({ SecretId: "does-not-exist" });
 const result = await client.send(command);
```

#### Observed behavior
original stack trace is not included in error details

#### Expected behavior

expecting original stack trace to be included in error details

**Comment by ajredniwja** [comment]
Hi @w-turner-getbamboo-io, thanks for opening this issue, I am not quite able to understand the ask here, it seems that this is a server side error so this seems to be expected behavior.

**Comment by w-turner-getbamboo-io** [comment]
Hi @ajredniwja  can you see this response by your collage @AllanZhengYP
https://github.com/aws/aws-sdk-js-v3/issues/1287#issuecomment-711439271

not sure why this behavior is to be expected when you can preserve the stack and make debugging easier?

**Comment by ajredniwja** [comment]
@w-turner-getbamboo-io I do get something like: 

```

ResourceNotFoundException: Secrets Manager can't find the specified secret.
    at deserializeAws_json1_1GetSecretValueCommandError (/path/to/node_modules/@aws-sdk/client-secrets-manager/dist/cjs/protocols/Aws_json1_1.js:808:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /path/to/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /path/to/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (path/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /path/node_modules/@aws-sdk/client-secrets-manager/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async /path/to/GH2261.js:7:24 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '48b6fe50-bd4a-40b7-80ba-84e091f389',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
