### ISSUE TITLE
Mismatch Credential Type (@aws-sdk/client-ec2 and @aws-sdk/client-sts)

### ISSUE THREAD

**Issue by endercrest** [aws/aws-sdk-js-v3#2273]
## Describe the bug
Looks like there is a mismatch between credential types in `@aws-sdk/client-ec2`, `@aws-sdk/client-sts` such that credentials generated by the Security Token Service SDK can't directly be used in the EC2 SDK. 

Type defintion of `Credentials` from `@aws-sdk/client-ec2`
```js
interface Credentials {
    /**
     * AWS access key ID
     */
    readonly accessKeyId: string;
    /**
     * AWS secret access key
     */
    readonly secretAccessKey: string;
    /**
     * A security or session token to use with these credentials. Usually
     * present for temporary credentials.
     */
    readonly sessionToken?: string;
    /**
     * A {Date} when these credentials will no longer be accepted.
     */
    readonly expiration?: Date;
}
```

Type defintion of `Credentials` from `@aws-sdk/client-sts`
```js
interface Credentials {
    /**
     * <p>The access key ID that identifies the temporary security credentials.</p>
     */
    AccessKeyId: string | undefined;
    /**
     * <p>The secret access key that can be used to sign requests.</p>
     */
    SecretAccessKey: string | undefined;
    /**
     * <p>The token that users must pass to the service API to use the temporary
     *          credentials.</p>
     */
    SessionToken: string | undefined;
    /**
     * <p>The date on which the current credentials expire.</p>
     */
    Expiration: Date | undefined;
}
```

#### SDK version number
`@aws-sdk/client-ec2@3.12.0`
`@aws-sdk/client-sts@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
v15.10.0
```

## Steps to reproduce

```js
const credentialsProvider = fromIni({ profile: argv.profile });

const roleCredentialsProvider = async () => {
  const client = new STSClient({ region: 'us-east-1', credentials: credentialsProvider});

  const assumeRoleRequest = new AssumeRoleCommand({
    RoleArn: 'arn:aws:iam::<ACCOUNT_HERE>:role/<ROLE_HERE>',
    RoleSessionName: '<SESSION_NAME>',
  });

  const response = await client.send(assumeRoleRequest);

  return response.Credentials;
};

const client = new EC2Client({ region: 'us-east-1', credentials: roleCredentialsProvider });
```

#### Observed behavior
The error that results in this incorrect value being passed in.
```
TypeError: Cannot read property 'byteLength' of undefined
    at Object.fromArrayBuffer (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/util-buffer-from/dist/cjs/index.js:6:60)
    at castSourceData (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/hash-node/dist/cjs/index.js:29:31)
    at Hash.update (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/hash-node/dist/cjs/index.js:12:26)
    at hmac (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/signature-v4/dist/cjs/credentialDerivation.js:60:10)
    at Object.getSigningKey (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/signature-v4/dist/cjs/credentialDerivation.js:32:29)
    at SignatureV4.getSigningKey (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:139:39)
    at SignatureV4.signRequest (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:98:73)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:14:22
    at async StandardRetryStrategy.retry (/Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /Users/tcvs/Development/Tulip/tulip/environments/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async initSpotInstances (/Users/tcvs/Development/Tulip/tulip/environments/cypress/loadTest/ec2LoadTest.js:171:30)
    at async main (/Users/tcvs/Development/Tulip/tulip/environments/cypress/loadTest/ec2LoadTest.js:255:18) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

#### Expected behaviour
Expected that I would be able to pass the credentials object directly or at least have a more usuable error to make this more easily debuggable.

**Comment by jackallnutt** [comment]
I am experiencing the same problem with `@aws-skd/client-s3`.

**Comment by Frogvall** [comment]
This is not unique to any particular client. It goes for all of them. 

The problem arise in the shared file `@aws-sdk/signature-v4/dist/cjs/credentialDerivation.js`

```js
const getSigningKey = async (sha256Constructor, credentials, shortDate, region, service) => {
    const credsHash = await hmac(sha256Constructor, credentials.secretAccessKey, credentials.accessKeyId); // undefined
    const cacheKey = `${shortDate}:${region}:${service}:${util_hex_encoding_1.toHex(credsHash)}:${credentials.sessionToken}`;
    if (cacheKey in signingKeyCache) {
        return signingKeyCache[cacheKey];
    }
    cacheQueue.push(cacheKey);
    while (cacheQueue.length > constants_1.MAX_CACHE_SIZE) {
        delete signingKeyCache[cacheQueue.shift()];
    }
    let key = `AWS4${credentials.secretAccessKey}`;
    for (const signable of [shortDate, region, service, constants_1.KEY_TYPE_IDENTIFIER]) {
        key = await hmac(sha256Constructor, key, signable);
    }
    return (signingKeyCache[cacheKey] = key);
};
```

**Comment by AllanZhengYP** [comment]
Hi @endercrest 

The issue is caused by the fact that SDK internally uses lower-cased key for credentials: https://github.com/aws/aws-sdk-js-v3/blob/72cc2dc89f89b6f3290bed623ebb43e5725bed0d/packages/types/src/credentials.ts#L10-L27
However, all the credentials keys from the STS response are upper-cased: https://github.com/aws/aws-sdk-js-v3/blob/3bd30bb798cee9739b98842cfdca5a6b60dec124/clients/client-sts/models/models_0.ts#L301-L320

since we cannot change any of them, but we can provide better error message by asserting the resolved credentials before signing the request to make sure all the expired keys are lower-cased. I will post a PR fixing it.

**Comment by Frogvall** [comment]
Hey @AllanZhengYP, thanks for looking into this.

Fixing a better error message is a good start and saves your customers from having to debug your code in order to figure out what's wrong.

I do however think you can do more. You can have the sts sdk transform the object into lower case before returning it to the customer, saving them from having to deal with the internal logic of AWS, which they shouldn't have to be concerned about. Otherwise you push this transformation on each and every customer.
