### ISSUE TITLE
"not implemented" error when trying to use a AWS SDK JS v3 client with react-native

### ISSUE THREAD

**Issue by kmalkan** [aws/aws-sdk-js-v3#2288]
## Describe the bug
I am trying to make an API call using the Rekognition V3 client in my react-native application but am encountering this error whenever I try to test the call in the app on my iOS emulator:

```
not implemented
at node_modules/react-native/Libraries/Blob/URL.js:169:10 in get__hostname
at node_modules/@aws-sdk/url-parser-node/dist/cjs/index.js:6:4 in parseUrl
at node_modules/@aws-sdk/client-rekognition/node_modules/@aws-sdk/config-resolver/dist/cjs/EndpointsConfig.js:26:30 in getEndPointFromRegion
```

#### SDK version number
`@aws-sdk/rekognition@3.13.0`

#### Is the issue in the browser/Node.js/ReactNative?
ReactNative

#### Details of the browser/Node.js/ReactNative version
react-native-cli: 2.0.1
react-native: 0.63.2

## Steps to reproduce
Using Amplify Auth get valid AWS credentials:

```
private getCredentials = async () => {
    if (!this.credentials) {
      const credentials = await Auth.currentCredentials();
      this.credentials = Auth.essentialCredentials(credentials);
    }

    return this.credentials;
  };

  getRekognition = async () => {
    if (!this.rekognition) {
      const credentials = await this.getCredentials();
      this.rekognition = new Rekognition(credentials, region);
    }
    return this.rekognition;
  };
```

```
    async () => {
      const rekognition = await clients.getRekognition();
      return await rekognition.listProjects();
    }
```

#### Observed behavior
The app renders and the error appears in the console once the page renders and the app tries to initialize the client and make the API call

#### Expected behavior
The client should initialize and the application should successfully call the API and get a response.

**Comment by kmalkan** [comment]
Solution: 

You need to install react-native polyfills.

Instructions under Getting Started https://github.com/aws/aws-sdk-js-v3#getting-started
