### ISSUE TITLE
"TypeError: input is not async iterable" when using StartMedicalStreamTranscriptionCommand

### ISSUE THREAD

**Issue by drewmcd621** [aws/aws-sdk-js-v3#2291]
## Describe the bug

A TypeError is being thrown in EventStreamPayloadHandler.js (line 52) I believe while trying to parse TranscriptResultStream from the result of a successful StartMedicalStreamTranscriptionCommand.

#### SDK version number
@aws-sdk/client-transcribe-streaming v3.12.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.16.1

## Steps to reproduce

1. Create a TranscribeStreamingClient
2. Create a StartMedicalStreamTranscriptionCommand with the following parameters:
```
{
  LanguageCode: 'en-US',
  MediaEncoding: 'ogg-opus',
  MediaSampleRateHertz: 16000,
  Specialty: 'PRIMARYCARE',
  Type: 'DICTATION',
  AudioStream: {
    AudioEvent: {
      AudioChunk: <base64 encoded ogg opus file>
    }
  }
}
```

3. Send the command with the client and await the response. 

#### Observed behavior
A TypeError is thrown, there still appears to be some data returned but the TranscriptResultStream is not iterable despite it appearing to be an async generator:

```
  TranscriptResultStream: {
    [Symbol(Symbol.asyncIterator)]: [AsyncGeneratorFunction: [Symbol.asyncIterator]]
  }
```

#### Expected behavior
Some ability to iterate over the TranscriptResultStream in order to retrieve data or if I am doing something incorrect a more informative error message of the issue that is going on.

#### Screenshots
N/A

## Additional context
Request ID: 44591330-60d1-4539-bb0c-87cdff4e8604
Session ID: b3834a9d-ee5e-4299-9b91-3174187d44fd

Stack trace of exception:

```
node_modules\@aws-sdk\eventstream-handler-node\dist\cjs\EventStreamPayloadHandler.js:52
                throw err;
                ^

TypeError: input is not async iterable
    at Object.serializedIterator (\node_modules\@aws-sdk\eventstream-serde-universal\dist\cjs\EventStreamMarshaller.js:25:39)
    at serializedIterator.next (<anonymous>)
    at next (internal/streams/from.js:77:46)
    at Readable.readable._read (internal/streams/from.js:51:7)
    at Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Log of returned data:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '386114ac-c2c3-4538-acc9-b0dfd2cd65c4',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  EnableChannelIdentification: false,
  LanguageCode: 'en-US',
  MediaEncoding: 'ogg-opus',
  MediaSampleRateHertz: 16000,
  NumberOfChannels: undefined,
  RequestId: '386114ac-c2c3-4538-acc9-b0dfd2cd65c4',
  SessionId: '8131dd1d-2050-4948-8a72-a96377d8eded',
  ShowSpeakerLabel: false,
  Specialty: 'PRIMARYCARE',
  TranscriptResultStream: {
    [Symbol(Symbol.asyncIterator)]: [AsyncGeneratorFunction: [Symbol.asyncIterator]]
  },
  Type: 'DICTATION',
  VocabularyName: undefined
}
```

**Comment by drewmcd621** [comment]
Figure out that the audio stream input was incorrect and that's why the error was showing up, I do think the error should be clearer but I'm closing the issue.
