### ISSUE TITLE
The waiter configuration should accept abortSignal and not AbortController

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2316]
## Describe the bug
The waiter configuration accepts abortController https://github.com/aws/aws-sdk-js-v3/blob/9ac1f40eea78075e6b301df50cfae17c19ad77c3/packages/util-waiter/src/waiter.ts#L14-L17

This is not following [AbortController spec](https://dom.spec.whatwg.org/#aborting-ongoing-activities) which recommends APIs to accept AbortSignal object.

> The API which wishes to support aborting can accept an AbortSignal object, and use its state to determine how to proceed.

#### SDK version number
`@aws-sdk/client-s3@3.13.1`
`@aws-sdk/util-waiter@3.13.1`

#### Is the issue in the browser/Node.js/ReactNative?
All

#### Details of the browser/Node.js/ReactNative version
Tested in Node.js v14.16.1

## Steps to reproduce
Code which passes AbortController to waiter

```js
const {
  S3Client,
  CreateBucketCommand,
  waitUntilBucketExists,
} = require("../waiters/aws-sdk-js-v3/clients/client-s3");

(async () => {
  const region = "us-west-2";
  const client = new S3Client({ region });

  const Bucket = "test-bucket-for-abort-controller";
  await client.send(new CreateBucketCommand({ Bucket }));
  const abortController = new AbortController();
  const waiterPromise = waitUntilBucketExists(
    { client, maxWaitTime: 60, abortController },
    { Bucket }
  );

  abortController.abort();
  try {
    await waiterPromise;
  } catch (error) {
    console.log(error);
  }
})();

```

Note: Code is written on waitUntilOperationName which is introduced in https://github.com/aws/aws-sdk-js-v3/pull/2302

#### Observed behavior

The error is thrown as expected:

```console
$ Error: ABORTED
    at waitUntilBucketExists (/local/home/trivikr/workspace/waiters/aws-sdk-js-v3/clients/client-s3/dist/cjs/waiters/waitForBucketExists.js:41:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /local/home/trivikr/workspace/test-waiters/abortController.js:24:5
```

However, the entire AbortController is sent to API when only AbortSignal needs to be sent.
The spec requires API to only expect AbortSignal. If API accepts AbortController, it can call `.abort()` internally.

#### Expected behavior

Accept abortSignal like it's done in [client.send() operation](https://aws.amazon.com/blogs/developer/abortcontroller-in-modular-aws-sdk-for-javascript/), and deprecate `abortController` configuration.

The example code would be:

```js
const {
  S3Client,
  CreateBucketCommand,
  waitUntilBucketExists,
} = require("../waiters/aws-sdk-js-v3/clients/client-s3");

(async () => {
  const region = "us-west-2";
  const client = new S3Client({ region });

  const Bucket = "test-bucket-for-abort-controller";
  await client.send(new CreateBucketCommand({ Bucket }));
  const abortController = new AbortController();
  const waiterPromise = waitUntilBucketExists(
    { client, maxWaitTime: 60, abortSignal: abortController.signal },
    { Bucket }
  );

  abortController.abort();
  try {
    await waiterPromise;
  } catch (error) {
    console.log(error);
  }
})();

```

**Comment by trivikr** [comment]
Verified that the waiter configuration now takes abortSignal since `v3.15.0`

Code:
```js
import { S3, waitUntilBucketExists } from "@aws-sdk/client-s3";

const region = "us-west-2";
const client = new S3({ region });

const Bucket = "test-waiters-bucket-does-not-exist";
const abortController = new AbortController();
const waiterPromise = waitUntilBucketExists(
  { client, maxWaitTime: 60, abortSignal: abortController.signal },
  { Bucket }
);

// Abort after 3 seconds
setTimeout(() => {
  abortController.abort();
}, 3000);

const t0 = performance.now();
try {
  await waiterPromise;
} catch (error) {
  console.log(error);
}
const t1 = performance.now();
console.log(`Call to waiter took ${((t1 - t0) / 1000).toFixed(3)} seconds.`);

```

Output:
```
Error [AbortError]: {"state":"ABORTED","reason":"Request was aborted"}
    at Object.checkExceptions (/local/home/trivikr/workspace/test-waiters/node_modules/@aws-sdk/util-waiter/dist/cjs/waiter.js:25:28)
    at waitUntilBucketExists (/local/home/trivikr/workspace/test-waiters/node_modules/@aws-sdk/client-s3/dist/cjs/waiters/waitForBucketExists.js:38:26)
    at async file:///local/home/trivikr/workspace/test-waiters/abortFirst.mjs:20:3
Call to waiter took 3.004 seconds.
```
