### ISSUE TITLE
CognitoIDP paginateListUserPools fails with validation error

### ISSUE THREAD

**Issue by eryon** [aws/aws-sdk-js-v3#2335]
## Describe the bug
When using `paginateListUserPools`, a validation error occurs regarding the `maxResults` parameter. The error occurs whether or not the `MaxResults` field is set in the paginator input and regardless of its letter casing.

#### SDK version number
`@aws-sdk/client-cognito-identity-provider@3.14.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.20.0

## Steps to reproduce
Run the following code and it fails:
```js
const { CognitoIdentityProviderClient, paginateListUserPools } = require('@aws-sdk/client-cognito-identity-provider');

async function test() {
  const client = new CognitoIdentityProviderClient({ region: 'us-west-2' });
  const paginator = paginateListUserPools({ client }, { MaxResults: 10 });
  const pools = [];

  for await (const chunk of paginator) {
    pools.push(...chunk.UserPools);
  }

  return pools;
}

test().then(console.log).catch(console.error);
```

#### Observed behavior
An error occurs:
```
InvalidParameterException: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1
    at deserializeAws_json1_1ListUserPoolsCommandError (<path-snipped>/node_modules/@aws-sdk/client-cognito-identity-provider/dist/cjs/protocols/Aws_json1_1.js:8378:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async <path-snipped>/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async <path-snipped>/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (<path-snipped>/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async <path-snipped>/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async makePagedClientRequest (<path-snipped>/node_modules/@aws-sdk/client-cognito-identity-provider/dist/cjs/pagination/ListUserPoolsPaginator.js:12:12)
    at async paginateListUserPools (<path-snipped>/node_modules/@aws-sdk/client-cognito-identity-provider/dist/cjs/pagination/ListUserPoolsPaginator.js:33:20)
    at async test (<path-snipped>/test.js:8:20) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '4a377f49-da20-451a-8634-145439bc5c12',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

#### Expected behavior
No error expected.

**Comment by eryon** [comment]
Replacing the pagination with
```js
const { UserPools } = await client.send(new ListUserPoolsCommand({ MaxResults: 10 }));
```
works as expected, but of course without pagination.

**Comment by ajredniwja** [comment]
Hey @eryon, thanks for opening this issue, looking at the code: 

https://github.com/aws/aws-sdk-js-v3/blob/73d2346b6624ce0deb607c07e4be71c33d24666c/clients/client-cognito-identity-provider/pagination/ListUsersPaginator.ts#L40

The `pageSize` needs to be included. 

Code: 

```JavaScript
const { CognitoIdentityProviderClient, paginateListUserPools } = require('@aws-sdk/client-cognito-identity-provider');

(async () => {
    const paginatorConfig = {
        client: new CognitoIdentityProviderClient({}),
        pageSize: 10
      };
      const commandParams = {};
      const paginator = paginateListUserPools(paginatorConfig, commandParams);
      
      const pools = [];
      for await (const chunk of paginator) {
        // page contains a single paginated output.
        pools.push(...chunk.UserPools);
      }
    //   console.log(pools)
  })();
```

You can check more about pagination in blog post on [Pagination using Async Iterators in modular AWS SDK for JavaScript](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/). 


Closing this issue now, please reach out if you have any other questions.
