### ISSUE TITLE
[client-sqs] receiveMessage fails if message contains combination from decodeEscapedXML function 

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2375]
## Describe the bug
receiveMessage fails if message contains combination from decodeEscapedXML function:

https://github.com/aws/aws-sdk-js-v3/blob/bae9fa9481b59c5721cbc36ae383c17e269e9dd1/codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/decodeEscapedXML.ts#L1-L7

#### SDK version number
`@aws-sdk/client-sqs@3.14.0`

#### Is the issue in the browser/Node.js/ReactNative?
All, tested in Node.js

#### Details of the browser/Node.js/ReactNative version
`v14.16.1`

## Steps to reproduce

```js
import { SQS } from "@aws-sdk/client-sqs";

const region = "us-west-2";
const client = new SQS({ region });

const messagesWithEscapeValues = ["&apos;", "&quot;", "&gt;", "&lt;"];

for (const MessageBody of messagesWithEscapeValues) {
  const QueueName = `test-${Date.now()}`;
  const { QueueUrl } = await client.createQueue({ QueueName });

  console.log(`MessageBody: "${MessageBody}"`);
  await client.sendMessage({
    MessageBody,
    QueueUrl,
  });

  try {
    await client.receiveMessage({ QueueUrl });
  } catch (error) {
    console.log(error);
  }
  await client.deleteQueue({ QueueUrl });
}

```

#### Observed behavior

```console
MessageBody: "&apos;"
Error: Invalid MD5 checksum on messages: 8c12d8b6-bba2-4ff8-8fcf-919f6fb9be8f
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/sqs-escaped.mjs:19:5
MessageBody: "&quot;"
Error: Invalid MD5 checksum on messages: 83a7f240-70db-4ddf-b42e-e41953fbc4e8
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/sqs-escaped.mjs:19:5
MessageBody: "&gt;"
Error: Invalid MD5 checksum on messages: a911a9bb-8979-426a-97c6-1979de2d4819
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/sqs-escaped.mjs:19:5
MessageBody: "&lt;"
Error: Invalid MD5 checksum on messages: d170f6b0-4aee-4c4e-a1fe-f67118024cd9
    at /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-sdk-sqs/dist/cjs/receive-message.js:21:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async file:///Users/trivikr/workspace/test/sqs-escaped.mjs:19:5
```

#### Expected behavior
The SQS should receiveMessage when sentMessage contains any of the following character combinations:
```
["&apos;", "&quot;", "&gt;", "&lt;"]
``` 

## Additional context
This issue was noticed while debugging https://github.com/aws/aws-sdk-js-v3/issues/2362

**Comment by trivikr** [comment]
This seems to be an issue with upstream at https://github.com/NaturalIntelligence/fast-xml-parser/issues/343
