### ISSUE TITLE
Error  RequestTimeTooSkewed: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-js-v3#2378]
## Describe the bug
I had this issue on another bug but this one relates to the mulitpart uploader.

My current uploader wouldnt work when upload a large file so I am moving everything over to a mulitpart upload with this v3 version.

Here is the code I have so far.

~~~
// Load the required clients and commands.
const {
    S3,
    CreateMultipartUploadCommand,
    UploadPartCommand,
    CompleteMultipartUploadCommand,
} = require("@aws-sdk/client-s3");

const fs = require('fs');

const s3Client = new S3({ 
	region: "us-east-1" 
});

// Set the parameters.
const createParams = {
    Bucket: 'bucket', 
    Key: 'Movie-3gb.mp4',
    ContentType: 'video/mp4'
};

let file_path = '/Users/dave/Desktop/large/Movie-3gb.mp4';

let uploader_id; // Sets the job upload id

let params = []; // Stores the upload parts array 

let partSize = 100 * 1024 * 1024; // 10mb chunks

let index = 1; // Parts increment

(async () => {

	const data = await s3Client.send(
	    new CreateMultipartUploadCommand(createParams)
	);

	uploader_id = data.UploadId;

	async function setupChunks(readable, callback) {

	  	for await (const chunk of readable) {

	    	params.push(new UploadPartCommand({
		        Bucket: createParams.Bucket,
		        Key: createParams.Key,
		        Body: chunk,
		        PartNumber: index++,
		        UploadId: uploader_id,
		    }));

	  	}

	  	callback(true);

	}

	const readable = fs.createReadStream(file_path, { 
		highWaterMark: partSize
	});

	setupChunks(readable, function(res){
		
		// Start function
		(async () => {

			try {

				total_files = params.length;

				progress = 1;

				const onProgress = async promise => {

				  	const result = await promise;

				  	console.log('Progress: ' + Math.round(progress / total_files * 100) + '%');

				  	progress++;
				  	
				  	return result;

				};
		     	
		     	const responses = await Promise.all(
			        params.map(param => onProgress(s3Client.send(param)))
			    ).then(function(response){

			    	(async () => {

					 	try {

					    	var parts = [];

					    	for (var i = 0; i < response.length; i++) {
					    		
					    		parts.push({
	                                ETag: response[i].ETag,
	                                PartNumber: (i+1),
	                            });

					    	}

					        // Complete the mutlipart upload.
					        const uploader = await s3Client.send(
					            new CompleteMultipartUploadCommand({
				                    Bucket: createParams.Bucket,
				                    Key: createParams.Key,
				                    MultipartUpload: {
				                        Parts: parts,
				                    },
				                    UploadId: uploader_id
				                })
					        );

					        console.log("Upload completed. File location: ", uploader.Location);

					    } catch (err) {
					        
					        console.log("Error ", err);
					    
					    }

				    })();

				}).catch(function(err){
				  	
				  	console.log(err);


				});

		    } catch (err) {
		      	
		      	return console.log("There was an error uploading: ", err.message);
		    
		    }

		})();

	});

})();
~~~

The mulitpart upload seems to be working fine on smaller files but anything above 2gb it fails with this error again.
~~~
Error  RequestTimeTooSkewed: The difference between the request time and the current time is too large.
    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/Users/dave/Documents/ElectronJs/uploader/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4295:41)
~~~

It did make it to 100% progress but then failed right at the end.

Here is my console output.

~~~
Upload started. Upload ID:  EAXi.iSfCoF55dMrtRzCbgt6mlkZRo1hXRmdFZQFkyCIjI4fUsm6xjVNapeMGlk3tVH.oCeu_QS4M_XAK_jzgKUj80PNNhrT41aIC92pCWJwWOVJ8lGhSODSlLUcj2sM
Progress: 4%
Progress: 8%
Progress: 12%
Progress: 16%
Progress: 20%
Progress: 24%
Progress: 28%
Progress: 32%
Progress: 36%
Progress: 40%
Progress: 44%
Progress: 48%
Progress: 52%
Progress: 56%
Progress: 60%
Progress: 64%
Progress: 68%
Progress: 72%
Progress: 76%
Progress: 80%
Progress: 84%
Progress: 88%
Progress: 92%
Progress: 96%
Progress: 100%
{
  Bucket: 'bucket',
  Key: 'Movie-3gb.mp4',
  MultipartUpload: {
    Parts: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ]
  },
  UploadId: 'EAXi.iSfCoF55dMrtRzCbgt6mlkZRo1hXRmdFZQFkyCIjI4fUsm6xjVNapeMGlk3tVH.oCeu_QS4M_XAK_jzgKUj80PNNhrT41aIC92pCWJwWOVJ8lGhSODSlLUcj2sM'
}
Error  RequestTimeTooSkewed: The difference between the request time and the current time is too large.
    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/Users/dave/Documents/ElectronJs/uploader/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4295:41)
~~~

**Comment by samueleastdev** [comment]
> Hey @samueleastdev thanks for opening this issue, I was not quite able to understand what you meant by "current uploader", does that mean you tried using `upload` from lib-storage, which uses multipart uploading under the hood. To find the implementation of multipart upload see: https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-storage/src
> 
> As for your use case:
> 
> I tried uploading a 3GB file using the code below and it works perfectly fine:
> 
> ```ts
> import * as fs from "fs";
> import { Upload } from "@aws-sdk/lib-storage";
> import { S3 } from "@aws-sdk/client-s3";
> 
> const fileStream = fs.createReadStream("path/to/file");
> 
> (async () => {
>   try {
>     const upload = new Upload({
>       params: {
>         Bucket: "bucket-name",
>         Key: "3gbFile",
>         Body: fileStream,
>       },
>       client: new S3({region: "us-west-2"}),
>       queueSize: 3,
>     });
>   
>     upload.on("httpUploadProgress", (progress) => {
>       console.log(progress);
>     });
>   
>     const result = await upload.done();
>     console.log(result);
>   }
>   catch (error) {
>     console.log(error)
>   }
> })();
> ```
> 
> With that being said, I didn't completely go through your code, I believe you might be doing something wrong, but since it is something already implemented in the SDK it might be easy to use it. Please let me know if I missed something here or you have a different user case.
> 
> Closing this issue now, will re-open if the above solution doesn't solve your problem.

Thanks @ajredniwja I will try this today it looks like I am over complicating things I wasn't aware of this function.
