### ISSUE TITLE
STS Client doesn't close all asynchronous processes, reported by Jest.

### ISSUE THREAD

**Issue by clcpolevaulter** [aws/aws-sdk-js-v3#2389]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When the AWS STS Client invokes the Metadata API, it doesn't close all its processes. When invoking STS with Jest on a host that has an AWS identity, Jest complains about the hung processes. The only way around the issue is to use a `--forceExit` flag which hides other issues. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.22.1

**SDK version number**

"@aws-sdk/client-sts": "3.13.1"

**To Reproduce (observed behavior)**

1. clone https://github.com/clcpolevaulter/sts-example to EC2 with Docker installed
2. Modify `test/sample.spec.js` to have an `accountNumber` and `roleName` that the EC2 Instance Profile can assume [here](https://github.com/clcpolevaulter/sts-example/blob/main/test/sample.spec.js#L2-L3)
3. Run `docker run -w /workspace -v $(pwd):/workspace  node:12-alpine npm run test`

**Expected behavior**
Jest test to exit with a status code of 0. 

```bash
machine:sts-example bob$ npm run test

> sts-example@1.0.0 test /Users/bob/Developer/sts-example
> npm i && jest --testEnvironment=node --testTimeout=60000

npm WARN sts-example@1.0.0 No repository field.

audited 580 packages in 2.503s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

  console.log
    <redacted>

      at Object.<anonymous> (test/sample.spec.js:10:17)

 PASS  test/sample.spec.js
  STS Example
    ✓ This will hang in docker... (267 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.876 s, estimated 2 s
Ran all test suites.
  console.log
    {
      AssumedRoleId: 'redacted',
      Arn: 'arn:aws:sts::<redacted>:assumed-role/<redacted>/axios'
    }

      at Object.<anonymous> (test/sample.spec.js:17:17)
```

**Actual behavior**
Jest test doesn't exit.

```bash
> sts-example@1.0.0 test /workspace
> npm ci && jest --testEnvironment=node --testTimeout=60000

added 580 packages in 7.106s
  console.log
    <redacted>

      at Object.<anonymous> (test/sample.spec.js:10:17)

PASS test/sample.spec.js
  STS Example
    ✓ This will hang in docker... (1092 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.781 s
Ran all test suites.
  console.log
    {
      AssumedRoleId: '<redacted>',
      Arn: 'arn:aws:sts::<redacted>:assumed-role/<redacted>/axios'
    }

      at Object.<anonymous> (test/sample.spec.js:17:17)

Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by trivikr** [comment]
@clcpolevaulter What is the output if you run Jest with `--detectOpenHandles`?

**Comment by clcpolevaulter** [comment]
> @clcpolevaulter What is the output if you run Jest with `--detectOpenHandles`?

Nothing additional. I will run it again shortly and post back. 

[On mobile]

**Comment by trivikr** [comment]
The command doesn't hang when I try to run on docker:

```console
$ sudo docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm i && node node_modules/.bin/jest --runInBand --detectOpenHandles

npm WARN sts-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 581 packages in 2.81s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 PASS  test/sample.spec.js
  STS Example
    ✓ This will hang in docker... (82 ms)

  console.log
    temp

      at Object.<anonymous> (test/sample.spec.js:10:13)

  console.log
    {
      AssumedRoleId: '<REDACTED>',
      Arn: 'arn:aws:sts::<REDACTED>:assumed-role/<REDACTED>/axios'
    }

      at Object.<anonymous> (test/sample.spec.js:17:13)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.054 s
Ran all test suites.

```

Docker version:
```
$ docker version
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Oct 12 18:51:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

@clcpolevaulter Which docker version are you using? Can you test the code with v3.16.0?

**Comment by clcpolevaulter** [comment]
```bash
WDXAB51793VCG:sts-example ab51793$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
```

**This command does hang:**

Original:
```
docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm run test
```

**These commands don't hang:**

Provided by https://github.com/aws/aws-sdk-js-v3/issues/2389#issuecomment-842715083

```
docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm i && node node_modules/.bin/jest --runInBand --detectOpenHandles
```

Expanded from the original npm script:

```
docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm i && node node_modules/.bin/jest --testEnvironment=node --testTimeout=60000
```

🤔 Could this be npm script related?

**Comment by clcpolevaulter** [comment]
No change with v3.16.0 of @aws-sdk/client-sts.

**Comment by trivikr** [comment]
> 🤔 Could this be npm script related?

This issue appears to be with Jest, as the command does hang when `--detectOpenHandles` is not passed, but doesn't hang when `--detectOpenHandles` is passed to detect troubleshooting.

@clcpolevaulter Can you create an issue on Jest repo to get more information on `--detectOpenHandles` behavior?

**Comment by trivikr** [comment]
Jest doesn't hang in my workspace even if `--detectOpenHandles` is not passed.

```console
$ sudo docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm i && node node_modules/.bin/jest

npm WARN sts-example@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 581 packages in 2.813s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 PASS  test/sample.spec.js
  STS Example
    ✓ This will hang in docker... (77 ms)

  console.log
    temp

      at Object.<anonymous> (test/sample.spec.js:10:13)

  console.log
    {
      AssumedRoleId: 'AROA5ROEOH3WHQXMYHX6Y:axios',
      Arn: 'arn:aws:sts::930809265900:assumed-role/temp/axios'
    }

      at Object.<anonymous> (test/sample.spec.js:17:13)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.928 s, estimated 1 s
Ran all test suites.
```

Docker version:
```console
$ sudo docker version 
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Oct 12 18:51:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Mon Oct 12 18:51:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by clcpolevaulter** [comment]
@trivikr can you try still leveraging the npm script?

**Comment by clcpolevaulter** [comment]
But yes, I can open an issue with Jest.

**Comment by trivikr** [comment]
> @trivikr can you try still leveraging the npm script?

I'm able to reproduce the issue on explicitly running the npm script:
```console
$ sudo docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm run test
```

The issue is not reproducible if I replace npm script, with the code inside npm script
```console
$ sudo docker run -w /workspace -v $(pwd):/workspace node:12-alpine npm i && node node_modules/.bin/jest --testEnvironment=node --testTimeout=60000
```

**Comment by trivikr** [comment]
Closing as triaging indicated that this issue is not with `@aws-sdk/client-sts`, and likely to be either npm script or jest.

Please request for reopening this issue, or create a new one after getting feedback on Jest repo.

**Comment by clcpolevaulter** [comment]
Thanks again for your time looking at this @trivikr.
