### ISSUE TITLE
Exception on SubscribeToShard Command

### ISSUE THREAD

**Issue by mjpolak** [aws/aws-sdk-js-v3#2418]
## Describe the bug
I'm trying to subscribe to events from Kinesis Shard. But the execution of `SubscribeToShardCommand` hangs for few minutes (probably some timeout) and then throws an error.

## Your environment
 - Ubuntu 20 (In WSL 2.0)
 -  Node 12

#### SDK version number
```
    "@aws-sdk/client-kinesis": "^3.16.0",
    "@aws-sdk/client-s3": "^3.16.0",
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.0.0

## Steps to reproduce
```js
const { StreamDescription } = await client.send(
  new DescribeStreamCommand({
    StreamName: "streamName",
  })
);

const { StreamARN } = StreamDescription;

const { Consumers } = await client.send(
  new ListStreamConsumersCommand({
    StreamARN,
  })
);

let Consumer = Consumers.find((x) => x.ConsumerName == "tester");

if (Consumer == null) {
  const consumerData = await client.send(
    new RegisterStreamConsumerCommand({
      ConsumerName: "tester",
      StreamARN,
    })
  );
  Consumer = consumerData.Consumer;
}

console.log(`StreaARM: ${StreamARN}`);
console.log(`Consumer: ${Consumer.ConsumerARN}`);

const { EventStream } = await client.send(
  new SubscribeToShardCommand({
    ConsumerARN: Consumer.ConsumerARN,
    ShardId: "shardId-000000000000",
    StartingPosition: {
      Type: "LATEST",
    },
  })
);
console.log("Consuming");
```

#### Observed behavior
Error after timeout:

```console
(node:2667) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/client-kinesis/protocols/Aws_json1_1.ts:4020:19
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at Object.deserializeAws_json1_1SubscribeToShardCommand (/home/mjpolak/Documents/company/project/node_modules/@aws-sdk/client-kinesis/protocols/Aws_json1_1.ts:2583:21)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20
    at /home/mjpolak/Documents/company/project/kinesis-subscribe.ts:85:29
```

#### Expected behavior
Receiving response (`SubscribeToShardCommandOutput`), or understandable error.

**Comment by mjpolak** [comment]
By investigating communication via Wireshark, I can confirm that HTTP connection is established, and AWS pushes some data to my client. So I'm guessing that there is some kind of bug in client library that holds the block instead of returning the result.

**Comment by ajredniwja** [comment]
Related: https://github.com/aws/aws-sdk-js-v3/issues/2131

Is this still an issue with the latest version?

**Comment by mjpolak** [comment]
It is the same as before, version `3.22.0`

**Comment by francescopace** [comment]
same on 3.24.0

**Comment by AWare** [comment]
same in `3.39.0`

**Comment by BDNilsson** [comment]
I am having the same issue.

Has anyone got any workaround?

**Comment by vudh1** [comment]
Hi all, we are aware of this issue and in progress of fixing this. Related to #2131 for more updates.

**Comment by wr-ssingh1** [comment]
@vudh1 Is there any update on the fix for this?
