### ISSUE TITLE
@aws/lib-storage MalformedXML error on Upload

### ISSUE THREAD

**Issue by Galacs** [aws/aws-sdk-js-v3#2425]
## Describe the bug
When using Upload from @aws/lib-storage a MalformedXML error is thrown just after the last piece is sent

#### SDK version number
`@aws-sdk/lib-storage@3.16.0`
`@aws-sdk/client-s3@3.16.0`

#### Details of the browser/Node.js/ReactNative version
Tested with:

- Node.js 16.1.0
- Node.js 15.14.0
- Node.js 14.14.0

## Steps to reproduce
This code comes from the official documentation:
[https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_storage.html#upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_storage.html#upload)
```javascript
import fs from "fs";
import { Upload } from "@aws-sdk/lib-storage";
import { S3Client } from "@aws-sdk/client-s3";

const target = {
  Bucket: "ceph-bkt-fca7a89f-c6a6-460b-85fc-af4a2923105a",
  Key: "object",
  Body: fs.createReadStream("./test.img"),
};
try {
  const paralellUploads3 = new Upload({
    client: s3,
    params: target,
  });

  paralellUploads3.on("httpUploadProgress", (progress) => {
    console.log(progress);
  });

  paralellUploads3.done();
} catch (e) {
  console.log(e);
}

```
#### Observed behavior
```javascript
{
  loaded: 99614720,
  total: 104857600,
  part: 21,
  Key: 'object',
  Bucket: 'ceph-bkt-fca7a89f-c6a6-460b-85fc-af4a2923105a'
}
{
  loaded: 104857600,
  total: 104857600,
  part: 20,
  Key: 'object',
  Bucket: 'ceph-bkt-fca7a89f-c6a6-460b-85fc-af4a2923105a'
}
/mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4391
    return Promise.reject(Object.assign(new Error(message), response));
                                        ^

MalformedXML: MalformedXML
    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4391:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Upload.__doMultipartUpload (/mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/lib-storage/dist/cjs/Upload.js:104:41)
    at async Upload.done (/mnt/c/Users/GalacsG/bugreport_s3/node_modules/@aws-sdk/lib-storage/dist/cjs/Upload.js:45:16) {
  Code: 'MalformedXML',
  BucketName: 'ceph-bkt-fca7a89f-c6a6-460b-85fc-af4a2923105a',
  RequestId: 'tx000000000000000001610-0060abbe5f-1245d-my-store',
  HostId: '1245d-my-store-my-store',
  '$fault': 'client',
  '$metadata': {
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

**Comment by Galacs** [comment]
I think it's a duplicate of #1814
