### ISSUE TITLE
WriteGetObjectResponseCommand issue

### ISSUE THREAD

**Issue by anton-makarov-photobox** [aws/aws-sdk-js-v3#2476]
## Describe the bug

`WriteGetObjectResponseCommand` throw error when try to send command
LambdaResponseNotReceived: The Lambda exited without successfully calling WriteGetObjectResponse.

## Code example 

```
import { S3Client, S3 } from '@aws-sdk/client-s3';

 const s3Client = new S3Client({});

async function passTransformedPhoto(
  body: Buffer,
  outputRoute: string,
  outputToken: string,
): Promise<WriteGetObjectResponseCommandOutput> {
  try {
    const writeGetObjectParams: WriteGetObjectResponseCommandInput = {
      RequestRoute: outputRoute,
      RequestToken: outputToken,
      Body: body,
    };

    const command = new WriteGetObjectResponseCommand(writeGetObjectParams);
    console.log('s3Client send');

    const res = await s3Client.send(command);
    return res;
  } catch (e) {
    console.log('Error happens in passTransformedPhoto');
    console.log(e);
    return e;
  }
}
```

The same issue with the aggregated client

```
import { S3Client, S3 } from '@aws-sdk/client-s3';
 const s3Aggregated = new S3({});

async function passTransformedPhoto(body: Buffer, outputRoute: string, outputToken: string) {
  try {
    const result = await s3Aggregated.writeGetObjectResponse({
      RequestRoute: outputRoute,
      RequestToken: outputToken,
      Body: body,
    });
    return result;
  } catch (e) {
    console.log('Error happens in passTransformedPhoto');
    console.log(e);
    return e;
  }
}

```

## Output 

Error happens in passTransformedPhoto

```
INFO	TypeError: Cannot destructure property 'service' of 'bucketName' as it is undefined.
    at getEndpointFromArn (/var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketHostname.js:26:13)
    at Object.bucketHostname (/var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketHostname.js:17:13)
    at /var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketEndpointMiddleware.js:47:67
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Expected result

bucketName should looks like this 

```
bucketName: {
    partition: 'aws',
    service: 's3-object-lambda',
    region: 'us-east-2',
    accountId: '11111111',
    resource: 'accesspoint/access-point'
  }

```

#### SDK version number
`@aws-sdk/client-s3": "^3.18.0"`
Node.js v 14.17.0
 "typescript": "^4.3.2",

**Comment by antowkabond** [comment]
Yes, we got the same problem.

In **bucketEndpointMiddleware.ts** , when HTTP Request is **Post** in case using **writeGetObjectResponse**

bucketName is **undefined** 

```
export const bucketEndpointMiddleware =
  (options: BucketEndpointResolvedConfig): BuildMiddleware<any, any> =>
  <Output extends MetadataBearer>(
    next: BuildHandler<any, Output>,
    context: HandlerExecutionContext
  ): BuildHandler<any, Output> =>
  async (args: BuildHandlerArguments<any>): Promise<BuildHandlerOutput<Output>> => {
    const { Bucket: bucketName } = args.input as { Bucket: string };  // undefined
    let replaceBucketInPath = options.bucketEndpoint;
    const request = args.request;
    if (HttpRequest.isInstance(request)) {...}
```

**HttpRequest** has all property wich we pushed to **writeGetObjectResponse** like   
      RequestRoute: outputRoute,
      RequestToken: outputToken,
      Body: body,

```
HttpRequest {
  method: 'POST',
  hostname: 'io-cell002.s3.eu-east-1.amazonaws.com',
  port: undefined,
  query: { 'x-id': 'WriteGetObjectResponse' },
  headers: {
    'content-type': 'application/octet-stream',
    'x-amz-content-sha256': 'UNSIGNED-PAYLOAD',
    'x-amz-request-route': 'io-cell002',
    'x-amz-request-token': 'TOKEN',
    'content-length': '623653',
    Expect: '100-continue'
  },
  body: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 01 2c 01 2c 00 00 ff db 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 08 0a 10 0a 0a 09 09 0a 14 0e 0f 0c ... 623603 more bytes>,
  protocol: 'https:',
  path: '/WriteGetObjectResponse'
}
```

But Bucket name is **undefined**

**Comment by youbek** [comment]
Same issue here

**Comment by youbek** [comment]
Hello guys, any updates on this? Thanks in advance!

**Comment by antowkabond** [comment]
Hi @youbek we are supporting AWS SDK versions 2 and 3. Also waiting for updates

**Comment by ajredniwja** [comment]
Hi @anton-makarov-photobox, thanks for opening this issue, can I please have some more info of your environment? With the lates version of the SDK I was not able to reproduce the same. Are you using react for this?

**Comment by ahmedelamine** [comment]
I also have the same error
The Lambda exited without successfully calling WriteGetObjectResponse.
TypeError: Cannot destructure property 'service' of 'bucketName' as it is undefined
