### ISSUE TITLE
Unable to use GetRecommendationsCommand 

### ISSUE THREAD

**Issue by natyleitner** [aws/aws-sdk-js-v3#2520]
## Describe the bug
Following the example in the [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-personalize-runtime/classes/getrecommendationscommand.html) I'm unable to get recommendations.

#### SDK version number
`@aws-sdk/client-personalize-runtime@3.19.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.19.1

## Steps to reproduce
```
import { GetRecommendationsCommand, PersonalizeRuntimeClient } from '@aws-sdk/client-personalize-runtime';
import dotenv from 'dotenv';
dotenv.config();

const getRecommendations = async (userId) => {
    const client = new PersonalizeRuntimeClient({ region: 'eu-west-1' });
    const input = {
        campaignArn: 'arn:aws:personalize:eu-west-1......',
        userId,
        numResults: 10
    }
    const command = new GetRecommendationsCommand(input);
    try {
        const data = await client.send(command);
        return data;
    } catch (error) {
        console.error(error, 'error calling AWS')
        return error.message
    }
}
```

Logging shows input is as expected. Authentication is done through env variables for now, defined in .env file.

#### Observed behavior
Code runs and catches the following error:
```
InternalFailure: InternalFailure
    at deserializeAws_restJson1GetRecommendationsCommandError (/Users/natalialeitnerova/recommendation-api/node_modules/@aws-sdk/client-personalize-runtime/protocols/Aws_restJson1.ts:211:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users/natalialeitnerova/recommendation-api/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:18:20
    at /Users/natalialeitnerova/recommendation-api/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/Users/natalialeitnerova/recommendation-api/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:83:38)
    at /Users/natalialeitnerova/recommendation-api/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '7256f87e-9427-4919-a776-edf4c6a2033c',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 311
  }
}
```

#### Expected behavior
`await client.send(command)` returns GetRecommendationsCommandOutput

**Comment by natyleitner** [comment]
Closing this as it turned out to be an issue with the dataset (additional commas in csv) rather than the command
