### ISSUE TITLE
S3 PutObjectCommand fails with ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by tonila** [aws/aws-sdk-js-v3#2538]
## Describe the bug
Uploading large files of a few megabytes of size using the upload aws-sdk s3 API throws UnhandledPromiseRejectionWarning with ERR_STREAM_WRITE_AFTER_END and

It seems aws-sdk-js-v3 is affected with the same bug, that has already been fixed in aws-sdk-js
https://github.com/aws/aws-sdk-js/issues/3404

## Your environment
Debian Buster

#### SDK version number
`@aws-sdk/client-s3@3.19.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.17.1

## Steps to reproduce
Upload a file large enough (>2MB) to Linode Object Storage
```
const data = fs.readFileSync('test.txt', 'utf8')
const params = {
  Bucket: 'test-bucket',
  Key: 'testdir/test.txt',
  Body: data,
};
await s3Client.send(new PutObjectCommand(params));
```

Exception thrown:
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ClientRequest.end (_http_outgoing.js:815:7)
    at writeBody (/home/node/app/node_modules/@aws-sdk/node-http-handler/dist/cjs/write-request-body.js:23:21)
    at ClientRequest.<anonymous> (/home/node/app/node_modules/@aws-sdk/node-http-handler/dist/cjs/write-request-body.js:9:13)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:612:11)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 'ERR_STREAM_WRITE_AFTER_END',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

```

**Comment by opti21** [comment]
Running into a similar issue as well trying but using the `@aws-sdk/lib-storage` upload function

```javascript
const parallellUploads = new Upload({
  client: new S3Client({
    credentials: {
      accessKeyId: process.env.S3_KEY,
      secretAccessKey: process.env.S3_SECRET,
    },
    region: process.env.S3_REGION,
    endpoint: "http://us-east-1.linodeobjects.com",
  }),
  params: {
    Bucket: process.env.S3_BUCKET,
    Key: "gauntlet_" + uuid() + "_" + files.files.name,
    Body: fs.createReadStream(files.files.path),
  },
});

parallellUploads.on("httpUploadProgress", (progress) => {
  console.log(progress);
});

await parallellUploads.done();
```

**Comment by ajredniwja** [comment]
Hey @tonila thanks for opening this issue, I believe this is because of the same reason which solved the V2 issue, I'll try to create the PR with a fix similar to V2 :https://github.com/aws/aws-sdk-js/pull/3674
And make changes in: https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/packages/node-http-handler/src/write-request-body.ts#L9

Thanks for your patience.
