### ISSUE TITLE
Cannot PutObject to s3 if key contain asterisk character

### ISSUE THREAD

**Issue by tranvansang** [aws/aws-sdk-js-v3#2596]
## Describe the bug
client-s3 fails to upload a file if `Key` contains an asterisk character.

#### SDK version number
`"@aws-sdk/client-s3": "^3.17.0",`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
node --version
v16.3.0
```

## Steps to reproduce

This code works

```
await s3ClientInstance(new PutObjectCommand({
			Key: 'uploads/ab.png',
			Body: await readFile(filePath),
			Bucket: 'bucket-name',
		}))
```

But, this fails to work

```
await s3ClientInstance(new PutObjectCommand({
			Key: 'uploads/*.png',
			Body: await readFile(filePath),
			Bucket: 'bucket-name',
		}))
```

#### Observed behavior
S3Client failed to upload the file when the `Key` is `'uploads/*.png'`.

#### Expected behavior
`*` is a safe character, S3Client should uploads the file normally.

## Additional context

The following error was thrown

```
Error: AWS SDK error wrapper for SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.

    at asSdkError (/home/obfuscated/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:124:10)
    at StandardRetryStrategy.retry (/home/obfuscated/node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:94:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/obfuscated/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22
    at uploadWithKey (/home/obfuscated/src/components/aws/s3/s3Service.test.ts:46:48)
    at Object.<anonymous> (/home/obfuscated/src/components/aws/s3/s3Service.test.ts:76:3)
```

**Comment by tranvansang** [comment]
with exactly the same code, now it can run and upload.

I believe that there was a change in the s3 backend.
