### ISSUE TITLE
Issue in lambda pipeline api resolver

### ISSUE THREAD

**Issue by sourabpramanik** [aws/aws-sdk-js-v3#2604]
```const cognitoIdentityServiceProvider = new CognitoIdentityServiceProvider();
const USER_POOL_ID = "<user_pool_id>";
const stripe = require("stripe")("<stripe_id>");

const getUserEmail = async (event) => {
  const params = {
    UserPoolId: USER_POOL_ID,
    Username: event.identity.claims.username
  };
  const user = await cognitoIdentityServiceProvider.adminGetUser(params).promise();
  const { Value: email } = user.UserAttributes.find((attr) => {
    if (attr.Name === "email") {
      return attr.Value;
    }
  });
  return email;
};

/*
 * Get the total price of the order
 * Charge the customer
 */
exports.handler = async (event) => {
  try {
    const { id, cart, total, address, token } = event.arguments.input;
    const { username } = event.identity.claims;
    const email = await getUserEmail(event);

    await stripe.charges.create({
      amount: total,
      currency: "usd",
      source: token,
      description: `Order ${new Date()} by ${username} with ${email} email`
    });
    return { id, cart, total, address, username, email };
  } catch (err) {
    throw new Error(err);
  }
};```

**FROM CLOUDWATCH CONSOLE LOGS**

2021-07-21T05:16:02.503Z	2c03c648-5521-4c38-88e0-b768998a64a3	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "TypeError: Cannot read property 'claims' of null",
    "stack": [
        "Error: TypeError: Cannot read property 'claims' of null",
        "    at Runtime.exports.handler (/var/task/index.js:40:11)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

**Comment by ajredniwja** [comment]
Hi @sourabpramanik can you please fill out the [issue template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?

**Comment by ajredniwja** [comment]
Closing this because https://github.com/aws/aws-sdk-js-v3/issues/2608

**Comment by sourabpramanik** [comment]
Why did you closed this this issue?
