### ISSUE TITLE
Issue in Lambda function to claim username from user pool

### ISSUE THREAD

**Issue by sourabpramanik** [aws/aws-sdk-js-v3#2608]
## Describe the bug
I am trying to get the username of the current event user in my lambda function using appsync api pipeline resolvers but it says cannot find claims of null but I am very sure that it works.

#### SDK version number
`@aws-sdk/types@3.22.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
`Node v14.17.1`

## Steps to reproduce

```js
const USER_POOL_ID = "<user_pool_id>";
const stripe = require("stripe")("<stripe_id>");

const getUserEmail = async (event) => {
  const params = {
    UserPoolId: USER_POOL_ID,
    Username: event.identity.claims.username
  };
  const user = await cognitoIdentityServiceProvider.adminGetUser(params).promise();
  const { Value: email } = user.UserAttributes.find((attr) => {
    if (attr.Name === "email") {
      return attr.Value;
    }
  });
  return email;
};

/*
 * Get the total price of the order
 * Charge the customer
 */
exports.handler = async (event) => {
  try {
    const { id, cart, total, address, token } = event.arguments.input;
    const { username } = event.identity.claims;
    const email = await getUserEmail(event);

    await stripe.charges.create({
      amount: total,
      currency: "usd",
      source: token,
      description: `Order ${new Date()} by ${username} with ${email} email`
    });
    return { id, cart, total, address, username, email };
  } catch (err) {
    throw new Error(err);
  }
};
```

#### Observed behavior
```
2021-07-21T05:16:02.503Z	2c03c648-5521-4c38-88e0-b768998a64a3	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "TypeError: Cannot read property 'claims' of null",
    "stack": [
        "Error: TypeError: Cannot read property 'claims' of null",
        "    at Runtime.exports.handler (/var/task/index.js:40:11)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

#### Expected behavior
To get the username from the user pool of the current event and create an order.

**Comment by sourabpramanik** [comment]
I logged the event parameter and found that the identity is null. Any idea how the get that ?
