### ISSUE TITLE
Getting error on MediaConvert CreateJobCommand call : BadRequestException: /outputGroups/0/outputs/0: containerSettings is a required property

### ISSUE THREAD

**Issue by pradeep-mishra** [aws/aws-sdk-js-v3#2661]
## Describe the bug
Getting an error on MediaConvert CreateJobCommand call : BadRequestException: /outputGroups/0/outputs/0: containerSettings is a required property.

```sh
on job create BadRequestException: /outputGroups/0/outputs/0: containerSettings is a required property
      at deserializeAws_restJson1CreateJobCommandError (/Users/pradeepmishra/github/video-on-demand/node_modules/@aws-sdk/client-mediaconvert/dist/cjs/protocols/Aws_restJson1.js:976:41)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /Users/pradeepmishra/github/video-on-demand/node_modules/@aws-sdk/client-mediaconvert/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
      at async /Users/pradeepmishra/github/video-on-demand/node_modules/@aws-sdk/client-mediaconvert/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
      at async StandardRetryStrategy.retry (/Users/pradeepmishra/github/video-on-demand/node_modules/@aws-sdk/client-mediaconvert/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
      at async /Users/pradeepmishra/github/video-on-demand/node_modules/@aws-sdk/client-mediaconvert/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
      at async MediaConvert.createJob (/Users/pradeepmishra/github/video-on-demand/dist/common/mediaconvert.js:22:22)

```

The error says I need to pass containerSettings , which I am already passing as per the doc.

## Your environment
Dev

#### SDK version number
"@aws-sdk/client-mediaconvert": "^3.24.0"

## Steps to reproduce
Here is the sample data I am passing as a CreateJobCommandInput

```json

{
  "UserMetadata": {
    "user_id": "local_user",
    "org_id": "local_org"
  },
  "Role": "ROLE_ARN",
  "Settings": {
    "OutputGroups": [
      {
        "Name": "File Group",
        "OutputGroupSettings": {
          "Type": "FILE_GROUP_SETTINGS",
          "FileGroupSettings": {
            "Destination": "s3://OUTPUT_BUCKET"
          }
        },
        "Outputs": [
          [
            {
              "VideoDescription": {
                "ScalingBehavior": "DEFAULT",
                "TimecodeInsertion": "DISABLED",
                "AntiAlias": "ENABLED",
                "Sharpness": 50,
                "CodecSettings": {
                  "Codec": "H_264",
                  "H264Settings": {
                    "InterlaceMode": "PROGRESSIVE",
                    "NumberReferenceFrames": 3,
                    "Syntax": "DEFAULT",
                    "Softness": 0,
                    "GopClosedCadence": 1,
                    "GopSize": 90,
                    "Slices": 1,
                    "GopBReference": "DISABLED",
                    "SlowPal": "DISABLED",
                    "SpatialAdaptiveQuantization": "ENABLED",
                    "TemporalAdaptiveQuantization": "ENABLED",
                    "FlickerAdaptiveQuantization": "DISABLED",
                    "EntropyEncoding": "CABAC",
                    "Bitrate": 7500000,
                    "FramerateControl": "INITIALIZE_FROM_SOURCE",
                    "RateControlMode": "CBR",
                    "CodecProfile": "MAIN",
                    "Telecine": "NONE",
                    "MinIInterval": 0,
                    "AdaptiveQuantization": "HIGH",
                    "CodecLevel": "AUTO",
                    "FieldEncoding": "PAFF",
                    "SceneChangeDetect": "ENABLED",
                    "QualityTuningLevel": "SINGLE_PASS",
                    "FramerateConversionAlgorithm": "DUPLICATE_DROP",
                    "UnregisteredSeiTimecode": "DISABLED",
                    "GopSizeUnits": "FRAMES",
                    "ParControl": "INITIALIZE_FROM_SOURCE",
                    "NumberBFramesBetweenReferenceFrames": 2,
                    "RepeatPps": "DISABLED"
                  }
                },
                "AfdSignaling": "NONE",
                "DropFrameTimecode": "ENABLED",
                "RespondToAfd": "NONE",
                "ColorMetadata": "INSERT",
                "Width": 1280,
                "Height": 720
              },
              "AudioDescriptions": [
                {
                  "AudioTypeControl": "FOLLOW_INPUT",
                  "CodecSettings": {
                    "Codec": "AAC",
                    "AacSettings": {
                      "AudioDescriptionBroadcasterMix": "NORMAL",
                      "Bitrate": 96000,
                      "RateControlMode": "CBR",
                      "CodecProfile": "LC",
                      "CodingMode": "CODING_MODE_2_0",
                      "RawFormat": "NONE",
                      "SampleRate": 48000,
                      "Specification": "MPEG4"
                    }
                  },
                  "LanguageCodeControl": "FOLLOW_INPUT"
                }
              ],
              "OutputSettings": {
                "HlsSettings": {
                  "AudioGroupId": "program_audio",
                  "AudioRenditionSets": "program_audio",
                  "IFrameOnlyManifest": "EXCLUDE"
                }
              },
              "ContainerSettings": {
                "Container": "M3U8",
                "M3u8Settings": {
                  "AudioFramesPerPes": 4,
                  "PcrControl": "PCR_EVERY_PES_PACKET",
                  "PmtPid": 480,
                  "PrivateMetadataPid": 503,
                  "ProgramNumber": 1,
                  "PatInterval": 0,
                  "PmtInterval": 0,
                  "Scte35Source": "NONE",
                  "Scte35Pid": 500,
                  "TimedMetadata": "NONE",
                  "TimedMetadataPid": 502,
                  "VideoPid": 481,
                  "AudioPids": [
                    482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492
                  ]
                }
              },
              "NameModifier": "_720"
            }
          ]
        ]
      }
    ],
    "AdAvailOffset": 0,
    "Inputs": [
      [
        {
          "AudioSelectors": {
            "Audio Selector 1": {
              "Tracks": [1],
              "Offset": 0,
              "DefaultSelection": "DEFAULT",
              "SelectorType": "TRACK",
              "ProgramSelection": 1
            },
            "Audio Selector 2": {
              "Tracks": [2],
              "Offset": 0,
              "DefaultSelection": "DEFAULT",
              "SelectorType": "TRACK",
              "ProgramSelection": 1
            }
          },
          "VideoSelector": {
            "ColorSpace": "FOLLOW"
          },
          "FilterEnable": "AUTO",
          "PsiControl": "USE_PSI",
          "FilterStrength": 0,
          "DeblockFilter": "DISABLED",
          "DenoiseFilter": "DISABLED",
          "TimecodeSource": "EMBEDDED",
          "FileInput": "s3://MY_BUCKET/FILE_NAME"
        }
      ]
    ],
    "TimecodeConfig": {
      "Source": "EMBEDDED"
    }
  }
}


```

**Comment by pradeep-mishra** [comment]
fixed it.
i was passing array of array as a content in outputs
