### ISSUE TITLE
@aws-sdk/lib-dynamodb import from @aws-sdk/util-dynamodb but doesn’t include it in dependencies

### ISSUE THREAD

**Issue by acusti** [aws/aws-sdk-js-v3#2758]
## Describe the bug

this file, https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/src/commands/utils.ts#L1, starts with:

```ts
import { marshall, marshallOptions, unmarshall, unmarshallOptions } from "@aws-sdk/util-dynamodb";
```

but the package.json only includes `@aws-sdk/util-dynamodb` as a [dev and peer dependency](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/package.json#L30). same is true for `@aws-sdk/smithy-client`, though in that case, it doesn’t cause issues, because `@aws-sdk/client-dynamodb` includes smithy-client as a [dependency](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-dynamodb/package.json#L48).

the result is that in a project that includes @aws-sdk/client-dynamodb and @aws-sdk/lib-dynamodb, running `npm install` or `yarn install` with the `--production` flag (or with `NODE_ENV=production`) will result in:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@aws-sdk/util-dynamodb'\nRequire stack:\n- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/utils.js\n- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/BatchExecuteStatementCommand.js\n- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@aws-sdk/util-dynamodb'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/utils.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/commands/BatchExecuteStatementCommand.js",
        "- /var/task/node_modules/@aws-sdk/lib-dynamodb/dist/cjs/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

i believe that both `@aws-sdk/util-dynamodb` and `@aws-sdk/smithy-client` should be moved from `devDependencies` to `dependencies` in the package.json. and i believe the same is true for `@aws-sdk/client-dynamodb`, because `@aws-sdk/lib-dynamodb` imports actual functions and not just types from that package, e.g. in [`BatchGetCommand.ts`](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/src/commands/BatchGetCommand.ts#L5), but because the docs specify that “To create document client you need to create DynamoDB client first as follows”, so for anyone following the docs, there won’t be a situation where `@aws-sdk/lib-dynamodb` is installed but not `@aws-sdk/client-dynamodb`.

## Your environment

macOS 11.5.2 and lambda’s node.js v14 runtime
yarn v1.22.11

#### SDK version number
`@aws-sdk/lib-dynamodb@3.29.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.8.0 (locally) and the lambda node.js v14 runtime

## Steps to reproduce
add:
```
        "@aws-sdk/client-dynamodb": "^3.29.0",
        "@aws-sdk/lib-dynamodb": "^3.29.0",
```
to your dependencies in your package.json, then run `yarn install --production`.

#### Observed behavior
the steps to reproduce will result in `@aws-sdk/util-dynamodb` not getting installed and the `ImportModuleError` i pasted above when the package is run in lambda.

#### Expected behavior
i was expecting that installing `@aws-sdk/client-dynamodb` and `@aws-sdk/lib-dynamodb` would allow me to use the DynamoDB document client from lib-dynamodb when installed in production mode.

**Comment by AllanZhengYP** [comment]
Looks like it's miss in https://github.com/aws/aws-sdk-js-v3/pull/2516, I'm working on the fix to add it back.
