### ISSUE TITLE
NodeJs 14 Aws sdk 3 pagination issue for generator functions

### ISSUE THREAD

**Issue by PravinP252021** [aws/aws-sdk-js-v3#2785]
## Describe the bug
```console
"stack_trace": "/sandbox/node_modules/@aws-sdk/client-sso/dist/cjs/pagination/ListAccountRolesPaginator.js:21
async function* paginateListAccountRoles(config, input, ...additionalArguments) {
 ^

SyntaxError: Unexpected token *
 at createScript (vm.js:80:10)
 at Object.runInThisContext (vm.js:139:10)
 at Module._compile (module.js:616:28)
 at Object.Module._extensions..js (module.js:663:10)
 at Module.load (module.js:565:32)
 at tryModuleLoad (module.js:505:12)
 at Function.Module._load (module.js:497:3)
 at Module.require (module.js:596:17)
 at require (internal/module.js:11:18)
 at Object.<anonymous> (/sandbox/node_modules/@aws-sdk/client-sso/dist/cjs/index.js:8:22)"
```
getting above issue in aws sdk version 3

## Your environment
NodeJs 14

#### SDK version number
`@aws-sdk/cloudwatch`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

**Comment by ajredniwja** [comment]
Hey can you please fill out the complete issue template? Or provide the code that you are using?
