### ISSUE TITLE
rds-data-client postgres ExecuteStatementCommand with certain column types

### ISSUE THREAD

**Issue by indeediansbrett** [aws/aws-sdk-js-v3#2790]
## Describe the bug
Sending an `ExecuteStatementCommand` to a postgres database will fail to parse the response on timestamp with time zone and auto increment and/or integer columns.

#### SDK version number
`@aws-sdk/client-rds-data@3.31.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v12.22.3

## Steps to reproduce
Inside a lambda function with a postgres table created in RDS:
```sql
CREATE TABLE IF NOT EXISTS "tableName" 
("id" INTEGER GENERATED BY DEFAULT AS IDENTITY
,"numeric_id" INTEGER
,"zoned_timestamp" TIMESTAMP WITH TIME ZONE
,PRIMARY KEY ("id"));
```
```js
return await rdsDataClient.send(
        new ExecuteStatementCommand({
            ...config,
            sql: format(
                'SELECT zoned_timestamp ' +
                    'FROM %1$I',
                tableName
            )
        })
    );
```
```js
return await rdsDataClient.send(
        new ExecuteStatementCommand({
            ...config,
            sql: format(
                'SELECT integer_id ' +
                    'FROM %1$I',
                tableName
            )
        })
    );
```

#### Observed behavior
`RDSDataClient` attempts to parse auto increment columns as boolean in `deserializeAws_restJson1Field` when calling `deserializeAws_restJson1BatchExecuteStatementCommand` and `serializeAws_restJson1ExecuteStatementCommand`. It tries to parse timestamp with time zone columns as a float.

#### Expected behavior
Integer columns would be returned in the response as either doubleValue or longValue. Date columns would be returned in the response as either longValue or stringValue. There doesn't appear to be a dateValue Field type. 

#### Screenshots
```json
{
  "level": "fatal",
  "time": 1631730962046,
  "id": "3d4b57d8-34b5-1bb4-eb39-bc251bb75474",
  "route": "redacted",
  "method": "GET",
  "msg": "Expected boolean, got number",
  "timer": 151,
  "int": "apigateway",
  "statusCode": 500,
  "coldStart": true,
  "stack": "
TypeError: Expected boolean, got number\n
    at expectBoolean (/var/task/node_modules/@aws-sdk/smithy-client/dist/cjs/parse-utils.js:35:11)\n
    at deserializeAws_restJson1Field (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:947:43)\n
    at /var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:971:16\n
    at Array.map (<anonymous>)\n
    at deserializeAws_restJson1FieldList (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:967:10)\n
    at /var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:1046:16\n
    at Array.map (<anonymous>)\n
    at deserializeAws_restJson1SqlRecords (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:1042:10)\n
    at deserializeAws_restJson1ExecuteStatementCommand (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:512:28)\n
    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
  "remaining": 9490,
  "function": "redacted",
  "memory": "1536",
  "path": "redacted",
  "ip": "redacted",
  "device": "unknown",
  "country": "unknown",
  "version": "v1"
}
```

```json
{
  "level": "fatal",
  "time": 1631731229767,
  "id": "18e1f0e2-fe1d-1350-1bfa-0eaf936aca75",
  "route": "redacted",
  "method": "GET",
  "msg": "Unable to parse float value: 2021-08-01T00:00:00.000Z",
  "timer": 240,
  "int": "apigateway",
  "statusCode": 500,
  "coldStart": true,
  "stack": "
Error: Unable to parse float value: 2021-08-01T00:00:00.000Z\n
    at parseFloatString (/var/task/node_modules/@aws-sdk/smithy-client/dist/cjs/parse-utils.js:325:19)\n 
    at limitedParseDouble (/var/task/node_modules/@aws-sdk/smithy-client/dist/cjs/parse-utils.js:286:16)\n
    at deserializeAws_restJson1Field (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:950:48)\n
    at /var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:971:16\n
    at Array.map (<anonymous>)\n
    at deserializeAws_restJson1FieldList (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:967:10)\n
    at /var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:1046:16\n
    at Array.map (<anonymous>)\n
    at deserializeAws_restJson1SqlRecords (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:1042:10)\n
    at deserializeAws_restJson1ExecuteStatementCommand (/var/task/node_modules/@aws-sdk/client-rds-data/dist/cjs/protocols/Aws_restJson1.js:512:28)",
  "remaining": 9391,
  "function": "redacted",
  "memory": "1536",
  "path": "redacted",
  "ip": "redacted",
  "device": "unknown",
  "country": "unknown",
  "version": "v1"
}
```

**Comment by yenfryherrerafeliz** [comment]
Hi @indeediansbrett, is this still a persistent issue for you?, if so, could you please confirm if have the same problem using the latest version of the SDK?

Thanks!

**Comment by indeediansbrett** [comment]
Uhhh better late than never? I pivoted off this a long time ago when it became apparent RDS in Lambda has issues

**Comment by yenfryherrerafeliz** [comment]
@indeediansbrett sorry it took a long getting back to you. Please if you have any other issues feel free to open a new issue and will be happy to assist you.

Thanks!
