### ISSUE TITLE
S3 client incorrectly sign requests with special object key

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#283]
**Describe the bug**
S3 client incorrectly sign requests with special object key

**Additional context**
```typescript
    const client = new S3Client({region: 'us-west-2'});
    const command = new PutObjectCommand({
        Key: 'key?:colon',
        Bucket: 'bucket',
        Body: 'body'
    });
    try {
        const data = await client.send(command);
        console.log(data);
    } catch(e) {
        console.log(e)
    }
```
response:
```
{ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at RestParser.exports.s3ErrorUnmarshaller [as parseServiceException] (/Users/zheallan/workspace/aws-sdk-js-v3/packages/s3-error-unmarshaller/build/index.js:46:58)
    at /Users/zheallan/workspace/aws-sdk-js-v3/packages/protocol-rest/build/RestParser.js:27:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SignatureDoesNotMatch',
  message:
   'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  details: {},
  '$metadata':
   { httpHeaders:
      { 'x-amz-request-id': 'F3E9A251974AF6C4',
        'x-amz-id-2':
         '//lL4YKgVhUwD/29upCQcqyniyrDAJSuTyUrnjjUQKeSmVcB2M3SzCDIyBJxRBPpGSQfJN1/oT4=',
        'content-type': 'application/xml',
        'transfer-encoding': 'chunked',
        date: 'Fri, 28 Jun 2019 18:30:33 GMT',
        connection: 'close',
        server: 'AmazonS3' },
     httpStatusCode: 403,
     requestId: 'F3E9A251974AF6C4',
     extendedRequestId:
      '//lL4YKgVhUwD/29upCQcqyniyrDAJSuTyUrnjjUQKeSmVcB2M3SzCDIyBJxRBPpGSQfJN1/oT4=',
     cfId: undefined,
     retries: 0,
     totalRetryDelay: 0 } }
```

**Comment by AllanFly120** [comment]
It turns our the sigV4 signer for S3 double-uri-encoded the the request path. I will push a fix.
