### ISSUE TITLE
Getting clients in CommonJS, expecting ES6, with client protocol-http: 3.36.0

### ISSUE THREAD

**Issue by brmur** [aws/aws-sdk-js-v3#2899]
### Describe the bug
Attempting to import HttpHandler from `"@aws-sdk/protocol-http"` yields error `Named export 'HttpHandler' not found.`

### Your environment
Windows

### SDK version number
```json
{
  "dependencies": {
    "@aws-sdk/signature-v4": "3.30.0",
    "@aws-sdk/protocol-http": "3.36.0",
    "@aws-sdk/credential-provider-node": "3.30.0"
  },
  "type": "module"
}
```

Is the issue in the browser/Node.js/ReactNative?
Node

Details of the browser/Node.js/ReactNative version
v16.3.0

Steps to reproduce
package.json

```json
{
  "dependencies": {
    "@aws-sdk/signature-v4": "3.30.0",
    "@aws-sdk/protocol-http": "3.36.0",
    "@aws-sdk/credential-provider-node": "3.30.0"
  },
  "type": "module"
}
```

script
```js

import { SignatureV4 } from "@aws-sdk/signature-v4";
import { HttpRequest, HttpHandler} from "@aws-sdk/protocol-http";
//import { HttpRequest } from "@aws-sdk/types";
import { defaultProvider } from "@aws-sdk/credential-provider-node";
var region = 'us-east-1'; // e.g. us-west-1
var domain = 'search-movies-65o7iezozl76qgv7jxwrd3mxii.us-east-1.es.amazonaws.com'; // e.g. search-domain.region.es.amazonaws.com
var index = 'signers-test';
var type = '_doc';
var id = '1';
var json = {
    "title": "Moneyball",
    "director": "Bennett Miller",
    "year": "2011"
};

indexDocument(json);

async function indexDocument(document) {

var request = new HttpRequest({
    body: JSON.stringify(document),
    headers: ['Content-Type = application/json'],
    hostname: domain,
    method: "PUT",
    path: index + '/' + type + '/' + id
});

var signer = new SignatureV4({
    credentials: defaultProvider(),
    region: region,
    service: 'es'
});

console.log(request)

return signer.sign(request);

}
```

### Observed behavior
```console
"import { HttpRequest, HttpHandler} from "@aws-sdk/protocol-http";
                      ^^^^^^^^^^^
SyntaxError: Named export 'HttpHandler' not found. The requested module '@aws-sdk/protocol-http' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aws-sdk/protocol-http';
const { HttpRequest, HttpHandler} = pkg;
```

### Expected behavior
Code to run without error

**Comment by trivikr** [comment]
Verified that issue is reproducible:

```mjs
// index.mjs
import { HttpRequest, HttpHandler } from "@aws-sdk/protocol-http";
```

```console
$ node -v
v14.18.1

$ node index.mjs 
file:///Users/trivikr/workspace/temp/index.mjs:1
import { HttpRequest, HttpHandler } from "@aws-sdk/protocol-http";
                      ^^^^^^^^^^^
SyntaxError: Named export 'HttpHandler' not found. The requested module '@aws-sdk/protocol-http' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aws-sdk/protocol-http';
const { HttpRequest, HttpHandler } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by trivikr** [comment]
This happens because `HttpHandler` is a [TypeScript type](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html) which is removed when TypeScript is compiled to JavaScript.

Source code for HttpHandler: https://github.com/aws/aws-sdk-js-v3/blob/c23cbc468247746f597d7ec5827e119478549ed6/packages/protocol-http/src/httpHandler.ts#L6

```console
$ cat node_modules/@aws-sdk/protocol-http/dist-cjs/httpHandler.js 
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

**Comment by trivikr** [comment]
The type definition is available for HttpHandler though.
```console
$ cat node_modules/@aws-sdk/protocol-http/dist-types/httpHandler.d.ts 
import { HttpHandlerOptions, RequestHandler } from "@aws-sdk/types";
import { HttpRequest } from "./httpRequest";
import { HttpResponse } from "./httpResponse";
export declare type HttpHandler = RequestHandler<HttpRequest, HttpResponse, HttpHandlerOptions>;
```

The following TS file is run without any errors:
```ts
// index.ts
import { HttpRequest, HttpHandler } from "@aws-sdk/protocol-http";
```

```console
$ npm install -D typescript
...

$ npx ts-node index.ts
```
