### ISSUE TITLE
ImageBuilder SDK: Cannot use filter for version

### ISSUE THREAD

**Issue by y0x** [aws/aws-sdk-js-v3#2901]
## Describe the bug
I´m trying to filter the api output of the `listImages` command by a specific version but always get "InvalidParameterCombinationException: The value supplied for parameter 'filters' is not valid. You cannot list Images by name and filter by version in the same request."

#### SDK version number
"@aws-sdk/client-imagebuilder": "^3.36.1"

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Lambda Nodejs 14.x

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

```
const { ImagebuilderClient, ListImagesCommand } = require("@aws-sdk/client-imagebuilder");
const config = { region: "eu-central-1" };

exports.handler = async (event, context, callback) => {

    const client = new ImagebuilderClient(config);

    //Does not work
    const params = {
        filters: [
            {
                "name": "version",
                "values": ['1.0.4']
            }
        ]
    };

    const command = new ListImagesCommand(params);
    try {
        const data = await client.send(command);
        console.log(data);
        // process data.
    } catch (error) {
        // error handling.
        console.log(error)
    } finally {
        // finally.
    }
    callback(null, "Hello World!");
};
```

#### Observed behavior
A clear and concise description of what happens.

Throws following error

```
InvalidParameterCombinationException: The value supplied for parameter 'filters' is not valid. You cannot list Images by name and filter by version in the same request.

 at deserializeAws_restJson1ListImagesCommandError (/var/task/node_modules/@aws-sdk/client-imagebuilder/dist-cjs/protocols/Aws_restJson1.js:5270:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Runtime.exports.handler (/var/task/index.js:24:22)
```

#### Expected behavior
A clear and concise description of what you were expecting to happen.

Return images that have version 1.0.4.

**Comment by vudh1** [comment]
Hi @y0x, thanks for reaching out. Can you confirm if this is still an issue with the latest SDK version `3.42.0`?
