### ISSUE TITLE
"Region is missing" error when using CloudFront

### ISSUE THREAD

**Issue by eddyvlad** [aws/aws-sdk-js-v3#3024]
## Describe the bug
When trying to do invalidation on CloudFront, I get an error 'Region is missing'. As far as I know, CloudFront doesn't require a region.

#### SDK version number
`@aws-sdk/client-cloudfront@3.39.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the Node.js version
v16.11.1

## Steps to reproduce
```javascript
import {
  CloudFront,
  CreateInvalidationCommand,
} from '@aws-sdk/client-cloudfront';

const cloudfront = new CloudFront({
  credentials: awsConfig.credentials,
});

const createInvalidationCommand = new CreateInvalidationCommand({
  DistributionId: awsConfig.distributionId,
  InvalidationBatch: {
    CallerReference: callerReference,
    Paths: {
      Items: itemKeys,
      Quantity: itemKeys.length,
    },
  },
});

cloudfront.send(createInvalidationCommand);
```

#### Observed behavior
The send command failed with error 'Region is missing'

#### Expected behavior
Should return `CreateInvalidationResult` object.

## Error trace
```
Error: Region is missing
    at default (/Users/ec2-user/projects/.../node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /Users/ec2-user/projects/.../node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:77
    at /Users/ec2-user/projects/.../node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async coalesceProvider (/Users/ec2-user/projects/.../node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:13:24)
    at async Object.isConstant [as region] (/Users/ec2-user/projects/.../node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:24:28)
    at async Object.getEndpointFromRegion (/Users/ec2-user/projects/.../node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/utils/getEndpointFromRegion.js:7:20)
    at async Object.serializeAws_restXmlCreateInvalidationCommand (/Users/ec2-user/projects/.../node_modules/@aws-sdk/client-cloudfront/dist-cjs/protocols/Aws_restXml.js:254:68)
    at async /Users/ec2-user/projects/.../node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:21
    at async /Users/ec2-user/projects/.../node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
```

**Comment by eddyvlad** [comment]
Hi @vudh1. That is weird. CloudFront should not require a region. There is no region tied to CloudFront.
![image](https://user-images.githubusercontent.com/200831/142140135-a96f7298-40f5-4e1b-b29d-b5dd87d21b95.png)

**Comment by benheymink** [comment]
I swear this use to work without specifying a region (and so did the S3 client when listing buckets) - has something changed recently?
