### ISSUE TITLE
RestJson tests are failing for server protocols

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3058]
## Describe the bug
RestJson tests are failing for server protocols.

#### SDK version number
main

#### Is the issue in the browser/Node.js/ReactNative?
N/A

#### Details of the browser/Node.js/ReactNative version
N/A

## Steps to reproduce
* Disable skipping of RestJson tests introduced in [`354c0ad` (#3053)](https://github.com/aws/aws-sdk-js-v3/pull/3053/commits/354c0add5afa789535175d140b7688abf6d1fc1c)
* Follow steps in [server-protocol-tests](https://github.com/aws/aws-sdk-js-v3/blob/main/.github/workflows/server-protocol-tests.yml)

#### Observed behavior
Server protocol tests fail with the following error:
```console
  ● RestJsonTestPayloadStructure:ServerRequest

    expect(received).toBeDefined()

    Received: undefined

      29065 |   ][0];
      29066 |   Object.keys(paramsToValidate).forEach((param) => {
    > 29067 |     expect(r[param]).toBeDefined();
            |                      ^
      29068 |     expect(equivalentContents(r[param], paramsToValidate[param])).toBe(true);
      29069 |   });
      29070 | });

      at test/functional/restjson1.spec.ts:29067:22
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/functional/restjson1.spec.ts:29066:33)

  ● RestJsonHttpWithHeadersButNoPayload:ServerRequest

    expect(received).toBeDefined()

    Received: undefined

      29109 |   ][0];
      29110 |   Object.keys(paramsToValidate).forEach((param) => {
    > 29111 |     expect(r[param]).toBeDefined();
            |                      ^
      29112 |     expect(equivalentContents(r[param], paramsToValidate[param])).toBe(true);
      29113 |   });
      29114 | });

      at test/functional/restjson1.spec.ts:29111:22
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/functional/restjson1.spec.ts:29110:33)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 14 skipped, 684 passed, 700 total
Snapshots:   0 total
Time:        17.936 s
Ran all test suites.
error Command failed with exit code 1.
```

#### Expected behavior
RestJSON server protocol tests are successful

## Additional context
[Failures while bumping smithy to 1.14.x](https://github.com/aws/aws-sdk-js-v3/pull/3053#issuecomment-976727058)

**Comment by trivikr** [comment]
The server protocol tests are still failing
https://github.com/aws/aws-sdk-js-v3/pull/3062
