### ISSUE TITLE
The e2e tests for client-s3 are failing with Error during loading "@aws-sdk/karma-credential-loader" plugin

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3094]
## Describe the bug
The e2e tests for client-s3 are failing with Error during loading "@aws-sdk/karma-credential-loader" plugin

#### SDK version number
`main`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
Versions used by karma

## Steps to reproduce
Follow-steps in README in https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-s3/test/e2e

#### Observed behavior
Throws error `Error during loading "@aws-sdk/karma-credential-loader" plugin`

<details>
<summary>Details</summary>

```console
13 12 2021 23:58:17.108:ERROR [plugin]: Error during loading "@aws-sdk/karma-credential-loader" plugin:
  Cannot find module '/local/home/trivikr/workspace/aws-sdk-js-v3/packages/karma-credential-loader/node_modules/@aws-sdk/client-sts/dist-cjs/index.js'. Please verify that the package.json has a valid "main" entry
13 12 2021 23:58:17.453:ERROR [preprocess]: Can not load "credentials", it is not registered!
  Perhaps you are missing some plugin?
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣:    445 modules
ℹ ｢wdm｣: Compiled successfully.
13 12 2021 23:58:28.625:ERROR [karma-server]: Error during file loading or preprocessing
TypeError: process is not a function
    at executeProcessor (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:47:11)
    at runProcessors (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:60:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileList.preprocess [as _preprocess] (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:134:5)
    at async Promise.all (index 0)
    at async /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/file-list.js:90:11
    at async Promise.all (index 4)
13 12 2021 23:58:28.626:ERROR [karma-server]: Error: Found 2 load errors
    at Server.<anonymous> (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/server.js:213:27)
    at Object.onceWrapper (node:events:509:28)
    at Server.emit (node:events:402:35)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1368:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13 12 2021 23:58:28.627:ERROR [karma-server]: UnhandledRejection: process is not a function
13 12 2021 23:58:28.631:ERROR [karma-server]: TypeError: process is not a function
    at executeProcessor (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:47:11)
    at runProcessors (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:60:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FileList.preprocess [as _preprocess] (/local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/preprocessor.js:134:5)
    at async Promise.all (index 0)
    at async /local/home/trivikr/workspace/aws-sdk-js-v3/node_modules/karma/lib/file-list.js:90:11
    at async Promise.all (index 4)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

#### Expected behavior
The e2e tests are successful.

**Comment by trivikr** [comment]
Probably related to https://github.com/aws/aws-sdk-js-v3/pull/3016
