### ISSUE TITLE
"Unauthenticated access is not supported for this identity pool" when authenticated

### ISSUE THREAD

**Issue by jashsayani** [aws/aws-sdk-js-v3#3113]
### Describe the bug
```
fetch-http-handler.js:39 POST https://cognito-identity.us-east-1.amazonaws.com/ 400

Uncaught (in promise) NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at http://localhost:3000/static/js/0.chunk.js:5934:51
    at step (http://localhost:3000/static/js/0.chunk.js:12323:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:12254:14)
    at fulfilled (http://localhost:3000/static/js/0.chunk.js:12209:24)
```

I believe the Cognito part is failing, so SDK thinks everything is setup correctly, sending a Bad Request, and failing subsequent call.

The Cognito request sent by SDK:
```
fetch("https://cognito-identity.us-east-1.amazonaws.com/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "amz-sdk-invocation-id": "REDACTED",
    "amz-sdk-request": "attempt=1; max=3",
    "content-type": "application/x-amz-json-1.1",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "x-amz-target": "AWSCognitoIdentityService.GetId",
    "x-amz-user-agent": "aws-sdk-js/3.45.0 os/macOS/10.15.7 lang/js md/browser/Chrome_96.0.4664.110 api/cognito_identity/3.45.0"
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"IdentityPoolId\":\"REDACTED\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```
(Used "Copy as fetch" in Chrome DevTools)

#### Your environment
SDK version number
```
    "@aws-sdk/client-cognito-identity": "^3.43.0",
    "@aws-sdk/client-dynamodb": "^3.44.0",
    "@aws-sdk/credential-provider-cognito-identity": "^3.45.0",
    "@aws-sdk/credential-providers": "^3.45.0",
```

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
```
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
```

### Steps to reproduce
```
import { fromCognitoIdentityPool } from '@aws-sdk/credential-providers';
import { CognitoIdentityClient } from '@aws-sdk/client-cognito-identity';
import { DynamoDBClient, PutItemCommand } from '@aws-sdk/client-dynamodb';

const REGION = "us-east-1";
const cognitoClient = new CognitoIdentityClient();
const ddbClient = new DynamoDBClient({
  region: REGION,
  credentials: fromCognitoIdentityPool({
    clientConfig: { region: REGION },
    client: cognitoClient,
    identityPoolId: "us-east-1:one-two-three-four-five"
  })
});
const params = {
  TableName: "TABLE_NAME",
  Item: {
    CUSTOMER_ID: { N: "001" },
    CUSTOMER_NAME: { S: "Joe Doe" },
  },
};

ddbClient.send(new PutItemCommand(params));
```

**Comment by jashsayani** [comment]
FYI: I added the `logins` (even though it should be done by the SDK) -

```
const ddbClient = new DynamoDBClient({
  region: REGION,
  credentials: fromCognitoIdentityPool({
    clientConfig: { region: REGION },
    client: cognitoClient,
    identityPoolId: "REDACTED",
    logins: {
      "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_REDACTED": "idToken-JWT-of-user"
    }
  })
});
```

but it says:

```
Uncaught (in promise) NotAuthorizedException: Invalid login token. Issuer doesn't match providerName
    at http://localhost:3000/static/js/0.chunk.js:5934:51
    at step (http://localhost:3000/static/js/0.chunk.js:12323:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:12254:14)
    at fulfilled (http://localhost:3000/static/js/0.chunk.js:12209:24)
```

**Comment by jashsayani** [comment]
Update: it worked after removing "https://" from logins map. However, the logins map is documented as optional and its expected that the `fromCognitoIdentityPool` API gets it and populates it.

**Comment by RanVaknin** [comment]
@jashsayani Hi.

I'm glad to see that you have unblocked yourself. Like @t-lock mentioned, the `logins` param is optional because most uses cases for `fromCognitoIdentityPool()` use Cognito to generate credentials, whereas if you want to use a token from an identity provider you _must_ specify it under the `logins` param as specified in the official docs:

> The Logins parameter is required when using identities associated with external identity providers such as Facebook. For examples of Logins maps, see the code examples in the [External Identity Providers](https://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) section of the Amazon Cognito Developer Guide.

I'll discuss it with the team and see if we can make a documentation revision.

Im closing this issue since it seems like you were able to figure it out. Feel free to reopen if you need any further assistance.
