### ISSUE TITLE
@aws-sdk/client-s3 install throws CMake error

### ISSUE THREAD

**Issue by maximelafarie** [aws/aws-sdk-js-v3#3137]
## Describe the bug
I got an error while installing the latest version of `@aws-sdk/client-s3`

## Your environment
MacOS Monterey 12.1
NPM 8.1.0
Node v16.3.0

#### SDK version number
`@aws-sdk/client-s3@3.45.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js / Install

#### Details of the browser/Node.js/ReactNative version
Node v16.3.0

## Steps to reproduce
Simply run `npm i @aws-sdk/client-s3 --save`

#### Observed behavior
Error happens during the library install

#### Expected behavior
The installation to succeed

#### Screenshots
Here's the console output:
```
❯ npm i @aws-sdk/client-s3 --save
npm ERR! code 1
npm ERR! path /Users/bobby/workspace/my-project/node_modules/aws-crt
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info TOOL Building only the install target, as specified from the command line.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! /Users/bobby/workspace/my-project/node_modules/cmake-js/lib/cMake.js:117
npm ERR!         throw new Error("CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.");
npm ERR!               ^
npm ERR!
npm ERR! Error: CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR!     at CMake.verifyIfAvailable (/Users/bobby/workspace/my-project/node_modules/cmake-js/lib/cMake.js:117:15)
npm ERR!     at CMake.build (/Users/bobby/workspace/my-project/node_modules/cmake-js/lib/cMake.js:287:10)
npm ERR!     at BuildSystem._invokeCMake (/Users/bobby/workspace/my-project/node_modules/cmake-js/lib/buildSystem.js:70:40)
npm ERR!     at async buildFromRemoteSource (/Users/bobby/workspace/my-project/node_modules/aws-crt/scripts/build.js:148:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bobby/.npm/_logs/2022-01-05T10_28_42_792Z-debug.log
```

## Additional context
Nothing

**Comment by maximelafarie** [comment]
Apparently, CMake was missing. `brew install cmake` did the trick.
