### ISSUE TITLE
Errors with ESM/ type: module

### ISSUE THREAD

**Issue by cujarrett** [aws/aws-sdk-js-v3#3231]
## Describe the bug
Tring to use Dynamo SDK calls in Lambda node 14 environment. I am getting module not found errors. I beleive the probelm is rooted in if a package.json uses `"type": "module"`.

## Your environment

Lambda Node 14.x.x

#### SDK version number

```
"@aws-sdk/client-dynamodb": "~3.48.0",
"@aws-sdk/lib-dynamodb": "~3.48.0",
```

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce
Run the function in Lambda that seems to work fine locally.

#### Observed behavior
Error

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Cannot find module '@aws-sdk/querystring-builder'\nRequire stack:\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Cannot find module '@aws-sdk/querystring-builder'\nRequire stack:\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
        "code": "MODULE_NOT_FOUND",
        "requireStack": [
            "/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
            "/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js"
        ],
        "stack": [
            "Error: Cannot find module '@aws-sdk/querystring-builder'",
            "Require stack:",
            "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
            "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
            "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
            "    at Module.require (internal/modules/cjs/loader.js:974:19)",
            "    at require (internal/modules/cjs/helpers.js:93:18)",
            "    at Object.<anonymous> (/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:5:31)",
            "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
            "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
            "    at Module.load (internal/modules/cjs/loader.js:950:32)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
            "    at Module.require (internal/modules/cjs/loader.js:974:19)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Cannot find module '@aws-sdk/querystring-builder'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
        "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)",
        "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:64:3)",
        "    at /var/runtime/deasync.js:23:15",
        "    at _tryAwaitImport (/var/runtime/UserFunction.js:74:12)",
        "    at _tryRequire (/var/runtime/UserFunction.js:162:21)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)"
    ]
}
```

#### Expected behavior
Working without error

## Additional context
My code:

```js
import { DynamoDBClient, QueryCommand, ScanCommand } from "@aws-sdk/client-dynamodb"
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb"
import * as fs from "fs"
const { name } = JSON.parse(fs.readFileSync("./package.json"))

export const getAuth = async () => {
  try {
    // eslint-disable-next-line no-console
    console.log("getAuth called")
    const ddbClient = new DynamoDBClient({ region: "us-east-1" })
    const params = {
      TableName: "destiny-insights-backend-bungie-api-auth",
      KeyConditionExpression: "app = :app",
      ExpressionAttributeValues: { ":app": { "S": name } }
    }

    const response = await ddbClient.send(new QueryCommand(params))
    const authObject = response.Items[0]
    const result = {}
    for (const key of Object.keys(authObject)) {
      result[key] = authObject[key].S || authObject[key].N
    }

    return result
  } catch (error) {
    console.log(error)
  }
}

export const setAuth = async (newAuth) => {
  try {
    // eslint-disable-next-line no-console
  console.log("setAuth called")
  const ddbClient = new DynamoDBClient({ region: "us-east-1" })
  const marshallOptions = {
    convertEmptyValues: false,
    removeUndefinedValues: false,
    convertClassInstanceToMap: false
  }
  const unmarshallOptions = {
    wrapNumbers: false
  }
  const translateConfig = { marshallOptions, unmarshallOptions }
  const ddbDocClient = DynamoDBDocumentClient.from(ddbClient, translateConfig)

  const params = {
    TableName: "destiny-insights-backend-bungie-api-auth",
    Key: { app: name },
    // eslint-disable-next-line max-len
    UpdateExpression: "set #ei = :expiresIn, #ltr = :lastTokenRefresh, #mi = :membershipId, #at = :accessToken, #tt = :tokenType, #rt = :refreshToken, #rei = :refreshExpiresIn",
    ExpressionAttributeValues: {
      ":expiresIn": newAuth.expiresIn,
      ":lastTokenRefresh": newAuth.lastTokenRefresh,
      ":membershipId": newAuth.membershipId,
      ":accessToken": newAuth.accessToken,
      ":tokenType": newAuth.tokenType,
      ":refreshToken": newAuth.refreshToken,
      ":refreshExpiresIn": newAuth.refreshExpiresIn
    },
    ExpressionAttributeNames: {
      "#ei": "expiresIn",
      "#ltr": "lastTokenRefresh",
      "#mi": "membershipId",
      "#at": "accessToken",
      "#tt": "tokenType",
      "#rt": "refreshToken",
      "#rei": "refreshExpiresIn"
    }
  }
  await ddbDocClient.send(new UpdateCommand(params))
  } catch (error) {
    console.log(error)
  }
}

export const getModDataForLastYear = async () => {
  try {
// eslint-disable-next-line no-console
console.log("getModDataForLastYear called")
const ddbClient = new DynamoDBClient({ region: "us-east-1" })
const responses = []
const results = []

// eslint-disable-next-line newline-per-chained-call
const now = new Date().toISOString().split("T")[0]
let oneYearAgo = new Date(now)
oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1)
oneYearAgo = oneYearAgo.toISOString().split("T")[0]

const params = {
  TableName: "destiny-insights-items",
  // eslint-disable-next-line max-len
  FilterExpression: "#ts > :startDate AND (#type = :armorType OR #type = :combatSyleType OR #type = :weaponType)",
  ExpressionAttributeValues: {
    // AWS DynamoDB uses single char for types
    // eslint-disable-next-line id-length
    ":startDate": { S: oneYearAgo },
    // eslint-disable-next-line id-length
    ":armorType": { S: "Armor Mod" },
    // eslint-disable-next-line id-length
    ":weaponType": { S: "Weapon Mod" },
    // eslint-disable-next-line id-length
    ":combatSyleType": { S: "Combat Style Mod" }
  },
  ExpressionAttributeNames: {
    "#ts": "timestamp",
    "#type": "type"
  }
}

const response = await ddbClient.send(new ScanCommand(params))
responses.push(...response.Items)

for (const mod of responses) {
  results.push({
    timestamp: mod.timestamp.S,
    name: mod.name.S,
    type: mod.type.S
  })
}

const sortedResults = results.sort((first, second) => {
  return new Date(second.timestamp) - new Date(first.timestamp)
})

return sortedResults
  } catch (error) {
    console.log(error)
  }
}
```

**Comment by cujarrett** [comment]
Is this my problem?

<img width="802" alt="Screen Shot 2022-02-03 at 10 40 02 PM" src="https://user-images.githubusercontent.com/16245634/152472809-31c706a1-87fd-4c43-a481-7d1d221f85d8.png">

**Comment by cujarrett** [comment]
Looks like it should work.

https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/

**Comment by vudh1** [comment]
Hi @cujarrett is this still persisting. Can you check if you have @aws-sdk/querystring-builder install or mentioned inside `package.json`?

**Comment by cujarrett** [comment]
It's still happening @vudh1 , do I need to explicitly include `@aws-sdk/querystring-builder` in my setup?

I am just doing dynamo query, scan, and update.

I'm currently using these:

```
import { DynamoDBClient, QueryCommand, ScanCommand } from "@aws-sdk/client-dynamodb"
import { DynamoDBDocumentClient, UpdateCommand } from "@aws-sdk/lib-dynamodb"
```

**Comment by stevesirois** [comment]
Same problem here. Just tried to use this example for the SDK docs (https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-dynamodb-utilities.html). I take the same approach, adjust the package.json file ( type = "module" ) and put it in a Lambda and the got the same kind of error : Cannot find module '/var/task/src/handlers/libs/ddbDocClient' imported from /var/task/src/handlers/test-lambda.js

**Comment by cujarrett** [comment]
Any thoughts?

**Comment by cujarrett** [comment]
I think the bug has is rooted in the manner common JS or ESM is handled in the sdk.

**Comment by bguilder** [comment]
I came across a similar issue using AWS Layers and ES modules. Using the absolute specifier for the import fixed the issue for me.
```
import {S3Client, GetObjectCommand} from "file:///opt/nodejs/node_modules/@aws-sdk/client-s3/dist-cjs/index.js";
```

**Comment by cujarrett** [comment]
I’ll take a look, thanks @bguilder 👀

**Comment by cujarrett** [comment]
Still seeing the problem after moving to importing explixct files.

```js
import { DynamoDBClient, QueryCommand, ScanCommand } from "../../node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js"
import { DynamoDBDocumentClient, UpdateCommand } from "../../node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js"
```

@bguilder - Do you have `"type":  "module"` in your `package.json`?

```js
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Cannot find module '@aws-sdk/querystring-builder'\nRequire stack:\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Cannot find module '@aws-sdk/querystring-builder'\nRequire stack:\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js\n- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js\n- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js\n- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js\n- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js\n- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js\n- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js\n- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
        "code": "MODULE_NOT_FOUND",
        "requireStack": [
            "/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
            "/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
            "/var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js",
            "/var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
            "/var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
            "/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
            "/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js"
        ],
        "stack": [
            "Error: Cannot find module '@aws-sdk/querystring-builder'",
            "Require stack:",
            "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
            "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
            "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js",
            "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
            "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
            "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
            "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
            "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
            "    at Module.require (internal/modules/cjs/loader.js:974:19)",
            "    at require (internal/modules/cjs/helpers.js:101:18)",
            "    at Object.<anonymous> (/var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:5:31)",
            "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
            "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
            "    at Module.load (internal/modules/cjs/loader.js:950:32)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
            "    at Module.require (internal/modules/cjs/loader.js:974:19)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Cannot find module '@aws-sdk/querystring-builder'",
        "Require stack:",
        "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js",
        "- /var/task/node_modules/@aws-sdk/node-http-handler/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSOClient.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/SSO.js",
        "- /var/task/node_modules/@aws-sdk/client-sso/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js",
        "- /var/task/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js",
        "- /var/task/node_modules/@aws-sdk/client-sts/dist-cjs/index.js",
        "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js",
        "- /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)",
        "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:64:3)",
        "    at /var/runtime/deasync.js:23:15",
        "    at _tryAwaitImport (/var/runtime/UserFunction.js:74:12)",
        "    at _tryRequire (/var/runtime/UserFunction.js:162:21)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)"
    ]
}
```

**Comment by cujarrett** [comment]
Any thoughts?

**Comment by danielhelen** [comment]
I've found a very similar issue with `@aws-sdk/client-sns`. If I set the package to ES6 (`"type": "module"`), it does not install `@aws-sdk/client-sso` and I get the following:

```
  Cannot find module '@aws-sdk/client-sso'
  Require stack:
  - /my-package/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js
  - /my-package/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js
  - /my-package/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js
  - /my-package/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js
  - /my-package/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
  - /my-package/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
  - /my-package/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
  - /my-package/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
  - /my-package/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
  - /my-package/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
  - /my-package/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
  - /my-package/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
  - /my-package/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
  - /my-package/node_modules/@aws-sdk/client-sns/dist-cjs/runtimeConfig.js
  - /my-package/node_modules/@aws-sdk/client-sns/dist-cjs/SNSClient.js
```

It does work, however, if my package uses CommonJS.

For now I am going to explicitly require `@aws-sdk/client-sso`, but this is obviously not a great long-term solution.

**Comment by JonHolman** [comment]
> Any thoughts?

I know it's been a long time.  In case anyone ends up here via google, like I did.  @bguilder 's tip worked for me, thank you.  I do have `"type": "module"` in my package.json.  

Changing:
`from "@aws-sdk/client-dynamodb";`
to:
`from "file:///opt/nodejs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js";`
which goes to my lambda layer.  Worked for me.

**Comment by aBurmeseDev** [comment]
Hi @cujarrett - apologies for the long silence here. I just came across this and before I investigate, can you please verify this behavior with SDK latest version (also NodeJS) and confirm if this's still an issue?

I also found this similar issue in our repo and will share here for reference: https://github.com/aws/aws-sdk-js-v3/issues/5594
