### ISSUE TITLE
S3 GetBucketLifecycleConfigurationCommand does not work if lifecycle rule applied to entire bucket

### ISSUE THREAD

**Issue by sashakorman** [aws/aws-sdk-js-v3#3274]
## Describe the bug
GetBucketLifecycleConfigurationCommand throws error on a bucket with "all objects in the bucket" lifecycle rule

## Your environment
Windows Node.js

#### SDK version number
`@aws-sdk/client-s3@3.49.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the Node.js version
v17.3.0

## Steps to reproduce
Create a lifecycle rule using "Apply to all objects in the bucket" option.
Try to run GetBucketLifecycleConfigurationCommand

#### Observed behavior
The following error is thrown:
`TypeError: Expected object, got string
    at Object.expectObject (C:\work\sasha\watchdog\node_modules\@aws-sdk\smithy-client\dist-cjs\parse-utils.js:98:11)
    at Object.expectUnion (C:\work\sasha\watchdog\node_modules\@aws-sdk\smithy-client\dist-cjs\parse-utils.js:115:30)
    at deserializeAws_restXmlLifecycleRule (C:\work\sasha\watchdog\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:11792:85)
    at C:\work\sasha\watchdog\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:11876:16
    at Array.map (<anonymous>)
    at deserializeAws_restXmlLifecycleRules (C:\work\sasha\watchdog\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:11872:10)
    at Object.deserializeAws_restXmlGetBucketLifecycleConfigurationCommand (C:\work\sasha\watchdog\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:5568:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\work\sasha\watchdog\node_modules\@aws-sdk\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\work\sasha\watchdog\node_modules\@aws-sdk\middleware-signing\dist-cjs\middleware.js:11:20 {
  '$response': HttpResponse {
    statusCode: 200,
    headers: {
      'x-amz-id-2': 'KLX19q4dytED1NaZyZqX8UCXIrjCmmD7KV6eehjQOj8ih8y4kiFBW9D9GxEmINvLW+K8Nr+UdFQ=',
      'x-amz-request-id': '0RC6NZDQVNPBHJDG',
      date: 'Wed, 02 Feb 2022 16:10:47 GMT',
      server: 'AmazonS3',
      'content-length': '560'
    }`

#### Expected behavior
Rules should be received in the response

#### Code
`import {
    S3Client,
    GetBucketLifecycleConfigurationCommand
} from '@aws-sdk/client-s3';

const client = new S3Client({ region: 'us-west-2' });
const response = await client.send(new GetBucketLifecycleConfigurationCommand({ Bucket: '1bkt1' }));`

**Comment by yenfryherrerafeliz** [comment]
Hi @sashakorman thank you for reaching out and sorry for the delayed response. This issue is also in another [ticket](https://github.com/aws/aws-sdk-js-v3/issues/3585), which is marked to be reviewed, and shows what the problem may be and a possible workaround in the meantime. 

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @sashakorman, this issue has been fixed by the following [PR](https://github.com/aws/aws-sdk-js-v3/pull/3623).

I am closing this issue as completed.

Thanks!
