### ISSUE TITLE
[bug] - Textract AnalyzeDocument + HumanLoopConfig

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws/aws-sdk-js-v3#3306]
## Describe the bug
Log:

```
ERROR	Invoke Error 	
{
    "errorType": "InvalidParameterException",
    "errorMessage": "Request has invalid parameters",
    "code": "InvalidParameterException",
    "message": "Request has invalid parameters",
    "time": "2022-02-11T18:02:52.168Z",
    "requestId": "fce321bd-794d-41af-8213-2687e5e4205a",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 71.68748078340795,
    "stack": [
        "InvalidParameterException: Request has invalid parameters",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}




```

#### SDK version number
`@aws-sdk/package-name@version`

#### Is the issue in the browser/Node.js/ReactNative?
v14 Node.js (Lambda)

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

## Steps to reproduce'

Very similar to this 
```
    console.log("a2i params", {
        FlowDefinitionArn: HUMAN_WORKFLOW_ARN,
        HumanLoopName: event.human_loop_id,
    });
    const params = {
        Document: {
            S3Object: {
                Bucket: event.bucket,
                Name: event.process_key
            }
        },
        FeatureTypes: ["TABLES", "FORMS"],
        HumanLoopConfig: {
            FlowDefinitionArn: HUMAN_WORKFLOW_ARN,
            HumanLoopName: "",
            DataAttributes: {
                ContentClassifiers: [
                    "FreeOfAdultContent",
                ]
            }
        }
    };
    return textract.analyzeDocument(params, (err, data) => {
        if (err) {
            console.log(err, err.stack);
            return err;
        }
        return (data); // successful response
    }).promise();
```

#### Observed behavior
- Callback token never calls, breaks lambda logic

#### Expected behavior
- Expects to return a promise
- More verbose error message for debugging
-

**Comment by MichaelWalker-git** [comment]
I edited out the humanloopname, but I was using something similar to `${event.id}${new Date().toTime()}` to ensure uniqueness.

**Comment by MichaelWalker-git** [comment]
It turned out to because I was using underscores.

**Comment by RanVaknin** [comment]
@MichaelWalker-git ,

It seems like you figured out the issue you were having?
