### ISSUE TITLE
Parsing json code error: `cleanValue.indexOf is not a function`

### ISSUE THREAD

**Issue by WassimBenzarti** [aws/aws-sdk-js-v3#3370]
## Describe the bug
When creating a cloud9 envrionment (using the `CreateEnvironmentEC2Command`) with the same name as another cloud9 environment, I receive the following 400 error that doesn't tell much about the error:
```
TypeError: cleanValue.indexOf is not a function
```

After some investigation, the error seems to be originating from the use of `.indexOf` inside the function [`sanitizeErrorCode`](https://github.com/aws/aws-sdk-js-v3/blob/a331a3b38494fa0c21a0121043a4e7f6c70ee9be/codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/load-json-error-code-stub.ts#L7). This function expects the `rawValue` to be a `string` but the API is returning a `number`.

#### SDK version number
`@aws-sdk/client-cloud9@3.53.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```
v16.13.2
```

## Steps to reproduce
I made this [minimal repository](https://github.com/WassimBenzarti/aws-sdk-js-json-error-code-parsing) to reproduce this bug. 

These are the exact steps to reproduce it:
1. Clone the respository
2. Set all the environment variables related to AWS (or `aws configure`) to set your credentials (Note: the minimal example uses environment variables).
3. Install all the required packages using:
```
yarn
```
4. `yarn start` to run the node file `index.js`

#### Observed behavior
I receieve the following **misleading** error:
```
sandbox@sse-sandbox-6uen59:/sandbox$ yarn start
yarn run v1.22.17
$ node index.js
TypeError: cleanValue.indexOf is not a function
    at sanitizeErrorCode (/sandbox/node_modules/@aws-sdk/client-cloud9/dist-cjs/protocols/Aws_json1_1.js:1280:24)
    at loadRestJsonErrorCode (/sandbox/node_modules/@aws-sdk/client-cloud9/dist-cjs/protocols/Aws_json1_1.js:1293:16)
    at deserializeAws_json1_1CreateEnvironmentEC2CommandError (/sandbox/node_modules/@aws-sdk/client-cloud9/dist-cjs/protocols/Aws_json1_1.js:159:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /sandbox/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /sandbox/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/sandbox/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /sandbox/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
  '$response': HttpResponse {
    statusCode: 400,
    headers: {
      date: 'Sat, 26 Feb 2022 09:14:14 GMT',
      'content-type': 'application/x-amz-json-1.1',
      'content-length': '189',
      connection: 'keep-alive',
      'x-amzn-requestid': '<REDACTED>'
    },
    body: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    }
  },
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
Done in 0.92s.
```

#### Expected behavior
A clear error message stating the name chosen is conflicting with other Cloud9 environments.

#### Screenshots

_Debugging the value of `encoded` in the `parseBody` function inside the generated file  [`Aws_json1_1.js`](https://github.com/aws/aws-sdk-js-v3/blob/a331a3b38494fa0c21a0121043a4e7f6c70ee9be/clients/client-cloud9/src/protocols/Aws_json1_1.ts#L1655)_
<img width="1057" alt="Screen Shot 2022-02-26 at 10 36 53 AM" src="https://user-images.githubusercontent.com/20246795/155838393-b5b6b5ce-140e-4193-b525-334f03e8ba90.png">

_Debugging the value of `data` in the `loadRestJsonErrorCode` function inside the generated file  [`Aws_json1_1.js`](https://github.com/aws/aws-sdk-js-v3/blob/a331a3b38494fa0c21a0121043a4e7f6c70ee9be/clients/client-cloud9/src/protocols/Aws_json1_1.ts#L1669)_
<img width="1059" alt="Screen Shot 2022-02-26 at 10 37 13 AM" src="https://user-images.githubusercontent.com/20246795/155838396-b37953e1-2a9c-4261-88ae-80d55caed07a.png">

## Additional context
The error message (about the conflict in the name) is already returned by the AWS API but it's not correctly parsed thus, the `TypeError` is being displayed instead which is misleading.

**Comment by RanVaknin** [comment]
Hi @WassimBenzarti,

Thanks for the detailed repro steps. I was indeed able to reproduce your error. I have tested it with the AWS CLI and got a "friendlier" error: `An error occurred (ConflictException) when calling the CreateEnvironmentEC2 operation: There is already an environment with this name for the user. Environment name needs to be unique per user. Retry with a different name.`

I'll work on a fix and let you know when it is resolved.
Thank you!

**Comment by RanVaknin** [comment]
@trivikr 
I have confirmed that the issue is coming from [here](https://github.com/aws/aws-sdk-js-v3/blob/95361044a5f2291389bd2886fb5dffe238ae6cdb/clients/client-cloud9/src/protocols/Aws_json1_1.ts#L1667-L1695)
please check out the [pull request](https://github.com/aws/aws-sdk-js-v3/pull/3371) the user has submitted. I have made the same changes to the package locally, and it works as expected.

Thanks.
