### ISSUE TITLE
S3 throws `NotImplemented` error if readStream is created from a file descriptor

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3377]
## Describe the bug
S3 throws `NotImplemented` error if readStream is created from a file descriptor

#### SDK version number
`@aws-sdk/client-s3@3.53.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```console
$ node -v
v16.13.2
```

## Steps to reproduce

Code to run:
```js
import { S3 } from "@aws-sdk/client-s3"; // v3.53.1
import { open } from "fs/promises";

const region = "us-west-2";
const client = new S3({ region });

// File created with command "(for i in {1..1000}; do echo $i "hello world"; done) > hello-world.txt"
const fileName = "hello-world.txt";
const fd = await open(fileName);
const readableStream = fd.createReadStream();

const Bucket = "aws-sdk-js-trivikr";
const Key = fileName;
const Body = readableStream;

try {
  await client.putObject({ Bucket, Key, Body });
} catch (error) {
  console.log({ error });
}
```

#### Observed behavior
Error thrown:
```console
{
  error: NotImplemented: A header you provided implies functionality that is not implemented
      at deserializeAws_restXmlPutObjectCommandError (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:8037:24)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at async /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
      at async StandardRetryStrategy.retry (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
      at async /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
      at async /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
      at async file:///local/home/trivikr/workspace/temp/putObject.fd.mjs:17:3 {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 501,
      requestId: undefined,
      extendedRequestId: 'GOVk18ll6dWtKlcPbQ7rD5uxqSk2Tp7q7ZPXrgSFK+NJbVGq9N1x61TnECH3byDoz36Qpc7It6o=',
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    Code: 'NotImplemented',
    Header: 'Transfer-Encoding',
    RequestId: 'VP83Z7NM6W9B3WJZ',
    HostId: 'GOVk18ll6dWtKlcPbQ7rD5uxqSk2Tp7q7ZPXrgSFK+NJbVGq9N1x61TnECH3byDoz36Qpc7It6o=',
    '$response': HttpResponse {
      statusCode: 501,
      headers: [Object],
      body: [IncomingMessage]
    }
  }
}
```

#### Expected behavior
The putObject operation to be successful.

**Comment by trivikr** [comment]
This happens a content-length is not populated for this special case.
