### ISSUE TITLE
S3 throws ERR_INVALID_ARG_TYPE error if file stream is read from file descriptor when ChecksumAlgorithm is available

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3378]
## Describe the bug
S3 throws ERR_INVALID_ARG_TYPE error if file stream is read from file descriptor when ChecksumAlgorithm is available

#### SDK version number
`@aws-sdk/client-s3@3.53.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
```console
$ node -v
v16.13.2
```

## Steps to reproduce
Code to run:
```js
import { S3 } from "@aws-sdk/client-s3"; // v3.53.1
import { open } from "fs/promises";

const region = "us-west-2";
const client = new S3({ region });

// File created with command "(for i in {1..1000}; do echo $i "hello world"; done) > hello-world.txt"
const fileName = "hello-world.txt";
const fd = await open(fileName);
const readableStream = fd.createReadStream();

const Bucket = "aws-sdk-js-trivikr-flexible-checksums-testing";
const Key = fileName;
const Body = readableStream;
const ChecksumAlgorithm = "CRC32";

await client.putObject({ Bucket, Key, Body, ChecksumAlgorithm });
```

#### Observed behavior
```console
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at new ReadStream (node:internal/fs/streams:171:5)
    at Object.createReadStream (node:fs:2869:10)
    at Object.fsCreateReadStream (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/hash-stream-node/dist-cjs/fsCreateReadStream.js:5:49)
    at readableStreamHasher (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/hash-stream-node/dist-cjs/readableStreamHasher.js:11:93)
    at getAwsChunkedEncodingStream (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/util-stream-node/dist-cjs/getAwsChunkedEncodingStream.js:11:39)
    at /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:31:27
    at /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-expect-continue/dist-cjs/index.js:14:16
    at /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/use-regional-endpoint.js:15:12 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

#### Expected behavior
The putObject call is successful.

## Additional context
We'd previously attempted to support file descriptor, but it was disabled because of issues discussed in https://github.com/aws/aws-sdk-js-v3/issues/3368

**Comment by trivikr** [comment]
Proposal: Do not create copy of stream for hashing, if it's a file stream. Throw an error if provided readableStream is flowing.
https://github.com/aws/aws-sdk-js-v3/blob/a331a3b38494fa0c21a0121043a4e7f6c70ee9be/packages/hash-stream-node/src/fsCreateReadStream.ts#L3-L9

Pros:
* We will not create a copy of filestream using Node.js internals which can change - like in this case where fs.ReadStream is created using file descriptor.
* It will not create a new stream for hashing and use existing stream, resulting in less file descriptors. Lot of file descriptors had caused EMFILE errors in the past discussed in https://github.com/aws/aws-sdk-js-v3/issues/3019

Cons:
*Will cause issues if customer code provides fs.ReadStream which is already flowing will fail. But we suspect this to be a rare case. Customer can always create a new filestream to be passed to client oepration, or attach `.pipe` after the stream is passed to the client operation.
