### ISSUE TITLE
SDK throws "Region is missing" error even if region is defined in config

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#3469]
## Describe the bug
SDK throws "Region is missing" error even if region is defined in config

#### SDK version number
`@aws-sdk/client-dynamodb@3.55.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.14.0

## Steps to reproduce
Configure AWS profile as follows, and verify that region is set in AWS Config

```console
$ aws --version
aws-cli/2.4.27 Python/3.8.13 Linux/5.4.181-109.354.amzn2int.x86_64 source/x86_64.amzn.2 prompt/off

$ aws configure --profile test
AWS Access Key ID [None]: HIDDEN
AWS Secret Access Key [None]: HIDDEN
Default region name [None]: us-west-2
Default output format [None]:

$ cat ~/.aws/config
[profile test]
region = us-west-2
```

Test code to run:
```js
// testRegion.mjs
import { DynamoDB } from "@aws-sdk/client-dynamodb"; // v3.55.0

const client = new DynamoDB({ profile: "test" });
console.log(await client.config.region());
```

#### Observed behavior
```console
/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10
        throw new Error("Region is missing");
              ^

Error: Region is missing
    at default (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async coalesceProvider (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async /local/home/trivikr/workspace/temp/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
    at async Object.region (/local/home/trivikr/workspace/temp/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:17:36)
    at async file:///local/home/trivikr/workspace/temp/testRegion.mjs:4:13
```

#### Expected behavior
Prints `us-west-2`

**Comment by trivikr** [comment]
This happens because `profile` passed in the client configuration is not passed to function fromSharedConfigFiles

https://github.com/aws/aws-sdk-js-v3/blob/ec43acf7340618666ce2171881577b0caa60ad47/packages/node-config-provider/src/fromSharedConfigFiles.ts#L38-L41

**Comment by trivikr** [comment]
The `profile` from client configuration needs to be passed when calling loadConfig

https://github.com/aws/aws-sdk-js-v3/blob/ec43acf7340618666ce2171881577b0caa60ad47/packages/node-config-provider/src/configLoader.ts#L27-L37

https://github.com/aws/aws-sdk-js-v3/blob/ec43acf7340618666ce2171881577b0caa60ad47/clients/client-acm/src/runtimeConfig.ts#L50

**Comment by trivikr** [comment]
Proposed fix: read profile from configuration and pass it to loadNodeConfig call.

Example diff in client-dynamodb:

```console
$ git diff  
diff --git a/clients/client-dynamodb/src/DynamoDBClient.ts b/clients/client-dynamodb/src/DynamoDBClient.ts
index a3241382b9..30196d4e2b 100644
--- a/clients/client-dynamodb/src/DynamoDBClient.ts
+++ b/clients/client-dynamodb/src/DynamoDBClient.ts
@@ -399,6 +399,11 @@ export interface ClientDefaults extends Partial<__SmithyResolvedConfiguration<__
    * The {@link DefaultsMode} that will be used to determine how certain default configuration options are resolved in the SDK.
    */
   defaultsMode?: DefaultsMode | Provider<DefaultsMode>;
+
+  /**
+   * Name of the AWS CLI profile to use.
+   */
+  profile: string | undefined;
 }
 
 type DynamoDBClientConfigType = Partial<__SmithyConfiguration<__HttpHandlerOptions>> &
diff --git a/clients/client-dynamodb/src/runtimeConfig.ts b/clients/client-dynamodb/src/runtimeConfig.ts
index bd9889770e..fb2795e60b 100644
--- a/clients/client-dynamodb/src/runtimeConfig.ts
+++ b/clients/client-dynamodb/src/runtimeConfig.ts
@@ -31,6 +31,7 @@ import { resolveDefaultsModeConfig } from "@aws-sdk/util-defaults-mode-node";
  * @internal
  */
 export const getRuntimeConfig = (config: DynamoDBClientConfig) => {
+  const { profile } = config;
   const defaultsMode = resolveDefaultsModeConfig(config);
   const defaultConfigProvider = () => defaultsMode().then(loadConfigsForDefaultMode);
   const clientSharedValues = getSharedRuntimeConfig(config);
@@ -50,7 +51,8 @@ export const getRuntimeConfig = (config: DynamoDBClientConfig) => {
     endpointDiscoveryEnabledProvider:
       config?.endpointDiscoveryEnabledProvider ?? loadNodeConfig(NODE_ENDPOINT_DISCOVERY_CONFIG_OPTIONS),
     maxAttempts: config?.maxAttempts ?? loadNodeConfig(NODE_MAX_ATTEMPT_CONFIG_OPTIONS),
-    region: config?.region ?? loadNodeConfig(NODE_REGION_CONFIG_OPTIONS, NODE_REGION_CONFIG_FILE_OPTIONS),
+    region:
+      config?.region ?? loadNodeConfig(NODE_REGION_CONFIG_OPTIONS, { profile, ...NODE_REGION_CONFIG_FILE_OPTIONS }),
     requestHandler: config?.requestHandler ?? new RequestHandler(defaultConfigProvider),
     retryMode:
       config?.retryMode ??
```

**Comment by AllanZhengYP** [comment]
Adding `profile` in the client config but only control the `region` resolution will add too much confusion for users. Credentials and other config also relies on the profile. In v2 region resolution, region is only resolved from the default profile or the `AWS_PROFILE` environmental variable. I'm leaning towards keeping the behavior.

**Comment by trivikr** [comment]
Closing this issue as:
* [AWS SDK for JavaScript (v2)](https://github.com/aws/aws-sdk-js/blob/c578c8346494654914efb335779ca2620c3e6b36/lib/config.js#L1) doesn't support passing `profile` during client creation.
* [AWS SDK for Go (v2)](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-profiles) also reads profile only from environment variable `AWS_PROFILE`
* [AWS SDK for Java (v2)](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html#set-a-custom-profile-as-the-default) also reads profile only from environment variable `AWS_PROFILE`
