### ISSUE TITLE
Incorrect date type for emr-containers-client

### ISSUE THREAD

**Issue by dacort** [aws/aws-sdk-js-v3#3511]
## Describe the bug
I believe this is related to #2760 but the `EMRContainersClient` throws an exception when parsing the results of the `ListVirtualClustersCommand` command.

#### SDK version number
`@aws-sdk/client-emr-containers@3.58.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v17.5.0

## Steps to reproduce
1. Open a new node repl
2. Paste the following code
```node
const { EMRContainers, ListVirtualClustersCommand, } = require("@aws-sdk/client-emr-containers");
var emrc = new EMRContainers({ region: "us-east-1" });
emrc.send(new ListVirtualClustersCommand({}));

emrc.listVirtualClusters({}, function(err,data){console.log(err, data)})
```

#### Observed behavior
An uncaught TypeError is thrown:
<details>

```
> Uncaught TypeError: Expected number, got string
    at expectNumber (/Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:32:11)
    at deserializeAws_restJson1VirtualCluster (/Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:1595:124)
    at /Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:1612:16
    at Array.map (<anonymous>)
    at deserializeAws_restJson1VirtualClusters (/Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:1608:10)
    at deserializeAws_restJson1ListVirtualClustersCommand (/Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:1031:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/dcortesi/src/emr-tools-v2/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
```

</details>

#### Expected behavior
Expect a list of virtual clusters to be shown on the console. 

## Additional context
I tried this with version 3.30.0 as well and observed the following output:
```
    {
      arn: 'arn:aws:emr-containers:us-east-1:<REDACTED>:/virtualclusters/<REDACTED>',
      containerProvider: [Object],
      createdAt: Invalid Date,
      id: '<REDACTED>',
      name: 'dacort-virtual-emr',
      state: 'RUNNING',
      tags: {}
    }
```

Note the `Invalid Date` under `createdAt`. 

When running `aws emr-containers list-virtual-clusters` the `createdAt` field is shown as a string: `"2021-03-04T00:02:32+00:00"`

**Comment by yenfryherrerafeliz** [comment]
Hi @dacort, thanks for opening this issue. Could you please test in the latest version of the SDK and see if the problem persist there?. In my local reproduction I am not having any issues, but it maybe because I am not getting the same list of virtual cluster that you are getting as response. So, if you are still experiencing this issue could you please do the following so I can have the exact response you are getting:
- install the node http handler ```npm i @aws-sdk/node-http-handler ```
- Then, create a customer handler class, that extends from the base handler class as follow:
```js
class CustomHandler extends NodeHttpHandler {
    handle(request, {abortSignal}) {
        const promise = super.handle(request, {abortSignal});
        
        return promise.then((response) => {
            const readableStream = response.response.body;
            const chunks = [];
            // On Data
            readableStream.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
            // On Error
            readableStream.on('error', (error) => {
                console.log('Error: ', error)
                process.exit(1)
            })
            // On End
            readableStream.on('end', () => {
                console.log('Response: ', Buffer.concat(chunks).toString('utf-8'));
            })

            return response;
        });
    }
}
```

And then use an instance of that class as the request handler for the client as follow:
```js
const client = new EMRContainers({
    region: "us-east-2",
    requestHandler: new CustomHandler()
});
const response = await client.send(new ListVirtualClustersCommand({}));
```

A full example would be:

<details>

```js
import {
    EMRContainers,
    ListVirtualClustersCommand,
} from "@aws-sdk/client-emr-containers";
import {
    NodeHttpHandler
} from "@aws-sdk/node-http-handler";

class CustomHandler extends NodeHttpHandler {
    handle(request, {abortSignal}) {
        const promise = super.handle(request, {abortSignal});

        return promise.then((response) => {
            const readableStream = response.response.body;
            const chunkArray = [];
            // On Data
            readableStream.on('data', (chunk) => chunkArray.push(Buffer.from(chunk)));
            // On Error
            readableStream.on('error', (error) => {
                console.log('Error: ', error)
                process.exit(1)
            })
            // On End
            readableStream.on('end', () => {
                console.log('Response: ', Buffer.concat(chunkArray).toString('utf-8'));
            })

            return response;
        });
    }
}

const client = new EMRContainers({
    region: "us-east-2",
    requestHandler: new CustomHandler()
});
const response = await client.send(new ListVirtualClustersCommand({}));

console.log('Response: ', response);

```
</details>

Then, please post the logged response here. 

Note: Please make sure you redact any sensitive information.

Thanks!

**Comment by dacort** [comment]
Hi @yenfryherrerafeliz - Looks like this is now resolved. I tried `3.245.0` of the `@aws-sdk/client-emr-containers` package.

Thanks for following up!
