### ISSUE TITLE
GetBucketLocationCommand - cross account issue

### ISSUE THREAD

**Issue by amithalle** [aws/aws-sdk-js-v3#3603]
## Describe the bug
When calling GetBucketLocationCommand  for a cross account bucket, we are getting Access Denied, even though permission-wise we are supposed to get a correct answer

#### SDK version number
`@aws-sdk/client-s3@3.88.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.19.1

## Steps to reproduce
```js
const {
  S3Client,
  GetObjectCommand,
  HeadObjectCommand,
  GetBucketLocationCommand,
  NoSuchKey,
  NotFound,
} = require("@aws-sdk/client-s3");

async function get_bucket_client(bucket_name) {
  const S3 = new S3Client({ region: "eu-central-1" });
  const getLoc = new GetBucketLocationCommand({ Bucket: bucket_name });
  const bucket_region = await S3.send(getLoc);

  return new S3Client({ region: bucket_region.LocationConstraint });
}
```

#### Observed behavior
we get the following exception when calling the above function with a cross account bucket
```console
AccessDenied: Access Denied
    at deserializeAws_restXmlGetBucketLocationCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protoc
ols/Aws_restXml.js:5621:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/app/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async get_bucket_client (/app/src/utils/s3.js:15:27) [truncated...]
```
#### Expected behavior
We expect to get no error

## Additional context
we did check that the bucket has policy with the following statement
```json
{
    "Effect": "Allow",
    "Principal": {
        "AWS": [
            "arn:aws:iam::src_account_id_1:root",
            "arn:aws:iam::src_account_id_2:root"
        ]
    },
    "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
    ],
    "Resource": "arn:aws:s3:::my-bucket"
}
```

plus, the role running the nodejs script has this policy
```json
{
    "Statement": [
        {
            "Action": [
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::my-bucket/*",
                "arn:aws:s3:::my-bucket",
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

also notable, the same behavior is seen with aws-cli v1 but not v2:
```console
# docker run -i --rm -v /root/.aws:/root/.aws -v /app:/aws amazon/aws-cli --version
aws-cli/2.6.3 Python/3.9.11 Linux/4.14.232-177.418.amzn2.x86_64 docker/x86_64.amzn.2 prompt/off

# docker run -i --rm -v /root/.aws:/root/.aws -v /app:/aws amazon/aws-cli s3api get-bucket-location --bucket my-bucket --profile src_account
{
    "LocationConstraint": "eu-west-1"
}
# aws --version
aws-cli/1.22.26 Python/3.7.10 Linux/4.14.232-177.418.amzn2.x86_64 botocore/1.23.26
# aws s3api get-bucket-location --bucket my-bucket --profile src_account 

An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied

```

**Comment by yenfryherrerafeliz** [comment]
Hi @amithalle, thank you for reaching out. After a deeper investigation, I found that the error that you are getting may be due to the region specified for the client that is sending the command, to get the bucket location, being different from where the bucket is located. Analyzing the nature of this command, probably the region should not be a parameter to validate when getting the region is the intention of this command. I will mark this issue to review so we can investigate this further. I expect to provide you an update after we end with the reviewing. 

Thanks!

**Comment by AllanZhengYP** [comment]
Hi @amithalle 

Sorry for taking so long the get back to this ticket. I can no longer reproduce the issue. Can you confirm the issue still happens to you?

```
const client = new S3Client({ region: "eu-central-1" });
client.send(new GetBucketLocationCommand({ Bucket })).then((resp) => {
  console.log(resp);
});

/**
{
  '$metadata': {
...
  },
  LocationConstraint: 'ap-northeast-1'
}
**/
```
