### ISSUE TITLE
Repeat of Issue 3068

### ISSUE THREAD

**Issue by ekasprzyk** [aws/aws-sdk-js-v3#3708]
### Describe the bug

As per https://github.com/aws/aws-sdk-js-v3/issues/3068

In our case:

```js
const deleteFileApi = async (
  req: NextApiRequest,
  res: NextApiResponse
): Promise<void> => {
  const body = JSON.parse(req.body);
  console.log(body);

  console.log(process.env.AWS_SDK_LOAD_CONFIG);
  console.log(process.env.AWS_PROFILE);

  if (!body.bucket) {
    res.status(400).send('Missing bucket');
    return;
  }

  if (!body.key) {
    res.status(400).send('Missing bucket');
    return;
  }

  const client = new S3Client({});

  if (req.method === 'DELETE') {
    const command = new DeleteObjectCommand({
      Bucket: body.bucket,
      Key: body.key,
    });
    const response = await client.send(command);

    res
      .status(response.$metadata.httpStatusCode || 500)
      .json(response.$metadata);
  }
};

export default deleteFileApi;
```

### Expected Behavior

That the s3 sdk would initialise properly and detect the .aws folder, loading credentials correctly.

### Current Behavior

We used the same code as we've used elsewhere in other repos and got the `environmentVariableSelector` error outlined in the issue.

### Reproduction Steps

This cropped up in one of our NextJS apps.  

### Possible Solution

It might be due to the way that NextJS passes environment variables into the application.

We're using no config in the S3 client itself because it picks it up form the AWS_PROFILE and AWS_LOAD_SDK_CONFIG variables.  

This is happening in one of the API routes, so it might not be picking those up, however, it doesn't seem to be a barrier in some of our other apps.

However, this error is a bit vague.  Are we just not providing the right credentials?  Or are they wrong?  It's hard to tell.

### SDK version used

3.107 and 3.112 both had this problem

### Environment details (OS name and version, etc.)

Mac OS Catalina

**Comment by ajredniwja** [comment]
@ekasprzyk thanks for opening this issue. As mentioned in the docs, the V3 uses default credential provider which tries to resolve the credentials in an order mentioned in the link below. "When obtaining credentials in Node.js, be careful about relying on more than one source, such as an environment variable and a JSON file you load."

https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html

It be helpful to see the stack trace as well.

**Comment by ekasprzyk** [comment]
Here you go:

```
TypeError: Cannot destructure property 'environmentVariableSelector' of 'undefined' as it is undefined.
    at loadConfig (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/node-config-provider/dist/cjs/configLoader.js:8:23)
    at getRuntimeConfig (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js:56:185)
    at new S3Client (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:20:64)
    at deleteFileApi (webpack-internal:///./src/pages/api/s3/files/delete.ts:22:18)
    at apiResolver (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DevServer.handleApiRequest (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/next-server.js:64:462)
    at async Object.fn (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/next/dist/next-server/server/next-server.js:34:504)
```

BTW, does it help to know that we're also successfully using the AWS sdk v3 for MediaVodPipeline?

This is what the API route in NextJS looks like for that case:

```
onst awsConfig = {
  region: environment === 'PROD' ? 'us-east-1' : 'eu-west-1',
};

const getAssetApi = async (
  req: NextApiRequest,
  res: NextApiResponse
): Promise<void> => {
  const { id: assetId } = req.query;

  if (!assetId) {
    res.status(400).send('Missing assetId');
    return;
  }

  if (req.method === 'GET') {
    const command = new DescribeAssetCommand({ Id: assetId as string });
    const client = new MediaPackageVodClient(awsConfig);
    const asset: DescribeAssetResponse = await client.send(command);

    res.status(200).json(asset);
  }
};

export default getAssetApi;
```

Would love to know why one is picking up the credentials and the other isn't.

**Comment by ekasprzyk** [comment]
Any updates on this?  It's basically blocked an API I'm trying to create to manage some AWS resources.

**Comment by ekasprzyk** [comment]
Got a little further by doing:

```
  const client = new S3Client({
    region: 'us-east-1',
    useDualstackEndpoint: false,
    useFipsEndpoint: false,
  });
```

But the send now fails with:

```
TypeError: (0 , config_resolver_1.getRegionInfo) is not a function
    at Object.defaultRegionInfoProvider [as regionInfoProvider] (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/dist-cjs/endpoints.js:447:98)
    at getEndPointFromRegion (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/config-resolver/dist/cjs/EndpointsConfig.js:34:45)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async serializeAws_restXmlDeleteObjectCommand (/Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:849:68)
    at async /Users/ela/Projects/dtplus-new/media-publishing/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:21
```

In fact the config resolver looks like this:

```
{
  resolveCustomEndpointsConfig: [Getter],
  resolveEndpointsConfig: [Getter],
  REGION_ENV_NAME: [Getter],
  REGION_INI_NAME: [Getter],
  NODE_REGION_CONFIG_OPTIONS: [Getter],
  NODE_REGION_CONFIG_FILE_OPTIONS: [Getter],
  resolveRegionConfig: [Getter]
}
```
which is blatantly missing a load of config parameters that the library expects and was why the earlier parts were failing.  

Pausing there, may try and track more tomorrow.

**Comment by ekasprzyk** [comment]
OK, I fixed this.  

For anyone else having this issue - it's an old version of the SDK not playing nicely with the rest of the config libraries, which will be newer.

I was working in a repo that had s3 set up previously a year or two back and everything else I wrote was newer, and that's how it happened.  That and goddamn COVID...
