### ISSUE TITLE
InvalidSignatureException when using `@aws-sdk/client-transcribe-streaming` SDK

### ISSUE THREAD

**Issue by matthabermehl** [aws/aws-sdk-js-v3#3796]
### Describe the bug

Following this guide: https://docs.aws.amazon.com/transcribe/latest/dg/getting-started-sdk.html

I have tried including using a root level access key as well as an IAM user access key with `AmazonTranscribeFullAccess` permission.

Using node 16.16.0

When running the file, I get error 
```
response = new TranscribeStreamingServiceException_1.TranscribeStreamingServiceException({
                       ^
InvalidSignatureException: 'Host' or ':authority' must be a 'SignedHeader' in the AWS Authorization.

```

### Expected Behavior

Expect call to be made successfully after providing correct credentials to the SDK

### Current Behavior

Response
```
{
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: '78320ae7-9fea-4142-ab28-6fde15db4ff0',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 301
  }
```

### Reproduction Steps

 https://docs.aws.amazon.com/transcribe/latest/dg/getting-started-sdk.html

### SDK version used

3.128.0

### Environment details (OS name and version, etc.)

Mac OS 11.6.3 (Big Sur)

**Comment by archiehharris** [comment]
I am encountering what appears to be the same error when using the package **@aws-sdk/client-kinesis** (v3.128.0). PutRecordsCommand is throwing an error (excerpt from CloudWatch)

**InvalidSignatureException: 'Host' or ':authority' must be a 'SignedHeader' in the AWS Authorization.**
`at deserializeAws_json1_1PutRecordsCommandError (/opt/nodejs/node_modules/@aws-sdk/client-kinesis/dist-cjs/protocols/Aws_json1_1.js:1245:24)`
`at processTicksAndRejections (node:internal/process/task_queues:96:5)`
`at async /opt/nodejs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24`
`at async /opt/nodejs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20`
`at async StandardRetryStrategy.retry (/opt/nodejs/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)`
`at async /opt/nodejs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22`

possibly caused by https://github.com/aws/aws-sdk-js-v3/pull/3789
