### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by ionscorobogaci** [aws/aws-sdk-js-v3#3831]
### Describe the bug

When using the library inside lambda bundled with ESM, the following error is displayed always

```json
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"crypto\" is not supported",
    "stack": [
        "Error: Dynamic require of \"crypto\" is not supported",
        "    at file:///var/task/index.mjs:12:9",
        "    at asset-input/node_modules/uuid/dist/rng.js (file:///var/task/index.mjs:2099:42)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/uuid/dist/v1.js (file:///var/task/index.mjs:2184:39)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/uuid/dist/index.js (file:///var/task/index.mjs:2567:37)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js (file:///var/task/index.mjs:2590:18)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/commands/CancelRotateSecretCommand.js (file:///var/task/index.mjs:4657:25)"
    ]
}
```

### Expected Behavior

The client should be able to read the secret value

### Current Behavior

this error is always thrown

```json
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"crypto\" is not supported",
    "stack": [
        "Error: Dynamic require of \"crypto\" is not supported",
        "    at file:///var/task/index.mjs:12:9",
        "    at asset-input/node_modules/uuid/dist/rng.js (file:///var/task/index.mjs:2099:42)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/uuid/dist/v1.js (file:///var/task/index.mjs:2184:39)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/uuid/dist/index.js (file:///var/task/index.mjs:2567:37)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js (file:///var/task/index.mjs:2590:18)",
        "    at __require2 (file:///var/task/index.mjs:15:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/commands/CancelRotateSecretCommand.js (file:///var/task/index.mjs:4657:25)"
    ]
}
```

### Reproduction Steps

Create a lambda function and bundle it as ESM, for example with CDK :

```js
new NodejsFunction(scope, 'EsmNodeJsFunction', {
      functionName: props.stage.concat(HYPHEN).concat('esm-node-js'),
      description: 'Check nodejs function esm build',
      handler: 'handler',
      depsLockFilePath: join(__dirname, '../../../services/package-lock.json'),
      entry: join(__dirname, '../../../services/account-settings/fail/index.js'),
      runtime: Runtime.NODEJS_16_X,
      logRetention: RetentionDays.TWO_WEEKS,
      bundling: {
        format: OutputFormat.ESM,
      },
    });
```
lambda handler 

```js
import { GetSecretValueCommand, SecretsManagerClient } from '@aws-sdk/client-secrets-manager';
const client = new SecretsManagerClient({});

export const handler = async (event) => {
  const getSecretValueCommand = new GetSecretValueCommand({ SecretId: 'secret-name' });
  const secret = await client.send(getSecretValueCommand);
  const secretValue = JSON.parse(secret.SecretString);
  console.log('secretValue : ', secretValue);
  return secretValue;
};
```

### Additional Information/Context

this only fails when deployed with CDK via NodejsFunction and 

```
    bundling: {
        format: OutputFormat.ESM,
    }
```

### SDK version used

3.131.0

### Environment details (OS name and version, etc.)

lambda environment running on nodejs 16

**Comment by RanVaknin** [comment]
Hi @ionscorobogaci,

I see that you have opened the same issue in CDK. Since this is clearly a CDK related issue, and not JS SDK, Im closing it and ask that you wait for an update from the CDK team on the original ticket.

**Comment by ionscorobogaci** [comment]
@RanVaknin , yes agree. it's a CDK issue, the bundling has to be passed like this in order to be able to use top-level awaits :
```
      bundling: {
        format: OutputFormat.ESM,
        mainFields: ['module', 'main'],
        minify: true,
        target: 'esnext',
        banner: "import { createRequire } from 'module';const require = createRequire(import.meta.url);",
      }
```
i don't think there is something to wait from cdk team, as they were not even able to understand the issue in 2 weeks ))) we fixed it, hope this help others as well.

**Comment by VladimirGrenaderov** [comment]
@RanVaknin it's not CDK issue, explanation & workaround [here](https://github.com/aws/aws-cdk/issues/21329#issuecomment-1212336356)
