### ISSUE TITLE
PostToConnection not working

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#3835]
### Describe the bug

Trying to use PostToConnection for a ping/pong socket route.

Getting the error

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at parseUrl (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/url-parser/dist-cjs/index.js:6:60)
    at resolveEndpointsConfig (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/resolveEndpointsConfig.js:14:87)
    at new ApiGatewayManagementApiClient (/opt/nodejs/node_modules/@aws-sdk/client-apigatewaymanagementapi/dist-cjs/ApiGatewayManagementApiClient.js:18:72)
    at Handler.main (/var/task/index.js:10:35)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1016:29) {
  input: '2lcn9ye627.execute-api.eu-west-1.amazonaws.com/socket',
  code: 'ERR_INVALID_URL'
}
```

Code:

```
class Handler {
  main = async (event: APIGatewayProxyWebsocketEventV2) => {
    try {
      const apiClient = new ApiGatewayManagementApiClient({
        endpoint: event.requestContext.domainName + '/' + event.requestContext.stage,
        region: REGION,
      });
      const connectionID = event.requestContext.connectionId;
      await apiClient.send(new PostToConnectionCommand({
        ConnectionId: connectionID,
        Data: new TextEncoder().encode('pong!'),
      }));
    } catch (error) {
      console.error(error);
      return { statusCode: 500, body: JSON.stringify(error) };
    }
    return { statusCode:200 };
  };
}
```

### Expected Behavior

route should respond with "pong!"

### Current Behavior

No response from socket route. Error in logs.

### Reproduction Steps

* Create `$connect` and `ping` routes
* Connect to socket via wscat
* Send `{"action":"ping"}` via wscat
* No response in wscat, error in log

### SDK version used

3.137.0 (client-apigatewaymanagementapi)

### Environment details (OS name and version, etc.)

AWS Lambda NodeJS v16

**Comment by paul-uz** [comment]
Seems you need to include `https://` in the endpoint URL 🙄
