### ISSUE TITLE
marshallInput fails to marshall AttributeUpdates for map attributes

### ISSUE THREAD

**Issue by aaaristo** [aws/aws-sdk-js-v3#3849]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug
```js
marshallInput({ AttributeUpdates: { customer: { Action: "PUT", Value: { first_name: 'Andrea', last_name: 'Gariboldi' } } } }, [{"key":"AttributeUpdates","children":{"children":[{"key":"Value"}]}}])) 
```
returns
```console
{
    "AttributeUpdates": {
        "customer": {
            "Action": "PUT",
            "Value": {
                "first_name": {
                    "S": "Andrea"
                },
                "last_name": {
                    "S": "Gariboldi"
                }
            }
        }
    }
}
```
But it should return
```console
{
    "AttributeUpdates": {
        "customer": {
            "Action": "PUT",
            "Value": {
                "M": {
                    "first_name": {
                        "S": "Andrea"
                    },
                    "last_name": {
                        "S": "Gariboldi"
                    }
                }
            }
        }
    }
}
```
Then it fails shortly after due to the fact that Value has an unknown type
```console
TypeError: Cannot read property '0' of undefined
  at Object.AttributeValue.visit (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:457:40)
  at serializeAws_json1_0AttributeValue (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3025:38)
  at serializeAws_json1_0AttributeValueUpdate (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3049:45)
  at /code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3020:20
  at Array.reduce (<anonymous>)
  at serializeAws_json1_0AttributeUpdates (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3014:34)
  at serializeAws_json1_0UpdateItemInput (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:4216:31)
  at serializeAws_json1_0UpdateItemCommand (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:476:27)
  at serialize (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/UpdateItemCommand.js:30:72)
  at /code/api/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:27
  at /code/api/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/baseCommand/DynamoDBDocumentClientCommand.js:11:20
```

### SDK version number

@aws-sdk/lib-dynamodb@3.142.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.18.1

### Reproduction Steps
```js
JSON.stringify(require('./node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/utils.js').marshallInput({ AttributeUpdates: { customer: { Action: "PUT", Value: { first_name: 'Andrea', last_name: 'Gariboldi' } } } }, [{"key":"AttributeUpdates","children":{"children":[{"key":"Value"}]}}]))
```
### Observed Behavior

I got his error while trying to update an object with the document client 
```console
TypeError: Cannot read property '0' of undefined
  at Object.AttributeValue.visit (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:457:40)
  at serializeAws_json1_0AttributeValue (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3025:38)
  at serializeAws_json1_0AttributeValueUpdate (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3049:45)
  at /code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3020:20
  at Array.reduce (<anonymous>)
  at serializeAws_json1_0AttributeUpdates (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3014:34)
  at serializeAws_json1_0UpdateItemInput (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:4216:31)
  at serializeAws_json1_0UpdateItemCommand (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:476:27)
  at serialize (/code/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/UpdateItemCommand.js:30:72)
  at /code/api/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:27
  at /code/api/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/baseCommand/DynamoDBDocumentClientCommand.js:11:20
```
### Expected Behavior

It is possible to set map attributes using the document client on a dynamodb item

**Comment by yenfryherrerafeliz** [comment]
Hi @aaaristo, thanks for opening this issue. I tried to reproduce the reported behavior but in my tests I got successfully results. 
Please see below:
```js
const {marshallInput} = require('../node_modules/@aws-sdk/lib-dynamodb/dist-cjs/commands/utils.js');

const response = marshallInput({ AttributeUpdates: { customer: { Action: "PUT", Value: { first_name: 'Andrea', last_name: 'Gariboldi' } } } }, [{"key":"AttributeUpdates","children":{"children":[{"key":"Value"}]}}]);

console.log('Response: ', JSON.stringify(response));
```
Output:
```console
Response:  {"AttributeUpdates":{"customer":{"Action":"PUT","Value":{"first_name":{"S":"Andrea"},"last_name":{"S":"Gariboldi"}}}}}
```
The versions I tested with are:
-  @aws-sdk/lib-dynamodb@3.142.0
-  @aws-sdk/lib-dynamodb@3.145.0

So, could you please try updating to the latest version?

Thanks!

**Comment by aaaristo** [comment]
The output above is not correct, you are trying to set a map attribute. And it will fail if you try to send an actual UpdateItem command.

**Comment by yenfryherrerafeliz** [comment]
> @yenfryherrerafeliz The output above is not correct, you are trying to set a map attribute. And it will fail if you try to send an actual UpdateItem command.

Hi @aaaristo, I can confirm this is an issue. Unfortunately the marshallInput function does not handle map attributes yet, nonetheless I will mark this issue to be reviewed, so we can further address this.

Thanks!

**Comment by zoellner** [comment]
given that aws-sdk v3 is the new default, I would assume that it is stable and feature complete (general availability 2 years as of today). This seems to be a pretty big issue for anyone using DynamoDB and is a blocker for switching to v3. 
Can we expect a fix soon? If not, I think this should be added to the [Known Issues](https://github.com/aws/aws-sdk-js-v3#known-issues)

**Comment by aaaristo** [comment]
@ajredniwja you have an example fix here, I'm not familiar with the build system but if you can point me to some doc maybe I can make a test for it

https://github.com/aws/aws-sdk-js-v3/pull/3850

**Comment by Aanu1995** [comment]
While migrating my code to use v3, I also experienced the issue with both Map attributes and Array Attributes..... It is a blocker for me too. I will appreciate if the issue could be fixed
