### ISSUE TITLE
TimeoutError is not retried

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js-v3#3851]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are experiencing intermittent `TimeoutError` errors when using the SDK, particularly the `ListRulesCommand` in EventBridge.

```
Error: AWS SDK error wrapper for TimeoutError: socket hang up
    at asSdkError (/home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:88:12)
    at StandardRetryStrategy.retry (/home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:61:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-logger@3.127.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at func (/home/runner/work/project/project/test.ts:174:13)
    at Object.<anonymous> (/home/runner/work/project/project/test.ts:315:7) {
    '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

According to the [service-error-classification](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/service-error-classification/src/constants.ts), we would expect `TimeoutError` to be included as a transient error code, and therefore automatically retried, however this does not occur. By logging the error above, we see that there was only one attempt.

### SDK version number

@aws-sdk/client-eventbridge@3.128.0
@aws-sdk+middleware-retry@3.127.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.16.0

### Reproduction Steps

The error occurs intermittently when running integration tests in a workflow, however it always occurs on the same API call in the same test.

```ts
const client = new EventBridgeClient({
  region: "eu-central-1",
});

await client.send(
  new ListRulesCommand({
    EventBusName: "event-bus",
    NamePrefix: "rule",
  })
);
```

### Observed Behavior

```
Error: AWS SDK error wrapper for TimeoutError: socket hang up
    at asSdkError (/home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:88:12)
    at StandardRetryStrategy.retry (/home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:61:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/runner/work/project/project/node_modules/.pnpm/@aws-sdk+middleware-logger@3.127.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at func (/home/runner/work/project/project/test.ts:174:13)
    at Object.<anonymous> (/home/runner/work/project/project/test.ts:315:7) {
    '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

The API call would retry by itself and then succeed.

**Comment by cecheta-lego** [comment]
This seems to be an issue caused by using `jest`

https://github.com/facebook/jest/issues/2549

I am guessing that all these checks fail, therefore a new Error object is created

https://github.com/aws/aws-sdk-js-v3/blob/fcb4ba102eafbc847048c9b83d99ac9733fe620e/packages/middleware-retry/src/StandardRetryStrategy.ts#L120

**Comment by yenfryherrerafeliz** [comment]
Hi @cecheta-lego, thanks for opening this issue. This issue seems to be similar to this [one](https://github.com/aws/aws-sdk-js-v3/issues/4219), where I have asked for more details to reproduce the error. In that related issue I see there are 3 retries, so, could you update to the latest version and see if the error is retried there?

Thanks!

**Comment by cecheta-lego** [comment]
Hello @yenfryherrerafeliz,

This error occurs intermittently when we run tests in a GitHub Actions workflow. We are using v3.215.0. When the error occurred, there were no retries, most likely due to this comment https://github.com/aws/aws-sdk-js-v3/issues/3851#issuecomment-1211618132.

I no longer have access to the codebase so I will be unable to reproduce this again or update to the latest version.
