### ISSUE TITLE
GetPipelineStateCommand Not Returning Token

### ISSUE THREAD

**Issue by jacob-hyde** [aws/aws-sdk-js-v3#3871]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am attempting to use the PutApprovalResultCommand, however it requires a token according to the docs.

Within the documentation at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codepipeline/interfaces/putapprovalresultcommandinput.html under token it states "The system-generated token used to identify a unique approval request. The token for each open approval request can be obtained using the GetPipelineState action. It is used to validate that the approval request corresponding to this token is still valid."

The GetPipelineStateCommand however does not return a token. Looking at the source code, the only two fields returned in a stages latestExecution property are pipelineExecutionId and status.

### SDK version number

@aws-sdk/client-codepipeline@3.154.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18.6.0

### Reproduction Steps

`async function pollPipeline(pipeline, spinner) {
  let command = new GetPipelineStateCommand({
    name: pipeline,
  })

  let response = await client.send(command);
  let stages = response.stageStates;
  let stage = stages.find(stage => stage.latestExecution.status === 'InProgress');
  **console.log(stage.latestExecution.token)**

  if (stage) {
    spinner.text = `${pipeline} - ${stage.stageName}: ${stage.latestExecution.status}`;
  }

  if (stage && stage.stageName !== 'Approval') {
    await sleep(10000)
    pollPipeline(pipeline, spinner)
  } else {
    command = new PutApprovalResultCommand({
      actionName: stage.actionStates[0].actionName,
      pipelineName: pipeline,
      stageName: stage.stageName,
      result: {
        summary: 'Approved',
        status: 'Approved',
      },
      token: '??'
    });
    response = await client.send(command);
    console.log(response)
  }
}`

### Observed Behavior

`ValidationException: 1 validation error detected: Value at 'token' failed to satisfy constraint: Member must not be null
    at deserializeAws_json1_1ValidationExceptionResponse (/Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/client-codepipeline/dist-cjs/protocols/Aws_json1_1.js:2317:23)
    at deserializeAws_json1_1PutApprovalResultCommandError (/Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/client-codepipeline/dist-cjs/protocols/Aws_json1_1.js:1432:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/xxx/Sites/devops-tools/util/update-rc-aws/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async pollPipeline (file:///Users/xxx/Sites/devops-tools/util/update-rc-aws/index.js:177:16) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '9cea9e31-b72c-4263-a514-c899ec66fe2c',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'ValidationException'
}`

### Expected Behavior

Ability to get the token from the stage and pass it to the PutApprovalResultCommand

### Possible Solution

Return the token in the GetPipelineStateCommand

**Comment by ajredniwja** [comment]
Hey @jacob-hyde thanks for opening the issue, I was able to reproduce it and get similar results, have reached `codePipeLine` team for some more insight.

**Comment by aBurmeseDev** [comment]
Hi there, sorry for the long silence here. I tracked this internally and found a response from service team: 

>Customer may be referring to the incorrect object.

>They should look at `stageStates[<stageNum>].actionStates[<actionNum>].latestExecution.token` (look at the GetPipelineState response model https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_GetPipelineState.html ) I think the customer is trying to use stageState[<stageNum>].latestExecution object which does not have token info. This is probably because customer is assuming that approval is a stage, however it is actually an action.

Hope it helps and if there's any other questions we can communicate to service team, please let us know.
