### ISSUE TITLE
AWS SDK error wrapper for Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by ap0h** [aws/aws-sdk-js-v3#3879]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

```typescript
const s3 = new S3Client({
  apiVersion: '2006-03-01',
  region: AWS_REGION,
  endpoint: MOTO_SERVER_ENDPOINT,
  forcePathStyle: true,
})

const removeFiles = async (fileKeys: string | string[], bucketName = AWS_BUCKET_NAME) => {
  if (!Array.isArray(fileKeys)) {
    fileKeys = [fileKeys]
  }

  return s3
    .send(
      new DeleteObjectsCommand({
        Bucket: bucketName,
        Delete: {
          Objects: fileKeys.map((key) => ({ Key: key })),
        },
      }),
    )
}
```
When I call `removeFiles()` function I got the following error.
```
Error: AWS SDK error wrapper for Error [ERR_STREAM_WRITE_AFTER_END]: write after end
            at asSdkError (/Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:88:12)
            at StandardRetryStrategy.retry (/Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:61:29)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at /Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
            at /Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
          '$metadata': { attempts: 1, totalRetryDelay: 0 }
```

### SDK version number

@aws-sdk/client-s3@3.44.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.19.3

### Reproduction Steps

I'm using latest  `motoserver/moto` docker image for testing.
Just pull the image and write test to upload and remove file. 

### Observed Behavior

```
Error: AWS SDK error wrapper for Error [ERR_STREAM_WRITE_AFTER_END]: write after end
            at asSdkError (/Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:88:12)
            at StandardRetryStrategy.retry (/Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:61:29)
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
            at /Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
            at /Users/apox/Projects/TX/mx-trip-service/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22 {
          '$metadata': { attempts: 1, totalRetryDelay: 0 }
```

### Expected Behavior

To pass without any errors.

**Comment by ap0h** [comment]
Looks like it's a motoserver issue, when I change motoserver docker version  to 3.1.1 putCommand is working fine and with the last version it throws the error mentioned here.
