### ISSUE TITLE
Upgrade uuid to > 9

### ISSUE THREAD

**Issue by spence-novata** [aws/aws-sdk-js-v3#3964]
### Describe the feature

uuid v9 brings changes to exports allowing it to work with latest versions of Jest without a moduleNameMapper workaround

See https://github.com/uuidjs/uuid/issues/451

### Use Case

I'd like to update to jest 29 without hacks

### Proposed Solution

Update to UUID v9

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.171.0

### Environment details (OS name and version, etc.)

macos 12.5

**Comment by Fouzyyyy** [comment]
Hello here 👋 

Is this being worked on? Or should someone else take it?

**Comment by Fouzyyyy** [comment]
Hello @ajredniwja @spence-novata 

Is there any plan to move forward with this issue?

**Comment by yoyoonarock** [comment]
Hey there! Just wanted to bump this and ask if there are any plans to upgrade to `uuid` v9.0.0 - we're facing a similar issue and don't want to have to implement a `moduleNameMapper` or custom resolver.

Additional related threads:
https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149
https://github.com/uuidjs/uuid/pull/616

**Comment by kachkaev** [comment]
Getting this warning with each `pnpm install`:

```
deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

```
pnpm why uuid@3
```
```
pnpm why uuid@3                                       20:10:49
Legend: production dependency, optional only, dev only

dependencies:
@aws-amplify/api-graphql 3.2.0
├─┬ @aws-amplify/api-rest 3.1.0
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/auth 5.3.6
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/cache 5.0.32
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/core 5.3.0
│ ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│ │ └─┬ @aws-sdk/middleware-retry 3.6.1
│ │   └── uuid 3.4.0
│ ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│ │ └─┬ @aws-sdk/middleware-retry 3.6.1
...
```

**Comment by diogotorres97** [comment]
bump on this one 🙏

**Comment by RanVaknin** [comment]
Approved @yoyoonarock 's PR.

**Comment by mxro** [comment]
Note while this upgrades `uuid` in the `@aws-sdk/` packages, I still get an error since `uuid@8.3.2` is a dependency in `@smithy/middleware-retry@2.1.2`, which is used by many of the SDK packages.

```
SyntaxError: Unexpected token 'export'

      38 |   });
      39 | };
    > 40 |
         | ^
      41 | export interface ConnectTableParams {
      42 |   deploymentName?: string;
      43 |   documentClient?: DynamoDBDocumentClient;

      at Runtime.createScriptFromCode (../../.yarn/cache/jest-runtime-npm-29.5.0-e692162e2b-7af27bd9d5.zip/node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (../../.yarn/cache/@smithy-middleware-retry-npm-2.1.1-82a581ceb3-a4bc59d2ff.zip/node_modules/@smithy/middleware-retry/dist-cjs/index.js:51:19)
```

This is with client SDK versions `3.521.0`
