### ISSUE TITLE
Decode InvokeCommandOutput.Payload object on "@aws-sdk/client-lambda" package

### ISSUE THREAD

**Issue by jamesnight1994** [aws/aws-sdk-js-v3#4021]
### Describe the issue

I am invoking my lambda function like so in express.JS TypeScript, expecting the following response from my lambda function.
```JSON
{
  "challenge_name": "CHALLENGE_NAME",
  "session":  "session string"
}
```

. I did this using the following package https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/index.html

```Typescript
import { LambdaClient, InvokeCommand, InvokeCommandOutput } from "@aws-sdk/client-lambda"; 
const command = new InvokeCommand({
                FunctionName: this.client_name,
                InvocationType: 'RequestResponse',
                Payload: Buffer.from(JSON.stringify(event))
    
            });
            const response: InvokeCommandOutput = await this.client.send(command);
            let payLoad = response.Payload;
            if(payLoad != undefined){
                return response.Payload;
            }
```
I've also tried the example on  AWS as well as the `toUtf8` and `fromUtf8` functions in the SDK to decode the UINT8Array. However, they give me the following error.
```
{"errorType":"TypeError","errorMessage":"The \"key\" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null","trace":["TypeError [ERR_INVALID_ARG_TYPE]: The \"key\" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null","    at new NodeError (node:internal/errors:372:5)","    at prepareSecretKey (node:internal/crypthe \"key\" argument must be of type string or ano/keys:580:11)","    at new Hmac (node:internal/crypto/hash:132:9)","    at createHmac (node:crypto:162:10)","    at AuthService.initiateAuth (/var/task/main.js:57511:48)","    at processTicksAndRejections (node:internal/process/task_queues:crypto/hash:132:9)","    at createHmac (node:cry96:5)","    at async Runtime.handler (/var/task/main.js:34:9)"]}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-lambda/classes/invokecommand.html

**Comment by RanVaknin** [comment]
Hi @jamesnight1994 ,

I'm not entirely sure why you are getting this error. I spun up a lambda and got the desired output

Client Setup:
```js
import { LambdaClient, InvokeCommand } from "@aws-sdk/client-lambda"; 

const client = new LambdaClient({region: "us-east-1"})

const command = new InvokeCommand({
    FunctionName: lambdaName,
    InvocationType: 'RequestResponse',
});

try {
    const response = await client.send(command);
    const payLoad = response.Payload;
    if (payLoad != undefined){
        const asciiDecoder = new TextDecoder('ascii');
        const data = asciiDecoder.decode(response.Payload);
        console.log(data)
    }
} catch (error) {
    console.log(error)
}
```

Output:
```console
{
  "challenge_name": "CHALLENGE_NAME",
  "session": "session string"
}
```

This error is very convoluted and could stem from different issues.
- Not sure what is `event` here in your case. Maybe the way you are sending your request is not correct?
- Try to update your dependencies perhaps. 
- Removing `package.json` and running `npm init` again
- Converting your file to js instead of ts might help isolate the problem.

Let me know if that helps.

Thanks,
Ran~

**Comment by jamesnight1994** [comment]
> Hi @jamesnight1994 ,
> 
> I saw you opened a discussion in this repo as well. I'm closing this issue in favor of helping you in the discussion thread instead.
> 
> Thanks, Ran

Thanks for closing the issue the payload was null actually due to an error on lambda caused by my Lambda clients' payload.  My dumb mistake
