### ISSUE TITLE
SyntaxError: Unexpected export specifier type in aws

### ISSUE THREAD

**Issue by milk-XD** [aws/aws-sdk-js-v3#4130]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi aws-sdk team,

AWS SDK package does not work properly with mongodb dependency in Vue project, while using `npm install mongodb`. Can you help to take a look?

### SDK version number

"@aws-sdk/util-endpoints": "3.200.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v17.7.2

### Reproduction Steps

1. Create a Vue project
2. Run `npm install mongodb`
3. Setup MongoDB in a JS file `database.js`
    `const MongoClient = require('mongodb').MongoClient;`
4. Import the JS file in a Vue file
    `import * as database from '../../server/mongodb/database.js'`
5. Compile the project, you will see the exception

### Observed Behavior

`23:00:29.128 Module build failed (from ./node_modules/babel-loader/lib/index.js):
23:00:29.136 SyntaxError: {{project_path}}/node_modules/@aws-sdk/util-endpoints/dist-es/lib/index.js: Unexpected export specifier type
23:00:29.136 > 1 | export * as aws from "./aws";
23:00:29.144     |        ^^^^^^^^
23:00:29.145   2 | export * from "./booleanEquals";
23:00:29.156   3 | export * from "./getAttr";
23:00:29.156   4 | export * from "./isSet";
23:00:29.170     at File.buildCodeFrameError (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/core/lib/transformation/file/file.js:248:12)
23:00:29.177     at NodePath.buildCodeFrameError (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/path/index.js:144:21)
23:00:29.188     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:150:22
23:00:29.205     at Array.forEach (<anonymous>)
23:00:29.222     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:148:31
23:00:29.223     at Array.forEach (<anonymous>)
23:00:29.238     at getModuleMetadata (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:96:27)
23:00:29.239     at normalizeModuleAndLoadMetadata (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:39:7)
23:00:29.255     at rewriteModuleStatementsAndPrepareHeader (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/helper-module-transforms/lib/index.js:77:54)
23:00:29.272     at PluginPass.exit (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:145:83)
23:00:29.288     at newFn (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/visitors.js:179:21)
23:00:29.305     at NodePath._call (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/path/context.js:55:20)
23:00:29.322     at NodePath.call (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/path/context.js:42:17)
23:00:29.339     at NodePath.visit (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/path/context.js:99:8)
23:00:29.355     at TraversalContext.visitQueue (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/context.js:112:16)
23:00:29.372     at TraversalContext.visitSingle (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@babel/traverse/lib/context.js:84:19)`

### Expected Behavior

The Vue file can import database JS file properly and execute CRUD operations.

**Comment by koshic** [comment]
@milk-XD is it https://stackoverflow.com/questions/61718768/how-can-i-export-as-namespace-in-babel ?

**Comment by milk-XD** [comment]
@koshic Problem resolved! Thanks!
