### ISSUE TITLE
@aws-sdk/client-ssm does not load credentials from environment

### ISSUE THREAD

**Issue by clever-rob** [aws/aws-sdk-js-v3#4230]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Any call to @aws-sdk/client-ssm fails woith the following error message
"Could not load credentials from any providers"

AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are correctly defined as environment variables.

import { SSM } from '@aws-sdk/client-ssm'
const ssmClient = new SSM()

const params = { Name: '{ssm param name}', WithDecryption: true }
const res = await ssmClient.getParameter(params)

### SDK version number

"@aws-sdk/client-ssm: 3.216.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.12.1

### Reproduction Steps

AWS_REGION, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are correctly defined as environment variables.

test.spec.js:

import { SSM } from '@aws-sdk/client-ssm'
const ssmClient = new SSM()

const params = { Name: '{ssm param name}', WithDecryption: true }
const res = await ssmClient.getParameter(params)

### Observed Behavior

      AssertionError [ERR_ASSERTION]: {"statusCode":500,"headers":{"Content-Type":"application/json"},"body":"{\"message\":\"Could not load credentials from any providers\"}"}

### Expected Behavior

get ssm parameters

### Possible Solution

Error appears only in version 3 of the AWS SDK.
(aws sdk v2 runs fine)

**Comment by clever-rob** [comment]
Added stack trace

CredentialsProviderError: Could not load credentials from any providers
    at /kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/client-ssm/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
    at /kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/client-ssm/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async coalesceProvider (/kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/client-ssm/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async SignatureV4.credentialProvider (/kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/client-ssm/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
    at async SignatureV4.signRequest (/kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/middleware-signing/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:86:29)
    at async /kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18
    at async StandardRetryStrategy.retry (/kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /kake/api/lambda/mqtt-cert/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async getParam (file:///kake/api/lambda/mqtt-cert/test/test.spec.js:17:15)
    at async Context.<anonymous> (file:///kake/api/lambda/mqtt-cert/test/test.spec.js:30:32) {

**Comment by yenfryherrerafeliz** [comment]
Hi @clever-rob, thanks for opening this issue. I am not able to reproduce the reported behavior. Basically, I do not have any problems using aws env variables on my end. Please make sure the variables are being exported and loaded correctly. Maybe, if you are running your code from an IDE you may need to restart the IDE since if the variables were set after you launched your IDE, they will not be propagated to that process until a restart happens. You can also validate if the variables are being loaded by node process by doing the following before instancing the client:
```js
const varsAreSet = process.env.AWS_SECRET_ACCESS_KEY && process.env.AWS_ACCESS_KEY_ID;
console.log(varsAreSet ? "Variables are set" : "Variables are not set!");
```

Another option you have in the meantime is to specify which credential provider you want to use when instancing the client, which in this case would from environment. You can do the following:

```console
npm install @aws-sdk/credential-provider-env
```

```js
import {SSM} from "@aws-sdk/client-ssm";
import {fromEnv} from "@aws-sdk/credential-provider-env";

const client = new SSM({
    region: 'us-east-2',
    credentials: fromEnv()
});
const params = { Name: '{param}', WithDecryption: true }
const res = await client.getParameter(params);

console.log(res);
```

Thanks!
