### ISSUE TITLE
TypeError: Passphrase required for encrypted key 

### ISSUE THREAD

**Issue by unchaptered** [aws/aws-sdk-js-v3#4231]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Need to create new Params of passphrase in `@aws-sdk/cloudfront-signer`.

Iternally, `@aws-sdk/cloudfront-signer`  is using **crypto.sign** to create sign.

For creating **Viewer Access Restrictions of cloudfront**, we must use **RSA key only**.

Also, we need to provide passphrase of RSA key for **crypto.sign** when we use this libs.

getSignedUrl and getSignedCookie can receive **passphrase params** in @aws-sdk/cloudfront-signer/src/sign.ts.

So, these function always throw Error about 'TypeError: Passphrase required for encrypted key'.

### SDK version number

@aws-sdk/cloudfront-signer@3.215.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.0

### prepare RSA-SHA256 key using ssh-keygen

```sh
ssh-keygen -t rsa -b 2048 -m PEM -f private.pem -P abcdeabcdeabcdeabcde
ssh-keygen -e -m PEM -f private.pem > public.pem
```

### call getSIgnedUrl

```javascript
const privateKey = fs.readFileSync(path.join(process.cwd(), 'private.pem'), 'utf8');
const { getSignedUrl } = require('@aws-sdk/cloudfront-signer');

// Sample Variables
const url= 'sample.com';
const keyPairId= 'KEY_PAIR_ID';

const signedUrl = getSignedUrl({
    url,
    keyPairId,
    privateKey,
    dateLessThan: new Date(Date.now() + 1000 * 60 * 60)
});
```

### Observed Behavior

```cmd
TypeError: Passphrase required for encrypted key 
    at Sign.sign (node:internal/crypto/sig:131:29)
    at CloudfrontSignBuilder.signData (~\node_modules\@aws-sdk\cloudfront-signer\dist-cjs\sign.js:212:21)
    at CloudfrontSignBuilder.signPolicy (~\node_modules\@aws-sdk\cloudfront-signer\dist-cjs\sign.js:215:42)
    at CloudfrontSignBuilder.createCloudfrontAttribute (~\node_modules\@aws-sdk\cloudfront-signer\dist-cjs\sign.js:240:32)
    at getSignedUrl (~\node_modules\@aws-sdk\cloudfront-signer\dist-cjs\sign.js:27:57)
    at Object.<anonymous> (~\api\video\controllers\videoController.js:60:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  code: 'ERR_MISSING_PASSPHRASE'
}
```

### Expected Behavior

When I run this code, I expect to return getSignedUrl (string).

### Possible Solution

I create folk and PR to sovle it.

### Additional Information/Context

Our campany need to use @aws-sdk/cloudfront-signer, so we wanna quickly changes this error.

@Jeff-edint, @Edint-Lay. @Kevin-edint(me)

### CONTACT

unchaptered@edint.io
workstation19961002@gmail.com

**Comment by trivikr** [comment]
I'm able to reproduce the issue

Code:
```ts
// getSignedUrl.ts
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { getSignedUrl } from "@aws-sdk/cloudfront-signer"; // v3.222.0

const privateKey = readFileSync(join(process.cwd(), "private.pem"), "utf8");

// Sample Variables
const url = "http://example.com";
const keyPairId = "KEY_PAIR_ID";

const signedUrl = getSignedUrl({
  url,
  keyPairId,
  privateKey,
  dateLessThan: new Date(Date.now() + 1000 * 60 * 60).toDateString(),
});
```

Output:
```console
$ node -v
v16.18.1

$ esr getSignedUrl.ts                                             
TypeError: Passphrase required for encrypted key
    at Sign.sign (node:internal/crypto/sig:131:29)
    at CloudfrontSignBuilder.signData (/local/home/trivikr/workspace/test/node_modules/@aws-sdk/cloudfront-signer/dist-cjs/sign.js:212:21)
    at CloudfrontSignBuilder.signPolicy (/local/home/trivikr/workspace/test/node_modules/@aws-sdk/cloudfront-signer/dist-cjs/sign.js:215:42)
    at CloudfrontSignBuilder.createCloudfrontAttribute (/local/home/trivikr/workspace/test/node_modules/@aws-sdk/cloudfront-signer/dist-cjs/sign.js:240:32)
    at getSignedUrl (/local/home/trivikr/workspace/test/node_modules/@aws-sdk/cloudfront-signer/dist-cjs/sign.js:27:57)
    at Object.<anonymous> (/local/home/trivikr/workspace/test/getSignedUrl.ts:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module._compile (/local/home/trivikr/.fnm/node-versions/v16.18.1/installation/lib/node_modules/esbuild-runner/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.mod._compile (/local/home/trivikr/.fnm/node-versions/v16.18.1/installation/lib/node_modules/esbuild-runner/src/hook.ts:53:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

**Comment by unchaptered** [comment]
> Posted comments on #4232 to make it backward compatible.

Thnaks to kind reply!
I'm sorry about **that I forgot to post a code that could be reproduced**.

I wish it changes.

**Comment by unchaptered** [comment]
Solve this issue!
