### ISSUE TITLE
`Cannot find module '@aws-sdk/credential-provider-process'` for  S3 and SNS clients.

### ISSUE THREAD

**Issue by dszczepaniak-cksource** [aws/aws-sdk-js-v3#4264]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I try to upgrade @aws-sdk packages from `3.188.0` to `3.226.0` and as up to `3.224.0` I encountered issue from https://github.com/aws/aws-sdk-js-v3/issues/4075, running clients from `3.226.0` causes that a different message is emitted:

```
Error: Cannot find module '@aws-sdk/credential-provider-process'
Require stack:
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProcessCredentials.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-node@3.226.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-node@3.226.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
```

I've tried to install `@aws-sdk/credential-providers` but it did not resolve the issue. The issue can be resolved by installing `@aws-sdk/credential-provider-process` but the docs says clearly:
```
## Usage
You probably shouldn't, at least directly. Please use [@aws-sdk/credential-providers](https://www.npmjs.com/package/@aws-sdk/credential-providers) instead.
``` 

So I believe it is not an intentional flow.

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.13.1 but the same happens on Node 18

### Reproduction Steps

Just initialize a SQS client

```
const { SQS } = require( '@aws-sdk/client-sqs' );

this._sqs = new SQS( config );
```

### Observed Behavior

```
Error: Cannot find module '@aws-sdk/credential-provider-process'
Require stack:
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProcessCredentials.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-ini@3.226.0/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-node@3.226.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
- /project/node_modules/.pnpm/@aws-sdk+credential-provider-node@3.226.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
- /project/node_modules/.pnpm/@aws-sdk+client-sts@3.226.0/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.226.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
```

### Expected Behavior

As before `3.188.0` it was possible to use clients without additional credential packages I believe that including required libs is expected. If the lib cannot be included in the client packages, then adding `@aws-sdk/credential-providers` should resolve the issue.

**Comment by RanVaknin** [comment]
Hi @dszczepaniak-cksource ,

I'm not sure why you are running into this. Your repro code is missing your config. 
With 3.226.0 Im able to create a client and call the SQS api without an issue:

```js
const { SQS, ListQueuesCommand } = require( '@aws-sdk/client-sqs' );


const client = new SQS( {region: "us-east-1"} );

async function run(){
    try {
        const data = await client.send(new ListQueuesCommand({}))
        console.log(data)
    } catch (error) {
        console.log(error)
    }
}
run()
```
Output:
```console
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  NextToken: undefined,
  QueueUrls: [ 'https://sqs.us-east-1.amazonaws.com/REDACTED/test-queue' ]
}
```

That cognito error does not seem related to what you are describing.
I would do the following:
1. Delete your `package-lock.json` and run `npm install` again
2. Run `npm list` or `npm list -a` and check if you have there some unused dependencies that you might want to get rid of.

Let me know that helps at all,

Thanks,
Ran~

**Comment by o-alexandrov** [comment]
Same issue with `npm` v9 (latest).
The only aws-sdk v3 package I'm using in the project is `@aws-sdk/credential-provider-ini`.

Referring to the package above, triggers an error:
```sh
Error: Cannot find module '@aws-sdk/credential-provider-process'
Require stack:
- .../node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProcessCredentials.js
- .../node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
- .../node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js

...and unrelated stack afterwards
```

**Comment by RanVaknin** [comment]
@o-alexandrov , @douddle 

Can you please write some repro steps? before I can reproduce what you are experiencing I can't do anything on my end.

Thanks,
Ran~

**Comment by dszczepaniak-cksource** [comment]
> I would do the following:
> Delete your package-lock.json and run npm install again
> Run npm list or npm list -a and check if you have there some unused dependencies that you might want to get rid of.

I got the described error both on the local machine as well as on the CI pipeline. I use pnpm 6.10.3 for installing packages. The package I develop uses:
```
"@aws-sdk/client-sns": "3.186.0",
"@aws-sdk/client-sqs": "3.186.0",
"@aws-sdk/client-s3": "3.186.0",
"@aws-sdk/node-http-handler": "3.186.0",
```
I have updated packages to:
```
"@aws-sdk/client-s3": "3.229.0",
    "@aws-sdk/client-sns": "3.229.0",
    "@aws-sdk/client-sqs": "3.229.0",
    "@aws-sdk/node-http-handler": "3.226.0",
```
and the error message has been changed:
```
Error: Cannot find module '@aws-sdk/util-retry'
Require stack:
- /project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.229.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/AdaptiveRetryStrategy.js
- /project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.229.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/index.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.229.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.229.0/node_modules/@aws-sdk/client-s3/dist-cjs/S3.js
- /project/node_modules/.pnpm/@aws-sdk+client-s3@3.229.0/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
- /project/tests/integration/IntegrationTests.ts
- /project/node_modules/.pnpm/mocha@6.2.2/node_modules/mocha/lib/mocha.js
- /project/node_modules/.pnpm/mocha@6.2.2/node_modules/mocha/lib/cli/one-and-dones.js
- /project/node_modules/.pnpm/mocha@6.2.2/node_modules/mocha/lib/cli/options.js
- /project/node_modules/.pnpm/mocha@6.2.2/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/node_modules/.pnpm/@aws-sdk+middleware-retry@3.229.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/AdaptiveRetryStrategy.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/project/node_modules/.pnpm/ts-node@8.6.2_typescript@4.5.4/node_modules/ts-node/src/index.ts:807:44)
    at Module.load (node:internal/modules/cjs/loader:
```

In the affected file, clients are initialized as follows:

```
import { S3 } from '@aws-sdk/client-s3';
import { SQS, CreateQueueResult } from '@aws-sdk/client-sqs';

// ...

console.log('test1')

const s3 = new S3(
			{
				endpoint: 'http://localhost:4570',
				region: 'eu-west-1',
				credentials: {
					accessKeyId: 'accesskey',
					secretAccessKey: 'secretkey'
				},
				forcePathStyle: true
			}
		);

console.log('test2')

const sqs = new SQS(
			{
				endpoint: 'http://localhost:4576',
				region: 'eu-west-1',
				credentials: {
					accessKeyId: 'accesskey',
					secretAccessKey: 'secretkey'
				}
			}
		);

console.log('test3')
```

When I put a few console logs, none of the placed console logs were shown so it seems it fails before initializing clients.

**Comment by douddle** [comment]
PNPM is proposing a workaround by the way: [PNPM/packageExtensions](https://pnpm.io/fr/package_json#pnpmpackageextensions)
It should be done in the root package.json, not in a submodule.

**Comment by dszczepaniak-cksource** [comment]
The issue was reproducible both on Node 18 and 16, I use TS and CommonJS approach.

**Comment by RanVaknin** [comment]
Hi @dszczepaniak-cksource ,

Can you please create a minimal repo for reproduction? 

Thanks,
Ran

**Comment by mhassan1** [comment]
This should be resolved by https://github.com/aws/aws-sdk-js-v3/pull/4302.

**Comment by dszczepaniak-cksource** [comment]
@mhassan1 I can confirm https://github.com/aws/aws-sdk-js-v3/pull/4302 resolved the issue, thank you for your help! I close the issue as completed. Also @RanVaknin thanks for your engagement.
