### ISSUE TITLE
codecommit: unable to get all comments for pull requests 

### ISSUE THREAD

**Issue by PhilipAbed** [aws/aws-sdk-js-v3#4267]
### Describe the issue

I'm trying to get all pull request comments, so i'm using : `GetCommentsForPullRequestCommand`

according to [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecommit/interfaces/getcommentsforpullrequestcommandinput.html)

the `afterCommitId` and `beforeCommitId` are optional,

yet when i try to get all comments i get: `A commit ID is required, but no commit ID was specified`

see full exception:
```
   "err": {
         "name": "CommitIdRequiredException",
         "$fault": "client",
         "$metadata": {
           "httpStatusCode": 400,
           "requestId": "864df818-ab88-4224-9bc6-f5d924f7eb50",
           "attempts": 1,
           "totalRetryDelay": 0
         },
         "__type": "CommitIdRequiredException",
         "message": "A commit ID is required, but no commit ID was specified.",
         "stack": "CommitIdRequiredException: A commit ID is required, but no commit ID was specified.\n    at deserializeAws_json1_1CommitIdRequiredExceptionResponse (C:\\github\\renovate\\node_modules\\@aws-sdk\\client-codecommit\\dist-cjs\\prot
ocols\\Aws_json1_1.js:6620:23)\n    at deserializeAws_json1_1GetCommentsForPullRequestCommandError (C:\\github\\renovate\\node_modules\\@aws-sdk\\client-codecommit\\dist-cjs\\protocols\\Aws_json1_1.js:2875:25)\n    at runMicrotasks (<anonymous>)\n
    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\github\\renovate\\node_modules\\@aws-sdk\\middleware-serde\\dist-cjs\\deserializerMiddleware.js:7:24\n    at async C:\\github\\renovate\\node_modules\\@aws
-sdk\\middleware-signing\\dist-cjs\\middleware.js:11:20\n    at async StandardRetryStrategy.retry (C:\\github\\renovate\\node_modules\\@aws-sdk\\middleware-retry\\dist-cjs\\StandardRetryStrategy.js:51:46)\n    at async C:\\github\\renovate\\node_m
odules\\@aws-sdk\\middleware-logger\\dist-cjs\\loggerMiddleware.js:6:22\n    at async Object.getPrComments (C:\\github\\renovate\\lib\\modules\\platform\\codecommit\\codecommit-client.ts:89:10)\n    at async Proxy.ensureComment (C:\\github\\renova
te\\lib\\modules\\platform\\codecommit\\index.ts:602:26)\n    at async ensureComment (C:\\github\\renovate\\lib\\modules\\platform\\comment.ts:19:17)\n    at async handleModifiedPr (C:\\github\\renovate\\lib\\workers\\repository\\update\\branch\\h
andle-existing.ts:94:5)\n    at async processBranch (C:\\github\\renovate\\lib\\workers\\repository\\update\\branch\\index.ts:213:11)\n    at async writeUpdates (C:\\github\\renovate\\lib\\workers\\repository\\process\\write.ts:159:17)\n    at asy
nc update (C:\\github\\renovate\\lib\\workers\\repository\\process\\extract-update.ts:151:11)\n    at async Object.renovateRepository (C:\\github\\renovate\\lib\\workers\\repository\\index.ts:61:19)\n    at async attributes.repository (C:\\github\
\renovate\\lib\\workers\\global\\index.ts:173:11)\n    at async Object.start (C:\\github\\renovate\\lib\\workers\\global\\index.ts:158:7)\n    at async C:\\github\\renovate\\lib\\renovate.ts:17:22"
       }
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecommit/interfaces/getcommentsforpullrequestcommandinput.html

https://docs.aws.amazon.com/codecommit/latest/APIReference/API_CommentsForPullRequest.html

**Comment by PhilipAbed** [comment]
I'm trying to share a codecommit repository outside organization but it seems complicated and not secure,

i just have a codecommit simple repository and one pull request with some comments on it.

Here's the simplified code, 
1) a function called `ensureComment` which fails at the first part when it tries to find all pr comments (copied first part)
2) a function called `getPrComments` which tries to reach out to `@aws-sdk/client-codecommit` to get the info by using the method input: `repository name` + `pull request number`

```js

async function ensureComment({
  prNumber,
  commentTopic,
  commentContent,
  repositoryName,
}: EnsureCommentConfig): Promise<boolean> {
  const header = commentTopic ? `### ${commentTopic}\n\n` : '';
  const body = `${header}${commentContent}`;
  let prCommentsResponse: GetCommentsForPullRequestOutput;
  try {
    prCommentsResponse = await getPrComments(
      repositoryName,
      `${prNumber}`
    );
  } catch (err) {
    logger.debug({ err }, 'Unable to retrieve pr comments');
    return false;
  }
  return true;
}

export async function getPrComments(
  repositoryName: string,
  pullRequestId: string
): Promise<GetCommentsForPullRequestOutput> {
  const input: GetCommentsForPullRequestInput = {
    repositoryName,
    pullRequestId,
  };
  const cmd = new GetCommentsForPullRequestCommand(input);
  return await codeCommitClient.send(cmd);
}
```

**Comment by RanVaknin** [comment]
Hi @PhilipAbed ,

Thanks for the repro steps. 
I was able to reproduce your issue, howeverI'm not entirely sure this is a bug, but as you pointed out this should be documented. 

Since the codecommit service team owns the documentation, I have opened an internal ticket with them to get this addressed.  Since this is a cross SDK repo, I will transfer this to our general repo - you'll be able to track it there.

Thanks again!
Ran~

`#P77371655`
