### ISSUE TITLE
createPresignedPost -> RangeError: Invalid time value

### ISSUE THREAD

**Issue by wahabfun** [aws/aws-sdk-js-v3#4355]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

**I am getting the following error**

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at iso8601 (D:\proj\node_modules\@aws-sdk\s3-presigned-post\dist-cjs\createPresignedPost.js:65:32)

**65th code line on @aws-sdk\s3-presigned-post\dist-cjs\createPresignedPost.js is** 
const iso8601 = (date) => date.toISOString().replace(/\.\d{3}Z$/, "Z");

### SDK version number

@aws-sdk/s3-presigned-post@3.254.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.19.3

### Reproduction Steps

```
import { S3Client, GetObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

let options = {
    //apiVersion: '2012-08-10',
    region: process.env.region
}

let s3Client = new S3Client(options);

(async function() {

const params = {
  Bucket: 'dummy',
  Fields: {
    key: 'dummy_key',
    'content-type': 'video/mp4',
    'content-length': '3682374'
  },
Expires: 600
};

 try {
            const rsltDat = await createPresignedPost(s3Client, params );
        } catch(err) {
console.log(err);

        }

})();
```

### Observed Behavior

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at iso8601 (D:\proj\node_modules\@aws-sdk\s3-presigned-post\dist-cjs\createPresignedPost.js:65:32)

### Expected Behavior

There should be no **RangeError: Invalid time value** error

**Comment by yenfryherrerafeliz** [comment]
Hi @wahabfun, thanks for opening this issue. Could you please let me know if this issue is persistent or happens randomly?, I just tried on my machine and I got not issues, however, there are some scenarios where this problem could happen, and one of them is if the date being parsed for some reason is undefined. After looking at the code I found two places, inside of the presigned post implementation, from where this issue could occur:

One is [here](https://github.com/aws/aws-sdk-js-v3/blob/4942c01f6976188cccffb8e2ef041630fae04deb/packages/s3-presigned-post/src/createPresignedPost.ts#L49):
>const signingDate = iso8601(now).replace(/[\-:]/g, "");

We will get an error from the line above if the parameter given "now" is undefined, but how could that variable be undefined, well the only way I see for this to happen is if "systemClockOffset" is also undefined. I see that systemClockOffset is resolved from the client config so that we would need to investigate any case where this configuration "systemClockOffset" will be resolved as undefined. Lets see after [here](https://github.com/aws/aws-sdk-js-v3/blob/4942c01f6976188cccffb8e2ef041630fae04deb/packages/s3-presigned-post/src/createPresignedPost.ts#L45):
>const { systemClockOffset, base64Encoder, utf8Decoder, sha256 } = client.config;
  const now = new Date(Date.now() + systemClockOffset);

And the other place is [here](https://github.com/aws/aws-sdk-js-v3/blob/4942c01f6976188cccffb8e2ef041630fae04deb/packages/s3-presigned-post/src/createPresignedPost.ts#L79), however, if "now" is undefined, it should never reach this point.
 
So, I will be awaiting for your response to see if this issue is sporadically or persistent, and in case is persistent we could then check other aspect from your environment that could help us reproducing this issue.

Steps I took to reproduce:
- Create a new project: ``` npm init ```
- Install the dependencies:
    - ``` npm i @aws-sdk/client-s3 ```
    - ``` npm i @aws-sdk/s3-presigned-post ```
- Create a js file, maybe src/index.js, and copy paste the following code:
```js
import { S3Client } from "@aws-sdk/client-s3";
import { createPresignedPost } from "@aws-sdk/s3-presigned-post";

let options = {
    region: process.env.TEST_REGION
}
let s3Client = new S3Client(options);
(async function() {
    const params = {
        Bucket: process.env.TEST_BUCKET,
        Key: process.env.TEST_KEY,
        Fields: {
            key: process.env.TEST_KEY,
            'content-type': 'video/mp4',
            'content-length': '3682374'
        },
        Expires: 600
    };

    try {
        const response = await createPresignedPost(s3Client, params);
        console.log(response)
    } catch(err) {
        console.log(err);

    }
})();
```
- Run the code: ``` node src/index.js```

Thanks!

**Comment by wahabfun** [comment]
@yenfryherrerafeliz Also would you be so kind if you can tell me the temporary fixing of the bug so I will update the code and will continue the development of my project.

Thank You!

**Comment by wahabfun** [comment]
@yenfryherrerafeliz 

![image](https://user-images.githubusercontent.com/43115146/214120517-f7302968-d2e1-49bb-bd84-a7ae960a82ad.png)
I have consoled log your investigated variable and from the log it seems that the client.config object only have the "update" property.

Date.now is working fine.

**Here is the log output**
```
Aws client.config output { update: [Function: update] }
Date.now output 1674498549009
```

**Comment by yenfryherrerafeliz** [comment]
@wahabfun that is really weird, you should really get a lot of things more, when logging the client's config. For example, check my output:

<details>

```js
Aws client.config output:  {
  apiVersion: '2006-03-01',
  base64Decoder: [Function: fromBase64],
  base64Encoder: [Function: toBase64],
  disableHostPrefix: false,
  endpointProvider: [Function: defaultEndpointResolver],
  logger: NoOpLogger {},
  serviceId: 'S3',
  signerConstructor: [class SignatureV4MultiRegion],
  signingEscapePath: false,
  urlParser: [Function: parseUrl],
  useArnRegion: [AsyncFunction (anonymous)],
  region: [AsyncFunction: region],
  runtime: 'node',
  defaultsMode: [AsyncFunction (anonymous)],
  bodyLengthChecker: [Function: calculateBodyLength],
  credentialDefaultProvider: [Function (anonymous)],
  defaultUserAgentProvider: [AsyncFunction (anonymous)],
  eventStreamSerdeProvider: [Function: eventStreamSerdeProvider],
  getAwsChunkedEncodingStream: [Function: getAwsChunkedEncodingStream],
  maxAttempts: [AsyncFunction (anonymous)],
  md5: [Function: bound Hash],
  requestHandler: NodeHttpHandler {
    metadata: { handlerProtocol: 'http/1.1' },
    configProvider: Promise { <pending> }
  },
  retryMode: [AsyncFunction (anonymous)],
  sdkStreamMixin: [Function: sdkStreamMixin],
  sha1: [Function: bound Hash],
  sha256: [Function: bound Hash],
  streamCollector: [Function: streamCollector],
  streamHasher: [Function: readableStreamHasher],
  useDualstackEndpoint: [AsyncFunction (anonymous)],
  useFipsEndpoint: [AsyncFunction: useFipsEndpoint],
  utf8Decoder: [Function: fromUtf8],
  utf8Encoder: [Function: toUtf8],
  useAccelerateEndpoint: false,
  useGlobalEndpoint: false,
  disableMultiregionAccessPoints: false,
  defaultSigningName: 's3',
  endpoint: undefined,
  tls: true,
  isCustomEndpoint: false,
  retryStrategy: [AsyncFunction: retryStrategy],
  systemClockOffset: 0,
  credentials: [AsyncFunction (anonymous)],
  signer: [AsyncFunction: signer],
  forcePathStyle: false,
  customUserAgent: undefined,
  eventStreamMarshaller: EventStreamMarshaller {
    universalMarshaller: EventStreamMarshaller {
      eventStreamCodec: [EventStreamCodec],
      utfEncoder: [Function: toUtf8]
    }
  }
}
{
  apiVersion: '2006-03-01',
  base64Decoder: [Function: fromBase64],
  base64Encoder: [Function: toBase64],
  disableHostPrefix: false,
  endpointProvider: [Function: defaultEndpointResolver],
  logger: NoOpLogger {},
  serviceId: 'S3',
  signerConstructor: [class SignatureV4MultiRegion],
  signingEscapePath: false,
  urlParser: [Function: parseUrl],
  useArnRegion: [AsyncFunction (anonymous)],
  region: [AsyncFunction: region],
  runtime: 'node',
  defaultsMode: [AsyncFunction (anonymous)],
  bodyLengthChecker: [Function: calculateBodyLength],
  credentialDefaultProvider: [Function (anonymous)],
  defaultUserAgentProvider: [AsyncFunction (anonymous)],
  eventStreamSerdeProvider: [Function: eventStreamSerdeProvider],
  getAwsChunkedEncodingStream: [Function: getAwsChunkedEncodingStream],
  maxAttempts: [AsyncFunction (anonymous)],
  md5: [Function: bound Hash],
  requestHandler: NodeHttpHandler {
    metadata: { handlerProtocol: 'http/1.1' },
    configProvider: Promise { [Object] }
  },
  retryMode: [AsyncFunction (anonymous)],
  sdkStreamMixin: [Function: sdkStreamMixin],
  sha1: [Function: bound Hash],
  sha256: [Function: bound Hash],
  streamCollector: [Function: streamCollector],
  streamHasher: [Function: readableStreamHasher],
  useDualstackEndpoint: [AsyncFunction (anonymous)],
  useFipsEndpoint: [AsyncFunction: useFipsEndpoint],
  utf8Decoder: [Function: fromUtf8],
  utf8Encoder: [Function: toUtf8],
  useAccelerateEndpoint: false,
  useGlobalEndpoint: false,
  disableMultiregionAccessPoints: false,
  defaultSigningName: 's3',
  endpoint: undefined,
  tls: true,
  isCustomEndpoint: false,
  retryStrategy: [AsyncFunction: retryStrategy],
  systemClockOffset: 0,
  credentials: [AsyncFunction (anonymous)],
  signer: [AsyncFunction: signer],
  forcePathStyle: false,
  customUserAgent: undefined,
  eventStreamMarshaller: EventStreamMarshaller {
    universalMarshaller: EventStreamMarshaller {
      eventStreamCodec: [EventStreamCodec],
      utfEncoder: [Function: toUtf8]
    }
  }
}

``` 
</details>

Would you be able to create an empty project, just to test, by using the repro steps that I put [here](https://github.com/aws/aws-sdk-js-v3/issues/4355#issuecomment-1400338204), and let me know if you also have issues there.

Thanks!

**Comment by wahabfun** [comment]
@yenfryherrerafeliz Thank you so much for the help!

Sorry were busy. I just tried it with the empty and it is working fine. So for my original project I reinstalled the s3 nodejs modules and everything is working smooth!
