### ISSUE TITLE
date.getUTCFullYear is not a function

### ISSUE THREAD

**Issue by sumeetweb** [aws/aws-sdk-js-v3#4468]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi there,

While using client-s3 for a PutObjectCommand, I am getting the error:
date.getUTCFullYear is not a function

![image](https://user-images.githubusercontent.com/25149022/221301240-f6a01823-3213-42ae-910f-33c4e7955c01.png)

### SDK version number

@aws-sdk/client-s3@3.279.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.0

### Reproduction Steps

```
const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
const s3 = new S3Client({ region: "us-east-1" });

  const params = {
    Bucket: "Sample-Bucket-Name",
    Key: "Object-Key",
    Expires: 3600 // 1 hour
  };

  try {
    // Create the command.
    let command = new PutObjectCommand(params);
    // Create the presigned URL.
    const signedUrl = await getSignedUrl(s3, command, {
      expiresIn: 3600,
    });
    console.log(signedUrl);
  } catch (err) {
    console.log("Error: ", err);
  }
```

### Observed Behavior

Error:  TypeError: date.getUTCFullYear is not a function
    at dateToUtcString (/com.docker.devenvironments.code/node_modules/@aws-sdk/smithy-client/dist-cjs/date-utils.js:8:23)
    at map.expires (/com.docker.devenvironments.code/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:2404:109)
    at map (/com.docker.devenvironments.code/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:37:31)
    at mapWithFilter (/com.docker.devenvironments.code/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:60:12)
    at map (/com.docker.devenvironments.code/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:17:20)
    at serializeAws_restXmlPutObjectCommand (/com.docker.devenvironments.code/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:2390:21)
    at async /com.docker.devenvironments.code/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:21

### Expected Behavior

getSignedUrl for posting file to S3.

**Comment by sumeetweb** [comment]
Found the issue! It looks like I'm passing Expiration twice, once in Bucket params and then once again while generating signed URL. Removing it from bucket params worked. Also I added ContentType to bucket params.
```
  const params = {
    Bucket: "Sample-Bucket-Name",
    Key: "Object-Key",
    ContentType: "image/jpeg"
  };
```
