### ISSUE TITLE
RestoreObjectCommand Malformed XML

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [aws/aws-sdk-js-v3#4580]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I get this error:
```MalformedXML: The XML you provided was not well-formed or did not validate against our published schema```
The restore doesn't happen

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

In `.env` have `AWS_REGION` as the AWS region.
```js
import {
  S3Client,
  RestoreObjectCommand,
  Tier
} from '@aws-sdk/client-s3'
import { config } from 'dotenv'
config()

const s3Client = new S3Client({
  region: process.env.AWS_REGION
})
await s3Client.send(new RestoreObjectCommand({
  Bucket: 'programmatically-created-bucket',
  Key: 'file.txt',
  RestoreRequest: {
    Days: 30,
    Tier: Tier.Bulk
  }
}))
```

### Observed Behavior

Error:
```js
/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+smithy-client@3.296.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^

MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
    at throwDefaultError (/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+smithy-client@3.296.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restXmlRestoreObjectCommandError (/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5975:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async file:///home/rajas/aws-playground/repro.js:12:1 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'N8M7Z9KPAB9FJP3W',
    extendedRequestId: '5DHmRgSz8dv/TlHNPu2rPpRNvW+eIhSlzV1ujOIKrOn3SwzhThTKoeg5UxSnTkVZuDP9zy7VEWg=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'MalformedXML',
  RequestId: 'N8M7Z9KPAB9FJP3W',
  HostId: '5DHmRgSz8dv/TlHNPu2rPpRNvW+eIhSlzV1ujOIKrOn3SwzhThTKoeg5UxSnTkVZuDP9zy7VEWg='
}

Node.js v18.15.0
```

### Expected Behavior

The restore should happen, no error.

### Possible Solution

Maybe it's the logic for generating XML by the `RestoreObjectCommand`

**Comment by RanVaknin** [comment]
Hi @ChocolateLoverRaj,

I remember seeing this issue come up before but I couldn't find it.

If I remember correctly, the issue is that `RestoreRequest` has another place you can specify the tier in, and its specific to the glacier storage class:
```js

RestoreRequest: {
    Days: 30,
    //Tier: Tier.Bulk
    GlacierJobParameters: {
      Tier: Tier.Bulk
    }
}

```

Hope this actually solves your issue.
Thanks,
Ran~

**Comment by ChocolateLoverRaj** [comment]
@RanVaknin it worked. Also, when using the `Description` property it doesn't work.

**Comment by ChocolateLoverRaj** [comment]
I think that the TypeScript definitions need to be changed.

**Comment by RanVaknin** [comment]
Hi @ChocolateLoverRaj ,

The SDK types are all auto-generated from the API models of the all the service teams. The SDK team can't change any type definitions because they will get overwritten by the next release. Additionally changing types is not considered a backwards compatible solution and will cause customer's code to break, so this is not an option unfortunately.

>Also, when using the Description property it doesn't work.

Can you tell me more about what doesn't work?

Thanks,
Ran~

**Comment by ChocolateLoverRaj** [comment]
When including the description property, a 400 malformed xml error happens.

**Comment by RanVaknin** [comment]
Hi @ChocolateLoverRaj ,

Thanks for explaining, Indeed I'm also getting this error. This response is from the service, and Im guessing is this is a documentation issue. I will move this to the cross sdk repo and open an internal ticket with s3 regarding this documentation. 

Thanks,
Ran~
