### ISSUE TITLE
@aws-sdk/client-cloudwatch-logs/dist-cjs/endpoint/EndpointParameters.js:7 options.useDualstackEndpoint ?? false 

### ISSUE THREAD

**Issue by KarthikBharadwaj1996** [aws/aws-sdk-js-v3#4605]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Getting an issue in node_modules post install

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.19.1

### Reproduction Steps

Installing the node_modules is giving the error
export default new CloudWatchLogsClient({
    region: 'ap-southeast-1',
    credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
    }
});

### Observed Behavior

ERROR  Uncaught Error Caught: /mnt/app/user/server/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/endpoint/EndpointParameters.js:7
data:    server.js:10169 -         useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                       SyntaxError: Unexpected token '?'
data:    server.js:10169 -     at compileFunction (<anonymous>)
data:    server.js:10169 -     at wrapSafe (internal/modules/cjs/loader.js:1053:16)
data:    server.js:10169 -     at Module._compile (internal/modules/cjs/loader.js:1101:27)
data:    server.js:10169 -     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
data:    server.js:10169 -     at Module.load (internal/modules/cjs/loader.js:985:32)
data:    server.js:10169 -     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
data:    server.js:10169 -     at Module.require (internal/modules/cjs/loader.js:1025:19)
data:    server.js:10169 -     at require (internal/modules/cjs/helpers.js:72:18)
data:    server.js:10169 -     at Object.<anonymous> (/mnt/app/user/server/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/CloudWatchLogsClient.js:14:30)
data:    server.js:10169 -     at Module._compile (internal/modules/cjs/loader.js:1137:30)
data:    server.js:10169 -     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
data:    server.js:10169 -     at Module.load (internal/modules/cjs/loader.js:985:32)
data:    server.js:10169 -     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
data:    server.js:10169 -     at Module.require (internal/modules/cjs/loader.js:1025:19)
data:    server.js:10169 -     at require (internal/modules/cjs/helpers.js:72:18)
data:    server.js:10169 -     at Object.<anonymous> (/mnt/app/user/server/node_modules/@aws-sdk/client-cloudwatch-logs/dist-cjs/CloudWatchLogs.js:4:32)
data:    server.js:10169 -     at Module._compile (internal/modules/cjs/loader.js:1137:30)
data:    server.js:10169 -     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
data:    server.js:10169 -     at Module.load (internal/modules/cjs/loader.js:985:32)
data:    server.js:10169 -     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
data:    server.js:10169 -     at Module.require (internal/modules/cjs/loader.js:1025:19)
data:    server.js:10169 -     at require (internal/modules/cjs/helpers.js:72:18)

### Expected Behavior

Install without any errors

**Comment by KarthikBharadwaj1996** [comment]
Anyone who stumbled upon this thread, I am closing this thread because it was a silly mistake from my side, I had two terminals opened one with node 12 and other with node 16 and I was getting this error in the node 12 terminal which is obvious because optional chaining is supported from node 14 onwards.
