### ISSUE TITLE
Quicksight client CreateRefreshScheduleCommand doesn't work

### ISSUE THREAD

**Issue by dlamoris** [aws/aws-sdk-js-v3#4713]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Trying to use `new CreateRefreshScheduleCommand()` results in:
`"errorType": "TypeError",
  "errorMessage": "import_client_quicksight.CreateRefreshScheduleCommand is not a constructor",`

### SDK version number

@aws-sdk/client-quicksight 3.326.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

This is actually a lambda function that's deployed using aws-cdk. other commands like `CreateDataSetCommand` or `CreateDataSourceCommand` works, but not CreateRefreshScheduleCommand
```
import {CreateRefreshScheduleCommand, QuickSightClient} from "@aws-sdk/client-quicksight";
const qs = new QuickSightClient({
    region: 'us-gov-west-1',
});
async function create() {
     const latest = new CreateRefreshScheduleCommand({
            DataSetId: 'someId',
            AwsAccountId: ACCOUNTID,
            Schedule: {
                ScheduleId: randomUUID(),
                ScheduleFrequency: {
                    Interval: "DAILY",
                    Timezone: "America/Los_Angeles",
                    TimeOfTheDay: "05:30"
                },
                RefreshType: "FULL_REFRESH"
            },
        });
        await qs.send(latest);
}
export async function run() {
    await create();
}
```

### Observed Behavior

```
{
    "errorType": "TypeError",
    "errorMessage": "import_client_quicksight.CreateRefreshScheduleCommand is not a constructor",
    "stack": [
        "TypeError: import_client_quicksight.CreateRefreshScheduleCommand is not a constructor",
        "    at createRefreshSchedules (/var/task/index.js:1052:20)",
        "    at Runtime.run [as handler] (/var/task/index.js:1133:9)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}
```

### Expected Behavior

The function returns

**Comment by dlamoris** [comment]
I wondered if the aws-sdk that's included in the node 18 lambda runtime is the problem, but according to this https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/ it comes with sdk v3. Does anyone know if it's always the latest version?

**Comment by dlamoris** [comment]
solved by just bundling node_modules with lambda function. It seems the sdk v3 that comes with lambda node 18 runtime has problems
