### ISSUE TITLE
@aws-sdk/client-dynamodb TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by phun-ky** [aws/aws-sdk-js-v3#4726]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

With this code:

```javascript
import {
  DynamoDBClient,
  PutItemCommand,
  GetItemCommand,
  ScanCommand
} from '@aws-sdk/client-dynamodb';
import { marshall, unmarshall } from '@aws-sdk/util-dynamodb';

import config from '../../../../config/index.js';

const client = new DynamoDBClient({
  region: config.aws.region
});

export const getItem = async (tablename: string, key: string) => {
  if (!tablename || !key) {
    throw new Error(
      `Missing required parameter for \`getItem\`, you provided \`tablename\`: ${typeof tablename} and \`key\`:${typeof key}`
    );
  }

  const params = {
    TableName: tablename,
    Key: marshall(key)
  };
  const command = new GetItemCommand(params);
  const response = await client.send(command);

  return response;
};
```

With these parameters:

```javascript
{ TableName: 'applications', Key: { S: 'lrcl08uMQSo6nuAMym3L6' } }
```
I get this error

```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.AttributeValue.visit (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:737:36)
    at se_AttributeValue (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2948:38)
    at /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3220:20
    at Array.reduce (<anonymous>)
    at se_Key (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3216:34)
    at Key (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3172:21)
    at applyInstruction (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_GetItemInput (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3168:37)
    at se_GetItemCommand (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:203:27)

```

With the error pointing to this file and line: https://github.com/aws/aws-sdk-js-v3/blob/864b34a52aea8dbd52a63239027b4c203c75863c/clients/client-dynamodb-streams/src/models/models_0.ts#L870

Previous similar issues points to missing syntax, like `"S":'lrcl08uMQSo6nuAMym3L6'`, but I see from the sent parameters that I have the correct syntax.

What could be wrong here? I'm trying to fetch an item, and I know the item exist.

### SDK version number

@aws-sdk/client-dynamodb@^3.327.0, @aws-sdk/util-dynamodb@^3.327.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps
```javascript
import {
  DynamoDBClient,
  PutItemCommand,
  GetItemCommand,
  ScanCommand
} from '@aws-sdk/client-dynamodb';
import { marshall, unmarshall } from '@aws-sdk/util-dynamodb';

import config from '../../../../config/index.js';

const client = new DynamoDBClient({
  region: config.aws.region
});

const getItem = async (tablename: string, key: string) => {
  if (!tablename || !key) {
    throw new Error(
      `Missing required parameter for \`getItem\`, you provided \`tablename\`: ${typeof tablename} and \`key\`:${typeof key}`
    );
  }

  const params = {
    TableName: tablename,
    Key: marshall(key)
  };
  const command = new GetItemCommand(params);
  const response = await client.send(command);

  return response;
};


getItem('applications', 'lrcl08uMQSo6nuAMym3L6')
```

### Observed Behavior

```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.AttributeValue.visit (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:737:36)
    at se_AttributeValue (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2948:38)
    at /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3220:20
    at Array.reduce (<anonymous>)
    at se_Key (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3216:34)
    at Key (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3172:21)
    at applyInstruction (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_GetItemInput (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3168:37)
    at se_GetItemCommand (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:203:27)

```

### Expected Behavior

That I should've received the desired item from the table.

### Additional Information/Context

I think that somewhere in the flow, the parameters are stripped, I see from the output of the command, that the parameters are correct:

```
GetItemCommand {
  middlewareStack: {
    add: [Function: add],
    addRelativeTo: [Function: addRelativeTo],
    clone: [Function: clone],
    use: [Function: use],
    remove: [Function: remove],
    removeByTag: [Function: removeByTag],
    concat: [Function: concat],
    applyToStack: [Function: cloneTo],
    identify: [Function: identify],
    resolve: [Function: resolve]
  },
  input: { TableName: 'applications', Key: { S: 'lrcl08uMQSo6nuAMym3L6' } }
}

```

But when I output `value` in this function: https://github.com/aws/aws-sdk-js-v3/blob/864b34a52aea8dbd52a63239027b4c203c75863c/clients/client-dynamodb-streams/src/models/models_0.ts#L870 I get:

```
lrcl08uMQSo6nuAMym3L6
```

Which is unmarshalled value..

**Comment by RanVaknin** [comment]
Hi @phun-ky ,

Thanks for opening the issue!

I see where the confusion is coming from. Dynamodb has several different ways to put an item in a table, all of which has similar syntax which can lead to confusion.

The Marshal function, takes in a javascript object, and converts it into a Dynamodb type for you, so you dont have to worry about the attribute types. To fix your specific example you can use:
```js
  getItem('applications', {Key: 'lrcl08uMQSo6nuAMym3L6'})
```

There's actually an [example in our docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_dynamodb.html#convert-dynamodb-record-into-javascript-object) specifically for this type of operation.

Please let me know if this helps. 

All the best,
Ran~

**Comment by phun-ky** [comment]
@RanVaknin I got a bit further with your changes, but it does not make sense having two "key" attributes:

```javascript
const params = {
    TableName: tablename,
    Key: marshall({ Key: key })
  };
  const command = new GetItemCommand(params);
  const response = await client.send(command);
```

Now I get:

```
ValidationException: The provided key element does not match the schema
    at throwDefaultError (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_GetItemCommandError (/home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1554:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/alexander/Workspace/knowit/internal/dev.knowitlabs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async getItem (file:///home/alexander/Workspace/knowit/internal/dev.knowitlabs/server/src/database/lib/exec.ts:35:20)
    at async getApplication (file:///home/alexander/Workspace/knowit/internal/dev.knowitlabs/server/src/database/index.ts:27:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '2MILVH1GP1Q0CSCHU1MAR36177VV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}

```

And the command looks like:

```
GetItemCommand {
  middlewareStack: {
    add: [Function: add],
    addRelativeTo: [Function: addRelativeTo],
    clone: [Function: clone],
    use: [Function: use],
    remove: [Function: remove],
    removeByTag: [Function: removeByTag],
    concat: [Function: concat],
    applyToStack: [Function: cloneTo],
    identify: [Function: identify],
    resolve: [Function: resolve]
  },
  input: { TableName: 'applications', Key: { Key: [Object] } }
}

```
The value from https://github.com/aws/aws-sdk-js-v3/blob/864b34a52aea8dbd52a63239027b4c203c75863c/clients/client-dynamodb-streams/src/models/models_0.ts#L870 looks correct though.

```
{ S: 'lrcl08uMQSo6nuAMym3L6' }

```

The partition key in my table is a string, and points to "id", if that matters.

**Comment by phun-ky** [comment]
I think I worked it out, all though it's not that intuitive from the documentation:

```javascript
export const getItem = async (
  tablename: string,
  key: string,
  primary_key = 'id'
) => {
  if (!tablename || !key) {
    throw new Error(
      `Missing required parameter for \`getItem\`, you provided \`tablename\`: ${typeof tablename} and \`key\`:${typeof key}`
    );
  }

  const params = {
    TableName: tablename,
    Key: marshall({ [primary_key]: key })
  };
  const command = new GetItemCommand(params);
  const response = await client.send(command);

  return response;
};
```
I will close this for now, since the original issue is gone. Thanks for your time!

**Comment by RanVaknin** [comment]
I agree. Its not intuitive. If you have some documentation suggestions to make this clearer please feel free to open a documentation issue with your suggestion / create a PR.

Glad I could help :)
