### ISSUE TITLE
SyntaxError: Unexpected identifier 'runtime'

### ISSUE THREAD

**Issue by boriskogan81** [aws/aws-sdk-js-v3#4745]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to run the latest S3 client in a Node application and getting a runtime not found error on load.

### SDK version number

@aws-sdk/client-s3@3.332.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

19.4.0

### Reproduction Steps

Package.json:

```
  "dependencies": {
    "@aws-sdk/client-s3": "^3.332.0",
    "@aws-sdk/lib-storage": "^3.332.0",
```

Initial load: 

```
const { Upload } = require('@aws-sdk/lib-storage');
const { S3Client } = require("@aws-sdk/client-s3");
const stream = 'node:stream';
const client = new S3Client({});
```

### Observed Behavior

```
An error has occured. error is: C:\...\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:32
        runtime: "node",
        ^^^^^^^

SyntaxError: Unexpected identifier 'runtime'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1159:20)
    at Module._compile (node:internal/modules/cjs/loader:1203:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\...\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js:18:25)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:...\node_modules\@aws-sdk\client-s3\dist-cjs\S3.js:98:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18) and stack trace is: C:\...\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:32
        runtime: "node",
        ^^^^^^^

SyntaxError: Unexpected identifier 'runtime'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1159:20)
    at Module._compile (node:internal/modules/cjs/loader:1203:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\...\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js:18:25)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\...\node_modules\@aws-sdk\client-s3\dist-cjs\S3.js:98:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18) Process will restart now.
```

### Expected Behavior

I expected my application to load and not crash.

**Comment by RanVaknin** [comment]
Hi @boriskogan81 ,

Im not sure why you are seeing this error on load. There is no other application code other than the following?

```
const { Upload } = require('@aws-sdk/lib-storage');
const { S3Client } = require("@aws-sdk/client-s3");
const stream = 'node:stream';
const client = new S3Client({});
```

I have the same setup as yours, but I added a hello world to my `example.js` file:

```diff
const { Upload } = require('@aws-sdk/lib-storage');
const { S3Client } = require("@aws-sdk/client-s3");
const stream = 'node:stream';
const client = new S3Client({});

+ console.log("hello world")
```

```console
$ npm list 
4745@1.0.0 /Users/rvaknin/test_folder/4745
├── @aws-sdk/client-s3@3.338.0
└── @aws-sdk/lib-storage@3.338.0
$ nvm use 19.4.0
$ node -v 
v19.4.0
$ node example.js
hello world
```

___

Can you try deleting `node_modules`, and `package-lock.json` and then running `npm install` again?

Thanks!
Ran~

**Comment by boriskogan81** [comment]
Hey, that worked-thank you!

Sincerely,

Baruch

**Comment by RanVaknin** [comment]
@boriskogan81  you are welcome!
חג שבועות שמח :) 
רן~
