### ISSUE TITLE
How to decrypt cognito verification code with KMS in v3

### ISSUE THREAD

**Issue by JhonnK08** [aws/aws-sdk-js-v3#4768]
### Describe the issue

Hi, I'm trying to decrypt this code but I'm getting an error 

`An error occurred while trying to decrypt the text: 
InvalidCiphertextException: UnknownError
    at deserializeAws_json1_1InvalidCiphertextExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-kms/dist-cjs/protocols/Aws_json1_1.js:3157:23)
    at deserializeAws_json1_1DecryptCommandError (/var/runtime/node_modules/@aws-sdk/client-kms/dist-cjs/protocols/Aws_json1_1.js:850:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at Object.d0 (/packages/lambda-utils/dist/index.js:19:5560)
    at Runtime.C_ (/var/index.ts:46:18) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'bdb631ea-2013-4be9-a9f0-9a94164119d3',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'InvalidCiphertextException'
}`

 I searched and found nothing about this in AWS SDK v3, only in past versions.

### Links

https://github.com/aws/aws-sdk-js-v3/discussions/3691

**Comment by yenfryherrerafeliz** [comment]
Hi @JhonnK08, could you please take a look to the following documentation and let me know if that is what you are looking for:
- https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-email-sender.html#custom-email-sender-code-examples
- https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#symmetric-cmks

Thanks!

**Comment by JhonnK08** [comment]
> Hi @JhonnK08, could you please take a look to the following documentation and let me know if that is what you are looking for:
> 
> * https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-email-sender.html#custom-email-sender-code-examples
> * https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#symmetric-cmks
> 
> Thanks!

I tried to follow the first link example, but in my lambda, I got an error of missing import of aws-sdk, because my lambda is in node v18.

I tried to do with AWS KMS decrypt from SDK v3 and by the aws command line but got the same error.

**Comment by yenfryherrerafeliz** [comment]
@JhonnK08, you do not have to import aws-sdk, because it is not even used. You can remove that import statement.

Thanks!

**Comment by JhonnK08** [comment]
I tried to change the runtime of lambda to Node v16, and the error of aws-sdk was not appearing anymore, but I got errors for other packages that I used on SDK v3.

I think it's a problem with [aws-encryption-sdk](https://github.com/aws/aws-encryption-sdk-javascript) 😢

**Comment by yenfryherrerafeliz** [comment]
@JhonnK08, could you please switch back to node18, remove the dependency "aws-sdk", and see if that works?

Thanks!

**Comment by JhonnK08** [comment]
> Not working sob
> 
> `"Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs"`

Now my lambda is with a timeout, the error is not appearing anymore.

**Comment by yenfryherrerafeliz** [comment]
@JhonnK08,  so were you able to resolve the issue then?

Please let me know.

Thanks!

**Comment by JhonnK08** [comment]
Sorry for the delay.
I found an issue with the same problem here https://github.com/aws/aws-encryption-sdk-javascript/issues/1103.

I changed the runtime on my lambda to node v16 and removed the SDK v3 dependencies, which works.

 I think the problem is with some dependency of AWS Encryption SDK that is not working with AWS SDK v3 and the runtime node v18.
