### ISSUE TITLE
[credential-provider-cognito-identity] TypeError: Cannot redefine property: localStorage in Node.js v18.16.0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4807]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The unit tests of middleware-socket throw the following error:

```console
TypeError: Cannot redefine property: localStorage
```

This may or may not have impact SDK usage. The unit test needs to be fixed.

### SDK version number

main

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.16.0

### Reproduction Steps

Run credential-provider-cognito-identity unit tests in Node.js 18.16.0

### Observed Behavior

```console
$ credential-provider-cognito-identity> yarn test
...
 FAIL  src/localStorage.spec.ts
  ● localStorage › should return an IndexedDB-backed cache if possible

    TypeError: Cannot redefine property: localStorage

      11 |   beforeEach(() => {
      12 |     if (window) {
    > 13 |       (window.localStorage as any) = undefined;
         |                                   ^
      14 |     }
      15 |
      16 |     if (self) {

      at Object.<anonymous> (src/localStorage.spec.ts:13:35)

  ● localStorage › should return an IndexedDB-backed cache if possible

    TypeError: Cannot redefine property: localStorage

      21 |   afterEach(() => {
      22 |     if (window) {
    > 23 |       (window.localStorage as any) = storageAtInit;
         |                                   ^
      24 |     }
      25 |
      26 |     if (self) {

      at Object.<anonymous> (src/localStorage.spec.ts:23:35)

  ● localStorage › should return window.localStorage if IndexedDB is undefined but localStorage is available

    TypeError: Cannot redefine property: localStorage

      11 |   beforeEach(() => {
      12 |     if (window) {
    > 13 |       (window.localStorage as any) = undefined;
         |                                   ^
      14 |     }
      15 |
      16 |     if (self) {

      at Object.<anonymous> (src/localStorage.spec.ts:13:35)

  ● localStorage › should return window.localStorage if IndexedDB is undefined but localStorage is available

    TypeError: Cannot redefine property: localStorage

      21 |   afterEach(() => {
      22 |     if (window) {
    > 23 |       (window.localStorage as any) = storageAtInit;
         |                                   ^
      24 |     }
      25 |
      26 |     if (self) {

      at Object.<anonymous> (src/localStorage.spec.ts:23:35)

 PASS  src/fromCognitoIdentity.spec.ts
 PASS  src/fromCognitoIdentityPool.spec.ts

Test Suites: 1 failed, 1 skipped, 5 passed, 6 of 7 total
Tests:       2 failed, 3 skipped, 20 passed, 25 total
Snapshots:   0 total
Time:        3.723 s
Ran all test suites.
error Command failed with exit code 1.
```

### Expected Behavior

```console
$ credential-provider-cognito-identity> yarn test
...
Test Suites: 1 skipped, 6 passed, 6 of 7 total
Tests:       3 skipped, 22 passed, 25 total
Snapshots:   0 total
Time:        3.262 s, estimated 4 s
Ran all test suites.
✨  Done in 3.76s.
```

**Comment by kuhe** [comment]
maybe related https://github.com/nodejs/node/issues/47563
