### ISSUE TITLE
[util-stream]: browser unit tests are failing in Node.js v20.3.0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4824]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The unit tests of util-stream throw the following error:

```console
TypeError: Cannot assign to read only property 'TextDecoder' of object '[object global]'
```

This may or may not have impact SDK usage. The unit test needs to be fixed.

### SDK version number

main

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.3.0

### Reproduction Steps

Run util-stream unit tests in Node.js 20.3.0

### Observed Behavior

```console
$ util-stream> yarn test
yarn run v1.22.17
$ jest
 PASS  src/getAwsChunkedEncodingStream.spec.ts
 FAIL  src/sdk-stream-mixin.browser.spec.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'TextDecoder' of object '[object global]'

      88 |     let originalTextDecoder = global.TextDecoder;
      89 |     const mockDecode = jest.fn();
    > 90 |     global.TextDecoder = jest.fn().mockImplementation(function () {
         |                       ^
      91 |       return { decode: mockDecode };
      92 |     });
      93 |

      at src/sdk-stream-mixin.browser.spec.ts:90:23
      at src/sdk-stream-mixin.browser.spec.ts:87:3
      at Object.<anonymous> (src/sdk-stream-mixin.browser.spec.ts:18:1)

 PASS  src/sdk-stream-mixin.spec.ts

Test Suites: 1 failed, 2 passed, 3 total
Tests:       29 passed, 29 total
Snapshots:   0 total
Time:        1.752 s, estimated 2 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Run the browser tests in real browsers, instead of jest which uses fake browser?

**Comment by trivikr** [comment]
The browser tests should ideally be run in real browser and not jsdom.
