### ISSUE TITLE
[abort-controller] unit tests are failing in Node.js v20.3.0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4826]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The unit tests of `abort-controller` throw the following error in Node.js v20.3.0:

```console
TypeError: Cannot assign to read only property 'performance' of object '[object global]'
```

This is likely an issue with jest, and not with the SDK. The tests need to be fixed though.

### SDK version number

main

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.3.0

### Reproduction Steps

Run unit tests in `abort-controller`

### Observed Behavior

```console
$ abort-controller> yarn test
yarn run v1.22.17
$ jest
 FAIL  src/AbortController.spec.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      2 | import { AbortSignal } from "./AbortSignal";
      3 |
    > 4 | jest.useFakeTimers();
        |      ^
      5 |
      6 | describe("AbortController", () => {
      7 |   it("should communicate cancellation via its signal", () => {

      at hijackMethod (../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:946:32)
      at Object.install (../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1733:17)
      at FakeTimers.useFakeTimers (../../node_modules/@jest/fake-timers/build/modernFakeTimers.js:110:36)
      at Object.<anonymous> (src/AbortController.spec.ts:4:6)

 PASS  src/AbortSignal.spec.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.574 s, estimated 2 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

```console
$ abort-controller> yarn test
...
Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        1.856 s
Ran all test suites.
✨  Done in 2.64s.
```

### Additional Information/Context

Probably related https://github.com/aws/aws-sdk-js-v3/issues/4824

**Comment by trivikr** [comment]
This was fixed in Jest 29.x as per https://github.com/jestjs/jest/issues/13603#issuecomment-1311583107
