### ISSUE TITLE
[credential-provider-imds]: unit tests are failing in Node.js v20.3.0

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#4827]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The unit tests of `credential-provider-imds` throw the following error in Node.js v20.3.0:

```console
    Expected: [SyntaxError: Unexpected token . in JSON at position 0]
    Received: [SyntaxError: Unexpected token '.', "." is not valid JSON]
```

This may or may not have impact SDK usage. The unit test needs to be fixed.

### SDK version number

main

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.3.0

### Reproduction Steps

Run unit tests in `credential-provider-imds`

### Observed Behavior

```console
$ credential-provider-imds> yarn test
...
 FAIL  src/fromInstanceMetadata.spec.ts
  ● fromInstanceMetadata › throws SyntaxError if httpRequest returns unparseable creds

    expect(received).rejects.toEqual(expected) // deep equality

    Expected: [SyntaxError: Unexpected token . in JSON at position 0]
    Received: [SyntaxError: Unexpected token '.', "." is not valid JSON]

      182 |     (retry as jest.Mock).mockImplementation((fn: any) => fn());
      183 |
    > 184 |     await expect(fromInstanceMetadata()()).rejects.toEqual(new SyntaxError("Unexpected token . in JSON at position 0"));
          |                                                    ^
      185 |     expect(retry).toHaveBeenCalledTimes(2);
      186 |     expect(httpRequest).toHaveBeenCalledTimes(3);
      187 |     expect(fromImdsCredentials).not.toHaveBeenCalled();

      at Object.toEqual (../../node_modules/expect/build/index.js:241:22)
      at src/fromInstanceMetadata.spec.ts:184:52
      at src/fromInstanceMetadata.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/fromInstanceMetadata.spec.ts:4:12)
      at Object.<anonymous> (src/fromInstanceMetadata.spec.ts:177:80)

 PASS  src/config/EndpointConfigOptions.spec.ts
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 1 failed, 10 passed, 11 total
Tests:       1 failed, 74 passed, 75 total
Snapshots:   0 total
Time:        4.943 s
Ran all test suites.
error Command failed with exit code 1.
```

### Expected Behavior

```console
$ credential-provider-imds> yarn test
...
Test Suites: 11 passed, 11 total
Tests:       75 passed, 75 total
Snapshots:   0 total
Time:        4.505 s, estimated 5 s
Ran all test suites.
✨  Done in 5.04s.
```

**Comment by trivikr** [comment]
This happens as SyntaxError message has changed in Node.js 20.x

### Node.js <=18.x

```console
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> JSON.parse(".")
Uncaught SyntaxError: Unexpected token . in JSON at position 0
```

### Node.js 20.x

```console
Welcome to Node.js v20.3.0.
Type ".help" for more information.
> JSON.parse(".")
Uncaught SyntaxError: Unexpected token '.', "." is not valid JSON
```
