### ISSUE TITLE
s3-client generates uncatchable error on bad `Body` type

### ISSUE THREAD

**Issue by rafak** [aws/aws-sdk-js-v3#4848]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

when using `client-s3/PutObjectCommand` with a bad `Body` type, an uncatchable `TypeError` is thrown

### SDK version number

@aws-sdk/client-s3: ^3.352.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.20.0

### Reproduction Steps

dependencies: `@aws-sdk/client-s3` version `^3.352.0`
running the following inside a docker container:

file `x.js`
```js
'use strict'

process.on('uncaughtException', x => console.log('Uncaught Exception:', x))
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')
let config = {
  credentials: {
    accessKeyId: 'someAccessKeyId',
    secretAccessKey: 'someSecretAccessKey'
  }
}

const send = async () => {
  try {
    let s = new S3Client(config)
    let c = new PutObjectCommand({
      Bucket:'test-bucket', Key: 'testing-sdk', Body: {}
    })
    let result = await s.send(c)
    return result
  } catch (err) {
    console.error('GOT ERROR', err)
    throw err
  }
}
send()
  .then(result => console.log('RESULT', result))
  .catch(err => console.error('ERROR in promise chain:', err))


```

execute:
```
root@6c54747fe69a:/app# node x.js 
Uncaught Exception: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at writeBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:40:32)
    at writeRequestBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:31:9)
    at async resolve (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:55:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

### Observed Behavior

using and empty object (`{}`) as the input parameter `Body` to the `PutObjectCommand` creates and uncaught exception.
the error was not caught in the `try-catch` block
the exception was caught on the process level:
`process.on('uncaughtException', (...))`

```
Uncaught Exception: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at writeBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:40:32)
    at writeRequestBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:31:9)
    at async resolve (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:55:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Expected Behavior

i expected the aws-sdk to validate the input and throw an error early
i expected the error to be caught in the `catch (err) {}` block of the `async send() {}` function

**Comment by RanVaknin** [comment]
Hi @rafak ,

Unfortunately I'm not able to reproduce the reported behavior. My application logs the error from the context of the catch block:

```js
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')

const send = async () => {
  try {
    let s = new S3Client({
        region: "us-east-1", 
        credentials: {
		"accessKeyId": "Foo",
		"secretAccessKey": "Bar",
	}})
    let c = new PutObjectCommand({
      Bucket:'testbucket', Key: 'testing-sdk', Body: {}
    })
    let result = await s.send(c)
    return result
  } catch (err) {
    console.error('GOT ERROR', err)
    throw err
  }
}
send()
```

Dockerfile:
```dockerfile
FROM node:16.20.0
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD ["node", "sample.js"]
```

```console
$ docker build -t 4848 . 
$ docker run -it --rm 4848

node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at writeBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:40:32)
    at writeRequestBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:31:9)
    at async resolve (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:55:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I noticed that you are using both async await and .then().catch() which is the syntax for promises. While I'm not sure if this is the source of the issue, I would just choose one or the other. See my code example for how I would write make this call.

If you can give my implementation a try and let me know how it goes. Otherwise can you provide a github repository with minimal code required to consistently reproduce this issue?

Thank you very much,
Ran~

**Comment by rafak** [comment]
@RanVaknin  

how about if you swallow the error?

```
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')

const send = async () => {
  try {
    const client = new S3Client({
        region: "us-east-1", 
        credentials: {
		"accessKeyId": "Foo",
		"secretAccessKey": "Bar",
	}})
    const command = new PutObjectCommand({
      Bucket:'testbucket-3650', Key: 'testing-sdk', Body: {}
    })
    const result = await client.send(command)
    return result
  } catch (err) {
    // swallow error
  }
}
send()
```

will there be any output on the console?

**Comment by rafak** [comment]
@RanVaknin 
this is what i get after running the above test:

the file (x.js):
```
root@19ae8a71a36f:/app# cat x.js
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')

const send = async () => {
  try {
    const client = new S3Client({
        region: "us-east-1", 
        credentials: {
		"accessKeyId": "Foo",
		"secretAccessKey": "Bar",
	}})
    const command = new PutObjectCommand({
      Bucket:'testbucket-3650', Key: 'testing-sdk', Body: {}
    })
    const result = await client.send(command)
    return result
  } catch (err) {
    // swallow error
  }
}
send()
root@19ae8a71a36f:/app# 
```


execution:

```
root@19ae8a71a36f:/app# node x.js 
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at writeBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:40:32)
    at writeRequestBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:31:9)
    at async resolve (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/node-http-handler.js:55:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

would you agree that the error should not be output to the console if it was caught by the `try-catch` block in the `send()` function?

**Comment by RanVaknin** [comment]
@rafak 

Thanks for the clarification. I see what you are saying. 

Added this to our queue.

Thanks,
Ran~

**Comment by kuhe** [comment]
should be fixed in releases including the not yet created https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.360.0, the next expected release is on Monday.
