### ISSUE TITLE
DyandmoDB ListBackupsCommandInput states BackupType is Optional, but is actually required

### ISSUE THREAD

**Issue by acarlson0000** [aws/aws-sdk-js-v3#4868]
### Describe the issue

I found this when upgrading a DynamoDB backup lambda from the v2 SDK to v3.

The `BackupType` property on `ListBackupsCommandInput` is listed as **Optional** in the docs (and says it defaults to `User` if nothing is provided). However, when the code was ran it triggered an exception

```
const response = await dynamoDBClient.send(new ListBackupsCommand();

...

{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'BackupType')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'BackupType')",
        "    at applyInstruction (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:72:59)",
        "    at take (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:44:9)",
        "    at se_ListBackupsInput (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3257:37)",
        "    at se_ListBackupsCommand (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:217:27)",
        "    at serialize (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/ListBackupsCommand.js:40:56)",
        "    at /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27",
        "    at /var/task/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:20:16",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
        "    at async fetchBackupsList (/var/task/lib/verify-backup.js:18:22)",
        "    at async verifyBackupAvailable (/var/task/lib/verify-backup.js:8:25)"
    ]
}
```

Not sure if the code (or the docs) are incorrect here, but raising in any case.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/listbackupscommandinput.html#backuptype

https://github.com/aws/aws-sdk-js-v3/blob/d10238ae7849b8c7551fe58afa788b0d9aaa41aa/clients/client-dynamodb/src/models/models_0.ts#L4960

**Comment by RanVaknin** [comment]
Hi @acarlson0000 ,

You need to explicitly specify a parameter object 
```diff
- const response = await dynamoDBClient.send(new ListBackupsCommand();
+ const response = await dynamoDBClient.send(new ListBackupsCommand({});
```

Thanks,
Ran
