### ISSUE TITLE
translateDocument on HTML content returns an InternalFailure

### ISSUE THREAD

**Issue by fvisticot** [aws/aws-sdk-js-v3#4882]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

- Using a lambda nodeJS function.
- Sending an HTML document smaller than 100K
- content is html String

get the error:
```console
2023-06-24T09:30:56.305Z	9702b3a3-1367-46d8-a0ef-6aa6e6ee1307	ERROR	InternalFailure: UnknownError
    at throwDefaultError (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_TranslateDocumentCommandError (/var/task/node_modules/@aws-sdk/client-translate/dist-cjs/protocols/Aws_json1_1.js:825:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async AmazonTranslateTranslator.translateDocument (file:///var/task/amazon_translate_translator.mjs:97:26)
    at async PostTranslator.translate (file:///var/task/post_translator.mjs:94:46) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '855af825-7002-4b5b-af3f-2b4074c22c95',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 4,
    totalRetryDelay: 210
  },
  __type: 'InternalFailure'
}
```

```js
try {
            const buffer = Buffer.from(content, "utf-8")
            const input = {
                Document: {Content: buffer, ContentType: contentType},
                SourceLanguageCode: sourceLanguage,
                TargetLanguageCode: targetLanguage,
                Settings: {
                    Formality: "FORMAL"
                },
            };
            const data = await this.client.send(new TranslateDocumentCommand(input));
            return data.TranslatedText

        } catch (e) {
            throw e
        }
```

### SDK version number

@aws-sdk/client-translate@3.359.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

lambda function

### Reproduction Steps

- Using a lambda nodeJS function.
- Sending an HTML document smaller than 100K
- content is html String

get the error:
```console
2023-06-24T09:30:56.305Z	9702b3a3-1367-46d8-a0ef-6aa6e6ee1307	ERROR	InternalFailure: UnknownError
    at throwDefaultError (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_TranslateDocumentCommandError (/var/task/node_modules/@aws-sdk/client-translate/dist-cjs/protocols/Aws_json1_1.js:825:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async AmazonTranslateTranslator.translateDocument (file:///var/task/amazon_translate_translator.mjs:97:26)
    at async PostTranslator.translate (file:///var/task/post_translator.mjs:94:46) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '855af825-7002-4b5b-af3f-2b4074c22c95',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 4,
    totalRetryDelay: 210
  },
  __type: 'InternalFailure'
}
```

```js
try {
            const buffer = Buffer.from(content, "utf-8")
            const input = {
                Document: {Content: buffer, ContentType: contentType},
                SourceLanguageCode: sourceLanguage,
                TargetLanguageCode: targetLanguage,
                Settings: {
                    Formality: "FORMAL"
                },
            };
            const data = await this.client.send(new TranslateDocumentCommand(input));
            return data.TranslatedText

        } catch (e) {
            throw e
        }
```

### Observed Behavior

- Using a lambda nodeJS function.
- Sending an HTML document smaller than 100K
- content is html String

get the error:
```console
2023-06-24T09:30:56.305Z	9702b3a3-1367-46d8-a0ef-6aa6e6ee1307	ERROR	InternalFailure: UnknownError
    at throwDefaultError (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_TranslateDocumentCommandError (/var/task/node_modules/@aws-sdk/client-translate/dist-cjs/protocols/Aws_json1_1.js:825:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async AmazonTranslateTranslator.translateDocument (file:///var/task/amazon_translate_translator.mjs:97:26)
    at async PostTranslator.translate (file:///var/task/post_translator.mjs:94:46) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '855af825-7002-4b5b-af3f-2b4074c22c95',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 4,
    totalRetryDelay: 210
  },
  __type: 'InternalFailure'
}
```

```js
try {
            const buffer = Buffer.from(content, "utf-8")
            const input = {
                Document: {Content: buffer, ContentType: contentType},
                SourceLanguageCode: sourceLanguage,
                TargetLanguageCode: targetLanguage,
                Settings: {
                    Formality: "FORMAL"
                },
            };
            const data = await this.client.send(new TranslateDocumentCommand(input));
            return data.TranslatedText

        } catch (e) {
            throw e
        }
```

### Expected Behavior

No error returned

**Comment by yenfryherrerafeliz** [comment]
Hi @fvisticot, sorry to hear about your issues. By using the code below I did not get any problems:

```js
import {TranslateClient, TranslateDocumentCommand} from "@aws-sdk/client-translate";
import fs from "fs";

const client = new TranslateClient({
    region: 'us-east-2'
});
const buffer = fs.readFileSync("./index.html");
const response = await client.send(new TranslateDocumentCommand({
    Document: {
        Content: buffer,
        ContentType: "html"
    },
    SourceLanguageCode: "en",
    TargetLanguageCode: "es",
    Settings: {
        Formality: "FORMAL"
    }
}));

console.log(Buffer.from(response.TranslatedDocument.Content).toString('utf-8'))
```

Content for index.html
<Details>

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Translation App</title>
</head>
<body>
    <h1>Welcome to the translation app</h1>
    <section>
        <body>
            <p>This app is a project designed to help multiple users across the world.</p>
        </body>
    </section>
</body>
</html>
```
</Details>

However, in order to investigate this further could you please provide the value for the following variables:
- sourceLanguage
- targetLanguage
- buffer

Note: Please make sure any sensitive information is redacted.

Thanks!

**Comment by fvisticot** [comment]
Thank your for the support.
My issue was due because I was using "fr-FR" and "en-US" for source and language code
Using "en" and "fr" is OK

It seems that "fr-FR" is supported on the TranslateText command.

ContentType should be "text/html" and not "html". If i try your sample I get a validation error

**Comment by yenfryherrerafeliz** [comment]
@fvisticot, that is correct, it should be text/html. I was trying to reproduce the issue playing around and left the wrong content type. I am glad you got your issue resolved. 

If you have another problem please open a new issue.

Thanks!
