### ISSUE TITLE
DynamoDB Unmarshall Date ISO String - Unsupported type passed

### ISSUE THREAD

**Issue by hdhilip98** [aws/aws-sdk-js-v3#4903]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Blogs Table Attributes
- `id`: S (_Partition Key_)
- `createdAt`: S
- `status`: S
- `title`: S

I'm storing a `new Date().toISOString()` to the `createdAt` column. Also, using the `marshall()` function while performing `dynamodb:PutItem` to convert JavaScript object to DynamoDB record.

```js
const blog = {
  id: uuid(),
  title: "My blog post",
  status: "DRAFT",
  createdAt: new Date().toISOString(), //2023-07-02T03:44:06.004Z
};

try {
  const command = new PutItemCommand({
    TableName: "Blogs",
    Item: marshall(blog),
  });

  await dynamodb.send(command);
} catch (error) {
  console.error(error);
  throw new createError.InternalServerError(error);
}
```

Using `dynamodb:Scan` to fetch all items from the table. 

```js
try {
  var command = new ScanCommand({
    TableName: "Blogs",
  });

  const result = await dynamodb.send(command);

  blogs = unmarshall(result.Items);
} catch (error) {
  console.error(error);
  throw new createError.InternalServerError(error);
}
```

And while attempting to `unmarshall()` the result `Items`, getting the below error:

```
Error: Unsupported type passed: createdAt
    at convertToNative (/var/task/src/handlers/webpack:/@aws-sdk/util-dynamodb/dist-es/convertToNative.js:26:27)
    at /var/task/src/handlers/webpack:/@aws-sdk/util-dynamodb/dist-es/convertToNative.js:56:101
    at Array.reduce (<anonymous>)
    at Ew (/var/task/src/handlers/webpack:/@aws-sdk/util-dynamodb/dist-es/convertToNative.js:56:58)
    at convertToNative (/var/task/src/handlers/webpack:/@aws-sdk/util-dynamodb/dist-es/convertToNative.js:18:28)
    at unmarshall (/var/task/src/handlers/webpack:/@aws-sdk/util-dynamodb/dist-es/unmarshall.js:2:46)
    at /var/task/src/handlers/webpack:/src/handlers/getBlogs.js:23:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at xw (/var/task/src/handlers/webpack:/@middy/core/index.js:114:32)
```

Below is the result of `ScanCommand` without `unmarshall()` -
```json
[
  {
    "createdAt": {
      "S": "2023-07-02T03:44:06.004Z"
    },
    "id": {
      "S": "0aa8dea6-533e-478b-b948-accfbb9f8808"
    },
    "title": {
      "S": "My blog post"
    },
    "status": {
      "S": "DRAFT"
    }
  }
]
```

### SDK version number

@aws-sdk/util-dynamodb@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.16.1

### Reproduction Steps

Store a date ISO string to a Dynamodb table and attempt to unmarshall it while fetching it from the database.

### Observed Behavior

Error: Unsupported type passed

### Expected Behavior

The `unmarshall()` is expected to return the raw date string without attempting to parse it.

**Comment by hdhilip98** [comment]
Apologies. My mistake. 

While reviewing the definition of `unmarshall()` method, I understood that it takes an individual item as an argument. I was attempting to pass the item collection to `unmarshall()` function, which lead to the error.

```js
try {
  var command = new ScanCommand({
    TableName: "Blogs",
  });

  const result = await dynamodb.send(command);

  blogs = result.Items.map(unmarshall);
} catch (error) {
  console.error(error);
  throw new createError.InternalServerError(error);
}
```
