### ISSUE TITLE
TypeError: Invalid RFC-3339 date-time value when using AWS client-omics to list pre-configured Ready2Run workflows provided by AWS

### ISSUE THREAD

**Issue by zigtan** [aws/aws-sdk-js-v3#4941]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

AWS Omics' recently introduces pre-configured `Ready2Run` workflows in May 2023.

Using the AWS CLI, it is possible to obtain a list of the pre-configured `Ready2Run` workflows with the following command: `aws omics list-workflows --type READY2RUN`

e.g.
```
$ aws omics list-workflows --type READY2RUN
{
    "items": [
        {
            "arn": "arn:aws:omics:ap-southeast-1::workflow/3412776",
            "creationTime": "2023-05-15T00:00:00+00:00",
            "id": "3412776",
            "name": "Sentieon Somatic WGS",
            "status": "ACTIVE",
            "type": "READY2RUN"
        },
        {
            "arn": "arn:aws:omics:ap-southeast-1::workflow/5562080",
            "creationTime": "2023-05-15T00:00:00+00:00",
            "id": "5562080",
            "name": "GATK-BP Somatic WES bam2vcf",
            "status": "ACTIVE",
            "type": "READY2RUN"
        },
        ...
}
```

However when using the AWS SDK client (`"@aws-sdk/client-omics": "^3.363.0"`), the request throws the following JSON deserialization error:

```
2023-07-10T02:53:51.562Z	cbef6ed2-1f16-48ef-a55a-1e5fda0fe7d1	ERROR	TypeError: Invalid RFC-3339 date-time value
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at parseRfc3339DateTimeWithOffset (/var/task/index.js:8980:15)
    at creationTime (/var/task/index.js:24940:116)
    at applyInstruction (/var/task/index.js:9404:31)
    at take (/var/task/index.js:9377:9)
    at de_WorkflowListItem (/var/task/index.js:24938:39)
    at /var/task/index.js:24933:16
    at Array.map (<anonymous>)
    at de_WorkflowList (/var/task/index.js:24932:62)
    at items (/var/task/index.js:23622:23)
    at applyInstruction (/var/task/index.js:9404:31) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

The `TypeError("Invalid RFC-3339 date-time value")` exception looks to be thrown from the `aws-sdk-js-v3`'s `packages/smithy-client/src/date-utils.ts`'s `parseRfc3339DateTimeWithOffset()` function here on line 108: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/smithy-client/src/date-utils.ts#L108

I am unable to verify the actual `creationTime` string value that AWS Omics is passing to the `parseRfc3339DateTimeWithOffset()` function.

I have tried locally debugging the `packages/smithy-client/src/date-utils.ts`'s `parseRfc3339DateTimeWithOffset()` function with the `creationTime` value `2023-05-15T00:00:00+00:00` obtained from the AWS CLI response and it works without throwing the `TypeError("Invalid RFC-3339 date-time value")` exception. It just converts `2023-05-15T00:00:00+00:00` to `2023-05-15T00:00:00.000Z`.

Given that Omics `Ready2Run` workflows records are relatively new, there could be a data inconsistency for the source `creationTime` value that is being passed to `parseRfc3339DateTimeWithOffset()` that is causing the regular expression matching to fail and trigger the `TypeError("Invalid RFC-3339 date-time value")` exception to be thrown.

If someone could help verify the Omics `Ready2Run` workflow's `creationTime` values being passed to the `parseRfc3339DateTimeWithOffset()` that would help identify the cause of this error.

### SDK version number

@aws-sdk/client-omics@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

Create a Lambda function that uses the `@aws-sdk/client-omics` to make a `ListWorkflowsCommand` request with the type set to `WorkflowType.READY2RUN` and ensure the Lambda function has the necessary IAM policy to access Omics resources. Also ensure the AWS Region is set to a region that supports AWS Omics (e.g. `us-east-1`).

e.g.
```
import { ListWorkflowsCommand, ListWorkflowsCommandOutput, OmicsClient, WorkflowType } from '@aws-sdk/client-omics';
import { APIGatewayProxyEvent, APIGatewayProxyResult, Handler } from 'aws-lambda';

const omicsClient = new OmicsClient({
  region: process.env.AWS_REGION,
});

export const handler: Handler = async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
  console.log('EVENT: \n' + JSON.stringify(event, null, 2));
  try {
    const response: ListWorkflowsCommandOutput = await omicsClient.send(
      new ListWorkflowsCommand({
        type: WorkflowType.READY2RUN,
      })
    );
    return { statusCode: 200, body: JSON.stringify(response) };
  } catch (err: any) {
    console.error(err);
    return {
      statusCode: 400,
      body: `Error: ${err.message}`,
    };
  }
};

```

### Observed Behavior

Test the Omics SDK `ListWorkflowsCommand` call and it will throw the following error every time:
```
Error: Invalid RFC-3339 date-time value
  Deserialization error: to see the raw response, inspect the hidden field {error
}.$response on this object.
```

### Expected Behavior

Expect a valid JSON response similar to the AWS CLI equivalent command: `$ aws omics list-workflows --type READY2RUN` but with the `creationTime` converted successfully to `2023-05-15T00:00:00.000Z`.

```
{
    "items": [
        {
            "arn": "arn:aws:omics:ap-southeast-1::workflow/3412776",
            "creationTime": "2023-05-15T00:00:00.000Z",
            "id": "3412776",
            "name": "Sentieon Somatic WGS",
            "status": "ACTIVE",
            "type": "READY2RUN"
        },
        {
            "arn": "arn:aws:omics:ap-southeast-1::workflow/5562080",
            "creationTime": "2023-05-15T00:00:00.000Z",
            "id": "5562080",
            "name": "GATK-BP Somatic WES bam2vcf",
            "status": "ACTIVE",
            "type": "READY2RUN"
        },
        ...
}
```

**Comment by RanVaknin** [comment]
Hi @zigtan ,

Thanks for the in-depth repro steps. I've also ran this repro with the Go SDK and can confirm that this is a bug with the Omics service. 

If you examine the raw http response you can see that the service sends back the `creationTime` without the seconds delimeter: `"creationTime" : "2023-05-15T00:00Z"` , because this is missing the seconds delimiter, it fails deserialization. 

I have created an internal ticket with the Omics service team with high priority and hopefully they can fix their API to return the data in the correct format. 

Thanks for your patience.

All the best,
Ran~

**Comment by zigtan** [comment]
Thanks heaps @RanVaknin for the confirmation of the root-cause. No problems. Looking forward to the fix.

**Comment by RanVaknin** [comment]
This should be now fixed, 

@zigtan can you check and let us know?

Thanks,
Ran~
