### ISSUE TITLE
EMFIL (too many open files) when lambda sends many messages to SQS

### ISSUE THREAD

**Issue by Angoulema** [aws/aws-sdk-js-v3#4964]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We have a lambda which receives kaska-messages and after processing them sends sqs-messages to another lambda. In case of failure message should be sent to DLQ. Few days ago, we decided to migrate to v3 of SDK and encountered a problem: sporadically messages can't be sent both to SQS and DLQ (so in the end they are not sent anywhere) with the error:
```
"err": {
            "type": "NodeError",
            "message": "A system error occurred: uv_os_homedir returned EMFILE (too many open files)",
            "stack": "SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned EMFILE (too many open files)\n    at getHomeDir (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/getHomeDir.js:14:29)\n    at getCredentialsFilepath (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/getCredentialsFilepath.js:7:128)\n    at loadSharedConfigFiles (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:11:76)\n    at /var/task/node_modules/@smithy/node-config-provider/dist-cjs/fromSharedConfigFiles.js:8:102\n    at /var/task/node_modules/@smithy/property-provider/dist-cjs/chain.js:11:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async coalesceProvider (/var/task/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)\n    at async /var/task/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28\n    at async resolveParams (/var/task/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)",
            "code": "ERR_SYSTEM_ERROR",
            "info": {
                "type": "Object",
                "message": "too many open files",
                "stack": "",
                "errno": -24,
                "code": "EMFILE",
                "syscall": "uv_os_homedir"
            },
            "errno": -24,
            "syscall": "uv_os_homedir"
        }
```

Error can be reproduced on different environments. Approximately on 2000 messages (lambda batch is 75) 200+ fall with the error above.

### SDK version number

@aws-sdk/client-sqs@3.363.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v16.17.1

### Reproduction Steps

You basically need to create a SQS client in a lambda and send big amount of messages simultaneously (we used example batch of 2000 and 1500 messages and got 200+ and 300+ errors accordingly).

### Observed Behavior

During high load we get such errors:
```
"err": {
            "type": "NodeError",
            "message": "A system error occurred: uv_os_homedir returned EMFILE (too many open files)",
            "stack": "SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned EMFILE (too many open files)\n    at getHomeDir (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/getHomeDir.js:14:29)\n    at getCredentialsFilepath (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/getCredentialsFilepath.js:7:128)\n    at loadSharedConfigFiles (/var/task/node_modules/@smithy/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:11:76)\n    at /var/task/node_modules/@smithy/node-config-provider/dist-cjs/fromSharedConfigFiles.js:8:102\n    at /var/task/node_modules/@smithy/property-provider/dist-cjs/chain.js:11:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async coalesceProvider (/var/task/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)\n    at async /var/task/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28\n    at async resolveParams (/var/task/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)",
            "code": "ERR_SYSTEM_ERROR",
            "info": {
                "type": "Object",
                "message": "too many open files",
                "stack": "",
                "errno": -24,
                "code": "EMFILE",
                "syscall": "uv_os_homedir"
            },
            "errno": -24,
            "syscall": "uv_os_homedir"
        }
```

Error can be reproduced on different environments. Approximately on 2000 messages (lambda batch is 75) 200+ fall with the error above.

Also lambda exits with error 128 after those issues with SQS:
![image](https://github.com/aws/aws-sdk-js-v3/assets/70232156/98b4bb88-f21b-4fe5-8f22-d72c833e1a21)

### Expected Behavior

Not to get EMFILE error when using AWS SDK v3

### Additional Information/Context

I see numerous issues concerning EMFILE error during AWS SDK v3 work, yet it seems that most of them aren't fixed. That's concerning, taking into account that AWS users are constantly urged to move to v3 of lib.

**Comment by the-spanish-guy** [comment]
same issue it also started after migration to aws sdk v3 (lambda batch is 50)

**Comment by RanVaknin** [comment]
Hi @the-spanish-guy @Angoulema 

This was [reported in the past](https://github.com/aws/aws-sdk-js-v3/issues/4345)

But no one was able to provide a reproduction code for this. Can one of you publish a minimal github repo that can reliably reproduce this issue?

Thanks,
Ran~

**Comment by the-spanish-guy** [comment]
in my case it's something like this

```typescript
import {
  SNSClient,
  PublishCommand,
} from "@aws-sdk/client-sns";

export const updateShipments = async (): Promise<any> => {
  const chunkDatas = [
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...]
  ];

  for (const chunkData of chunkDatas) {
    await Promise.all(
      chunkData.map(async (data) => {
        const sns: SNSClient = new SNSClient({ region: "us-east-1" });
        try {
          const input: PublishCommand = new PublishCommand({
            TopicArn: "topic",
            Message: "message",
          });
          await sns.send(input);
          console.log(`Done !`);
        } catch (err) {
          console.log("Failed to deliver SNS Message");
          throw new Error(err);
        }
      })
    );
  }
}
```

and given the error
```
{
  "errorType": "Error",
  "errorMessage": "bind EMFILE 0.0.0.0",
  "code": "EMFILE",
  "errno": -24,
  "syscall": "bind",
  "address": "0.0.0.0",
  "stack": [
      "Error: bind EMFILE 0.0.0.0",
      "    at node:dgram:362:20",
      "    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
  ]
}

----

Unknown application error occurred Runtime.Unknown
```

I think the error is to instantiate the SNSClient several times but it is something that did not happen with the sdk v2

**Comment by Angoulema** [comment]
In our case sample code would be something like this:
```
import { SendMessageCommand, SQSClient, SendMessageRequest } from '@aws-sdk/client-sqs';
import { MSKEvent } from 'aws-lambda';

let isInitialized = false;
let sqs: SQSClient;
let sqsQueueUrl: SendMessageRequest['QueueUrl'] | undefined;

async function handler (event: MSKEvent) {
  if (!isInitialized) {
    sqs = new SQSClient({
      region: region
    });
    sqsQueueUrl = getSqsQueueUrl(sqsName);
  }

  const MessageToSend = new MessagesService(sqs, sqsQueueUrl);
  
  // here is logic to decode kafka messages and business logic, so in the end array of messages is extracted from MSKEvent
  const messages = [] as MessageToSend;
  for (const message of messages) {
    await MessageToSend.sendMessageToSQS(message)
  }
  
}

class MessagesService {
  constructor(
    private readonly sqs: SQSClient,
    private readonly queueUrl: SendMessageRequest['QueueUrl'] | undefined
  ) {
    this.sqs = new SQSClient({});
    this.queueUrl = queueUrl;
  }

  public async sendMessageToSQS(message: MessageToSend): Promise<void> {
    const command = new SendMessageCommand({
      QueueUrl: this.queueUrl,
      MessageBody: JSON.stringify(message)
    });
    await this.sqs.send(command);
  }
}
```

**Comment by RanVaknin** [comment]
Hi @the-spanish-guy @Angoulema ,

You are both creating an sqs client every time you process a message.
You need to create the client once, in the global scope, and increase the number of sockets if necessary. 


so @the-spanish-guy in your example:

```js
import {
  SNSClient,
  PublishCommand,
} from "@aws-sdk/client-sns";

const sns: SNSClient = new SNSClient({ region: "us-east-1" }); // client moved to the global scope

export const updateShipments = async (): Promise<any> => {
  const chunkDatas = [
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...],
    ["asdf", "asdf", "asdf", ...]
  ];

  for (const chunkData of chunkDatas) {
    await Promise.all(
      chunkData.map(async (data) => {
        try {
          const input: PublishCommand = new PublishCommand({
            TopicArn: "topic",
            Message: "message",
          });
          await sns.send(input);
          console.log(`Done !`);
        } catch (err) {
          console.log("Failed to deliver SNS Message");
          throw new Error(err);
        }
      })
    );
  }
}
```

If you need to increase the number of sockets you can do it like so:

```js
import { NodeHttpHandler } from "@aws-sdk/node-http-handler";
import  https from "https";    
var agent = new https.Agent({
  maxSockets: 25
});

var sqs = new SQSClient({
  requestHandler: new NodeHttpHandler({
    httpsAgent: agent
 })
});
```

Please let me know if this helps.
Thanks,
Ran~

**Comment by Angoulema** [comment]
@RanVaknin seems that this helps, thanks!

**Comment by RanVaknin** [comment]
@Angoulema glad to hear 👍 

Feel free to open another issue if you need additional assistance. 

All the best,
Ran~
