### ISSUE TITLE
client-dynamodb@3.379.1 broken

### ISSUE THREAD

**Issue by oscarprabhakar** [aws/aws-sdk-js-v3#5034]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I get a runtime error when instantiating DynamoDBDocumentClient in a Lambda handler:
```
    "errorMessage": "(0 , client_sts_1.decorateDefaultCredentialProvider) is not a function",
```

### SDK version number

@aws-sdk/client-dynamodb@3.379.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node v18.7

### Reproduction Steps

Runtime error when instantiating DynamoDBDocumentClient like so:

```
const documentClient = DynamoDBDocumentClient.from(new DynamoDBClient({}));
```

### Observed Behavior

```
{
    "errorType": "TypeError",
    "errorMessage": "(0 , client_sts_1.decorateDefaultCredentialProvider) is not a function",
    "stack": [
        "TypeError: (0 , client_sts_1.decorateDefaultCredentialProvider) is not a function",
        "    at getRuntimeConfig (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/runtimeConfig.js:32:124)",
        "    at new DynamoDBClient (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/DynamoDBClient.js:21:64)",
        "    at Object.<anonymous> (/var/task/target/build/src/<redacted>.js:14:67)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
        "    at Module._load (node:internal/modules/cjs/loader:960:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
        "    at require (node:internal/modules/cjs/helpers:110:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)"
    ]
}
```

when instantiating DynamoDBDocumentClient like so:
```
const documentClient = DynamoDBDocumentClient.from(new DynamoDBClient({}));
```

It appears that the dependency client-sts@v3.379 does not export the function `decorateDefaultCredentialProvider` and breaks in the constructor of `DynamoDBClient`. 

I do not get the error on `client-dynamodb@3.378.0

### Expected Behavior

No runtime errors

**Comment by oscarprabhakar** [comment]
Seems like our renovate bot has a bug. It updated the wrong `resolved` package .tgz URL for `client-sts` in the `package-lock` !
