### ISSUE TITLE
 Cannot find module '@aws-sdk/middleware-endpoint' on @aws-sdk/client-cognito-identity-provider dependency

### ISSUE THREAD

**Issue by clement-faure** [aws/aws-sdk-js-v3#5207]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Missing dependency make app crashing

### SDK version number

"@aws-sdk/client-cognito-identity-provider": "^3.410.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.12.1

### Reproduction Steps

Install 

```
"@aws-sdk/client-cognito-identity-provider": "^3.410.0",
"@aws-sdk/client-s3": "^3.410.0",
"@aws-sdk/client-ses": "^3.410.0",
"@aws-sdk/cloudfront-signer": "^3.410.0",
"@aws-sdk/lib-storage": "^3.410.0",
"@aws-sdk/s3-request-presigner": "^3.410.0",
```

And try to run your app

### Observed Behavior

<img width="1387" alt="Capture d’écran 2023-09-13 à 17 33 48" src="https://github.com/aws/aws-sdk-js-v3/assets/23209488/70daed12-6c3d-4465-9081-bb680d1ccf07">

### Expected Behavior

It should work normally

### Possible Solution

Missing dependency

**Comment by ajredniwja** [comment]
Hi @clement-faure, thanks for opening this issue however I was not able to encounter any errors when installing any of the dependencies you mentioned. Can you please provide code about how you are using it in your app?

**Comment by clement-faure** [comment]
> Hi @clement-faure, thanks for opening this issue however I was not able to encounter any errors when installing any of the dependencies you mentioned. Can you please provide code about how you are using it in your app?

Thank you for your quick response. Still having the issue with the lastest version of @aws-sdk modules.

I have `@aws-amplify/auth` and `@aws-amplify/core` dependencies causing a conflict on `@aws-sdk/credential-provider-node` with two versions installed (3.6.1 and 3.414.0). 

- `@aws-sdk/credential-provider-node@3.414.0` (for @aws-sdk/client-cognito-identity-provider@3.414.0)
- `@aws-sdk/credential-provider-node@3.6.1`(for @aws-amplify/core@5.8.4)

All was working fine with 

- `@aws-sdk/credential-provider-node@3.358.0` (for @aws-sdk/client-cognito-identity-provider@3.359.0)
- `@aws-sdk/credential-provider-node@3.6.1`(for @aws-amplify/core@5.8.4)

Any clue on this ? I've gone through yarn.lock but all seems fine.

**Comment by villelahdenvuo** [comment]
I'm also having issues after updating AWS SDK:

```
Error: Cannot find module '@aws-sdk/region-config-resolver'
Require stack:
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/mnt/ramdisk/repo/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/mnt/ramdisk/repo/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/mnt/ramdisk/repo/node_modules/@aws-sdk/token-providers/dist-cjs/bundle/client-sso-oidc-node.js:210:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/mnt/ramdisk/repo/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/mnt/ramdisk/repo/node_modules/@aws-sdk/token-providers/dist-cjs/index.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/token-providers/dist-cjs/bundle/client-sso-oidc-node.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/token-providers/dist-cjs/index.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/resolveSSOCredentials.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/fromSSO.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-sts/dist-cjs/index.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-cloudfront/dist-cjs/runtimeConfig.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-cloudfront/dist-cjs/CloudFrontClient.js',
    '/mnt/ramdisk/repo/node_modules/@aws-sdk/client-cloudfront/dist-cjs/index.js',
    ...
  ]
```

**Comment by aBurmeseDev** [comment]
Hi everyone, sorry this fell off our radar. I haven't been able to reproduce the error using a very minimal code with least dependencies installed. Could someone verify if the issue is ongoing with latest versions?

**Comment by villelahdenvuo** [comment]
I'm pretty sure this is not an issue anymore due to updated transient dependencies.

**Comment by aBurmeseDev** [comment]
Appreciate the update @villelahdenvuo. I'll go ahead and close this issue. Feel free to reach out again if anyone runs into SDK related issue here.
