### ISSUE TITLE
DynamoDBClient configuration as an array ignore custom endpoint

### ISSUE THREAD

**Issue by 1xtr** [aws/aws-sdk-js-v3#5211]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

DynamoDBClient with options as an object
```
{
  endpoint: getEnv('CUSTOM_ENDPOINT'),
  region: getEnv('AWS_REGION'),
  maxAttempts: 3,
  retryMode: 'adaptive',
  requestHandler,
}
```
IDE mark arg as error and wait an array of config.
![image](https://github.com/aws/aws-sdk-js-v3/assets/59780048/c14045fb-565b-404d-98ca-8113e2695205)
Client work fine. I can do any actions with DB.

**But**
If I wrap config to an array, my custom ENDPOINT will ignore
![image](https://github.com/aws/aws-sdk-js-v3/assets/59780048/89a72919-2a4a-4f18-9bd7-112ee4fbc674)

![image](https://github.com/aws/aws-sdk-js-v3/assets/59780048/f1565eba-2502-4498-8769-c26e772fdc95)

### SDK version number

"@aws-sdk/client-dynamodb": "^3.410.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

Clean install latest versions with simple config.

### Observed Behavior

"Error: AWS SDK error wrapper for Error: getaddrinfo ENOTFOUND dynamodb.us-local-1.amazonaws.com
  at asSdkError (D:\\project\\node_modules\\@smithy\\middleware-retry\\dist-cjs\\util.js:11:12)
  at D:\\project\\node_modules\\@smithy\\middleware-retry\\dist-cjs\\retryMiddleware.js:35:51
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at D:\\project\\node_modules\\@aws-sdk\\middleware-logger\\dist-cjs\\loggerMiddleware.js:7:26"

### Expected Behavior

successfully pit item to DB

### Possible Solution

config as an object work, and now I ignore IDE error

**Comment by yenfryherrerafeliz** [comment]
Hi @1xtr, please do not provide the configuration as an array. You should provide it  as an object since it is the expected type. I will investigate why you get this syntax error and I will get back to you.

Thanks!

**Comment by quyphan97** [comment]
Can anyone help me with this problem? please help me :((
[https://github.com/aws/aws-sdk-js-v3/discussions/5206](https://github.com/aws/aws-sdk-js-v3/discussions/5206)

**Comment by usamakamran1** [comment]
The same is happening for S3 Client:
`import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';
import {S3ClientConfig} from "@aws-sdk/client-s3/dist-types/S3Client";

const credentials = fromNodeProviderChain();
const s3 = new S3Client({
  credentials: credentials
});`

**Comment by usamakamran1** [comment]
The issue is not related to `@aws-sdk/client-*` or `aws-sdk/types`. It is how `__CheckOptionalClientConfig` is defined in `@smithy/types`. Explicitly defining it to two months ago i.e. version `2.0.2` resolved the issue for me.

Trying older versions of aws-sdk did not work for me.

**Comment by yenfryherrerafeliz** [comment]
@usamakamran1 I can confirm that installing @smithy/types@2.0.2 fixes the issue. @1xtr could you please workaround this issue by installing the package@version mentioned before as follow ```npm install @smithy/types@2.0.2```. I will investigate why this behavior happens.

Thanks!

**Comment by 1xtr** [comment]
> @usamakamran1 I can confirm that installing @smithy/types@2.0.2 fixes the issue. @1xtr could you please workaround this issue by installing the package@version mentioned before as follow `npm install @smithy/types@2.0.2`. I will investigate why this behavior happens.
> 
> Thanks!

Not solve.
I start new project now with latest version and storm mark client opts as error again
```json
"@aws-sdk/client-sqs": "^3.427.0"
```

![image](https://github.com/aws/aws-sdk-js-v3/assets/59780048/5bab4335-5e56-4d59-b732-bffc37c07b37)

In another project with
```json
"@aws-sdk/client-dynamodb": "^3.408.0",
"@aws-sdk/client-sqs": "^3.408.0",
"@aws-sdk/lib-dynamodb": "^3.408.0",
```
all works

**Comment by 1xtr** [comment]
I find changed my code, delete `requestHandler`
```js
export const requestHandler = new NodeHttpHandler({
  // ms
  connectionTimeout: getNumberFromEnv('CONNECTION_TIMEOUT', 3000),
  requestTimeout: getNumberFromEnv('REQUEST_TIMEOUT', 7000),
})
```
And set requestTimeout in client send method.
```js
const sendSQSResponse = await sqsClient.send(cmd, {
      requestTimeout: getNumberFromEnv('REQUEST_TIMEOUT', 5000)
    })
```
And now all works fine
