### ISSUE TITLE
Node 20 seems incompatible with streaming client

### ISSUE THREAD

**Issue by qhenkart** [aws/aws-sdk-js-v3#5265]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We have a 100% working version on node 18.15. I just tried upgrading to node 20.7 and everything works except for the aws streaming client. In fact, it fails at import on tests and on usage live

In tests it fails with the following error

```
 import { StartStreamTranscriptionCommand, TranscribeStreamingClient } from "@aws-sdk/client-transcribe-streaming"
        | ^
import { PassThrough } from "readable-stream"
import mic from "microphone-stream"


      at Runtime.createScriptFromCode (.yarn/cache/jest-runtime-npm-29.7.0-120fa64128-d19f113d01.zip/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (.yarn/cache/@aws-sdk-middleware-sdk-transcribe-streaming-npm-3.418.0-1473b98fc2-dc71c380d9.zip/node_modules/@aws-sdk/middleware-sdk-transcribe-streaming/dist-cjs/middleware-inject-response-values.js:4:16)
      at Object.<anonymous> (.yarn/cache/@aws-sdk-middleware-sdk-transcribe-streaming-npm-3.418.0-1473b98fc2-dc71c380d9.zip/node_modules/@aws-sdk/middleware-sdk-transcribe-streaming/dist-cjs/getTranscribeStreamingPlugin.js:4:45)
      at Object.<anonymous> (.yarn/cache/@aws-sdk-middleware-sdk-transcribe-streaming-npm-3.418.0-1473b98fc2-dc71c380d9.zip/node_modules/@aws-sdk/middleware-sdk-transcribe-streaming/dist-cjs/index.js:5:22)
      at Object.<anonymous> (.yarn/cache/@aws-sdk-client-transcribe-streaming-npm-3.418.0-88537ebf7b-7b03a07c71.zip/node_modules/@aws-sdk/client-transcribe-streaming/dist-cjs/TranscribeStreamingClient.js:8:47)
      at Object.<anonymous> (.yarn/cache/@aws-sdk-client-transcribe-streaming-npm-3.418.0-88537ebf7b-7b03a07c71.zip/node_modules/@aws-sdk/client-transcribe-streaming/dist-cjs/index.js:5:22)
      at Object.require (src/action_creators/audio_recording/liveTranscription.js:1:1)
      at Object.require (src/components/transcriptions/containers/AudioRecorder.js:11:1)
      at Object.require (src/components/cards/containers/CardDisplay.jsx:26:1)
      at Object.require (src/components/cards/containers/CardTransition.js:3:1)
      at Object.require (src/components/cards/__tests__/CardTransition.test.js:4:1)
```

live it fails with the following error but not on import

```
TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.
    at FetchHttpHandler.handle (vendors-_yarn___virtual___react-beautiful-dnd-virtual-e0869911dd_0_cache_react-beautiful-dnd--c9fc4a.bundle.js:18650:30)
```

Reverting back to node version 18.7 works fine. 
    "@aws-sdk/client-transcribe-streaming": "^3.418.0",

### SDK version number

    "@aws-sdk/client-transcribe-streaming": "^3.418.0",

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.7.0

### Reproduction Steps

follow the tutorial on how to create a transcription and then upgrade to node 20.7

### Observed Behavior

full errors are in the description

### Expected Behavior

no errors

### Possible Solution

looks like some breaking change with node v20

### Additional Information/Context

reverting back to node 18 resolves the issue

**Comment by RanVaknin** [comment]
Hi @qhenkart ,

I'm actually getting a different error when trying to run this code. This might be a breaking change caused by https://github.com/aws/aws-sdk-js-v3/pull/4987.

We will look into this with priority. 

Thanks,
Ran~

**Comment by kuhe** [comment]
```
TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.
    at FetchHttpHandler.handle
```

Could you please show the code that is being run leading up to this error?

- the method in question does not send a body if the method is GET or HEAD, so I don't know how this error can even happen. What is your version of `@smithy/fetch-http-handler` and/or `@aws-sdk/fetch-http-handler`?
- are you following the Node.js or browser example for Transcribe-streaming? 
- are you bundling your code? if so, with what settings?

**Comment by kuhe** [comment]
While it doesn't appear to be directly related to your issue, the following fix should fix `TypeError: Failed to parse URL` if you run into that.

Linking this fix: https://github.com/awslabs/smithy-typescript/pull/983 to be released later today. It will require an update to the latest version of `@smithy/fetch-http-handler` by reinstalling without a lockfile if you have one, or running npm upgrade.
