### ISSUE TITLE
unable to resolve module stream (react-native)

### ISSUE THREAD

**Issue by quteboy** [aws/aws-sdk-js-v3#5280]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

facing this issue while installing the module
`error: Error: Unable to resolve module stream from D:\newATM\newATM2\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\streams\create-read-stream-on-buffer.js: stream could not be found within the project or in these directories:
  node_modules
  2 | Object.defineProperty(exports, "__esModule", { value: true });
  3 | exports.createReadStreamOnBuffer = void 0;
> 4 | const stream_1 = require("stream");
    |                           ^
  5 | function createReadStreamOnBuffer(buffer) {
  6 |     const stream = new stream_1.Transform();
  7 |     stream.push(buffer);
    at ModuleResolver.resolveDependency (D:\newATM\newATM2\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (D:\newATM\newATM2\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (D:\newATM\newATM2\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (D:\newATM\newATM2\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (D:\newATM\newATM2\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._addDependency (D:\newATM\newATM2\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 3)
    at async Graph._processModule (D:\newATM\newATM2\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (D:\newATM\newATM2\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 1)`

### SDK version number

@aws-sdk/client-appsync@^3.421.0, ...

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

16.16.0

### Reproduction Steps

after installing the package
encountering the issue at compilation 
when i run the command `npx react-native run-android`

### Observed Behavior

`Unable to resolve module stream from D:\newATM\newATM2\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\streams\create-read-stream-on-buffer.js: stream could not be found within the project or in these directories:`

### Expected Behavior

it should work properly
after installing the package
project should compile and run as usual

**Comment by kuhe** [comment]
try the instructions here: https://github.com/aws/aws-sdk-js-v3/issues/4877#issuecomment-1656007484

**Comment by AmrutaPawar025** [comment]
facing same issue.
so updated package.json file of client-s3 as explained above.
"react-native": {

    "./dist-es/runtimeConfig": "./dist-es/runtimeConfig.native",

    "./dist-es/getAwsChunkedEncodingStream": "./dist-es/getAwsChunkedEncodingStream.browser",

  "./dist-es/sdk-stream-mixin": "./dist-es/sdk-stream-mixin.browser"

  },
  
  still issue exists

**Comment by enisze** [comment]
still an issue here: [comment](https://github.com/aws/aws-sdk-js-v3/issues/5246#issuecomment-1759990265)

**Comment by kuhe** [comment]
The latest version of the SDK should be able to build in react-native's default bundler configuration.
