### ISSUE TITLE
v3.423.0 Error during execution @smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:8:73)

### ISSUE THREAD

**Issue by anitatailor** [aws/aws-sdk-js-v3#5323]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We were facing this issue https://github.com/aws/aws-sdk-js-v3/issues/5276 in CI/CD pipeline. As v3.423 is launched pipeline  npm i is fixed but application started giving error during start
 

TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:7134:19)
    at Object.<anonymous> (/var/www/XXXX/node_modules/@smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:8:73)
    ... 5 lines matching cause stack trace ...
    at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/www/XXXX/node_modules/@smithy/fetch-http-handler/dist-cjs/index.js:4:22) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:611:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at Object.<anonymous> (/var/www/xxxxx/server/node_modules/@smithy/fetch-http-handler/dist-cjs/fetch-http-handler.js:8:73)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node -v v18.17.1

### Reproduction Steps

npm i and npm start after upgrade to V3.423.0

### Observed Behavior

Upgrade to V3.4.223.0

### Expected Behavior

npm start should not fail at initial loading

**Comment by ajredniwja** [comment]
Hi @anitatailor thanks for opening this issue, this might be related to https://github.com/awslabs/smithy-typescript/pull/983
Can you please follow the instructions mentioned here: https://github.com/aws/aws-sdk-js-v3/issues/5265#issuecomment-1743498985

**Comment by kuhe** [comment]
Upgrade to `@smithy/fetch-http-handler`@`2.2.1` (currently latest)

**Comment by trivikr** [comment]
@anitatailor As per error logs, it appeared that you were using node fetch provided by undici in Node.js core.

We now provide a request handler in [@aws-sdk/undici-http-handler](https://www.npmjs.com/package/@aws-sdk/undici-http-handler). You can import it in your application, and pass it as `requestHandler` in your client configuration.

Example:
```js
import { S3 } from "@aws-sdk/client-s3";
import { UndiciHttpHandler } from "@aws-sdk/undici-http-handler";

const client = new S3({
  requestHandler: new UndiciHttpHandler(),
});

client.listBuckets().then(console.log);
```

Would you like to give it a try?

If you do, please provide us feedback by creating a new issue or upvote existing [issues](https://github.com/aws/aws-sdk-js-v3/issues).
