### ISSUE TITLE
@aws-sdk/core@v3.436.0 lacks dependency on tslib

### ISSUE THREAD

**Issue by sjbarag** [aws/aws-sdk-js-v3#5437]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The recently-added `@aws-sdk/core` (at v3.436.0) requires `tslib` as a dependency, but doesn't declare that dependency. This violates `pnpm`'s (and Bazel's) strict dependency tracking when `hoist` is disabled.

Related:
* https://github.com/aws/aws-sdk-js-v3/issues/4814
* https://github.com/aws/aws-sdk-js-v3/issues/4075

### SDK version number

@aws-sdk/core@3.436.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.20.1

### Reproduction Steps
Save this file as `5437_repro.sh` and make it executable with `chmod u+x 5437_repro.sh`.

```sh
#!/usr/bin/env sh

set -ex

# Create a sandbox.
cd "$(mktemp -d)"

# Print the current version(s)
pnpm --version
pnpm version

# And the OS for good measure.
uname -om

# Create a new package.
pnpm init

# Don't hoist phantom dependencies to ./node_modules: https://pnpm.io/npmrc#hoist
echo "hoist=false" > .npmrc

# Add core.
pnpm add @aws-sdk/core@3.436.0

# Write a small repro script...
cat >index.js <<EOF
try {
  require("@aws-sdk/core");
  console.log("did not repro");
} catch (e) {
  console.error("repro'd!");
  console.error(e);
}
EOF

# ...and run it
node index.js
```

then run it with `./5437_repro.sh`.

### Observed Behavior

An error occurs, indicating that `tslib` couldn't be found from `@aws-sdk/core`:

```
$ node index.js
repro'd!
Error: Cannot find module 'tslib'
Require stack:
- /tmp/mwe/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js
- /tmp/mwe/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/tmp/mwe/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/mwe/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js',
    '/tmp/mwe/index.js'
  ]
}
```

### Expected Behavior

`@aws-sdk/core` can be `require`d with no error:

```
$ node index.js
did not repro
```

### Possible Solution

Add `"tslib": "^2.5.0"` to the `dependencies` block of the `core` package (same as https://github.com/aws/aws-sdk-js-v3/pull/4128)

### Additional Information/Context

For anyone running into this and currently blocked, `pnpm`'s `packageExtensions` allows you to manually declare that phantom dependency. Add this to your `package.json` (or merge it into an existing `.pnpm.packageExtensions`):

```diff
+  "pnpm": {
+    "packageExtensions": {
+      "@aws-sdk/core@3.436.0": {
+        "dependencies": {
+          "tslib": "^2.5.0"
+        }
+      }
+    }
+  }
```

and rerun `pnpm install`.

**Comment by mikhail-katrin** [comment]
Encountered this issue in 3.438.0 as well

**Comment by RanVaknin** [comment]
Hi @sjbarag ,

I'm not able to reproduce your issue. Running  config hoist false raised an error:
```console
$ pnpm config set hoist false

npm ERR! `hoist` is not a valid npm option
```

Instead, I used an .npmrc file as specified in the [pnpm docs](https://pnpm.io/npmrc#hoist).

Maybe you are using an older version of pnpm? 

```console
$ pnpm -v
7.16.1

$ ls -a
.              ..             .npmrc         node_modules   package.json   pnpm-lock.yaml sample.js

$ pnpm ls
Legend: production dependency, optional only, dev only

rvaknin/test_folder/5437

dependencies:
@aws-sdk/core 3.436.0

$ cat .npmrc 
hoist=false
                                                                                                                                                                                                                                                                                      
$ cat sample.js 
try {
    require("@aws-sdk/core");
    console.log("did not repro");
  } catch (e) {
    console.error("repro'd!");
    console.error(e);
  }     
                                                                                                                                                                                                                                                                                               
$ node sample.js 
did not repro
```

Can you provide any other details that can help with reproducing this issue?

Thanks,
Ran~

**Comment by sjbarag** [comment]
Hey @RanVaknin — looks like you're using `pnpm` 7.x, but the current major-version is 8.x. `hoist` was [still supported in 7.x](https://pnpm.io/7.x/npmrc#hoist) though, and I can repro on that version as well.

I've updated the repro script in the issue description (duplicated below), which still repro's on both 7.x and 8.x:

```
#!/usr/bin/env sh

set -ex

# Create a sandbox.
cd "$(mktemp -d)"

# Print the current version(s)
pnpm --version
pnpm version

# And the OS for good measure.
uname -om

# Create a new package.
pnpm init

# Don't hoist phantom dependencies to ./node_modules: https://pnpm.io/npmrc#hoist
echo "hoist=false" > .npmrc

# Add core.
pnpm add @aws-sdk/core@3.436.0

# Write a small repro script...
cat >index.js <<EOF
try {
  require("@aws-sdk/core");
  console.log("did not repro");
} catch (e) {
  console.error("repro'd!");
  console.error(e);
}
EOF

# ...and run it
node index.js
```

**Comment by sjbarag** [comment]
(for clarity, here's the full output of that script)

```
$ /tmp/repro.sh
+ mktemp -d
+ cd /tmp/tmp.rGqTaQa9ot
+ pnpm --version
7.33.6
+ pnpm version
{
  npm: '8.19.4',
  node: '16.20.1',
  v8: '9.4.146.26-node.26',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.11',
  openssl: '1.1.1u+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022f',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
+ uname -om
x86_64 GNU/Linux
+ pnpm init
Wrote to /tmp/tmp.rGqTaQa9ot/package.json

{
  "name": "tmp.rGqTaQa9ot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
+ echo hoist=false
+ pnpm add @aws-sdk/core@3.436.0
Packages: +17
+++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/barag/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ @aws-sdk/core 3.436.0

Progress: resolved 17, reused 17, downloaded 0, added 17, done
Done in 1.1s
+ cat
+ node index.js
repro'd!
Error: Cannot find module 'tslib'
Require stack:
- /tmp/tmp.rGqTaQa9ot/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js
- /tmp/tmp.rGqTaQa9ot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/tmp/tmp.rGqTaQa9ot/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/tmp.rGqTaQa9ot/node_modules/.pnpm/@aws-sdk+core@3.436.0/node_modules/@aws-sdk/core/dist-cjs/index.js',
    '/tmp/tmp.rGqTaQa9ot/index.js'
  ]
}
```

**Comment by RanVaknin** [comment]
Hi @sjbarag ,

Perfect. I can see the error now. Will discuss this with the team and get back to you. 

Thanks,
Ran~
