### ISSUE TITLE
Error "Region is missing" even though it's defined in config

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#5471]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The JS SDK v3 throws "Region is missing" even though it's defined in config

### SDK version number

3.445.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

All

### Reproduction Steps

Backup your existing configurations.
```console
$ mv ~/.aws/config ~/.aws/config.bkp
$ mv ~/.aws/credentials ~/.aws/credentials.bkp
```

Configure new profile `test`:
```console
$ aws configure --profile test
AWS Access Key ID [None]: <REDACTED>
AWS Secret Access Key [None]: <REDACTED>
Default region name [None]: us-west-2
Default output format [None]: 
```

Test code:
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";

const client = new DynamoDB({ profile: "test" });
await client.listTables({});
```

Restore your configurations after testing.
```console
$ rm ~/.aws/config && mv ~/.aws/config.bkp ~/.aws/config
$ rm ~/.aws/credentials && mv ~/.aws/credentials.bkp ~/.aws/credentials
```

### Observed Behavior

Error "Region is missing" is thrown

```console
/Users/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10
        throw new Error("Region is missing");
              ^

Error: Region is missing
    at default (/Users/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /Users/trivikr/workspace/test/node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /Users/trivikr/workspace/test/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at async coalesceProvider (/Users/trivikr/workspace/test/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async /Users/trivikr/workspace/test/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28
    at async useFipsEndpoint (/Users/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
    at async resolveParams (/Users/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:37:40)
    at async getEndpointFromInstructions (/Users/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:15:28)
    at async /Users/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
    at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

AWS CLI successfully executes as it reads the correct region:
```console
$ aws dynamodb list-tables --profile test
{
    "TableNames": []
}
```

### Expected Behavior

Read the region `us-west-2` from config

```console
$ cat ~/.aws/credentials
[test]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>

$ cat ~/.aws/config     
[profile test]
region = us-west-2
```

**Comment by trivikr** [comment]
For this specific case, an empty profile is passed in configFileSelector

https://github.com/awslabs/smithy-typescript/blob/7de91ee308862ad62ed95fe9222f239221fa5a90/packages/config-resolver/src/regionConfig/config.ts#L17

**Comment by trivikr** [comment]
This is not an issue with client configuration, as Clients do not accept `profile` in their configuration, either in v2 or v3.

Correct code
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";

const client = new DynamoDB();
await client.listTables({});
```

```console
AWS_PROFILE=test node test.mjs
```

However, it's an issue with `fromIni` which does accept profile
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { fromIni } from "@aws-sdk/credential-providers";

const client = new DynamoDB({
  credentials: fromIni({ profile: "test" }),
});
await client.listTables({});
```

**Comment by trivikr** [comment]
This issue happens as the `profile` if only used for reading credentials from credentials file as requested.
The profile name is not passed when reading region from config, so the error is thrown.

If application wants to read anything from config file, the profile name needs to be passed in `AWS_PROFILE` environment variable and everything will be read from profile.

There are two other workarounds in code:

Explicitly set region in code.
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { fromIni } from "@aws-sdk/credential-providers";

const client = new DynamoDB({
  region: "us-west-2",
  credentials: fromIni({ profile: "test" }),
});
console.log(await client.listTables({}));
```

Pass profile name with loadConfig call
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { fromIni } from "@aws-sdk/credential-providers";
import { loadConfig } from "@smithy/node-config-provider";
import { NODE_REGION_CONFIG_OPTIONS } from "@smithy/config-resolver";

const client = new DynamoDB({
  region: loadConfig(NODE_REGION_CONFIG_OPTIONS, { profile: "test" }),
  credentials: fromIni({ profile: "test" }),
});
console.log(await client.listTables({}));
```
