### ISSUE TITLE
The error 'code' got removed in sdk v3 of lex modelnig service LexModelBuildingService() and also the http status code has changed from 400 to 429

### ISSUE THREAD

**Issue by abhirpat** [aws/aws-sdk-js-v3#5473]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In SDK V2, for  LexModelBuildingService() when there is service error. It has code available which makes it easier to retry. Now this code is not available when migrated to sdk V3 @aws-sdk/client-lex-model-building-service

### SDK version number

@aws-sdk/client-lex-model-building-service

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.18

### Reproduction Steps

The error code got removed in sdk v3 of lex modelnig service LexModelBuildingService() and also the http status code has changed from 400 to 429

### Observed Behavior

Example of error in SDK V2 where you can access code but this is not available in SDK V3. Also, SDK V3 throws 429 instead of 400

````
2023-11-09T20:13:19.803Z	7d97b634-87ea-4038-9fa1-b987ff2d3d26	INFO	the error ResourceInUseException: null
    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:80:27)
    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'ResourceInUseException',
  '[exampleReference]': 'See error.exampleReference for details.',
  '[referenceType]': 'See error.referenceType for details.',
  time: 2023-11-09T20:13:19.803Z,
  requestId: 'cadf366d-542c-4e69-ac54-29d66c3d6b67',
  statusCode: 400,
  retryable: false,
  retryDelay: 75.16600089709434
}
````

### Expected Behavior

The error code and status should be same for the service. These changes required us to change code and error handling again.

**Comment by RanVaknin** [comment]
Hi @abhirpat ,

Can you please show the entire stack trace in v3, in addition to the reproduction code needed to raise this error?

Thanks,
Ran~
