### ISSUE TITLE
@aws-sdk/sqs-client DeleteMessageCommand undocumented & undefined required parameter 'MessageHandle'.

### ISSUE THREAD

**Issue by OffBy0x01** [aws/aws-sdk-js-v3#5478]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am using a FIFO SQS queue with Lambda. My function accepts a message via the event, processes it, and on success attempts to delete it. So far I have not been able to delete any messages.

I've been battling this issue for the last hour - it seems there is a hidden/undefined required param in `DeleteMessageCommand` - `MessageHandle`. I could find no reference to this param in the SQS docs, nor this repo, and yet when I try to run:

```js
import { SQSClient, SendMessageCommand, DeleteMessageCommand } from "@aws-sdk/client-sqs"
...
const proxyAgent = new httpsProxyAgent( process.env.https_proxy )

const sqsClient =  new SQSClient({
  region: process.env.AWS_REGION,
  requestHandler: new NodeHttpHandler({
  httpAgent: proxyAgent,
  httpsAgent: proxyAgent,
})

// where record is event.Record.at(i)
const input = {
    QueueUrl: process.env.AWS_SQS_QUEUE_URL,
    ReceiptHandle: record.receiptHandle,
  }
  
const command = new DeleteMessageCommand(input)

await sqsClient.send(command)
```

Send message works without any issues, however, delete message always fails with the below error:

```json
{
    "errorType": "MissingParameter",
    "errorMessage": "The request must contain the parameter MessageHandle.",
    "name": "MissingParameter",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "--snip--",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "__type": "com.amazon.coral.service#MissingRequiredParameterException",
    "message": "The request must contain the parameter MessageHandle.",
    "Code": "MissingParameter",
    "Type": "Sender",
    "stack": [
        "MissingParameter: The request must contain the parameter MessageHandle.",
        "    at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39",
        "    at de_DeleteMessageCommandError (/var/task/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:466:20)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
        "    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
        "    at async Runtime.main [as handler] (/var/task/services/lambda.js:3280:5)"
    ]
}
```

### SDK version number

@aws-sdk/sqs-client@3.441.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.16.0

### Reproduction Steps

```js
import { SQSClient, SendMessageCommand, DeleteMessageCommand } from "@aws-sdk/client-sqs"
...
const proxyAgent = new httpsProxyAgent( process.env.https_proxy )

const sqsClient =  new SQSClient({
  region: process.env.AWS_REGION,
  requestHandler: new NodeHttpHandler({
  httpAgent: proxyAgent,
  httpsAgent: proxyAgent,
})

// where record is event.Record.at(i)
const input = {
    QueueUrl: process.env.AWS_SQS_QUEUE_URL,
    ReceiptHandle: record.receiptHandle,
  }
  
const command = new DeleteMessageCommand(input)

await sqsClient.send(command)
```

### Observed Behavior

```json
{
    "errorType": "MissingParameter",
    "errorMessage": "The request must contain the parameter MessageHandle.",
    "name": "MissingParameter",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "--snip--",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "__type": "com.amazon.coral.service#MissingRequiredParameterException",
    "message": "The request must contain the parameter MessageHandle.",
    "Code": "MissingParameter",
    "Type": "Sender",
    "stack": [
        "MissingParameter: The request must contain the parameter MessageHandle.",
        "    at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39",
        "    at de_DeleteMessageCommandError (/var/task/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:466:20)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
        "    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
        "    at async Runtime.main [as handler] (/var/task/services/lambda.js:3280:5)"
    ]
}
```

### Expected Behavior

The target message is deleted.

**Comment by RanVaknin** [comment]
Hi @OffBy0x01 ,

Thanks for opening this issue. I have inspected both the SQS docs the SQS model files and nowhere a `MessageHandle` is mentioned. I think this must an old server side validation exception mentioning `MessageHandle` but actually meaning `receiptHandle` 

What Im guessing is happening is that `// where record is event.Record.at(i)` is null because passing a null value to receiptHandle produces the same error:

```js
const input = {
    QueueUrl: "https://sqs.us-east-1.amazonaws.com/REDACTED/test-queue",
    ReceiptHandle: null,
}
  
try {
    const response = await sqsClient.send(new DeleteMessageCommand(input))
    console.log(response)
} catch (error) {
    console.log(error)
}
await sqsClient.send(command)

/*
MissingParameter: The request must contain the parameter MessageHandle.
    at throwDefaultError (/Users/rvaknin/test_folder/5478/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /Users/rvaknin/test_folder/5478/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_DeleteMessageCommandError (/Users/rvaknin/test_folder/5478/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_json1_0.js:466:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/rvaknin/test_folder/5478/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/rvaknin/test_folder/5478/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/rvaknin/test_folder/5478/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/rvaknin/test_folder/5478/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async file:///Users/rvaknin/test_folder/5478/sample.mjs:15:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazon.coral.service#MissingRequiredParameterException',
  Code: 'MissingParameter',
  Type: 'Sender'
}
*/
```

However passing the receiptHandle directly results in successful deletion:

```js
const input = {
    QueueUrl: "https://sqs.us-east-1.amazonaws.com/REDACTED/test-queue",
    ReceiptHandle: "AQEBArA9LFcdN/7ypw7tBd7SqN6mMSYPqvAxPEPYBEzuSq0BSjnf1glMULdtDrkl2U8JVUT74MycD9gAZvADfX9BOciHGBBUVz6241bW4k+erOBS3vt8p6GsW4ZBb+L/F9mABb30MUq6iYLtwkE3ojXbpzDtEYJXCv///nqu4M7Tmtjyg31eqeRxbfJueWV48nF6BG0Z5t3v4wZAmUOxOoaBhi7u5ymuB9AQCwsel9POptoeVV6r8xAkK+wd0K7bjUV9HSniK75l81kj/gnH1H/6oULpsWAwUpD7IM1spN5HwJUl/yMWK+dJKgcctDp2vBLZK51qfvJEGxdlG4M2PIqn61jU+es+c0zg5Pdee/REDACTED",
}
  
try {
    const response = await sqsClient.send(new DeleteMessageCommand(input))
    console.log(response)
} catch (error) {
    console.log(error)
}
await sqsClient.send(command)

/*
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
*/
```

My suggestion to you is to see how receiptHandle is being piped down to the deleteMessageCommand. 

You can also create a middleware hook to inspect the outgoing request:

```js
// more code...

const sqsClient =  new SQSClient({
  region: "us-east-1",
})

sqsClient.middlewareStack.add(next => args => {
    console.log('before sign: ' , args.request);
    return next(args);
}, {step: 'build'})

// more code...
```

My guess is that you are going to see the value being null or undefined. Let me know how this goes.

Thanks,
Ran~

**Comment by OffBy0x01** [comment]
Hi Ran, thanks for the detailed response! You were correct - I've ported what I had over to typescript and in doing so realized I had used `RecieptHandle: record.receiptHandle`  in one case and `ReceiptHandle: record.ReceiptHandle` in another. 

Misleading error message but hopefully this issue serves as a good starting place for anyone else that runs into it!
