### ISSUE TITLE
The XML Parser throws an error with empty map objects that aren't flattened

### ISSUE THREAD

**Issue by GrahamFord** [aws/aws-sdk-js-v3#551]
**Describe the bug**
Xml Parser doesn't check for the existence of the `entry` key when trying to parse an unflattened map object.

The problem came to light when executing the `SimulatePrincipalPolicyCommand` in the IAM package.

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js?**
Node

**Details of the browser/Node.js version**
v12.12.0

**To Reproduce (observed behavior)**
Call the IAMClient with the `SimulatePrincipalPolicyCommand` in a similar way to this.
```javascript
  const iam = new IAMClient({
    credentials: {
      accessKeyId: 'accessKey',
      secretAccessKey: 'secret'
    };
    endpoint: "https://iam.amazonaws.com",
    region: 'us-east-1'
  });
  const simulatePrincipalPolicyCommand = new SimulatePrincipalPolicyCommand({
    PolicySourceArn: 'arn:aws:iam::1234567890:user/test',
    ActionNames: ['cloudformation:DescribeStacks'],
    ResourceArns: ['*'],
  });

  const result = await iam.send(simulatePrincipalPolicyCommand);
  console.log(result);
```

This error will be thrown when the code tries to parse the property `EvalDecisionDetails`
```
    TypeError: Cannot read property 'entry' of undefined

      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parseMap (node_modules/@aws-sdk/xml-body-parser/src/index.ts:164:28)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.unmarshall (node_modules/@aws-sdk/xml-body-parser/src/index.ts:81:19)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parseStructure (node_modules/@aws-sdk/xml-body-parser/src/index.ts:122:30)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.unmarshall (node_modules/@aws-sdk/xml-body-parser/src/index.ts:77:19)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parseList (node_modules/@aws-sdk/xml-body-parser/src/index.ts:155:22)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.unmarshall (node_modules/@aws-sdk/xml-body-parser/src/index.ts:79:19)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parseStructure (node_modules/@aws-sdk/xml-body-parser/src/index.ts:122:30)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.unmarshall (node_modules/@aws-sdk/xml-body-parser/src/index.ts:77:19)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parseStructure (node_modules/@aws-sdk/xml-body-parser/src/index.ts:122:30)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.unmarshall (node_modules/@aws-sdk/xml-body-parser/src/index.ts:77:19)
      at XmlBodyParser.Object.<anonymous>.XmlBodyParser.parse (node_modules/@aws-sdk/xml-body-parser/src/index.ts:50:33)
      at node_modules/@aws-sdk/protocol-query/src/QueryParser.ts:36:32
```

**Expected behavior**
The response should be similar to this:
```javascript
      {
        EvaluationResults: [
          {
            EvalActionName: 'cloudformation:DescribeStacks',
            EvalResourceName: '*',
            EvalDecision: 'implicitDeny',
            MatchedStatements: [],
            MissingContextValues: [Array],
            OrganizationsDecisionDetail: [Object],
            EvalDecisionDetails: {},
            ResourceSpecificResults: []
          }
        ],
        IsTruncated: false,
        Marker: undefined,
        '$metadata': {
          httpHeaders: {
            'x-amzn-requestid': '3ae7ebe7-16d3-488b-93c3-295512c3',
            'content-type': 'text/xml',
            'content-length': '853',
            date: 'Thu, 12 Dec 2019 11:00:44 GMT'
          },
          httpStatusCode: 200,
          requestId: '3ae7ebe7-16d3-488b-93c3-295512c3',
          extendedRequestId: undefined,
          cfId: undefined,
          retries: 0,
          totalRetryDelay: 0
        }
      }
```

**Additional context**
A potential fix could be to check that a map object isn't empty before trying to parse it, eg

https://github.com/aws/aws-sdk-js-v3/blob/master/packages/xml-body-parser/src/index.ts#L163
``` javascript
private parseMap(shape: Map, xmlObj: any): ObjectType {
    let obj: ObjectType = {},
      mapEntryList = xmlObj;
    if (xmlObj && !shape.flattened) {
      mapEntryList = xmlObj["entry"];
    }
    if (!mapEntryList || Object.keys(mapEntryList).length === 0) {
      return {};
    }
```

**Comment by AllanFly120** [comment]
Thank your bringing this up! I'm closing this issue because we recently moved to alpha clients. See [here](https://github.com/aws/aws-sdk-js-v3/issues/944) for more information. Please post a new issue if the bug persists.
