### ISSUE TITLE
Error: Named export 'CreateEncoderConfigurationCommand' not found when using "@aws-sdk/client-ivs-realtime" in Lambda

### ISSUE THREAD

**Issue by pkandathil** [aws/aws-sdk-js-v3#5550]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am trying to write a Lambda Function to create a SSC on IVS Stage Update event. The first step is creating an Encored Configuration and it's failing there.

```
import { IVSRealTimeClient, CreateEncoderConfigurationCommand } from "@aws-sdk/client-ivs-realtime";

export const handler = async (event, context) => {
    console.log({client: IVSRealTimeClient})
    if(event["detail-type"] !== 'IVS Stage Update' 
        || event.detail.event_name !== 'Participant Published') {
        return 
    }
    console.log({event});
    return;
}
```

When I run the Lamda with this code it fails with error:
```
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Named export 'CreateEncoderConfigurationCommand' not found. The requested module '@aws-sdk/client-ivs-realtime' is a CommonJS module, which may not support all module.exports as named exports.\nCommonJS modules can always be imported via the default export, for example using:\n\nimport pkg from '@aws-sdk/client-ivs-realtime';\nconst { IVSRealTimeClient, CreateEncoderConfigurationCommand  } = pkg;\n",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Named export 'CreateEncoderConfigurationCommand' not found. The requested module '@aws-sdk/client-ivs-realtime' is a CommonJS module, which may not support all module.exports as named exports.",
    "CommonJS modules can always be imported via the default export, for example using:",
    "",
    "import pkg from '@aws-sdk/client-ivs-realtime';",
    "const { IVSRealTimeClient, CreateEncoderConfigurationCommand  } = pkg;",
    "",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}
```

Runtime:
Node.js 20.x

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

20.x

### Reproduction Steps

Create a Lambda function in the us-west-2 region.
Copy and Paste the above code.
Click Test.

### Observed Behavior

When I run the Lamda with this code it fails with error:
```
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Named export 'CreateEncoderConfigurationCommand' not found. The requested module '@aws-sdk/client-ivs-realtime' is a CommonJS module, which may not support all module.exports as named exports.\nCommonJS modules can always be imported via the default export, for example using:\n\nimport pkg from '@aws-sdk/client-ivs-realtime';\nconst { IVSRealTimeClient, CreateEncoderConfigurationCommand  } = pkg;\n",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Named export 'CreateEncoderConfigurationCommand' not found. The requested module '@aws-sdk/client-ivs-realtime' is a CommonJS module, which may not support all module.exports as named exports.",
    "CommonJS modules can always be imported via the default export, for example using:",
    "",
    "import pkg from '@aws-sdk/client-ivs-realtime';",
    "const { IVSRealTimeClient, CreateEncoderConfigurationCommand  } = pkg;",
    "",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}
```

### Expected Behavior

It should find the `CreateEncoderConfigurationCommand` in the npm package.

### Possible Solution

The latest version of the realtime-client-sdk is not being loaded by lambda may be?

**Comment by pkandathil** [comment]
This code:
```
import * as RealTimeCleint from "@aws-sdk/client-ivs-realtime";


export const handler = async (event, context) => {
    console.log({client: RealTimeCleint})
}
```

Generates this Output:
```
PUBLISH_STOPPED: 'PUBLISH_STOPPED',
      SUBSCRIBE_ERROR: 'SUBSCRIBE_ERROR',
      SUBSCRIBE_STARTED: 'SUBSCRIBE_STARTED',
      SUBSCRIBE_STOPPED: 'SUBSCRIBE_STOPPED'
    },
    GetParticipantCommand: [class GetParticipantCommand extends Command],
    GetStageCommand: [class GetStageCommand extends Command],
    GetStageSessionCommand: [class GetStageSessionCommand extends Command],
    IVSRealTime: [class IVSRealTime extends IVSRealTimeClient],
    IVSRealTimeClient: [class IVSRealTimeClient extends Client],
    IVSRealTimeServiceException: [class IVSRealTimeServiceException extends ServiceException],
    InternalServerException: [class InternalServerException extends IVSRealTimeServiceException],
    ListParticipantEventsCommand: [class ListParticipantEventsCommand extends Command],
    ListParticipantsCommand: [class ListParticipantsCommand extends Command],
    ListStageSessionsCommand: [class ListStageSessionsCommand extends Command],
    ListStagesCommand: [class ListStagesCommand extends Command],
    ListTagsForResourceCommand: [class ListTagsForResourceCommand extends Command],
    ParticipantState: { CONNECTED: 'CONNECTED', DISCONNECTED: 'DISCONNECTED' },
    ParticipantTokenCapability: { PUBLISH: 'PUBLISH', SUBSCRIBE: 'SUBSCRIBE' },
    ParticipantTokenFilterSensitiveLog: [Function: ParticipantTokenFilterSensitiveLog],
    PendingVerification: [class PendingVerification extends IVSRealTimeServiceException],
    ResourceNotFoundException: [class ResourceNotFoundException extends IVSRealTimeServiceException],
    ServiceQuotaExceededException: [class ServiceQuotaExceededException extends IVSRealTimeServiceException],
    TagResourceCommand: [class TagResourceCommand extends Command],
    UntagResourceCommand: [class UntagResourceCommand extends Command],
    UpdateStageCommand: [class UpdateStageCommand extends Command],
    ValidationException: [class ValidationException extends IVSRealTimeServiceException],
    __Client: [class Client],
    __esModule: true,
    default: {
      IVSRealTimeServiceException: [Getter],
      __Client: [Getter],
      IVSRealTimeClient: [Getter],
      IVSRealTime: [Getter],
      '$Command': [Getter],
      CreateParticipantTokenCommand: [Getter],
      CreateStageCommand: [Getter],
      DeleteStageCommand: [Getter],
      DisconnectParticipantCommand: [Getter],
      GetParticipantCommand: [Getter],
      GetStageCommand: [Getter],
      GetStageSessionCommand: [Getter],
      ListParticipantEventsCommand: [Getter],
      ListParticipantsCommand: [Getter],
      ListStageSessionsCommand: [Getter],
      ListStagesCommand: [Getter],
      ListTagsForResourceCommand: [Getter],
      TagResourceCommand: [Getter],
      UntagResourceCommand: [Getter],
      UpdateStageCommand: [Getter],
      paginateListParticipantEvents: [Getter],
      paginateListParticipants: [Getter],
      paginateListStageSessions: [Getter],
      paginateListStages: [Getter],
      AccessDeniedException: [Getter],
      ParticipantTokenCapability: [Getter],
      PendingVerification: [Getter],
      ResourceNotFoundException: [Getter],
      ServiceQuotaExceededException: [Getter],
      ValidationException: [Getter],
      ConflictException: [Getter],
      ParticipantState: [Getter],
      EventErrorCode: [Getter],
      EventName: [Getter],
      InternalServerException: [Getter],
      ParticipantTokenFilterSensitiveLog: [Getter],
      CreateParticipantTokenResponseFilterSensitiveLog: [Getter],
      CreateStageResponseFilterSensitiveLog: [Getter]
    },
    paginateListParticipantEvents: [AsyncGeneratorFunction: paginateListParticipantEvents],
    paginateListParticipants: [AsyncGeneratorFunction: paginateListParticipants],
    paginateListStageSessions: [AsyncGeneratorFunction: paginateListStageSessions],
    paginateListStages: [AsyncGeneratorFunction: paginateListStages]
  }
}```

**Comment by pkandathil** [comment]
Seems like following this tutorial and adding a layer fixed the issue. Ideally we wouldn't have to add a layer. 
https://stackoverflow.com/questions/58703761/does-lambda-layer-include-aws-sdk

**Comment by RanVaknin** [comment]
Hi @pkandathil,

Thanks for reaching out. 

>Seems like following this tutorial and adding a layer fixed the issue. Ideally we wouldn't have to add a layer.

We cover this in [our docs](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#working-with-the-sdk-in-lambda). The SDK provided by lambda is set to a[ specific version](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) (currently 3.362.0). It seems like the operation you are trying to use was introduced in 3.468.0 which is a newer version from the one used by lambda. 

The SDK team cannot control the version of whichever platform vends the SDK, and since Lambda updates their SDK versions every 6-12 months a lot of the times newer features are not available out-of-the-box. 

As you have pointed out, one way to get around it is to provide your own SDK using a Lambda layer, the other way is to bundle your SDK as outlined in our docs. 

Thanks,
Ran~
