### ISSUE TITLE
Use the SDK to send Raw Email with SES, issue when Base64 Encoding

### ISSUE THREAD

**Issue by juliendogny** [aws/aws-sdk-js-v3#5624]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello,
I've upgraded a NodeJS 16 lambda function to NodeJS 20. The lambda function uses SES to send Raw Email.
The AWS SDK embedded in the Lambda function fails when encoding in base64 the raw string.

TypeError: Cannot read properties of undefined (reading 'byteLength')
      at fromArrayBuffer (/var/runtime/node_modules/@aws-sdk/util-buffer-from/dist-cjs/index.js:6:60)
      at Object.toBase64 [as base64Encoder] (/var/runtime/node_modules/@aws-sdk/util-base64/dist-cjs/toBase64.js:5:68)
      at se_RawMessage (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:4267:35)
      at se_SendRawEmailRequest (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:4661:31)
      at se_SendRawEmailCommand (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:546:12)
      at serialize (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/commands/SendRawEmailCommand.js:40:55)
      at /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27
      at /var/runtime/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:20:16

I've check the type in the RawMessage.Data and it is set and a String (not a byteArray or stream).

SendRawEmailCommand({
        Destinations: data.recipients,
        Source: data.originalRecipient,
        RawMessage: {
            Data: data.emailData
        }
    });

Also tried in NodeJS 18 and same result :'(

Thanks,
Julien

### SDK version number

@aws-sdk/ses 3.362.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Lambda function NodeJS 20.x

### Reproduction Steps

var sesClient = new SESClient({});
var sendCommand = new SendRawEmailCommand({
        Destinations: recipients,
        Source: source,
        RawMessage: {
            Data: content
        }
    });
var result = await sesClient.send(sendCommand);

### Observed Behavior

When encoding to base64, an error is raised.

TypeError: Cannot read properties of undefined (reading 'byteLength')
      at fromArrayBuffer (/var/runtime/node_modules/@aws-sdk/util-buffer-from/dist-cjs/index.js:6:60)
      at Object.toBase64 [as base64Encoder] (/var/runtime/node_modules/@aws-sdk/util-base64/dist-cjs/toBase64.js:5:68)
      at se_RawMessage (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:4267:35)
      at se_SendRawEmailRequest (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:4661:31)
      at se_SendRawEmailCommand (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:546:12)
      at serialize (/var/runtime/node_modules/@aws-sdk/client-ses/dist-cjs/commands/SendRawEmailCommand.js:40:55)
      at /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:12:27
      at /var/runtime/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:20:16

### Expected Behavior

Correct call of the API and a sent email

**Comment by juliendogny** [comment]
https://stackoverflow.com/questions/74877090/forward-raw-mail-from-s3-to-ses-via-lambda
