### ISSUE TITLE
AccessDeniedException: You don't have permissions to access this resource. On V3 SDK.

### ISSUE THREAD

**Issue by osgioia** [aws/aws-sdk-js-v3#5645]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In the dependency @aws-sdk/client-organizations the creation of OrganizationClient instance doesn't apply credentials on v3 SDK. 
Any method response "AccessDeniedException: You don't have permission to access this resource." and the role assumed has permission because it works on the v2 SDK.

### SDK version number

@aws-sdk/client-organizations@3.470.0, @aws-sdk/client-sts@3.470.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v17.9.1

### Reproduction Steps

The following code works well, 
This is an implementation in the v2:
```js
const AWS = require("aws-sdk");

(async () => {
    const primaryAccountRole = `arn:aws:iam::999999999999:role/LimitedRole`;
    AWS.config.update({ region: 'us-east-1' });
    const sts = new AWS.STS();

    const data = await sts
      .assumeRole({
        RoleArn: primaryAccountRole,
        RoleSessionName: "Test",
        ExternalId: "aaaaaa-bbbb-cccc-dddd-eeeeeeeee",
      })
      .promise();

    const credentials = {
      accessKeyId: data.Credentials.AccessKeyId,
      secretAccessKey: data.Credentials.SecretAccessKey,
      sessionToken: data.Credentials.SessionToken,
    };

    AWS.config.update({ region: 'us-east-1' });
    const org = new AWS.Organizations({ apiVersion: '2016-11-28', ...credentials });

    const units = (await org.listOrganizationalUnitsForParent({
      ParentId: "r-aa1a"
    }).promise()).OrganizationalUnits;
 

      console.log(units)
  })();


```
The implementation in v3, assume role well, but when try to run listOrganizationalUnitsForParent statement occurs the error:

```js
const{ STSClient, AssumeRoleCommand } = require("@aws-sdk/client-sts");
const { Organizations } = require("@aws-sdk/client-organizations");

(async () => {
    
    const primaryAccountRole = `arn:aws:iam::999999999999:role/LimitedRole`;
    let stsClient = new STSClient({ region: 'us-east-1' });
    var stsParams = {
        RoleArn: primaryAccountRole,
        RoleSessionName: "Test",
        ExternalId: "aaaaaa-bbbb-cccc-dddd-eeeeeeeee"
    };
    let stsCommand = new AssumeRoleCommand(stsParams);
    const stsResp = await stsClient.send(stsCommand);


    console.log(stsResp.Credentials)

    const getOrgUnits =  async (credentials, parentId, client) => {
      try {
        const organizationsClient =
            new Organizations({
            region: 'us-east-1',
            apiVersion: '2016-11-28',
            ...credentials,
          });
    
        const input = {
          ParentId: parentId,
        };
    
        
        const data = await organizationsClient.listOrganizationalUnitsForParent(
            input
          );
      
   
        return data.OrganizationalUnits;
      } catch (error) {
        console.error(error);
    
        throw error;
      }
    };


    let orgUnitsList = await getOrgUnits(
        stsResp.Credentials,
        "r-aa1a"
      );



      console.log(orgUnitsList)
  })();


```

### Observed Behavior

```
{
  AccessKeyId: 'ASIAUAAAAAAAAAAAA',
  SecretAccessKey: 'tfnrsLSkQAAAAAAAAAAAAAA',
  SessionToken: 'IQoJb3JpZ2luX2VjEOz//////////AAAAAAAAAAAAA=',
  Expiration: 2024-01-05T05:03:47.000Z
}
AccessDeniedException: You don't have permissions to access this resource.
    at de_AccessDeniedExceptionRes (/home/oz/Documents/node_modules/@aws-sdk/client-organizations/dist-cjs/protocols/Aws_json1_1.js:3324:23)
    at de_ListOrganizationalUnitsForParentCommandError (/home/oz/Documents/node_modules/@aws-sdk/client-organizations/dist-cjs/protocols/Aws_json1_1.js:2564:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/oz/Documents/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/oz/Documents/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /home/oz/Documents/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
    at async /home/oz/Documents/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async getOrgUnits (/home/oz/Documents/test_v3.js:33:22)
    at async /home/oz/Documents/test_v3.js:47:24 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'fdf30ef9-fe7b-47ae-9624-b51b12c68136',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'AccessDeniedException'
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AccessDeniedException: You don't have permissions to access this resource.
    at de_AccessDeniedExceptionRes (/home/oz/Documents/node_modules/@aws-sdk/client-organizations/dist-cjs/protocols/Aws_json1_1.js:3324:23)
    at de_ListOrganizationalUnitsForParentCommandError (/home/oz/Documents/node_modules/@aws-sdk/client-organizations/dist-cjs/protocols/Aws_json1_1.js:2564:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/oz/Documents/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/oz/Documents/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /home/oz/Documents/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
    at async /home/oz/Documents/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async getOrgUnits (/home/oz/Documents/test_v3.js:33:22)
    at async /home/oz/Documents/test_v3.js:47:24 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'fdf30ef9-fe7b-47ae-9624-b51b12c68136',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'AccessDeniedException'
}

Node.js v17.9.1
```

### Expected Behavior

The same response as V2 of aws-sdk dependency.

### Possible Solution

Using the same implementation of credentials as v2 SDK.

**Comment by osgioia** [comment]
Thank you, this was very helpful! As additional comment depend on the modules it's necessary to hard-code the region as a parameter.
