### ISSUE TITLE
Running Example Usage code for ListBucketsCommand results in an error

### ISSUE THREAD

**Issue by metadaddy** [aws/aws-sdk-js-v3#5700]
### Describe the issue

Running the code shown in "Example Usage" for `ListBucketsCommand` results in an error:

```
% node app.js
Error TypeError: Cannot read properties of undefined (reading 'Bucket')
    at /Users/ppatterson/src/test-aws-js-v3-import/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:448:16
    at /Users/ppatterson/src/test-aws-js-v3-import/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:28
    at _S3Client.send (/Users/ppatterson/src/test-aws-js-v3-import/node_modules/@smithy/smithy-client/dist-cjs/index.js:122:14)
    at /Users/ppatterson/src/test-aws-js-v3-import/app.js:10:31
    at Object.<anonymous> (/Users/ppatterson/src/test-aws-js-v3-import/app.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
```

You have to pass an empty object to the `ListBucketsCommand` constructor, since `middleware-sdk-s3` assumes that you've passed an object and tries to validate its `Bucket` property as a bucket name. This is a bit pointless, since the [ListBuckets API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html) doesn't use a bucket parameter.

The "Example Usage" code should match the "Example Syntax" earlier on the page. The following code runs without an error:

```
// The following example returns all the buckets owned by the sender of this request.
const input = {};
const command = new ListBucketsCommand(input);
const response = await client.send(command);
```

One could argue that the bug is in the SDK, and that you should be able to call `ListBucketsCommand()` with no arguments, but I'm guessing fixing the doc to match the implementation is the path of lesser resistance.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/ListBucketsCommand/

**Comment by RanVaknin** [comment]
Hi @metadaddy ,

Thanks for reporting this. Adding to the backlog.

All the best,
Ran~

**Comment by kuhe** [comment]
expected to be deployed to documentation site within a day
