### ISSUE TITLE
No matching version found for @smithy/abort-controller@^2.1.1

### ISSUE THREAD

**Issue by defields923** [aws/aws-sdk-js-v3#5732]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I suddenly began to get this issue while installing dependences. This is within a repo that has had these dependencies for months now and worked fine.

4779 verbose stack @smithy/abort-controller: No matching version found for @smithy/abort-controller@^2.1.1.
4779 verbose stack     at module.exports (/Users/.../.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
4779 verbose stack     at RegistryFetcher.manifest (/Users/.../.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
4780 verbose cwd /Users/.../workspaces/artillery-tester
4781 verbose Darwin 23.1.0
4782 verbose node v19.8.1
4783 verbose npm  v9.5.1
4784 error code ETARGET
4785 error notarget No matching version found for @smithy/abort-controller@^2.1.1.
4786 error notarget In most cases you or one of your dependencies are requesting
4786 error notarget a package version that doesn't exist.

We are installing the following aws-sdk v3 packages:

"@aws-sdk/client-apigatewaymanagementapi": "3.465.0",
  "@aws-sdk/client-cloudwatch-events": "^3.485.0",
  "@aws-sdk/client-codedeploy": "3.465.0",
  "@aws-sdk/client-cognito-identity-provider": "^3.485.0",
  "@aws-sdk/client-eventbridge": "3.465.0",
  "@aws-sdk/client-iot": "3.465.0",
  "@aws-sdk/client-iot-data-plane": "3.465.0",
  "@aws-sdk/client-kinesis": "3.465.0",
  "@aws-sdk/client-kms": "3.465.0",
  "@aws-sdk/client-lambda": "3.465.0",
  "@aws-sdk/client-pinpoint": "3.465.0",
  "@aws-sdk/client-s3": "3.465.0",
  "@aws-sdk/client-secrets-manager": "3.465.0",
  "@aws-sdk/client-sesv2": "3.465.0",
  "@aws-sdk/client-sfn": "3.465.0",
  "@aws-sdk/client-sns": "3.465.0",
  "@aws-sdk/client-sqs": "3.465.0",
  "@aws-sdk/client-ssm": "3.465.0",
  "@aws-sdk/lib-storage": "3.465.0",
  "@aws-sdk/s3-request-presigner": "3.465.0",
  "@aws-sdk/signature-v4-crt": "3.465.0",
  "@aws-sdk/util-stream-node": "3.374.0",

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v19.8.1

### Reproduction Steps

N/A

### Observed Behavior

4779 verbose stack @smithy/abort-controller: No matching version found for @smithy/abort-controller@^2.1.1.
4779 verbose stack     at module.exports (/Users/.../.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
4779 verbose stack     at RegistryFetcher.manifest (/Users/.../.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
4780 verbose cwd /Users/.../workspaces/artillery-tester
4781 verbose Darwin 23.1.0
4782 verbose node v19.8.1
4783 verbose npm  v9.5.1
4784 error code ETARGET
4785 error notarget No matching version found for @smithy/abort-controller@^2.1.1.
4786 error notarget In most cases you or one of your dependencies are requesting
4786 error notarget a package version that doesn't exist.

### Expected Behavior

The aws-sdk v3 packages should install without dependency version issues.

### Additional Information/Context

I have already tried `npm cache clean --force`, deleting node_modules, but no help. There is no package-lock in this repository.

I have reduced the packages down, removed all the aws-sdk packages and was still experiencing the issue. I noticed that 'artillery' has credentials-provider as a sub-dependency. Installing credentials-provider alone also causes the issue.

**Comment by defields923** [comment]
Closing the issue as it seems to be the fault of a private npm registry.
