### ISSUE TITLE
Module Not Found Error with GetApiKeyCommand 

### ISSUE THREAD

**Issue by sawilde** [aws/aws-sdk-js-v3#5768]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Trying to upgrade to AWS-SDK beyond 496 starts to throw this error when the lambda is 'triggered'

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '../../191/lambda.js'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/lambda.js",
        "/var/runtime/index.mjs"
    ],
    "stack": [
        "Error: Cannot find module '../../191/lambda.js'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/index.mjs",
        "    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)",
        "    at Module._load (node:internal/modules/cjs/loader:985:27)",
        "    at Module.require (node:internal/modules/cjs/loader:1235:19)",
        "    at require (node:internal/modules/helpers:176:18)",
        "    at key (/var/task/webpack/runtime/require chunk loading:29:17)",
        "    at <anonymous> (/var/task/webpack/runtime/ensure chunk:6:25)",
        "    at Array.reduce (<anonymous>)",
        "    at chunkId (/var/task/webpack/runtime/ensure chunk:5:56)",
        "    at async (/var/task/node_modules/@aws-sdk/credential-provider-node/dist-es/defaultProvider.js:9:39)",
        "    at async (/var/task/node_modules/@smithy/property-provider/dist-es/chain.js:9:39)"
    ]
}
```

using the following AWS packages

```
    "@aws-sdk/client-api-gateway": "3.507.0",
    "@aws-sdk/client-dynamodb": "3.507.0",
    "@aws-sdk/client-sns": "3.507.0",
    "@aws-sdk/lib-dynamodb": "3.507.0",
```

When I revert to these packages, everything works again

```
    "@aws-sdk/client-api-gateway": "3.496.0",
    "@aws-sdk/client-dynamodb": "3.496.0",
    "@aws-sdk/client-sns": "3.496.0",
    "@aws-sdk/lib-dynamodb": "3.496.0",
```

I use webpack/esbuild to build the lambda (original typescript) and the package < 200kb

<img width="1384" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/297165/7c77aa99-b24d-4eb9-803d-486887995382">

I don't understand where the `.../191/` in the path has come from in the stack trace

### SDK version number

@aws-sdk/package-name@3.507.0, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 20.x (lambda)

### Reproduction Steps

Use the following packages

```
    "@aws-sdk/client-api-gateway": "3.507.0",
    "@aws-sdk/client-dynamodb": "3.507.0",
    "@aws-sdk/client-sns": "3.507.0",
    "@aws-sdk/lib-dynamodb": "3.507.0",
```

and something like this lambda (authorizer) - nothing special (I don't think it is getting this far)

```
import {
  APIGatewayClient,
  GetApiKeyCommand,
} from '@aws-sdk/client-api-gateway';
import {
  APIGatewayRequestAuthorizerHandler,
} from 'aws-lambda';
import { getHeader } from '../../lib/common';

export const handler: APIGatewayRequestAuthorizerHandler = async (
  event,
  _context,
) => {
  const { TARGET_REGION } =
    process.env;

  const client = new APIGatewayClient({ region: TARGET_REGION });
  const command = new GetApiKeyCommand({
    apiKey: AUTH_KEY_NAME ?? '',
    includeValue: true,
  });

  const key = await client.send(command);

  const authorization = getHeader('Authorization', event.headers);
  const jwt = authorization?.replace('Bearer ', '').trim() ?? '';

  const payload = true; // removed the payload validation

  const effect = payload ? 'Allow' : 'Deny';

  const policy = {
    principalId: authorization ?? '',
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: effect,
          Resource: event.methodArn,
        },
      ],
    },
    context: undefined,
    usageIdentifierKey: key.value,
  };

  return policy;
};
```

### Observed Behavior

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '../../191/lambda.js'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/lambda.js",
        "/var/runtime/index.mjs"
    ],
    "stack": [
        "Error: Cannot find module '../../191/lambda.js'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/index.mjs",
        "    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)",
        "    at Module._load (node:internal/modules/cjs/loader:985:27)",
        "    at Module.require (node:internal/modules/cjs/loader:1235:19)",
        "    at require (node:internal/modules/helpers:176:18)",
        "    at key (/var/task/webpack/runtime/require chunk loading:29:17)",
        "    at <anonymous> (/var/task/webpack/runtime/ensure chunk:6:25)",
        "    at Array.reduce (<anonymous>)",
        "    at chunkId (/var/task/webpack/runtime/ensure chunk:5:56)",
        "    at async (/var/task/node_modules/@aws-sdk/credential-provider-node/dist-es/defaultProvider.js:9:39)",
        "    at async (/var/task/node_modules/@smithy/property-provider/dist-es/chain.js:9:39)"
    ]
}
```

### Expected Behavior

not do that ^

**Comment by kuhe** [comment]
The use of numbered folders is usually a result of splitting by webpack https://webpack.js.org/guides/code-splitting/ as a reaction to dynamic imports, which were introduced to the AWS SDK recently. When you generate a bundle, ensure that all files within the output folder are uploaded to the Lambda function.

**Comment by sawilde** [comment]
Thanks, everything in the folder pointed to by CodeUri (SAM) is being uploaded and I can't find any folder names `191`, looks like I'll need to investigate what webpack is doing.

> as a reaction to dynamic imports, which were introduced to the AWS SDK recently.

Do you have more details on any announcements around this change?

**Comment by sawilde** [comment]
Thanks, I managed to stop webpack doing the codes plotting.
