### ISSUE TITLE
AWS SDK error wrapper for Error: connect ECONNREFUSED ::1:9229 while connecting to DynamoDB Local

### ISSUE THREAD

**Issue by pjoshi-cs** [aws/aws-sdk-js-v3#5804]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am running DynamoDB Local on my machine:
```
java -Djava.library.path=./dynamodb_local_latest/DynamoDBLocal_lib -jar ./dynamodb_local_latest/DynamoDBLocal.jar -sharedDb -inMemory 
Initializing DynamoDB Local with the following configuration:
Port:   8000
InMemory:       true
Version:        2.2.1
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     null
```
I have DynamoDBClient setup as follow:
```
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';

const isTest = process.env.NODE_ENV === 'test';

const DynamoClient = new DynamoDBClient({
  region: isTest ? 'local' : process.env.AWS_REGION,
  ...(isTest && {
    endpoint: 'http://localhost:8000',
    sslEnabled: false,
  }),
});

export default DynamoClient;
```

while running jest test this used to work until now. Now I am getting error:
```
AWS SDK error wrapper for Error: connect ECONNREFUSED ::1:9229

      at asSdkError (node_modules/@smithy/middleware-retry/dist-cjs/util.js:11:12)
      at node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:39:51
      at /node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

### SDK version number

@aws-sdk/client-dynamodb@^3.347.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.1

### Reproduction Steps

setup dynamo db local
create dynamodb client with endpoint localhost:8000

### Observed Behavior

while running jest test this used to work until now. Now I am getting error:
```
AWS SDK error wrapper for Error: connect ECONNREFUSED ::1:9229

      at asSdkError (node_modules/@smithy/middleware-retry/dist-cjs/util.js:11:12)
      at node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:39:51
      at /node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

### Expected Behavior

Test should run (it used to run)

**Comment by pjoshi-cs** [comment]
Closing this as found the fix for it

**Comment by pjoshi-cs** [comment]
Found the fix
