### ISSUE TITLE
 @aws-sdk/client-iot-data-plane  identity.expiration.getTime

### ISSUE THREAD

**Issue by zhex900** [aws/aws-sdk-js-v3#5890]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

 @aws-sdk/client-iot-data-plane  
after upgrade from ^3.437.0  →  ^3.533.0

I start to get this error
```
"stack":

            TypeError: identity.expiration.getTime is not a function

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:270:154

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:315:9

                at processTicksAndRejections (node:internal/process/task_queues:95:5)

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:82:17

                at /opt/atlassian/pipelines/agent/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22

        "message": "identity.expiration.getTime is not a function"
```

This is how I use it. 

```
    const command = new GetThingShadowCommand({
      thingName,
    });

 const client = new IoTDataPlaneClient({
      endpoint: `https://${process.env.IOT_ENDPOINT}`,
      region: process.env.REGION,
      credentials,
    });

      client.send(command),
```

### SDK version number

 @aws-sdk/client-iot-data-plane  3.533.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.16.0

### Reproduction Steps

```
    const command = new GetThingShadowCommand({
      thingName,
    });

 const client = new IoTDataPlaneClient({
      endpoint: `https://${process.env.IOT_ENDPOINT}`,
      region: process.env.REGION,
      credentials,
    });

      client.send(command),
```

### Observed Behavior

error
```
     TypeError: identity.expiration.getTime is not a function

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:270:154

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:315:9

                at processTicksAndRejections (node:internal/process/task_queues:95:5)

                at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/core/dist-cjs/index.js:82:17

                at /opt/atlassian/pipelines/agent/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22

        "message": "identity.expiration.getTime is not a function"
```

### Expected Behavior

No error

**Comment by kuhe** [comment]
if `credentials.expiration` is set, it must be an instance of the native JavaScript `Date` class.

**Comment by zhex900** [comment]
Thank you!

```
        const url = `https://${process.env.AWS_IOT_CREDENTIALS_ENDPOINT}/role-aliases/${AWS_IOT_CREDENTIALS_ROLE_ALIAS}/credentials`;
        const { data } = await promiseRetry(
          axios.get(url, {
            headers: {
              "x-amzn-iot-thingname": this._deviceId,
            },
            httpsAgent,
          }),
          MAX_RETRY_COUNT,
        );

        this._credentials = {
          ...data?.credentials,
          // this fixed it
          expiration: new Date(data?.credentials?.expiration),
        };
```

**Comment by amaValeriya** [comment]
Thank you, @kuhe for the fix!
