### ISSUE TITLE
DynamoDBDocument transactWrite() errors when the TransactItems object contains Put objects

### ISSUE THREAD

**Issue by jwtrim** [aws/aws-sdk-js-v3#6007]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I am testing AWS Lambdas locally which store data in a DynamoDB table. The table has the following schema definition:
```
{
    "TableName": "test-table-v1-local",
    "KeySchema": [
      { "AttributeName": "PK", "KeyType": "HASH" },
      { "AttributeName": "SK", "KeyType": "RANGE" }
    ],
    "AttributeDefinitions": [
      {
        "AttributeName": "PK",
        "AttributeType": "S"
      },
      {
        "AttributeName": "SK",
        "AttributeType": "S"
      }
    ],
    "ProvisionedThroughput": {
      "ReadCapacityUnits": 10,
      "WriteCapacityUnits": 10
    }
}
```
For the local environment, I am initializing a DynamoDBDocument client in the following way
```
const client = new DynamoDBClient({ endpoint: 'http://host.docker.internal:8000' })
```
When updating the table, I am trying to use the `client.transactWrite()` API with the following input: 
```
{
  TransactItems:  [
    {
      Put: {
        TableName: 'test-table-v1-local',
        Item: {
          PK: { S: 'test' },
          SK: { S: 'test' }
        }
      }
    }
  ]
```
The API throws the following error:
```
ValidationException: Invalid attribute value type
    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2150:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}
```

I've had success using the `client.send(new PutCommand())` and `AWS.DynamoDB({  endpoint: 'http://host.docker.internal:8000' }).transactWriteItems()` with the same item, but would need/prefer the other method to work. 

### SDK version number

@aws-sdk/client-dynamodb@3.556.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.19.1

### Reproduction Steps

Create a DynamoDB table with the provided schema and try to put a new document with the provided `TransactItems` list.

### Observed Behavior

The API throws the following error:
```
ValidationException: Invalid attribute value type
    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2150:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}
```

### Expected Behavior

Document created successfully.

**Comment by RanVaknin** [comment]
Hi @jwtrim ,

When you are using the Document client you are abstracting away the need to define each item with their corresponding Dynamo attribute types and instead you can supply the value directly as native JS types (strings in this case).
Therefore your code should look something like:

```diff
 TransactItems:  [
    {
      Put: {
        TableName: 'test-table-v1-local',
        Item: {
-          PK: { S: 'test' },
-          SK: { S: 'test' }
+         PK: 'test',
+         SK: 'test',
        }
      }
    }
  ]
```

Feel free to revisit our [lib-dynamo docs](https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-dynamodb#marshalling-input-and-unmarshalling-response-data) for further context about this.

Thanks,
Ran~

**Comment by jwtrim** [comment]
@RanVaknin thanks for your response! 

This does appear to fix my issue, but I swear I repeatedly tried that exact approach during my initial testing, yet somehow the exception persisted. 

Anyhow, I can no longer reproduce so I will close this issue. Sorry for the inconvenience.
