### ISSUE TITLE
GetObjectCommand circular reference

### ISSUE THREAD

**Issue by vander99** [aws/aws-sdk-js-v3#6009]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hello, I am trying to download a file from nestjs, send it to angular server using a REST POST endpoint in order to trigger the download of this file. 

But I get this error:
ERROR [ExceptionsHandler] Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
Do you have a solution to this probleme ?

Her is my controller:
@Post('download')
async downloadFile(@Body() body:bodyObject) {
      return await this.s3Client.send(
        new GetObjectCommand({
          Bucket: 'bucket-name',
          Key: file-name,
        }));
}

My nodejs version: v20.10.0
nestjs version: @nestjs/core@8.4.7
aws-sdk/client-s3 version: 3.554.0

### SDK version number

@aws-sdk/client-s3@3.556.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

Download a file from s3 using GetObjectCommand then send it by rest endpoint to a frontend server

@Post('download')
async downloadFile(@Body() body:bodyObject) {
      return await this.s3Client.send(
        new GetObjectCommand({
          Bucket: 'bucket-name',
          Key: file-name,
        }));
}

### Observed Behavior

Error:

ERROR [ExceptionsHandler] Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle

### Expected Behavior

The file to be send, so we can trigger then download in the frontend

**Comment by aBurmeseDev** [comment]
Hi @vander99 - thanks for reaching out. 

i think the error you're seeing is more of NestJS related rather than SDK. From my quick research, this error is occurs when you try to convert an object into JSON but the object contains a circular reference. Here are my [search results](https://www.google.com/search?q=ERROR+%5BExceptionsHandler%5D+Converting+circular+structure+to+JSON&rlz=1C5GCCM_en&oq=ERROR+%5BExceptionsHandler%5D+Converting+circular+structure+to+JSON&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDg4MGowajE1qAIIsAIB&sourceid=chrome&ie=UTF-8).

If you need further assistance, please share a larger code snippet of your file to give me more insight.

Hope it helps,
John

**Comment by vander99** [comment]
Hello, 

The error is related to the fact that the api returns a circular reference, so their is no way we could send the response anywhere by using http request.

The snippet is easy I shared it above, I want only to get the file from s3 and send it via http request so I can download it in my front end.

The question is, how can we get a file from s3 using nestjs and send it to a frontend by using http request knowing that the api returns a circular reference. If no is their a fix comming so the api won't return a circular reference. If no why does the api return a circular reference ?

**Comment by whutchtwo** [comment]
Hi, Any solution on this. I have been fighting this issue for a full day now.

**Comment by robertocerdasilva** [comment]
Same problem here in Node 18.14.1, 20.11.1 or 20.13.1

```
 const command = new GetObjectCommand({ Bucket: AWS_S3_BUCKET, Key: KEY })
 const response = await S3.send(command)
 return response
```

Return: 
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (R:\Proyectos\simple-fibra\api-users\node_modules\express\lib\response.js:1159:12)
    at ServerResponse.json (R:\Proyectos\simple-fibra\api-users\node_modules\express\lib\response.js:272:14)
    at ServerResponse.send (R:\Proyectos\simple-fibra\api-users\node_modules\express\lib\response.js:163:21)
    at bulk (file:///R:/Proyectos/simple-fibra/api-users/src/controllers/user.controller.js:23:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by aBurmeseDev** [comment]
Checking in, were you able to find the root cause from the link I shared? As mentioned, the culprit is most likely in the rest of your code which you haven't shared.
