### ISSUE TITLE
yarn run generate-clients fails with "Could not find software.amazon.smithy:smithy-typescript-codegen:0.1.0"

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#613]
**Describe the bug**
* yarn run generate-clients fails with "Could not find software.amazon.smithy:smithy-typescript-codegen:0.1.0"
* Refs: https://github.com/aws/aws-sdk-js-v3/pull/545

**To Reproduce (observed behavior)**
* Follow steps from https://github.com/aws/aws-sdk-js-v3/pull/545
* Notice that command fails with the following error:
```console
yarn run v1.21.1
$ node ./scripts/generate-clients -m /Users/trivikr/Downloads/model
models directory:  /Users/trivikr/Downloads/model
clearing code gen input folder...
copying models from /Users/trivikr/Downloads/model to /Users/trivikr/workspace/aws-sdk-js-v3/codegen/sdk-codegen/aws-models...
copying model api-gateway.2015-07-09.json...
> Task :sdk-codegen:clean
 UP-TO-DATE
> Task :smithy-aws-typescript-codegen:clean UP-TO-DATE

> Task :smithy-aws-typescript-codegen:compileJava
 FAILED

stderr: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-aws-typescript-codegen:compileJava'.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
3 actionable tasks: 1 executed, 2 up-to-date

stderr: > Could not resolve all files for configuration ':smithy-aws-typescript-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-typescript-codegen:0.1.0.
     Searched in the following locations:
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-typescript-codegen/0.1.0/smithy-typescript-codegen-0.1.0.pom
       - file:/Users/trivikr/.m2/repository/software/amazon/smithy/smithy-typescript-codegen/0.1.0/smithy-typescript-codegen-0.1.0.jar
       - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-typescript-codegen/0.1.0/smithy-typescript-codegen-0.1.0.pom
       - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-typescript-codegen/0.1.0/smithy-typescript-codegen-0.1.0.jar
     Required by:
         project :smithy-aws-typescript-codegen

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

child process exited with code 1
Error: ENOENT: no such file or directory, scandir '/Users/trivikr/workspace/aws-sdk-js-v3/codegen/sdk-codegen/build/smithyprojections/sdk-codegen'
    at readdirSync (fs.js:854:3)
    at copyToClients (/Users/trivikr/workspace/aws-sdk-js-v3/scripts/generate-clients/copy-to-clients.js:41:27)
    at /Users/trivikr/workspace/aws-sdk-js-v3/scripts/generate-clients/index.js:23:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/trivikr/workspace/aws-sdk-js-v3/codegen/sdk-codegen/build/smithyprojections/sdk-codegen'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
the command should be successful, and generate clients

**Comment by trivikr** [comment]
The folder `smithy-typescript-codegen` is not present in `/Users/trivikr/.m2/repository/software/amazon/smithy/`
