### ISSUE TITLE
s3-request-presigner throws EndpointError: Invalid ARN for S3 

### ISSUE THREAD

**Issue by mvuckovic** [aws/aws-sdk-js-v3#6323]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi!

When trying to generate presigned S3 URLs via s3-request-presigner an error is thrown:

```
EndpointError: Invalid ARN: Unrecognized format: arn:aws:s3:::MY_BUCKET_NAME (type: MY_BUCKET_NAME)
at evaluateErrorRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:401:9)
```

IAM policy seems to be correct and I can generate presigned URL via aws cli.

### SDK version number

@aws-sdk/s3-request-presigner@3.620.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

```
import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

const client = new S3Client({
  region: "eu-central-1",
});
const command = new GetObjectCommand({
  Bucket: "MY_BUCKET_NAME"
  Key: "KEY_TO_FILE",
});
const url = await getSignedUrl(client, command, {
  expiresIn: 3600,
});
```

### Observed Behavior

An error was thrown and presigned url was not generated.

```
2024-07-29T15:25:28.778Z
	
EndpointError: Invalid ARN: Unrecognized format: arn:aws:s3:::MY_BUCKET_NAME (type: MY_BUCKET_NAME)
	
2024-07-29T15:25:28.778Z
	
at evaluateErrorRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:401:9)
	
2024-07-29T15:25:28.778Z
	
at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:431:7)
	
2024-07-29T15:25:28.778Z
	
at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:416:10)
	
2024-07-29T15:25:28.778Z
	
at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:433:35)
	
2024-07-29T15:25:28.778Z
	
at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:416:10)
	
2024-07-29T15:25:28.778Z
	
at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:433:35)
	
2024-07-29T15:25:28.778Z
	
at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:416:10)
	
2024-07-29T15:25:28.778Z
	
at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:433:35)
	
2024-07-29T15:25:28.778Z
	
at evaluateTreeRule (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:416:10)
	
2024-07-29T15:25:28.778Z
	
at evaluateRules (/app/node_modules/@smithy/util-endpoints/dist-cjs/index.js:433:35)
```

### Expected Behavior

I expected presigned S3 url to be generated.

### Possible Solution

I found a merged PR that seems to be related to the issue but patched packaged doesn't seem to be called by @smithy/util-endpoints

**Comment by mvuckovic** [comment]
Please ignore this. Issue was caused by ENV variable containing full S3 ARN instead of just the bucket name.
