### ISSUE TITLE
@aws-sdk/client-resource-groups ListGroupsCommandInput shows invalid filter value

### ISSUE THREAD

**Issue by lbjay** [aws/aws-sdk-js-v3#6357]
### Describe the issue

The description of the `Filters` option states that `AWS::AppRegistry::ApplicationResourceGroups` is a possible value for a `configuration-type` filter. This does not appear to be true as using it produces the error:

```
    BadRequestException: Filters not valid: One or more filter values are not supported: 
    AWS::AppRegistry::ApplicationResourceGroups
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-resource-groups/Interface/ListGroupsCommandInput/

**Comment by zshzbh** [comment]
Hey @lbjay ,

Thanks for bringing this and sorry for this experience. I can reproduce this issue. 

Code I have - 

```js
import {
  ResourceGroupsClient,
  ListGroupsCommand,
} from "@aws-sdk/client-resource-groups";
("");

const client = new ResourceGroupsClient();
const input = {
  // ListGroupsInput
  Filters: [
    // GroupFilterList
    {
      // GroupFilter
      Name: "configuration-type", // required
      Values: [
        // GroupFilterValues // required
        "AWS::AppRegistry::ApplicationResourceGroup",
      ],
    },
  ],
};
const command = new ListGroupsCommand(input);
const response = await client.send(command);
console.log("res", response);
```
And then I got 400 badRequest error -
```
/Users/zshzbh/Desktop/newProj/node_modules/@aws-sdk/client-resource-groups/dist-cjs/index.js:988
  const exception = new BadRequestException({
                    ^

BadRequestException: Filters not valid: One or more filter values are not supported: AWS::AppRegistry::ApplicationResourceGroups
    at de_BadRequestExceptionRes (/Users/zshzbh/Desktop/newProj/node_modules/@aws-sdk/client-resource-groups/dist-cjs/index.js:988:21)
    at de_CommandError (/Users/zshzbh/Desktop/newProj/node_modules/@aws-sdk/client-resource-groups/dist-cjs/index.js:952:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/zshzbh/Desktop/newProj/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/zshzbh/Desktop/newProj/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /Users/zshzbh/Desktop/newProj/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/zshzbh/Desktop/newProj/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async file:///Users/zshzbh/Desktop/newProj/6357/index.js:25:18 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'a01a496e-8a8c-400c-8b83-3d9763dc9653',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

Node.js v20.15.1
```


However, I changed `AWS::AppRegistry::ApplicationResourceGroups` to `AWS::AppRegistry::ApplicationResourceGroup` and the error is gone. 

This is the request response I have using `AWS::AppRegistry::ApplicationResourceGroup`
```
res {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'b1f971a1-4a3c-49b6-97f0-ffea52c84f97',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  GroupIdentifiers: [],
  Groups: [],
  NextToken: 'XwTUDb7jQyIh3da6u2wLmYktLM0D6AGCWcnnPRFG8rIY/eb+Gy0k2HfLC5C1k2HjOb/WywY2LVE73gjQqNxfhjXVG4aerR+LwcIOauz/QaKZN7oR2jR6n6KwevWTNcaaNq+bxe5OL6NYxbOT0kfsZfeHGHsIv0C6ih7Ku6ftf1rYLOZb6EaNZdNl5d03tfv59dWPb1GBta7OMC60uRF2RIb0QMjYfC1hJ/o5ymYmclu0TUj+QGRVdZlOjAMETsv5biz8SwZ16d5NYwuFmHm9437DCMcEB2+xjmblo60U2knh5u88J3WPbAun'
}
```

To unblock your work, you can use  `AWS::AppRegistry::ApplicationResourceGroup` for now.  I will check with service team on this documentation issue. And I will keep you updated!

Thanks! 
Maggie

**Comment by zshzbh** [comment]
Internal ticket ref : V1477922516

**Comment by zshzbh** [comment]
Hey @lbjay ,

I just got updates from service team, the correct version is `AWS::AppRegistry::ApplicationResourceGroup`  and it is supported. You can use `AWS::AppRegistry::ApplicationResourceGroup` as `configuration-type`.

We will update the documentation accordingly. 

Thanks!
Maggie

**Comment by zshzbh** [comment]
@lbjay ,

Fix has been made. Closing this ticket. Please let us know if you have any other questions. 

Thanks!
