### ISSUE TITLE
Latest versions of S3Client do not work with GCP

### ISSUE THREAD

**Issue by aslushnikov** [aws/aws-sdk-js-v3#6430]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm connecting to Google Cloud Storage with the client-s3, like this:

```ts
const s3client = new S3Client({
  endpoint,
  region,
  credentials: {
    accessKeyId,
    secretAccessKey,
  },
  forcePathStyle: true,
});
await s3client.send(new ListBucketsCommand({}));
```
Version `@aws-sdk/client-s3@3.460.0` works as expected.

All later versions, starting from `@aws-sdk/client-s3@3.461.0` throw the following error:

```
InvalidArgument: Invalid argument.
    at throwDefaultError (/Users/aslushnikov/flakiness/server/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /Users/aslushnikov/flakiness/server/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_ListBucketsCommandError (/Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4988:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/aslushnikov/flakiness/server/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/aslushnikov/flakiness/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /Users/aslushnikov/flakiness/server/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'InvalidArgument',
  Details: 'Invalid query parameter: x-id'
}
```

### SDK version number

@aws-sdk/client-s3

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.8.1

### Reproduction Steps

1. Register and Google Cloud platform; create a gbucket @ google storage.
1. `npm i @aws-sdk/client-s3@latest`
2. Run the following snippet:
```ts
const s3client = new S3Client({
  endpoint,
  region,
  credentials: {
    accessKeyId,
    secretAccessKey,
  },
  forcePathStyle: true,
});
await s3client.send(new ListBucketsCommand({}));
```

### Observed Behavior

Error is thrown: 
```
InvalidArgument: Invalid argument.
    at throwDefaultError (/Users/aslushnikov/flakiness/server/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /Users/aslushnikov/flakiness/server/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_ListBucketsCommandError (/Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4988:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/aslushnikov/flakiness/server/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/aslushnikov/flakiness/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /Users/aslushnikov/flakiness/server/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at async /Users/aslushnikov/flakiness/server/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'InvalidArgument',
  Details: 'Invalid query parameter: x-id'
}
```

### Expected Behavior

no error.

**Comment by RanVaknin** [comment]
Hi @aslushnikov ,

The error you are seeing is coming from the google server specifically about `x-id` query parameter not being supported when provided as a query parameter when sent by the SDK.

Newer SDKs are now adding this query parameter for internal reasons. On AWS S3 side, this is being disregarded, but it seems like the Google S3 clone / whatever you are using does not disregard it, and rejects the request.

Since we do not support integrations with competitors like GCP, you will have to reach out to Google to get this supported. 

Alternatively, you might be able to use a middleware to remove this from the request:

```
const client = new S3Client({ region: 'us-east-1' });

client.middlewareStack.add(next => args => {
    args.request.query = null
    return next(args);
}, {step: 'build'})

// rest of your code...
```

Thanks,
Ran~

**Comment by aslushnikov** [comment]
@RanVaknin thank you for the pointers!
