### ISSUE TITLE
[s3.copyObject]: Invalid character in header content ["x-amz-copy-source"]

### ISSUE THREAD

**Issue by shadoworion** [aws/aws-sdk-js-v3#6596]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

It looks like the "copyObject" function does not support Hebrew in the location path.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-s3@3.679.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

22.8.0

### Reproduction Steps

```
const oldLocation = "Files/ce59edb1-c78a-4e47-9cc1-b631b3f6e03b/דוד-טסט_orders_2024-10-28 (2).csv";
const newLocation = "Files/236bf060-db65-45fb-be2a-8d5845a75f6d/דוד-טסט_orders_2024-10-28 (2).csv";

await s3.copyObject({
      CopySource: `${process.env.AWS_STORAGE_BUCKET}/${oldLocation}`,
      Bucket: process.env.AWS_STORAGE_BUCKET,
      Key: newLocation,
});
```

### Observed Behavior

```
TypeError: Invalid character in header content ["x-amz-copy-source"]
    at ClientRequest.setHeader (node:_http_outgoing:702:3)
    at new ClientRequest (node:_http_client:295:14)
    at request (node:https:379:10)
    at /backend/node_modules/@smithy/node-http-handler/dist-cjs/index.js:349:19
    at new Promise (<anonymous>)
    at _NodeHttpHandler.handle (/backend/node_modules/@smithy/node-http-handler/dist-cjs/index.js:283:12)
    at /backend/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:534:18
    at /backend/node_modules/@smithy/middleware-serde/dist-cjs/index.js:33:24
    at /backend/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:485:18
    at /backend/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38 {
  code: 'ERR_INVALID_CHAR',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

Not to get an error

**Comment by shadoworion** [comment]
Hey @zshzbh 

Any updates?

**Comment by zshzbh** [comment]
@Nitro-N Thanks for the workaround solution. I think we can use the encode function as a workaround now, but still I want to let the service team know this issue. I have not received anything from service team yet, will try to reach out again.

Sorry for the wait and thanks for the provided workaround

**Comment by ChrisSong1994** [comment]
> [@shadoworion](https://github.com/shadoworion) [@zshzbh](https://github.com/zshzbh), try to wrap `CopySource` and `Key` value with `encodeURI` function
I have the same problem, but `encodeURI` can't  work;

**Comment by ChrisSong1994** [comment]
> [@Nitro-N](https://github.com/Nitro-N) Thanks for the workaround solution. I think we can use the encode function as a workaround now, but still I want to let the service team know this issue. I have not received anything from service team yet, will try to reach out again.
> 
> Sorry for the wait and thanks for the provided workaround

What is the progress on this issue now?

**Comment by zshzbh** [comment]
Hey @ChrisSong1994 ,

Thanks for the followup. I really understand how stressful this could be, however, the service team has some other high priority requests and they won't fix this issue in a couple weeks. 

The workaround is available though, could you please use the workaround for now? If you want to get a faster fix, I'd like to suggest you to list the impact of this issue, or reach out to your TAM to submit an internal ticket. Usually these two steps could make this issue getting triaged by service team faster. 

Thanks for being patient!

**Comment by shadoworion** [comment]
@zshzbh 

Hi, any updates?

**Comment by zshzbh** [comment]
Hey @shadoworion ,


Got response from service team and they want to confirm that if you try URL-encode the special characters?

**Comment by shadoworion** [comment]
> Hey [@shadoworion](https://github.com/shadoworion) ,
> 
> Got response from service team and they want to confirm that if you try URL-encode the special characters?

Yes, it works. The problem is only in "CopySource". 
"Key" parameter works without URL-encode.

**Comment by tMihaita** [comment]
Hello, any updates on this ?

**Comment by cob16** [comment]
Just hit this issues today and I wanted to point out this prevents copy object to any file that has a unicode character in it, 
for example  ꧂ and ۳  also also recreates the same error.

I appreciate the workaround is simple but I would have expected the AWS SDK have Unicode support given it is [handled elsewhere in the SDK](https://github.com/aws/aws-sdk-js-v3/blob/8aeb92dd6ab42e4b59ebb3ad5a7c43b503af0183/packages/cloudfront-signer/src/sign.ts#L172)
