### ISSUE TITLE
DELETE Request Stuck with @aws-sdk/client-s3 v3.717.0 When Using DigitalOcean Spaces

### ISSUE THREAD

**Issue by mgsgde** [aws/aws-sdk-js-v3#6761]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The DELETE operation using @aws-sdk/client-s3 (version 3.717.0) gets stuck when interacting with DigitalOcean Spaces. The request is sent, but the process appears to hang indefinitely without receiving a response. This behavior is observed specifically with the DeleteObjectsCommand.

Environment:
	•	@aws-sdk/client-s3 version: 3.717.0
	•	Node.js version: v21.7.1
	•	DigitalOcean Spaces
	•	Operating System: macOS

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/client-s3@3.717.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v21.7.1

### Reproduction Steps

	1.	Initialize an S3 client with DigitalOcean Spaces.
	2.	Attempt to delete objects using the DeleteObjectsCommand.
	3.	Observe that the operation hangs and does not complete.

### Observed Behavior

The DELETE operation does not proceed past sending the HTTP request. The process does not throw any errors or complete the operation, making it impossible to debug effectively.

### Expected Behavior

The DELETE operation should successfully remove the specified objects from the bucket and return a response without hanging.

### Additional Information/Context

Other S3 commands (e.g., ListObjectsV2Command) work as expected. The DELETE issue seems isolated to the DeleteObjectsCommand.

**Comment by aBurmeseDev** [comment]
Hi @mgsgde - thanks for reaching out. 

In order for us to further look into this, can you share the followings:
- A minimal SDK reproducible code
- Capture and share any logging requests by adding middleware to S3 client
```js
client.middlewareStack.add(
  (next, context) => async (args) => {
    console.log("AWS SDK context", context.clientName, context.commandName);
    console.log("AWS SDK request input", args.input);
    const result = await next(args);
    console.log("AWS SDK request output:", result.output);
    return result;
  },
  {
    name: "MyMiddleware",
    step: "build",
    override: true,
  }
);
```
- Try downgrading to an older version of SDK and share the result


Also are you able to test this same operation with AWS S3 bucket instead? We won't be able to provide support if the issue is specific to third-party service.

**Comment by n-lavrenko** [comment]
Hello guys!
and [aBurmeseDev](https://github.com/aBurmeseDev)
Please, take a look, it's like a **critical** bug. 

I have the same issue with the same environment. 
Previously, 6 month ago everything worked, but now -- not. 
I spent whole day to figure out what a hell is going on...

Upload is working. DeleteObjects - not.
After send a request DeleteObjects: in ~5 minutes I receive an error in try/catch: 

catching callstack:
```
Error: char 's' is not expected.:1:1
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at XMLParser.parse (/Users/n-lavrenko/dev/joiny-api/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:30:21)
    at /Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:177:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseXmlErrorBody (/Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:198:17)
    at async de_CommandError (/Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4874:11)
    at async /Users/n-lavrenko/dev/joiny-api/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:485:18
    at async /Users/n-lavrenko/dev/joiny-api/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:286:18
    at async /Users/n-lavrenko/dev/joiny-api/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
```
and more data in `error`:
```
{
  message: "char 's' is not expected.:1:1
    Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.",
  $responseBodyText: "stream timeout"
  $response: below ⬇️:
}
```

response.$response:
```
{
  "statusCode": 408,
  "reason": "Request Timeout",
  "headers": {
    "strict-transport-security": "max-age=15552000; includeSubDomains; preload",
    "content-length": "14",
    "content-type": "text/plain",
    "x-envoy-upstream-healthchecked-cluster": "",
    "date": "Tue, 31 Dec 2024 13:10:23 GMT",
    "connection": "close"
  },
  "body": "stream timeout"
}
```

**I've tried everything. It seems like a bug on maybe third-party lib. The request seems like not sending. 
Here is the code to reproduce the issue:**

```
import { DeleteObjectsCommand, S3Client } from '@aws-sdk/client-s3';

const client = new S3Client({
  endpoint: process.env.DIGITAL_OCEAN_SPACES_ENDPOINT,
  forcePathStyle: false,
  region: 'fra1',
  credentials: {
    accessKeyId: process.env.DIGITAL_OCEAN_SPACES_KEY_ID,
    secretAccessKey: process.env.DIGITAL_OCEAN_SPACES_KEY,
  },
});

(async () => {
  client.middlewareStack.add(
    (next, context) => async (args) => {
      console.log('AWS SDK context', context.clientName, context.commandName);
      console.log('AWS SDK request input', args.input);
      const result = await next(args);
      console.log('AWS SDK request output:', result.output);
      return result;
    },
    {
      name: 'MyMiddleware',
      step: 'build',
      override: true,
    },
  );

  try {
    console.log('Deleting object...');
    const res = await client.send(
      new DeleteObjectsCommand({
        Bucket: process.env.DIGITAL_OCEAN_SPACES_BUCKET,
        Delete: {
          Objects: [{ Key: 'order/6772f4f33c88f5ee2c9ceb6e.HEIC' }],
        },
      }),
    );
    console.log('Delete result:', res);
  } catch (err) {
    console.error(err);
  }
})();

```

**Comment by mgsgde** [comment]
Here’s a corrected version:

Logging:
```
{
  "Bucket": "mgsgde",
  "Delete": {
    "Objects": [
      {"Key": "object1"}, {"Key": "object2"},
      {"Key": "object3"}, {"Key": "object4"},
      {"Key": "object5"}, {"Key": "object6"},
      {"Key": "object7"}
    ]
  }
}
```
As mentioned earlier, there is no HTTP response logged.

Downgrading to version 3.645.0 resolved the issue.

For now, I am reverting to the previous version as a workaround.

I have also contacted DigitalOcean support, as the issue could be on their side, even though backward compatibility in the SDK makes this less likely.

**Comment by n-lavrenko** [comment]
@mgsgde, 
Thank you very much! 
I'll try and return back with the result.

**Comment by n-lavrenko** [comment]
I've tested quickly - it doesn't work

**Comment by n-lavrenko** [comment]
FYI:
I've rewrote my code into single deletion files, it's still working using latest version of your library.

**Comment by aBurmeseDev** [comment]
According to the error response, the server seems to be responding with "stream timeout" instead of a valid response.

This may be because the connection to the DigitalOcean Spaces endpoint may have timed out, causing the server to return a "stream timeout" response.

>I've rewrote my code into single deletion files, it's still working using latest version of your library.

@n-lavrenko - can you share the version that's last working for you? Also I noticed typo in your code for `DeleteObjectCommand`. 

As next step of troubleshooting, I'd like to isolate the issue to SDK first, (third-party not involved). Can you try the SDK code below to deletes an object in S3 bucket?
```js
import { S3Client, DeleteObjectCommand } from "@aws-sdk/client-s3"; 
const client = new S3Client();

  client.middlewareStack.add(
    (next, context) => async (args) => {
      console.log('AWS SDK context', context.clientName, context.commandName);
      console.log('AWS SDK request input', args.input);
      const result = await next(args);
      console.log('AWS SDK request output:', result.output);
      return result;
    },
    {
      name: 'MyMiddleware',
      step: 'build',
      override: true,
    },
  );

const input = { 
  Bucket: "STRING_VALUE", 
  Key: "STRING_VALUE", 
};
const command = new DeleteObjectCommand(input);
const response = await client.send(command);
```

Please share the output for our investigation, thank you for your corporation!

**Comment by n-lavrenko** [comment]
Hello @aBurmeseDev !

> Also I noticed typo in your code for DeleteObjectCommand
What the typo? 
FYI: I used DeleteObjectsCommand (not the DeleteObjectCommand). 

As I said before, DeleteObjectsCommand previously worked, but now work only DeleteObjectCommand.
So, when I said above: 
> I've rewrote my code into single deletion files, it's still working using latest version of your library.
I mean that I used DeleteObjectCommand which no have any problems. 

So your code with single file deletion is not around the issue. The issue is only with bulk deletion: DeleteObjectsCommand

**Comment by pdesmarais** [comment]
So, had the same issue as detailed in previous comments with DO Spaces timing out with the DeleteObjectsCommand (multiple) but not the DeleteObjectCommand (single).

Noticed in the error that it was smithy/node-http-handler that was complaining. Had updated packages recently.

First difference from the people above mentioning that downgrading to an older version of s3client fixed the issue for them is that it didn't fix it for us.

Then, I noticed that we are explicitly requiring @smithy/node-http-handler in our package.json. We were now using 3.3.1 of that package (before the latest package updates, we were using 3.3.0).

Downgraded smithy/node-http-handler back to 3.3.0 and everything was working normally.

Now, we're using latest s3client (3.723) and smithy/node-http-handler (3.3.0) and everything works.
What's weird is that the latest s3client uses smithy 4.0.0 but if I explicitly use that version in the package.json, it doesn't work.

Hope this helps anyone!

**Comment by DeepakBalaraman** [comment]
Updating the `@aws-sdk/client-s3` to `v3.731.1` fixed the issue for me.

**Comment by aBurmeseDev** [comment]
Thank you all for sharing the updates. It sounds like incompatibility issue with third-party. According to the latest status from DigitalOcean [here](https://status.digitalocean.com/incidents/zbrpd3j7hrrd), it appears they've provided a resolution for their buckets which are now compatible with the latest versions of the AWS SDKs. 

Please note that AWS SDK for JavaScript is designed to be used with AWS services.
If you're using a different cloud service, please refer to their documentation on compatibility.
