### ISSUE TITLE
The e.Error.Message must be in e.message

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#763]
**Describe the bug**
The e.Error.Message must be in e.message

**SDK version number**
```console
$ yarn list aws-sdk
└─ aws-sdk@2.605.0
$ yarn list @aws-sdk/client-elastic-beanstalk
└─ @aws-sdk/client-elastic-beanstalk@1.0.0-alpha.2
```

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
```console
$ node -v
v12.14.0
```

**To Reproduce (observed behavior)**
Reproduced using the following code:
```javascript
const AWS = require("aws-sdk");
const { ElasticBeanstalk } = require("@aws-sdk/client-elastic-beanstalk");

(async () => {
  const region = "us-west-2";
  const params = {
    ApplicationName: ""
  };

  const v2Client = new AWS.ElasticBeanstalk({ region });
  try {
    await v2Client.createApplication(params).promise();
  } catch (e) {
    console.log("Error returned by v2:");
    console.log(JSON.stringify(e, null, 2));
  }

  const v3Client = new ElasticBeanstalk({ region });
  try {
    await v3Client.createApplication(params);
  } catch (e) {
    console.log("\nError returned by v3:");
    console.log(JSON.stringify(e, null, 2));
  }
})();
```

Output shows that in v3, there's an additional Error object inside existing Error object
```
Error returned by v2:
{
  "message": "2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1",
  "code": "ValidationError",
  "time": "2020-01-20T23:42:44.536Z",
  "requestId": "f3ca4ab8-896b-47db-937a-961df2986b5d",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 15.387417546477877
}

Error returned by v3:
{
  "xmlns": "http://elasticbeanstalk.amazonaws.com/docs/2010-12-01/",
  "Error": {
    "Type": "Sender",
    "Code": "ValidationError",
    "Message": "2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy
 regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length great
er than or equal to 1"
  },
  "RequestId": "fd167620-1375-46ee-a41b-c8a5db0145cb",
  "name": "ValidationError",
  "message": "ValidationError",
  "__type": "com.amazonaws.elasticbeanstalk#ValidationError",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "httpHeaders": {
      "content-type": "text/xml",
      "date": "Mon, 20 Jan 2020 23:42:44 GMT",
      "x-amzn-requestid": "fd167620-1375-46ee-a41b-c8a5db0145cb",
      "content-length": "515",
      "connection": "keep-alive"
    },
    "requestId": "fd167620-1375-46ee-a41b-c8a5db0145cb",
    "retries": 0,
    "totalRetryDelay": 0
  }
}
```

**Expected behavior**
The e.Error.Message is contained in e.message

**Comment by trivikr** [comment]
Related https://github.com/aws/aws-sdk-js-v3/issues/759

**Comment by trivikr** [comment]
On 01/21, we decided to place contents of e.Error.Message in e.message
We also decided to remove "__type" in favor of name as discussed, and to be followed up in https://github.com/awslabs/smithy-typescript/issues/96

**Comment by trivikr** [comment]
The message is missing as of `@aws-sdk/client-elastic-beanstalk@1.0.0-alpha.7`

```javascript
const AWS = require("aws-sdk");
const { ElasticBeanstalk } = require("@aws-sdk/client-elastic-beanstalk");

(async () => {
  const region = "us-west-2";
  const params = {
    ApplicationName: ""
  };

  const v2Client = new AWS.ElasticBeanstalk({ region });
  try {
    await v2Client.createApplication(params).promise();
  } catch (e) {
    console.log("Error returned by v2:");
    console.log(JSON.stringify(e, null, 2));
  }

  const v3Client = new ElasticBeanstalk({ region });
  try {
    await v3Client.createApplication(params);
  } catch (e) {
    console.log("\nError returned by v3:");
    console.log(JSON.stringify(e, null, 2));
  }
})();
```

Output:
```
Error returned by v2:
{
  "message": "2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1",
  "code": "ValidationError",
  "time": "2020-02-05T20:45:49.053Z",
  "requestId": "64f3956f-802e-41d8-b0f5-b3dcd886866c",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 36.927367229865716
}

Error returned by v3:
{
  "Type": "Sender",
  "Code": "ValidationError",
  "name": "ValidationError",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "httpHeaders": {
      "content-type": "text/xml",
      "date": "Wed, 05 Feb 2020 20:45:48 GMT",
      "x-amzn-requestid": "cc687f9d-6d64-4bc4-bde7-13aaf5811912",
      "content-length": "515",
      "connection": "keep-alive"
    },
    "requestId": "cc687f9d-6d64-4bc4-bde7-13aaf5811912",
    "retries": 0,
    "totalRetryDelay": 0
  }
}
```

**Comment by kstich** [comment]
This must be a JS internal thing, as it's set on `response` before this line:

```
  const message = response.message || response.Message || errorCode;
  response.message = message;
  delete response.Message;
  console.log(response);
  return Promise.reject(Object.assign(new Error(message), response)); <-- This line
```

Adding the `console.log(response);` above and running this:
```
await client
    .send(new CreateApplicationCommand({
      ApplicationName: ""
    }))
    .then(data => {
      console.log("got data");
      console.log(data);
    })
    .catch(err => {
      console.log("got err");
      console.log(err);
    });
```

Generates this output:
```
{
  Type: 'Sender',
  Code: 'ValidationError',
  name: 'ValidationError',
  message: "2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1",
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      'content-type': 'text/xml',
      date: 'Wed, 05 Feb 2020 21:14:43 GMT',
      'x-amzn-requestid': 'db12124a-e03a-47ee-b6d9-0d2a28b86424',
      'content-length': '515',
      connection: 'keep-alive'
    },
    requestId: 'db12124a-e03a-47ee-b6d9-0d2a28b86424'
  }
}
got err
Error [ValidationError]: 2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at deserializeAws_queryCreateApplicationCommandError (/Users/stickevi/Documents/Repositories/SmithyTypescript/aws-sdk-js-v3/clients/client-elastic-beanstalk/dist/cjs/protocols/Aws_query.js:549:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  Type: 'Sender',
  Code: 'ValidationError',
  name: 'ValidationError',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    httpHeaders: {
      'content-type': 'text/xml',
      date: 'Wed, 05 Feb 2020 21:14:43 GMT',
      'x-amzn-requestid': 'db12124a-e03a-47ee-b6d9-0d2a28b86424',
      'content-length': '515',
      connection: 'keep-alive'
    },
    requestId: 'db12124a-e03a-47ee-b6d9-0d2a28b86424',
    retries: 0,
    totalRetryDelay: 0
  }
}
```

Does these tests need to update the component of the error they're looking at?

**Comment by trivikr** [comment]
Verified that the issue is with using JSON.stringify while logging error, and the message is present as required.

Code:
```javascript
const AWS = require("aws-sdk");
const { ElasticBeanstalk } = require("@aws-sdk/client-elastic-beanstalk");

(async () => {
  const region = "us-west-2";
  const params = {
    ApplicationName: ""
  };

  const v2Client = new AWS.ElasticBeanstalk({ region });
  try {
    await v2Client.createApplication(params).promise();
  } catch (e) {
    console.log("Error returned by v2:");
    console.log(JSON.stringify(e.message, null, 2));
  }

  const v3Client = new ElasticBeanstalk({ region });
  try {
    await v3Client.createApplication(params);
  } catch (e) {
    console.log("\nError returned by v3:");
    console.log(JSON.stringify(e.message, null, 2));
  }
})();
```

Output:
```
Error returned by v2:
"2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1"

Error returned by v3:
"2 validation errors detected: Value '' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^/]+; Value '' at 'applicationName' failed to satisfy constraint: Member must have length greater than or equal to 1"
```
