### ISSUE TITLE
H2 request header field "content-type" must only have a single value

### ISSUE THREAD

**Issue by AllanFly120** [aws/aws-sdk-js-v3#811]
**Describe the bug**

**SDK version number**

**Is the issue in the browser/Node.js?**
Node.js

In Transcribe-streaming service we set `Content-Type` header as `""`. 
https://github.com/aws/aws-sdk-js-v3/blob/a89275006d284269260169d58ab5ab964341e9e4/clients/client-transcribe-streaming/protocols/Aws_restJson1_1.ts#L36
However this will trigger errors in NodeJS H2 handler:
```
TypeError [ERR_HTTP2_HEADER_SINGLE_VALUE]: Header field "content-type" must only have a single value
    at mapToHeaders (internal/http2/util.js:458:16)
    at ClientHttp2Session.request (internal/http2/core.js:1481:25)
    at Promise (/Users/zheallan/workspace/aws-sdk-js-v3/packages/node-http-handler/build/node-http2-handler.js:32:94)
```

One possible solution is to set a default value for `content-type` instead of empty string. [For example in V2](https://github.com/aws/aws-sdk-js/blob/917e10c904649dbc7080bdb836505412d3b7c129/lib/protocol/rest_json.js#L17-L24), we set default `content-type` to `'binary/octet-stream'` if request has binary payload or streaming, otherwise we set to `'application/json'`.

**Comment by AllanFly120** [comment]
This issue exists because multiple value is set to the same header actually. Close this issue because it's unrelated
