### ISSUE TITLE
CodeGen failing with "ReferenceError: fromConfig is not defined"

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#904]
**Describe the bug**
CodeGen failing with "ReferenceError: fromConfig is not defined"

**To Reproduce (observed behavior)**
```console
$ yarn generate-clients -m models
...
...
child process exited with code 0
copying @aws-sdk/client-accessanalyzer from /local/home/trivikr/workspace/aws-sdk-js-v3/codegen/sdk-codegen/build/smithyprojections/sdk-codegen/accessanalyzer.2019-11-01/typescript-codegen to /local/home/trivikr/workspace/aws-sdk-js-v3/clients
ReferenceError: fromConfig is not defined
    at mergeManifest (/local/home/trivikr/workspace/aws-sdk-js-v3/scripts/generate-clients/copy-to-clients.js:47:33)
    at copyToClients (/local/home/trivikr/workspace/aws-sdk-js-v3/scripts/generate-clients/copy-to-clients.js:89:32)
    at /local/home/trivikr/workspace/aws-sdk-js-v3/scripts/generate-clients/index.js:26:11
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

**Expected behavior**
CodeGen shouldn't fail

**Comment by trivikr** [comment]
Fixed in https://github.com/aws/aws-sdk-js-v3/pull/905
