### ISSUE TITLE
@aws-sdk/client-s3-node S3.deleteObjects SignatureDoesNotMatch error 

### ISSUE THREAD

**Issue by KeithGillette** [aws/aws-sdk-js-v3#916]
**Describe the bug**
We get the following error when calling `S3.deleteObjects` in Node.js:

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

`S3.deleteObjects` works in the browser and `S3.deleteObject` works in Node.js

**SDK version number**
0.1.0-preview.2

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.14.1

**To Reproduce (observed behavior)**

```typescript
import { DeleteObjectOutput, DeleteObjectsOutput, S3 } from '@aws-sdk/client-s3-node';

export class FileStorageService {
	private s3Client: S3 = new S3({
		credentials: {
			accessKeyId: process.env.ContentBucketKey,
			secretAccessKey: process.env.ContentBucketSecret
		},
		region: process.env.ContentBucketRegion
	});

	// Works fine:
	public deleteOne(s3ObjectKey: string): Promise<DeleteObjectOutput> {
		const s3Parameters = {
			Bucket: process.env.ContentBucketName,
			Key: s3ObjectKey
		};
		return this.s3Client.deleteObject(s3Parameters);
	}

	// Produces `SignatureDoesNotMatch` error:
	public deleteMany(s3ObjectKeyList: string[]): Promise<DeleteObjectsOutput> {
		const s3DeleteObjectsList = s3ObjectKeyList.map((s3ObjectKey: string) => {
			return { Key: s3ObjectKey };
		});
		const s3Parameters = {
			Bucket: process.env.ContentBucketName,
			Delete: {Objects: s3DeleteObjectsList}
		};
		return this.s3Client.deleteObjects(s3Parameters);
	}
}
```

**Expected behavior**
Given the same S3 client configuration, `S3.deleteObjects` should work.

**Screenshots**
N/A

**Additional context**
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at RestParser.exports.s3ErrorUnmarshaller [as parseServiceException] (…/node_modules/@aws-sdk/s3-error-unmarshaller/build/index.js:46:58)
    at …/node_modules/@aws-sdk/protocol-rest/build/RestParser.js:27:29
    at …/node_modules/meteor-promise/fiber_pool.js:43:40 {
  name: 'SignatureDoesNotMatch',
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  details: {},
  '$metadata': {
    httpHeaders: {
      'x-amz-request-id': '79694E11BA8B70BE',
      'x-amz-id-2': 'jyNuA8TEvbyThjnk26cq6GwIJdqzofTwITIznmX92g1FAXvqj9ss9QmT2gpPcJBGsukCG9xWdms=',
      'content-type': 'application/xml',
      'transfer-encoding': 'chunked',
      date: 'Tue, 11 Feb 2020 15:47:54 GMT',
      connection: 'close',
      server: 'AmazonS3'
    },
    httpStatusCode: 403,
    requestId: '79694E11BA8B70BE',
    extendedRequestId: 'jyNuA8TEvbyThjnk26cq6GwIJdqzofTwITIznmX92g1FAXvqj9ss9QmT2gpPcJBGsukCG9xWdms=',
    cfId: undefined,
    retries: 0,
    totalRetryDelay: 0
  }
}
```

**Comment by srchase** [comment]
Hi @KeithGillette 

Would you mind switching over to the alpha release and use the @aws-sdk/client-s3 instead?

You should be able to do the following:

```
const { S3 } = require("@aws-sdk/client-s3");

(async () => { 
    const client = new S3({
        region: "us-west-2"
    })
    await client.deleteObjects({
        Bucket: "bucket",
        Delete: {
            Objects: [ 
                { Key: "foo" },
                { Key: "bar" }
            ]
        } 
    }).then((res) => {
        console.log(res);
    }).catch((err) => {
        console.log(err);
    });
})();
```

**Comment by trivikr** [comment]
Verified that s3. deleteObjects is successful in `@aws-sdk/client-s3@1.0.0-alpha.8`:

Code:
```javascript
const AWS = require("aws-sdk");
const { S3 } = require("@aws-sdk/client-s3");

const getRandomString = () =>
  Math.random()
    .toString(36)
    .substring(2);

(async () => {
  let response;
  const bucketName = "test-bucket-" + getRandomString();
  const objectPrefix = "test-object-";
  const params = {
    Bucket: bucketName
  };

  const v2Client = new AWS.S3({ region: "us-west-2" });
  const v3Client = new S3({ region: "us-west-2" });

  console.log(`Creating bucket ${bucketName}`);
  await v3Client.createBucket(params);
  console.log(`Waiting for "${bucketName}" bucket creation\n`);
  await v2Client.waitFor("bucketExists", params).promise();

  for (let i = 0; i < 3; i++) {
    const Key = objectPrefix + getRandomString();
    console.log(`Putting object "${Key}" in ${bucketName}...`);
    await v3Client.putObject({
      Body: "000000",
      Bucket: bucketName,
      Key
    });
  }

  response = await v3Client.listObjects(params);
  console.log(`\nDeleting objects: ${response.Contents.map(obj => obj.Key)}\n`);

  await v3Client.deleteObjects({
    Bucket: bucketName,
    Delete: {
      Objects: response.Contents.map(obj => ({ Key: obj.Key }))
    }
  });

  response = await v3Client.listObjects(params);
  if (!response.Contents) {
    // Confirm that bucket is empty
    console.log(`Bucket ${bucketName} is empty`);
  }

  console.log(`Deleting bucket ${bucketName}`);
  await v2Client.deleteBucket(params).promise();
})();
```

Output:
```console
Creating bucket test-bucket-gg3u4xcdsa4
Waiting for "test-bucket-gg3u4xcdsa4" bucket creation

Putting object "test-object-bqul94p92ed" in test-bucket-gg3u4xcdsa4...
Putting object "test-object-ficvf9xwrx" in test-bucket-gg3u4xcdsa4...
Putting object "test-object-lr7qz8k77m" in test-bucket-gg3u4xcdsa4...

Deleting objects: test-object-bqul94p92ed,test-object-ficvf9xwrx,test-object-lr7qz8k77m

Bucket test-bucket-gg3u4xcdsa4 is empty
Deleting bucket test-bucket-gg3u4xcdsa4
```

Closing, please comment if the issue exists

**Comment by trivikr** [comment]
@KeithGillette The development of alpha versions is being done in `smithy-codegen` branch and it'll be soon merged to master https://github.com/aws/aws-sdk-js-v3/tree/smithy-codegen

Quick answers:
* the repository &/or documentation for `@aws-sdk/client-s3`
  * https://github.com/aws/aws-sdk-js-v3/tree/smithy-codegen
* Is `@aws-sdk/client-s3` a universal client for node & browser?
  * Yes
* If we should also be switching to `@aws-sdk/client-s3` in the browser as well, what are the compatible packages for the related libraries we use with the S3 on the client
  * Please refer browser section of aws-samples/aws-sdk-js-tests https://github.com/aws-samples/aws-sdk-js-tests/tree/master/src/browser
