### ISSUE TITLE
The operation putBucketLifecycle doesn't exist on S3 client

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#982]
**Describe the bug**
The operation putBucketLifecycle doesn't exist on S3 client
* v2 documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketLifecycle-property
* Code: Notice that there's no `putBucketLifecycle` between `putBucketInventoryConfiguration` and `putBucketLifecycleConfiguration `
https://github.com/aws/aws-sdk-js-v3/blob/15a66c720f49884087126d6d573c64b6a4a16dc5/clients/client-s3/S3.ts#L5120-L5130

**SDK version number**
@aws-sdk/client-s3@1.0.0-alpha.17

**Is the issue in the browser/Node.js?**
Browser/Node.js

**Details of the browser/Node.js version**
N/A

**To Reproduce (observed behavior)**
Run the following code in Node.js
```javascript
const { S3 } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-west-2";
  const client = new S3({ region });
  response = await client.putBucketLifecycle({});
})();
```

Output:
```console
(node:9815) UnhandledPromiseRejectionWarning: TypeError: client.putBucketLifecycle is not a function
    at /Users/trivikr/workspace/aws-sdk-js-tests/src/node/index.js:6:27
    at Object.<anonymous> (/Users/trivikr/workspace/aws-sdk-js-tests/src/node/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:9815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
The API `putBucketLifecycle` should be available on S3 client

**Comment by trivikr** [comment]
As per the S3 documentation, `PutBucketLifecycle` is updated by `PutBucketLifecycleConfiguration`
Documentation: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycle.html

So this is not an issue.
JS SDK v3 API reference will not have `PutBucketLifecycle` documented.
